gophercloud/gophercloud

STYLEGUIDE.md, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go
for #7 
Also adds a few style guide points.
=> Implement json.Unmarshaler for Flavor

acceptance/openstack/containerorchestration/v1/bay_test.go, acceptance/openstack/containerorchestration/v1/common.go, acceptance/openstack/containerorchestration/v1/pkg.go, openstack/client.go, openstack/containerorchestration/v1/bays/doc.go, openstack/containerorchestration/v1/bays/requests.go, openstack/containerorchestration/v1/bays/results.go, openstack/containerorchestration/v1/bays/testing/doc.go, openstack/containerorchestration/v1/bays/testing/requests_test.go, openstack/containerorchestration/v1/bays/urls.go, openstack/containerorchestration/v1/common/common_tests.go
For #10.
This is take two on PR (#15), this time targeting the correct branch (magnum). 😊
=> Support showing a Magnum bay

openstack/compute/v2/servers/results.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/compute/v2/servers/testing/requests_test.go
=> Implement json.Unmarshaler for Server

CONTRIBUTING.md
I've updated the contributing guide with the commands I used to setup a new fork.
=> Fix example commands to setup a new fork

acceptance/openstack/containerorchestration/v1/bay_test.go, openstack/containerorchestration/v1/bays/requests.go, openstack/containerorchestration/v1/bays/results.go, openstack/containerorchestration/v1/bays/testing/requests_test.go, openstack/containerorchestration/v1/bays/urls.go
=> Support listing Magnum bays

openstack/client.go, openstack/identity/v3/tokens/results.go, openstack/testing/client_test.go
=> Use EndpointOpts to query ServiceCatalog for endpoint for Identity service clients

acceptance/openstack/containerorchestration/v1/baymodel_test.go, openstack/containerorchestration/v1/baymodels/doc.go, openstack/containerorchestration/v1/baymodels/requests.go, openstack/containerorchestration/v1/baymodels/results.go, openstack/containerorchestration/v1/baymodels/testing/doc.go, openstack/containerorchestration/v1/baymodels/testing/requests_test.go, openstack/containerorchestration/v1/baymodels/urls.go
=> Support listing Magnum baymodels

MIGRATING.md, openstack/identity/v3/extensions/trusts/results.go, openstack/identity/v3/extensions/trusts/testing/fixtures.go, openstack/identity/v3/tokens/results.go, openstack/identity/v3/tokens/testing/requests_test.go
for #28 
[trust properties](https://github.com/openstack/keystone/blob/stable/mitaka/keystone/trust/schema.py#L17)
=> create trusts.TokenExt response object

openstack/identity/v2/extensions/admin/roles/requests.go
=> Allow return code 200 when adding role to user

openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/compute/v2/servers/testing/requests_test.go
=> set servers.CreateOpts field `ServiceClient` field to nil before unmarshaling

acceptance/openstack/containerorchestration/v1/bay_test.go, errors.go, openstack/containerorchestration/v1/bays/requests.go, openstack/containerorchestration/v1/bays/results.go, openstack/containerorchestration/v1/bays/testing/requests_test.go, openstack/containerorchestration/v1/bays/urls.go, openstack/containerorchestration/v1/common/errors.go, provider_client.go
=> Support deleting Magnum bays

acceptance/openstack/containerorchestration/v1/bay_test.go, acceptance/openstack/containerorchestration/v1/baymodel_test.go, openstack/containerorchestration/v1/baymodels/requests.go, openstack/containerorchestration/v1/baymodels/results.go, openstack/containerorchestration/v1/baymodels/testing/requests_test.go, openstack/containerorchestration/v1/baymodels/urls.go, openstack/containerorchestration/v1/bays/testing/requests_test.go
=> Support retrieving a Magnum baymodel

acceptance/openstack/containerorchestration/v1/bay_test.go, acceptance/openstack/containerorchestration/v1/certificate_test.go, openstack/blockstorage/v1/apiversions/urls.go, openstack/compute/v2/images/results.go, openstack/containerorchestration/v1/bays/results.go, openstack/containerorchestration/v1/bays/testing/requests_test.go, openstack/containerorchestration/v1/certificates/doc.go, openstack/containerorchestration/v1/certificates/requests.go, openstack/containerorchestration/v1/certificates/results.go, openstack/containerorchestration/v1/certificates/testing/doc.go, openstack/containerorchestration/v1/certificates/testing/requests_test.go, openstack/containerorchestration/v1/certificates/urls.go, openstack/testing/client_test.go
=> Suport creating Magnum certificates

openstack/networking/v2/extensions/provider/results.go, openstack/networking/v2/extensions/provider/testing/results_test.go
=> Ensure returned segmentation_id is a string

openstack/objectstorage/v1/accounts/results.go, openstack/objectstorage/v1/accounts/testing/fixtures.go, openstack/objectstorage/v1/accounts/testing/requests_test.go, openstack/objectstorage/v1/containers/results.go, openstack/objectstorage/v1/containers/testing/fixtures.go, openstack/objectstorage/v1/containers/testing/requests_test.go, openstack/objectstorage/v1/objects/results.go, openstack/objectstorage/v1/objects/testing/fixtures.go, openstack/objectstorage/v1/objects/testing/requests_test.go
=> More specific types for ObjectStorage response object fields

openstack/objectstorage/v1/objects/results.go, openstack/objectstorage/v1/objects/testing/fixtures.go, openstack/objectstorage/v1/objects/testing/requests_test.go
=> last_modified: rfc1123 -> rfc3339MilliNoZ

acceptance/openstack/compute/v2/compute.go, openstack/compute/v2/servers/requests.go
Fix typos in comments in acceptance tests and
compute package.
=> Fix typos in comments

script/acceptancetest_environments/keystonev2-lbaasv1.sh, script/acceptancetest_environments/keystonev3-lbaasv2.sh
=> Updating acceptance test environment scripts

acceptance/openstack/compute/v2/bootfromvolume_test.go, acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/extensions/bootfromvolume/testing/requests_test.go, openstack/compute/v2/servers/requests.go
=> Allow ImageRef to be empty when block device is present

openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/results.go, openstack/sharedfilesystems/v2/shares/testing/fixtures.go, openstack/sharedfilesystems/v2/shares/testing/request_test.go, openstack/sharedfilesystems/v2/shares/urls.go
Adds support for creating a [`share`][1]. 
For #129  
[1]: http://developer.openstack.org/api-ref/shared-file-systems/?expanded=create-share-detail
=> feature/shared file systems: create share

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/projects/urls.go
=> Identity v3 Projects List

openstack/objectstorage/v1/swauth/requests.go, openstack/objectstorage/v1/swauth/testing/fixtures.go
For #182 
Not sure if this is the best way of doing this.
=> Ensure StorageURL ends in a slash

acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/projects/urls.go
=> Identity v3 Projects Get

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/projects/urls.go
=> Identity v3 Projects Create

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/projects/urls.go
=> Identity v3 Projects Delete

acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/projects/urls.go
=> Identity v3 Projects Update

openstack/compute/v2/extensions/secgroups/results.go, openstack/compute/v2/extensions/secgroups/testing/fixtures.go, openstack/compute/v2/extensions/secgroups/testing/requests_test.go
=> Handle Unmarshaling Compute Security Group IDs

openstack/identity/v2/users/requests.go, openstack/identity/v2/users/testing/fixtures.go
For #208
(Links to source and documentation inside issue)
=> Fixed TenantID struct-tag in user/CommonOpts

openstack/compute/v2/servers/requests.go
=> fixed issue where personality wasn't working in request w/ config_drive

openstack/compute/v2/extensions/floatingips/results.go, openstack/compute/v2/extensions/floatingips/testing/fixtures.go, openstack/compute/v2/extensions/floatingips/testing/requests_test.go
=> Handle Unmarshaling Compute Floating IP IDs

FAQ.md, README.md
=> documenting example usage of a custom HTTP client

STYLEGUIDE.md
=> add item about dependent PRs to style guide

openstack/db/v1/instances/requests.go
For #200 
Adds support for specifying how an instance should be attached to networks when created by introducing the `nics` element supported by Trove:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/service.py#L286
=> db/instance: support giving nics in create opts

openstack/identity/v3/tokens/requests.go, openstack/testing/client_test.go
Fixes #247 for the magnum branch by cherry-picking 9152721b033df1efec3bd89195dc8ebe22a03fa6 from master.
=> Apply v3 auth failure fix to magnum branch

openstack/imageservice/v2/imagedata/requests.go
=> change io.ReadSeeker to io.Reader

acceptance/openstack/blockstorage/extensions/extensions.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go, openstack/blockstorage/extensions/volumeactions/testing/fixtures.go, openstack/blockstorage/extensions/volumeactions/testing/requests_test.go, openstack/blockstorage/extensions/volumeactions/urls.go
=> Add os-volume_upload_image action to volumeactions

openstack/imageservice/v2/images/testing/requests_test.go, pagination/pager.go
=> fix images 'AllPages' paging

acceptance/clients/clients.go, acceptance/openstack/imageservice/v2/images_test.go, acceptance/openstack/imageservice/v2/imageservice.go, openstack/imageservice/v2/images/requests.go, openstack/imageservice/v2/images/testing/fixtures.go, openstack/imageservice/v2/images/testing/requests_test.go
=> ImageService v2: Fixing Create Properties

openstack/compute/v2/servers/requests.go
For #241 
https://github.com/openstack/nova/blob/stable/newton/nova/api/openstack/compute/schemas/servers.py#L151
=> omit empty AdminPass in 'Rebuild' req body

internal/pkg.go
=> internal package

acceptance/openstack/networking/v2/ports_test.go
=> Fixing printing of port resources

acceptance/clients/clients.go, acceptance/openstack/dns/v2/zones.go, acceptance/openstack/dns/v2/zones_test.go, openstack/client.go, openstack/dns/v2/zones/doc.go, openstack/dns/v2/zones/requests.go, openstack/dns/v2/zones/results.go, openstack/dns/v2/zones/testing/doc.go, openstack/dns/v2/zones/testing/fixtures.go, openstack/dns/v2/zones/testing/requests_test.go, openstack/dns/v2/zones/urls.go
For #172 
Supersedes #173 
Here's some more info on the DNS methods: https://github.com/openstack/designate/blob/stable/newton/designate/api/v2/controllers/zones/__init__.py
And on the schema: 
https://github.com/openstack/designate/blob/stable/newton/designate/objects/zone.py
https://github.com/openstack/designate/blob/6ddf20aba5c361629168ce2f3103c1e8052528d5/designate/objects/adapters/base.py
=> DNS Zones: List / Get

acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/extensions/availabilityzones/results.go, openstack/compute/v2/servers/results.go, openstack/compute/v2/servers/testing/requests_test.go
=> Compute v2: Extended Availability Zone Status

openstack/networking/v2/extensions/security/rules/requests.go
For #293
https://github.com/openstack/neutron-lib/blob/stable/mitaka/neutron_lib/constants.py#L115-L135
=> NeutronV2: add protocols

acceptance/openstack/sharedfilesystems/v2/sharenetworks_test.go, acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/sharetypes_test.go
Updates the acceptance tests to pass in a current OpenStack
testing environment.
=> SharedFilesystem v2: Acceptance Test Updates

.github/CONTRIBUTING.md
* add a whitespace in CONTRIBUTING.md
=> fix markdown typo in CONTRIBUTING.md

openstack/identity/v3/tokens/requests.go, openstack/identity/v3/tokens/testing/requests_test.go
=> fix v3 token validate

openstack/sharedfilesystems/v2/shares/testing/fixtures.go
=> quick formatting fix

.travis.yml, script/format
=> add code formatting check for travis ci

acceptance/openstack/dns/v2/dns.go, acceptance/openstack/dns/v2/recordsets_test.go, openstack/dns/v2/recordsets/requests.go, openstack/dns/v2/recordsets/results.go, openstack/dns/v2/recordsets/testing/fixtures.go, openstack/dns/v2/recordsets/testing/requests_test.go
For #56 
Supersedes #176 
URLs:
https://github.com/openstack/designate/blob/master/designate/api/v2/controllers/recordsets.py
https://github.com/openstack/designate/blob/master/designate/api/v2/controllers/common.py
https://github.com/openstack/designate/blob/master/designate/objects/recordset.py
https://github.com/openstack/designate/blob/master/designate/objects/adapters/api_v2/recordset.py
https://github.com/openstack/designate/tree/stable/newton/api-ref/source/samples/recordsets
=> [Pending #279] DNS v2: RecordSet Create, Update, Delete

openstack/networking/v2/extensions/security/groups/requests.go, openstack/networking/v2/extensions/security/groups/results.go, openstack/networking/v2/extensions/security/groups/testing/fixtures.go, openstack/networking/v2/extensions/security/groups/testing/requests_test.go
=> Network v2: Security Group update

openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/testing/fixtures.go, openstack/networking/v2/subnets/testing/requests_test.go
=> Network v2: Subnet AllocationPool update

acceptance/openstack/networking/v2/extensions/fwaas/firewall_test.go, openstack/networking/v2/extensions/fwaas/firewalls/results.go, openstack/networking/v2/extensions/fwaas/firewalls/testing/requests_test.go, openstack/networking/v2/extensions/fwaas/routerinsertion/requests.go, openstack/networking/v2/extensions/fwaas/routerinsertion/results.go, openstack/networking/v2/extensions/fwaas/routerinsertion/testing/requests_test.go
=> Network v2: FWaaS v1 Router Updates

acceptance/openstack/compute/v2/flavors_test.go
=> Compute v2: Fix flavor acceptance tests

openstack/blockstorage/v1/snapshots/results.go, openstack/blockstorage/v1/snapshots/testing/requests_test.go, openstack/blockstorage/v1/volumes/results.go, openstack/blockstorage/v1/volumes/testing/requests_test.go
=> Block Storage v1: Fix time parsing

acceptance/openstack/compute/v2/servergroup_test.go
=> Compute v2: Fix Server Group acceptance test

.travis.yml
=> Travis: Remove Go 1.7 from testing

acceptance/openstack/imageservice/v2/images_test.go
=> ImageService v2: Acceptance tests for listing

openstack/imageservice/v2/images/results.go, openstack/imageservice/v2/images/urls.go
=> Fix broken next URI of ImageService v2 images.List

internal/testing/util_test.go, internal/util.go, openstack/cdn/v1/base/testing/requests_test.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/db/v1/configurations/testing/fixtures.go, openstack/sharedfilesystems/v2/sharetypes/testing/requests_test.go, testhelper/convenience.go, testing/params_test.go
=> Fix testhelper.deepDiffEqual

acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures.go, openstack/identity/v3/users/testing/requests_test.go, openstack/identity/v3/users/urls.go
=> Identity v3: Users Get / List

openstack/identity/v3/tokens/requests.go
=> Identity v3: 401 is not OK for tokens

openstack/imageservice/v2/members/requests.go
=> ImageService v2: Remove 400 codes from members

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures.go, openstack/identity/v3/users/testing/requests_test.go, openstack/identity/v3/users/urls.go
=> Identity v3: Users Create

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures.go, openstack/identity/v3/users/testing/requests_test.go, openstack/identity/v3/users/urls.go
=> Identityv3 users delete

acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures.go, openstack/identity/v3/users/testing/requests_test.go, openstack/identity/v3/users/urls.go
=> Identity v3: Users Update

openstack/dns/v2/zones/requests.go, openstack/identity/v2/tenants/requests.go, openstack/identity/v3/projects/requests.go
=> Fixing occurrences of incorrect required field tags

openstack/identity/v2/tenants/requests.go, openstack/identity/v2/tenants/results.go, openstack/identity/v2/tenants/testing/fixtures.go, openstack/identity/v2/tenants/testing/requests_test.go, openstack/identity/v2/tenants/urls.go
For #397 
delete_tenant general implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/core.py#L314
delete_tenant sql driver implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/backends/sql.py#L354
=> Add tenants V2 delete support

acceptance/openstack/identity/v3/token_test.go, openstack/identity/v3/tokens/results.go, openstack/identity/v3/tokens/testing/fixtures.go, openstack/identity/v3/tokens/testing/results_test.go
For #360
- Roles - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L242
- Project - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L140
- User - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L89
=> [RFR] Extract values from v3 token

openstack/identity/v2/tenants/requests.go, openstack/identity/v2/tenants/results.go, openstack/identity/v2/tenants/testing/fixtures.go, openstack/identity/v2/tenants/testing/requests_test.go, openstack/identity/v2/tenants/urls.go
For #397
delete_tenant general implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/core.py#L305
delete_tenant sql driver implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/backends/sql.py#L340
=> Add tenants V2 update support

acceptance/openstack/identity/v2/identity.go, acceptance/openstack/identity/v2/tenant_test.go
=> Identity v2: Tenant Acceptance Tests

acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go, acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
=> Network v2: Fix Typos in Layer 3 Acceptance Tests

acceptance/openstack/compute/v2/servers_test.go
=> Compute v2: Adding Pause/Unpause Acceptance Test

acceptance/openstack/compute/v2/servers_test.go
=> Compute v2: Add Suspend Acceptance Test

acceptance/openstack/networking/v2/extensions/extensions.go, openstack/networking/v2/extensions/external/requests.go, openstack/networking/v2/extensions/external/results.go, openstack/networking/v2/extensions/external/testing/fixtures.go, openstack/networking/v2/extensions/external/testing/results_test.go, openstack/networking/v2/extensions/provider/results.go, openstack/networking/v2/extensions/provider/testing/results_test.go, openstack/networking/v2/networks/results.go, openstack/networking/v2/networks/testing/fixtures.go, openstack/networking/v2/networks/testing/requests_test.go, results.go, testing/results_test.go
=> Extensions Refactor

openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go
=> BlockStorage v2: Fix small issues with volumeactions

acceptance/openstack/blockstorage/extensions/schedulerstats_test.go, openstack/blockstorage/extensions/schedulerstats/doc.go, openstack/blockstorage/extensions/schedulerstats/requests.go, openstack/blockstorage/extensions/schedulerstats/results.go
=> BlockStorage v2: Updating docs for schedulerstats

openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/results.go, openstack/sharedfilesystems/v2/shares/testing/fixtures.go, openstack/sharedfilesystems/v2/shares/testing/request_test.go, openstack/sharedfilesystems/v2/shares/urls.go
For #315 
https://github.com/openstack/manila/blob/stable/newton/manila/api/v1/shares.py#L393
=> Shared Filesystems: Grant Access

acceptance/openstack/blockstorage/extensions/extensions.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, openstack/blockstorage/extensions/volumeactions/doc.go, openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go
For #446 
This also contains the fixes in #452, so this should be merged (and possibly rebased) after that.
=> BlockStorage v2: Updating docs for volumeactions

openstack/auth_env.go, openstack/client.go, openstack/doc.go, openstack/endpoint_location.go
=> Docs: Updating openstack package

openstack/compute/v2/extensions/attachinterfaces/doc.go, openstack/compute/v2/extensions/attachinterfaces/requests.go, openstack/compute/v2/extensions/attachinterfaces/results.go
=> Compute v2: attachinterface docs

openstack/compute/v2/extensions/bootfromvolume/doc.go, openstack/compute/v2/extensions/bootfromvolume/results.go
=> Compute v2: bootfromvolume docs

openstack/compute/v2/extensions/defsecrules/doc.go, openstack/compute/v2/extensions/defsecrules/requests.go, openstack/compute/v2/extensions/defsecrules/results.go
=> Compute v2: defsecrules docs

openstack/compute/v2/extensions/floatingips/doc.go, openstack/compute/v2/extensions/floatingips/requests.go, openstack/compute/v2/extensions/floatingips/results.go
=> Compute v2: floatingips docs

openstack/compute/v2/extensions/hypervisors/doc.go, openstack/compute/v2/extensions/hypervisors/results.go
=> Compute v2: hypervisors docs

openstack/compute/v2/extensions/keypairs/doc.go, openstack/compute/v2/extensions/keypairs/requests.go, openstack/compute/v2/extensions/keypairs/results.go
=> Compute v2: keypairs docs

openstack/compute/v2/extensions/limits/doc.go, openstack/compute/v2/extensions/limits/requests.go, openstack/compute/v2/extensions/limits/results.go
=> Compute v2: limits docs

openstack/compute/v2/extensions/pauseunpause/doc.go
=> Compute v2: pauseunpause docs

openstack/compute/v2/extensions/networks/doc.go, openstack/compute/v2/extensions/networks/results.go
=> Compute v2: networks docs

openstack/compute/v2/extensions/quotasets/doc.go, openstack/compute/v2/extensions/quotasets/requests.go, openstack/compute/v2/extensions/quotasets/results.go
=> Compute v2: quotasets docs

openstack/compute/v2/extensions/startstop/doc.go
=> Compute v2: startstop docs

openstack/compute/v2/extensions/suspendresume/doc.go
=> Compute v2: suspendresume docs

openstack/compute/v2/extensions/schedulerhints/doc.go, openstack/compute/v2/extensions/schedulerhints/requests.go
=> Compute v2: schedulerhints docs

openstack/compute/v2/extensions/tenantnetworks/doc.go, openstack/compute/v2/extensions/tenantnetworks/requests.go, openstack/compute/v2/extensions/tenantnetworks/results.go
=> Compute v2: tenantnetwork docs

openstack/compute/v2/extensions/volumeattach/doc.go, openstack/compute/v2/extensions/volumeattach/requests.go, openstack/compute/v2/extensions/volumeattach/results.go
=> Compute v2: volumeattach docs

openstack/compute/v2/images/doc.go, openstack/compute/v2/images/requests.go, openstack/compute/v2/images/results.go
=> Compute v2: images docs

openstack/compute/v2/flavors/doc.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go
=> Compute v2: flavors docs

openstack/compute/v2/servers/doc.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/results.go, openstack/compute/v2/servers/util.go
=> Compute v2: servers docs

openstack/dns/v2/recordsets/doc.go, openstack/dns/v2/recordsets/requests.go, openstack/dns/v2/recordsets/results.go, openstack/dns/v2/zones/doc.go, openstack/dns/v2/zones/requests.go, openstack/dns/v2/zones/results.go
=> DNS v2: doc updates

auth_options.go, errors.go, openstack/identity/v3/tokens/requests.go, openstack/identity/v3/tokens/testing/requests_test.go
For #252
https://github.com/openstack/python-keystoneclient/blob/67b1cd3705c0e45f0304f8a9d008b03f554ec7d2/keystoneclient/auth/identity/v3/base.py#L165
=> Domain name scoping

openstack/identity/v3/endpoints/doc.go, openstack/identity/v3/endpoints/requests.go, openstack/identity/v3/endpoints/results.go, openstack/identity/v3/extensions/trusts/doc.go, openstack/identity/v3/extensions/trusts/requests.go, openstack/identity/v3/extensions/trusts/results.go, openstack/identity/v3/groups/doc.go, openstack/identity/v3/projects/doc.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/roles/doc.go, openstack/identity/v3/roles/requests.go, openstack/identity/v3/roles/results.go, openstack/identity/v3/services/doc.go, openstack/identity/v3/services/requests.go, openstack/identity/v3/services/results.go, openstack/identity/v3/tokens/doc.go, openstack/identity/v3/tokens/requests.go, openstack/identity/v3/tokens/results.go, openstack/identity/v3/users/doc.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go
=> Identity v3: Docs

openstack/blockstorage/extensions/volumeactions/doc.go, openstack/compute/v2/extensions/attachinterfaces/doc.go, openstack/compute/v2/extensions/defsecrules/doc.go, openstack/compute/v2/extensions/floatingips/doc.go, openstack/compute/v2/extensions/hypervisors/doc.go, openstack/compute/v2/extensions/keypairs/doc.go, openstack/compute/v2/extensions/limits/doc.go, openstack/compute/v2/extensions/networks/doc.go, openstack/compute/v2/extensions/quotasets/doc.go, openstack/compute/v2/extensions/tenantnetworks/doc.go, openstack/compute/v2/flavors/doc.go, openstack/compute/v2/images/doc.go, openstack/compute/v2/servers/doc.go, openstack/dns/v2/recordsets/doc.go, openstack/dns/v2/zones/doc.go, openstack/identity/v2/extensions/admin/roles/doc.go, openstack/identity/v2/tenants/doc.go, openstack/identity/v2/users/doc.go, openstack/identity/v3/endpoints/doc.go, openstack/identity/v3/projects/doc.go, openstack/identity/v3/roles/doc.go
=> Docs: Replace Println with Printf

openstack/imageservice/v2/imagedata/doc.go, openstack/imageservice/v2/imagedata/requests.go, openstack/imageservice/v2/imagedata/results.go, openstack/imageservice/v2/images/doc.go, openstack/imageservice/v2/images/requests.go, openstack/imageservice/v2/images/results.go, openstack/imageservice/v2/images/types.go, openstack/imageservice/v2/members/doc.go, openstack/imageservice/v2/members/requests.go, openstack/imageservice/v2/members/results.go
=> ImageService v2: Docs

acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/extensions/availabilityzones/doc.go, openstack/compute/v2/extensions/availabilityzones/results.go, openstack/compute/v2/servers/testing/requests_test.go
=> Compute v2: Clean up availabilityzones

openstack/compute/v2/flavors/requests.go
=> Compute v2: Use value receiver for ToFlavorCreateMap

openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go, openstack/compute/v2/flavors/urls.go
Add support for deleting flavors.
For #500
=> Flavors support delete update

acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/flavors_test.go
=> Compute v2: Flavor acceptance test

openstack/compute/v2/extensions/secgroups/doc.go, openstack/compute/v2/extensions/secgroups/requests.go, openstack/compute/v2/extensions/secgroups/results.go, openstack/compute/v2/extensions/servergroups/doc.go, openstack/compute/v2/extensions/servergroups/requests.go, openstack/compute/v2/extensions/servergroups/results.go
=> Compute v2: Forgotten Docs

openstack/sharedfilesystems/v2/sharetypes/requests.go, openstack/sharedfilesystems/v2/sharetypes/testing/requests_test.go
=> SharedFilesystems v2: Change Specs to ExtraSpecs

openstack/client.go, openstack/testing/client_test.go, openstack/utils/choose_version.go
For #424 
Supersedes #423, but there's useful discussion in #423 to reference.
=> Identity Versionless Endpoint

openstack/compute/v2/extensions/defsecrules/requests.go, openstack/compute/v2/extensions/defsecrules/results.go, openstack/compute/v2/extensions/lockunlock/results.go, openstack/compute/v2/extensions/migrate/results.go, openstack/compute/v2/extensions/pauseunpause/requests.go, openstack/compute/v2/extensions/pauseunpause/results.go, openstack/compute/v2/extensions/secgroups/requests.go, openstack/compute/v2/extensions/secgroups/results.go, openstack/compute/v2/extensions/startstop/requests.go, openstack/compute/v2/extensions/startstop/results.go, openstack/compute/v2/extensions/suspendresume/requests.go, openstack/compute/v2/extensions/suspendresume/results.go
=> Compute v2: Small Extension Fixes

openstack/networking/v2/extensions/layer3/routers/results.go, openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go
For #515
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/l3.py#L93-L99
=> Networking v2: Routers: Parse external_fixed_ips

acceptance/openstack/identity/v3/groups_test.go, acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/groups/doc.go, openstack/identity/v3/groups/requests.go, openstack/identity/v3/groups/results.go, openstack/identity/v3/groups/testing/fixtures.go, openstack/identity/v3/groups/testing/requests_test.go, openstack/identity/v3/groups/urls.go
For #539
List:
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/controllers.py#L327
Get:
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/controllers.py#L340
=> Identity v3 Groups Get / List

acceptance/openstack/identity/v3/groups_test.go, openstack/identity/v3/groups/doc.go, openstack/identity/v3/groups/requests.go, openstack/identity/v3/groups/results.go, openstack/identity/v3/groups/testing/fixtures.go, openstack/identity/v3/groups/testing/requests_test.go, openstack/identity/v3/groups/urls.go
For #539 
Update:
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/controllers.py#L345
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/backends/sql.py#L381
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/schema.py#L113
=> Identity v3: group update

acceptance/openstack/identity/v3/domains_test.go, acceptance/openstack/identity/v3/identity.go, openstack/identity/v3/domains/doc.go, openstack/identity/v3/domains/requests.go, openstack/identity/v3/domains/results.go, openstack/identity/v3/domains/testing/fixtures.go, openstack/identity/v3/domains/testing/requests_test.go, openstack/identity/v3/domains/urls.go
For #555
Create:
https://github.com/openstack/keystone/blob/master/keystone/resource/schema.py#L57
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/resource/controllers.py#L132
=> Identity v3: domain create

acceptance/openstack/identity/v3/domains_test.go, acceptance/openstack/identity/v3/identity.go, openstack/identity/v3/domains/doc.go, openstack/identity/v3/domains/requests.go, openstack/identity/v3/domains/results.go, openstack/identity/v3/domains/testing/fixtures.go, openstack/identity/v3/domains/testing/requests_test.go, openstack/identity/v3/domains/urls.go
For #555
Delete:
https://github.com/openstack/keystone/blob/master/keystone/resource/core.py#L751
https://github.com/openstack/keystone/blob/master/keystone/resource/core.py#L780
Controller / router:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/resource/controllers.py#L162
=> Identity v3: Domain delete

acceptance/openstack/identity/v3/domains_test.go, openstack/identity/v3/domains/doc.go, openstack/identity/v3/domains/requests.go, openstack/identity/v3/domains/results.go, openstack/identity/v3/domains/testing/fixtures.go, openstack/identity/v3/domains/testing/requests_test.go, openstack/identity/v3/domains/urls.go
For #555
Update:
https://github.com/openstack/keystone/blob/master/keystone/resource/core.py#L733
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/resource/controllers.py#L153
=> Identity v3: Domain update

openstack/identity/v3/users/results.go
trivial fix to update inaccurate comment
=> fix user delete result comment

openstack/networking/v2/extensions/layer3/routers/results.go, openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go
For #573
https://github.com/openstack/neutron/blob/97af09672735fb9d2742e23f3a6e94331d92e3cc/neutron/extensions/l3_ext_gw_mode.py#L32
=> allow to configure the enable_snat parameter

acceptance/openstack/networking/v2/extensions/layer3/layer3.go, acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
=> Networking v2: Add SNAT to external router acceptance test

openstack/imageservice/v2/images/requests.go
Hi!
For #579 
https://github.com/openstack/glance/blob/stable/pike/glance/api/v2/images.py#L683
Links to the docs:
https://specs.openstack.org/openstack/glance-specs/specs/api/v2/lists-image-api-v2.html
=> support for sort new syntax

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/roles_test.go, openstack/identity/v3/roles/doc.go, openstack/identity/v3/roles/requests.go, openstack/identity/v3/roles/results.go, openstack/identity/v3/roles/testing/fixtures.go, openstack/identity/v3/roles/testing/requests_test.go, openstack/identity/v3/roles/urls.go
For #571 
Delete:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L383
=> Identity v3 delete role

openstack/identity/v3/roles/testing/fixtures.go, openstack/identity/v3/roles/testing/requests_test.go
=> Updating old role assignment test

internal/testing/pkg.go, openstack/client.go, openstack/compute/v2/flavors/requests.go, pagination/pager.go
For #590
https://github.com/openstack/openstack-ansible-os_octavia/blob/stable/pike/defaults/main.yml#L122
=> add NewLoadBalancerV2 service client

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/regions_test.go, openstack/identity/v3/regions/doc.go, openstack/identity/v3/regions/requests.go, openstack/identity/v3/regions/results.go, openstack/identity/v3/regions/testing/fixtures.go, openstack/identity/v3/regions/testing/requests_test.go, openstack/identity/v3/regions/urls.go
For #583 
Delete:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L92
=> Identity v3 region delete

acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/flavors_test.go, openstack/compute/v2/flavors/doc.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go, openstack/compute/v2/flavors/urls.go
=> Compute v2: flavor access list

acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/quotaset_test.go, openstack/compute/v2/extensions/quotasets/requests.go, openstack/compute/v2/extensions/quotasets/results.go, openstack/compute/v2/extensions/quotasets/testing/fixtures.go
=> Quotaset field rename

acceptance/openstack/compute/v2/compute.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go
For #625 
https://github.com/openstack/nova/blob/1878039f8fcf757651c7923910a253f187891576/nova/api/openstack/compute/views/flavors.py#L48-L89
=> Compute v2: Fix Flavor IsPublic field

acceptance/openstack/networking/v2/networks_test.go, openstack/networking/v2/extensions/portsecurity/doc.go, openstack/networking/v2/extensions/portsecurity/results.go, openstack/networking/v2/networks/testing/fixtures.go, openstack/networking/v2/networks/testing/requests_test.go, openstack/networking/v2/ports/testing/fixtures.go, openstack/networking/v2/ports/testing/requests_test.go
=> Network v2: Port Security Get / List

openstack/blockstorage/v2/snapshots/requests.go, openstack/blockstorage/v2/volumes/requests.go, openstack/blockstorage/v3/snapshots/requests.go, openstack/blockstorage/v3/volumes/requests.go
=> BlockStorage v2/v3: Reorder snapshot/volume ListOpts and update godoc

acceptance/openstack/objectstorage/v1/objects_test.go, openstack/objectstorage/v1/objects/results.go, openstack/objectstorage/v1/objects/testing/fixtures.go, openstack/objectstorage/v1/objects/testing/requests_test.go
For #588 
Supersedes #589 
https://github.com/openstack/python-swiftclient/blob/c50823ebf1fc3d691e1589321fb03a6464604530/swiftclient/client.py#L910-L913
=> Object Storage v1: Subdir Support

acceptance/openstack/blockstorage/v2/volumes_test.go
For #637 
I'm curious if this will pass OpenLab tests. I believe this is an admin-only action. If the test fails, I'll modify it to only run if the username is `admin`.
=> AccTests: BlockStorage v2 ForceDelete

acceptance/openstack/compute/v2/attachinterfaces_test.go
=> Compute v2: attachinterfaces acceptance test

openstack/db/v1/configurations/results.go, openstack/db/v1/configurations/testing/fixtures.go
For #647
Fixes time parsing error.
=> Configuration group time parsing error 

acceptance/openstack/db/v1/configurations_test.go
=> DBv1: configurations acceptance test

openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/results.go, openstack/networking/v2/subnets/testing/fixtures.go, openstack/networking/v2/subnets/testing/requests_test.go
=> Add support for ipv6_address_mode and ipv6_ra_mode in subnets

openstack/networking/v2/networks/requests.go, openstack/networking/v2/networks/results.go, openstack/networking/v2/networks/testing/fixtures.go, openstack/networking/v2/networks/testing/requests_test.go
=> availability_zone_hints for network(s)

openstack/networking/v2/extensions/layer3/routers/requests.go, openstack/networking/v2/extensions/layer3/routers/results.go, openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go
=> Support for setting availability_zone_hints to a router

.github/CONTRIBUTING.md, STYLEGUIDE.md
For #668 
/cc @dklyle (Github isn't letting me request a review from you). I'm also interested if you have any comments/thoughts which might be useful from when you started working on Gophercloud.
=> Docs: Updating Contributing and Style Guides 

acceptance/openstack/blockstorage/v3/volumetypes_test.go
=> BlockStorage v3: volumetype get/list acc test

acceptance/openstack/blockstorage/v3/blockstorage.go, acceptance/openstack/blockstorage/v3/pkg.go, acceptance/openstack/blockstorage/v3/volumes_test.go
=> Add basic CRUD acceptance testcases in volume V3

acceptance/openstack/blockstorage/v3/blockstorage.go, acceptance/openstack/blockstorage/v3/snapshots_test.go
=> Add basic CRUD acceptance testcases in snapshot V3

acceptance/openstack/blockstorage/v3/volumetypes_test.go
=> Fix incorrect variable name

acceptance/openstack/compute/v2/flavors_test.go, openstack/compute/v2/flavors/doc.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go, openstack/compute/v2/flavors/urls.go
For #506 
Code and reference is listed in #506
=> Compute v2: Flavor Access Add

openstack/compute/v2/extensions/availabilityzones/doc.go, openstack/compute/v2/extensions/availabilityzones/results.go
Just some minor fixes.
For #320
=> Compute v2: Update docs for Availability Zones

acceptance/openstack/compute/v2/flavors_test.go, openstack/compute/v2/flavors/doc.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go
For #506 
Code and reference is listed in #506
=> Compute v2: Flavor Access Remove

openstack/compute/v2/flavors/testing/requests_test.go
=> Compute v2: Add unit tests for Ephemeral field

openstack/compute/v2/extensions/aggregates/doc.go, openstack/compute/v2/extensions/aggregates/requests.go, openstack/compute/v2/extensions/aggregates/results.go, openstack/compute/v2/extensions/aggregates/testing/fixtures.go, openstack/compute/v2/extensions/aggregates/testing/requests_test.go, openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc:
- https://developer.openstack.org/api-ref/compute/#show-aggregate-details
Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L88
=> Compute v2: Get aggregate

openstack/compute/v2/extensions/aggregates/results.go, openstack/compute/v2/extensions/aggregates/testing/fixtures.go
=> Add missing `Deleted` and `DeletedAt` fields

acceptance/openstack/compute/v2/aggregates_test.go, openstack/compute/v2/extensions/aggregates/doc.go, openstack/compute/v2/extensions/aggregates/requests.go, openstack/compute/v2/extensions/aggregates/results.go, openstack/compute/v2/extensions/aggregates/testing/fixtures.go, openstack/compute/v2/extensions/aggregates/testing/requests_test.go, openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc: 
- https://developer.openstack.org/api-ref/compute/#update-aggregate
Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L101
=> Compute v2: Update aggregate

openstack/compute/v2/flavors/requests.go
For #761 
/cc @dklyle (I think Github won't let me request a review because you aren't a collaborator for this repo?)
=> Compute v2: Fix flavor extra spec builder names

acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/requests.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/results.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L440
=>  Vpnaas: Delete IPSec policy

acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/requests.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/results.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L449
=> Vpnaas: Show IPSec Policy Details

openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go, openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go
=> Networking v2: VPNaaS Doc fixes

acceptance/openstack/networking/v2/extensions/vpnaas/service_test.go, openstack/networking/v2/extensions/vpnaas/services/doc.go, openstack/networking/v2/extensions/vpnaas/services/requests.go, openstack/networking/v2/extensions/vpnaas/services/results.go, openstack/networking/v2/extensions/vpnaas/services/testing/requests_test.go
For #723 
List:
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L531
Get:
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L526
API:
https://developer.openstack.org/api-ref/network/v2/#show-vpn-service-details
https://developer.openstack.org/api-ref/network/v2/#list-vpn-services
=> Vpnaas: Service Get/List

acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicy_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L358
=> Vpnaas: Delete IKE policy

acceptance/openstack/networking/v2/extensions/vpnaas/group_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/testing/requests_test.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/urls.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L583
=>  Vpnaas: Create Endpoint Group

errors.go, provider_client.go
=> Add support for custom 403 error handling

acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicy_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L454
=> Vpnaas: List IKE policies

acceptance/openstack/networking/v2/extensions/vpnaas/group_test.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L621
=>  Vpnaas: Get Endpoint Group

acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicy_test.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L338
=>  Vpnaas: Update IKE policy

acceptance/openstack/networking/v2/extensions/vpnaas/group_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L614
=>  Vpnaas: Delete Endpoint Group

.github/CONTRIBUTING.md
=> Docs: Update CONTRIBUTING Guide

acceptance/clients/clients.go, acceptance/clients/http.go
For #818 
This commit adds the ability to view the OpenStack API JSON
requests and responses during acceptance test execution by
setting the OS_DEBUG environment variable to 1/true/yes.
This implementation is based on Terraform's.
/cc @dklyle
=> Acc: Add Debug Logging

acceptance/clients/clients.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/testing/requests_test.go
For #830 
https://github.com/openstack/octavia/blob/2d206289d005737d87f7712ba443a345d5547b18/octavia/api/v2/controllers/load_balancer.py#L451
=> add cascade option to loadbalancers.Delete

acceptance/openstack/networking/v2/networks_test.go, acceptance/openstack/networking/v2/ports_test.go, openstack/networking/v2/extensions/portsecurity/doc.go, openstack/networking/v2/extensions/portsecurity/requests.go, openstack/networking/v2/networks/testing/fixtures.go, openstack/networking/v2/networks/testing/requests_test.go, openstack/networking/v2/ports/testing/fixtures.go, openstack/networking/v2/ports/testing/requests_test.go
=> Networking v2: Port Security Update

acceptance/openstack/networking/v2/extensions/vpnaas/siteconnection_test.go, openstack/networking/v2/extensions/vpnaas/services/requests.go, openstack/networking/v2/extensions/vpnaas/siteconnections/doc.go, openstack/networking/v2/extensions/vpnaas/siteconnections/requests.go, openstack/networking/v2/extensions/vpnaas/siteconnections/results.go, openstack/networking/v2/extensions/vpnaas/siteconnections/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L270
=>  Vpnaas: List IPSec site connections

acceptance/openstack/networking/v2/extensions/vpnaas/group_test.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go, openstack/networking/v2/extensions/vpnaas/endpointgroups/testing/requests_test.go
For #723
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L603
https://github.com/openstack/neutron-vpnaas/blob/7afbde584aec3b0401b0431d358ae3e1ad359da9/neutron_vpnaas/extensions/vpn_endpoint_groups.py#L31
=> Vpnaas: Update endpoint groups

acceptance/openstack/clustering/v1/policytypes_test.go, openstack/clustering/v1/policytypes/doc.go, openstack/clustering/v1/policytypes/requests.go, openstack/clustering/v1/policytypes/results.go, openstack/clustering/v1/policytypes/testing/fixtures.go, openstack/clustering/v1/policytypes/testing/requests_test.go, openstack/clustering/v1/policytypes/urls.go
For #823 
API doc:
https://developer.openstack.org/api-ref/clustering/#show-policy-type-details
API code:
https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/policy_types.py#L43
=> Clustering PolicyType Get implementation

acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/doc.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures.go, openstack/identity/v3/users/testing/requests_test.go, openstack/identity/v3/users/urls.go
For #874 
API reference:
[Identity API v3 - Remove user from group](https://developer.openstack.org/api-ref/identity/v3/#remove-user-from-group)
Python source code:
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/routers.py#L49
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/core.py#L1273
https://github.com/openstack/python-keystoneclient/blob/40642d597deecce4dd81428449353bbd0c2ad5be/keystoneclient/v3/users.py#L266
=> Identity V3: remove user from group

acceptance/openstack/compute/v2/secgroup_test.go
=> Acc tests: Fix TestSecGroupsAddGroupToServer

.travis.yml, openstack/compute/v2/extensions/quotasets/testing/fixtures.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go, script/format
=> Fix go tip gofmt errors

service_client.go, testing/service_client_test.go
=> add MoreHeaders field to ServiceClient

acceptance/clients/conditions.go, acceptance/openstack/identity/v2/extension_test.go, acceptance/openstack/identity/v2/identity.go, acceptance/openstack/identity/v2/role_test.go, acceptance/openstack/identity/v2/tenant_test.go, acceptance/openstack/identity/v2/token_test.go, acceptance/openstack/identity/v2/user_test.go, acceptance/openstack/identity/v3/domains_test.go, acceptance/openstack/identity/v3/endpoint_test.go, acceptance/openstack/identity/v3/groups_test.go, acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/projects_test.go, acceptance/openstack/identity/v3/regions_test.go, acceptance/openstack/identity/v3/roles_test.go, acceptance/openstack/identity/v3/service_test.go, acceptance/openstack/identity/v3/token_test.go, acceptance/openstack/identity/v3/users_test.go
=> Acc Tests: Update Identity Tests

openstack/client.go, openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/doc.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L76
=> Messaging Queue Create

acceptance/clients/conditions.go, acceptance/openstack/dns/v2/dns.go, acceptance/openstack/dns/v2/recordsets_test.go, acceptance/openstack/dns/v2/zones_test.go
=> Test Acc: Updating DNS Tests

openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L253
=> Messaging Queue List

acceptance/openstack/clustering/v1/policies_test.go, openstack/clustering/v1/policies/doc.go, openstack/clustering/v1/policies/requests.go, openstack/clustering/v1/policies/results.go, openstack/clustering/v1/policies/testing/fixtures.go, openstack/clustering/v1/policies/testing/requests_test.go, openstack/clustering/v1/policies/urls.go
For #823 
API doc:
https://developer.openstack.org/api-ref/clustering/#create-policy
API code:
https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/policies.py#L57
=> Clustering Policy Create Implementation

acceptance/openstack/clustering/v1/policies_test.go, openstack/clustering/v1/policies/requests.go, openstack/clustering/v1/policies/results.go, openstack/clustering/v1/policies/testing/fixtures.go, openstack/clustering/v1/policies/testing/requests_test.go, openstack/clustering/v1/policies/urls.go
For #823
API doc:
https://developer.openstack.org/api-ref/clustering/#delete-policy
API code:
https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/policies.py#L89
https://github.com/openstack/senlin/blob/master/senlin/engine/service.py#L637
=> Clustering Policy Delete Implementation

acceptance/clients/clients.go, acceptance/openstack/messaging/v2/messaging.go, acceptance/openstack/messaging/v2/queue_test.go, openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L43
=> Messaging Queue Acceptance Tests

openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L55
=> Messaging Queue Get

openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L109
=> Messaging Queue Delete

acceptance/openstack/messaging/v2/queue_test.go, openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/stats.py#L38
=> Messaging Queue Stats

openstack/compute/v2/extensions/quotasets/requests.go
=> Compute v2: Style fixes for quotasets

acceptance/openstack/messaging/v2/messaging.go, acceptance/openstack/messaging/v2/queue_test.go, openstack/messaging/v2/queues/doc.go, openstack/messaging/v2/queues/requests.go, openstack/messaging/v2/queues/results.go, openstack/messaging/v2/queues/testing/fixtures.go, openstack/messaging/v2/queues/testing/requests_test.go, openstack/messaging/v2/queues/urls.go
For #836 
https://github.com/openstack/zaqar/blob/28f1f0f9370c395023bc5ae01693e5d952b3e1c1/zaqar/transport/wsgi/v2_0/urls.py#L43
=> Messaging Queue Share

openstack/clustering/v1/webhooks/requests.go
=> Fix query tag format

acceptance/openstack/clustering/v1/actions_test.go, acceptance/openstack/clustering/v1/webhooktrigger_test.go
=> Clustering v1: Fixing acceptance tests

acceptance/openstack/messaging/v2/message_test.go, acceptance/openstack/messaging/v2/messaging.go, acceptance/openstack/messaging/v2/queue_test.go, openstack/messaging/v2/messages/doc.go, openstack/messaging/v2/messages/requests.go, openstack/messaging/v2/messages/results.go, openstack/messaging/v2/messages/testing/doc.go, openstack/messaging/v2/messages/testing/fixtures.go, openstack/messaging/v2/messages/testing/requests_test.go, openstack/messaging/v2/messages/urls.go, openstack/messaging/v2/queues/requests.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/messages.py#L170
=> Add Create for messages

openstack/objectstorage/v1/containers/doc.go, openstack/objectstorage/v1/objects/doc.go
=> Object Storage v1: Doc update

acceptance/openstack/messaging/v2/message_test.go, openstack/messaging/v2/messages/doc.go, openstack/messaging/v2/messages/requests.go, openstack/messaging/v2/messages/results.go, openstack/messaging/v2/messages/testing/fixtures.go, openstack/messaging/v2/messages/testing/requests_test.go, openstack/messaging/v2/messages/urls.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/messages.py#L255
=> Messaging Message List

openstack/identity/v3/tokens/requests.go, openstack/identity/v3/users/requests.go, openstack/objectstorage/v1/accounts/requests.go, openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/objects/requests.go, service_client.go
=> Service Client: add HEAD method

openstack/clustering/v1/actions/doc.go, openstack/clustering/v1/actions/requests.go, openstack/clustering/v1/actions/results.go, openstack/clustering/v1/actions/testing/requests_test.go, openstack/clustering/v1/actions/urls.go
[[actions:get]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/actions.py#L96)
https://github.com/openstack/senlin/blob/98d8cf30a374858079eed653b2acbf9dd5d57318/senlin/objects/action.py#L29
https://github.com/openstack/senlin/blob/98d8cf30a374858079eed653b2acbf9dd5d57318/senlin/objects/action.py#L179
=> Senlin: Actions Get

acceptance/openstack/clustering/v1/policies_test.go, openstack/clustering/v1/actions/urls.go, openstack/clustering/v1/policies/doc.go, openstack/clustering/v1/policies/requests.go, openstack/clustering/v1/policies/results.go, openstack/clustering/v1/policies/testing/fixtures.go, openstack/clustering/v1/policies/testing/requests_test.go, openstack/clustering/v1/policies/urls.go
[[policies:validate]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/policies.py#L97)
=> Clustering Policy Validate Implementation

openstack/container/v1/capsules/results.go, openstack/container/v1/capsules/testing/fixtures.go, openstack/container/v1/capsules/testing/requests_test.go
For #700 
Container: https://review.openstack.org/565085
Host: https://review.openstack.org/564695
Status_reason is already inside the return value before.
=> Add container dict, host, status_reason field to capsule

openstack/identity/v3/endpoints/requests.go
=> Identity V3: Fix Fields of Struct endpoints.ListOpts

.gitignore
=> Git: Ignore .vscode

acceptance/openstack/container/v1/capsules_test.go, openstack/container/v1/capsules/requests.go, openstack/container/v1/capsules/results.go, openstack/container/v1/capsules/testing/fixtures.go, openstack/container/v1/capsules/testing/requests_test.go, openstack/container/v1/capsules/urls.go
For #700 
Depends-on: #944 
Reference:
https://github.com/openstack/zun/blob/master/zun/api/controllers/v1/capsules.py#L85
=> Add Zun Capsule List Operation

acceptance/openstack/messaging/v2/message_test.go, openstack/messaging/v2/messages/doc.go, openstack/messaging/v2/messages/requests.go, openstack/messaging/v2/messages/results.go, openstack/messaging/v2/messages/testing/fixtures.go, openstack/messaging/v2/messages/testing/requests_test.go, openstack/messaging/v2/messages/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/messages.py#L254
=> Messaging Message GetMessages

acceptance/openstack/identity/v3/users_test.go, openstack/identity/v3/users/errors.go, openstack/identity/v3/users/requests.go, openstack/identity/v3/users/testing/requests_test.go, params.go
=> Identity V3: Add Filters into Struct users.ListOpts

acceptance/openstack/identity/v3/projects_test.go, openstack/identity/v3/projects/errors.go, openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/testing/requests_test.go
=> Add Field *Filters* into Struct projects.ListOpts

acceptance/openstack/identity/v3/groups_test.go, openstack/identity/v3/groups/errors.go, openstack/identity/v3/groups/requests.go, openstack/identity/v3/groups/testing/requests_test.go
=> Add Field *Filters* into Struct groups.ListOpts

acceptance/openstack/container/v1/capsules_test.go, openstack/container/v1/capsules/requests.go, openstack/container/v1/capsules/results.go, openstack/container/v1/capsules/testing/fixtures.go, openstack/container/v1/capsules/testing/requests_test.go, openstack/container/v1/capsules/urls.go
For #700 
Depends-on: #944 #955
=> Add capsule delete operation

acceptance/openstack/messaging/v2/message_test.go, openstack/messaging/v2/messages/doc.go, openstack/messaging/v2/messages/requests.go, openstack/messaging/v2/messages/testing/fixtures.go, openstack/messaging/v2/messages/testing/requests_test.go, openstack/messaging/v2/messages/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/messages.py#L375
=> Messaging Message Delete Message

acceptance/openstack/identity/v3/policies_test.go, openstack/identity/v3/policies/doc.go, openstack/identity/v3/policies/errors.go, openstack/identity/v3/policies/requests.go, openstack/identity/v3/policies/results.go, openstack/identity/v3/policies/testing/fixtures.go, openstack/identity/v3/policies/testing/requests_test.go, openstack/identity/v3/policies/urls.go
=> Identity V3: Create Policy

acceptance/openstack/identity/v3/roles_test.go, openstack/identity/v3/roles/errors.go, openstack/identity/v3/roles/requests.go, openstack/identity/v3/roles/testing/requests_test.go
=> Add Field *Filters* into Struct roles.ListOpts

acceptance/openstack/identity/v3/policies_test.go, openstack/identity/v3/policies/doc.go, openstack/identity/v3/policies/requests.go, openstack/identity/v3/policies/results.go, openstack/identity/v3/policies/testing/fixtures.go, openstack/identity/v3/policies/testing/requests_test.go, openstack/identity/v3/policies/urls.go
=> Identity V3: Delete Policy

acceptance/openstack/identity/v3/policies_test.go, openstack/identity/v3/policies/doc.go, openstack/identity/v3/policies/requests.go, openstack/identity/v3/policies/results.go, openstack/identity/v3/policies/testing/fixtures.go, openstack/identity/v3/policies/testing/requests_test.go, openstack/identity/v3/policies/urls.go
=> Identity V3: Get Policy

acceptance/openstack/clustering/v1/autoscaling_test.go, openstack/clustering/v1/clusters/testing/requests_test.go, openstack/clustering/v1/profiles/doc.go, openstack/clustering/v1/profiles/requests.go, openstack/clustering/v1/profiles/results.go, openstack/clustering/v1/profiles/testing/requests_test.go, openstack/clustering/v1/profiles/urls.go
[[profiles:list]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L75)
=> Senlin: Profiles List

acceptance/openstack/identity/v3/policies_test.go, openstack/identity/v3/policies/doc.go, openstack/identity/v3/policies/requests.go, openstack/identity/v3/policies/results.go, openstack/identity/v3/policies/testing/fixtures.go, openstack/identity/v3/policies/testing/requests_test.go, openstack/identity/v3/policies/urls.go
=> Identity V3: Update Policy

.zuul/playbooks/gophercloud-acceptance-test/run.yaml, .zuul/playbooks/gophercloud-unittest/run.yaml, script/acceptancetest, script/stackenv
Remove the unused theopenlab/gophercloud branches.
Put env variables setup for accp test into script/stackenv.
Move the test case enable/disable to script/acceptancetest.
Closed #994
=> Acceptance test job definition cleanup

acceptance/openstack/clustering/v1/autoscaling_test.go, openstack/clustering/v1/clusters/doc.go, openstack/clustering/v1/clusters/requests.go, openstack/clustering/v1/clusters/results.go, openstack/clustering/v1/clusters/testing/requests_test.go, openstack/clustering/v1/clusters/urls.go
[[clusters:list]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L81)
=> Senlin: Cluster List

openstack/db/v1/instances/results.go, openstack/db/v1/instances/testing/fixtures.go, openstack/db/v1/instances/testing/requests_test.go
=> DB v1: add support for fault information in response body

openstack/objectstorage/v1/containers/requests.go
=> Object Storage v1: Close Body on Container Create

script/acceptancetest
CI report SUCCESS when some test cases fails.
For theopenlab/openlab-zuul-jobs#219
=> Fix the CI report issue

acceptance/openstack/compute/v2/keypairs_test.go, script/acceptancetest
=> Acc Tests: Parse the key returned by Nova

openstack/objectstorage/v1/accounts/results.go, openstack/objectstorage/v1/accounts/testing/fixtures.go, openstack/objectstorage/v1/accounts/testing/requests_test.go
=> Object Storage v1: Add X-Account-Meta-Quota-Bytes to Accounts

acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/results.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/compute/v2/servers/testing/requests_test.go
=> Compute v2: Add ability to show console output

openstack/messaging/v2/messages/urls.go, openstack/messaging/v2/queues/urls.go
=> Messaging v2: URL const nit

openstack/container/v1/capsules/results.go, openstack/container/v1/capsules/testing/fixtures.go, openstack/container/v1/capsules/testing/requests_test.go, results.go
=> Container v1: Support new time format

acceptance/openstack/messaging/v2/claims_test.go, acceptance/openstack/messaging/v2/messaging.go, openstack/messaging/v2/claims/doc.go, openstack/messaging/v2/claims/requests.go, openstack/messaging/v2/claims/results.go, openstack/messaging/v2/claims/testing/doc.go, openstack/messaging/v2/claims/testing/fixtures.go, openstack/messaging/v2/claims/testing/requests_test.go, openstack/messaging/v2/claims/urls.go
For #836 
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/claims.py#L60
=> Messaging Claim Create

acceptance/openstack/blockstorage/v2/blockstorage.go, acceptance/openstack/blockstorage/v2/snapshots_test.go, acceptance/openstack/blockstorage/v2/volumes_test.go, acceptance/openstack/blockstorage/v3/blockstorage.go, acceptance/openstack/blockstorage/v3/snapshots_test.go, acceptance/openstack/blockstorage/v3/volumes_test.go, acceptance/openstack/blockstorage/v3/volumetypes_test.go, script/acceptancetest
=> Acc Tests: Enable Block Storage v3 Tests

acceptance/openstack/messaging/v2/claims_test.go, acceptance/openstack/messaging/v2/messaging.go, openstack/messaging/v2/claims/doc.go, openstack/messaging/v2/claims/requests.go, openstack/messaging/v2/claims/results.go, openstack/messaging/v2/claims/testing/fixtures.go, openstack/messaging/v2/claims/testing/requests_test.go, openstack/messaging/v2/claims/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/claims.py#L130
=> Messaging Claim Get

openstack/objectstorage/v1/objects/requests.go
=> fix downloading with range OkCode

acceptance/openstack/identity/v3/policies_test.go, openstack/identity/v3/policies/errors.go, openstack/identity/v3/policies/requests.go, openstack/identity/v3/policies/testing/requests_test.go
=> Identity V3: add field Filters to policies.ListOpts

acceptance/openstack/messaging/v2/claims_test.go, openstack/messaging/v2/claims/doc.go, openstack/messaging/v2/claims/requests.go, openstack/messaging/v2/claims/results.go, openstack/messaging/v2/claims/testing/fixtures.go, openstack/messaging/v2/claims/testing/requests_test.go, openstack/messaging/v2/claims/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/claims.py#L164
=> Messaging Claim Update

docs/contributor-tutorial/.template/doc.go, docs/contributor-tutorial/.template/requests.go, docs/contributor-tutorial/.template/results.go, docs/contributor-tutorial/.template/testing/fixtures.go, docs/contributor-tutorial/.template/testing/requests_test.go, docs/contributor-tutorial/.template/urls.go, docs/contributor-tutorial/step-05-pull-requests.md
=> Docs: adding template

openstack/identity/v3/roles/testing/fixtures.go, openstack/identity/v3/roles/testing/requests_test.go
=> Identity v3: Fixing Role Assignments unit test

openstack/networking/v2/extensions/provider/testing/results_test.go, openstack/networking/v2/networks/testing/requests_test.go, results.go
=> Core: Fixing issue with extractIntoPtr and Slices

acceptance/openstack/objectstorage/v1/containers_test.go, acceptance/openstack/objectstorage/v1/objects_test.go, openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/containers/testing/requests_test.go, openstack/objectstorage/v1/objects/requests.go, openstack/objectstorage/v1/objects/testing/requests_test.go
=> Object Storage v1: X-Newest

acceptance/openstack/objectstorage/v1/objects_test.go, openstack/objectstorage/v1/objects/requests.go
=> Object Storage v1: Add X-Newest to Object Download

openstack/clustering/v1/clusters/doc.go, openstack/clustering/v1/clusters/requests.go, openstack/clustering/v1/clusters/testing/fixtures.go, openstack/clustering/v1/clusters/testing/requests_test.go
[[clusters:completelifecycle]](https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/clusters.py#L232)
=> Senlin: Clusters CompleteLifecycle

acceptance/openstack/messaging/v2/claims_test.go, acceptance/openstack/messaging/v2/messaging.go, openstack/messaging/v2/claims/doc.go, openstack/messaging/v2/claims/requests.go, openstack/messaging/v2/claims/results.go, openstack/messaging/v2/claims/testing/fixtures.go, openstack/messaging/v2/claims/testing/requests_test.go, openstack/messaging/v2/claims/urls.go
For #836
https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/claims.py#L194
=> Messaging Claim Delete

docs/contributor-tutorial/.template/testing/requests_test.go, openstack/keymanager/v1/acls/testing/requests_test.go, openstack/keymanager/v1/containers/testing/requests_test.go, openstack/keymanager/v1/orders/testing/requests_test.go, openstack/keymanager/v1/secrets/testing/requests_test.go
=> Prefer Assert over Check

acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go, openstack/blockstorage/v1/snapshots/requests.go, openstack/blockstorage/v1/volumes/requests.go, openstack/blockstorage/v2/snapshots/requests.go, openstack/blockstorage/v2/volumes/requests.go, openstack/blockstorage/v3/snapshots/requests.go, openstack/blockstorage/v3/volumes/requests.go, openstack/compute/v2/servers/requests.go, openstack/networking/v2/extensions/security/groups/requests.go, openstack/networking/v2/networks/requests.go, openstack/networking/v2/ports/requests.go, openstack/networking/v2/subnets/requests.go
=> Make IDFromName More Efficient

acceptance/openstack/compute/v2/usage_test.go, openstack/compute/v2/extensions/usage/doc.go, openstack/compute/v2/extensions/usage/requests.go, openstack/compute/v2/extensions/usage/results.go, openstack/compute/v2/extensions/usage/testing/fixtures.go, openstack/compute/v2/extensions/usage/testing/requests_test.go, openstack/compute/v2/extensions/usage/urls.go
=> Compute v2: AllTenants Usage

acceptance/openstack/compute/v2/bootfromvolume_test.go, openstack/compute/v2/extensions/bootfromvolume/requests.go, openstack/compute/v2/extensions/bootfromvolume/testing/fixtures.go, openstack/compute/v2/extensions/bootfromvolume/testing/requests_test.go
=> Compute v2: BootFromVolume disk_bus and device_type

acceptance/openstack/clustering/v1/webhooktrigger_test.go, openstack/clustering/v1/webhooks/requests.go
- Clean up webhook test
- Remove unnecessary import for crypto openpgp errors
For #1122 
https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/webhooks.py
=> Clean up Senlin webhook implementation and test

openstack/utils/base_endpoint.go, openstack/utils/testing/base_endpoint_test.go
=> BaseEndpoint Fix

acceptance/openstack/containerinfra/v1/clustertemplates_test.go, acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clustertemplates/doc.go, openstack/containerinfra/v1/clustertemplates/requests.go, openstack/containerinfra/v1/clustertemplates/results.go, openstack/containerinfra/v1/clustertemplates/testing/fixtures.go, openstack/containerinfra/v1/clustertemplates/testing/requests_test.go, openstack/containerinfra/v1/clustertemplates/urls.go
[[clustertemplates:delete]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster_template.py#L461)
=> Magnum: Manage Cluster Templates Delete

acceptance/openstack/containerinfra/v1/certificates_test.go, openstack/containerinfra/v1/certificates/doc.go, openstack/containerinfra/v1/certificates/requests.go, openstack/containerinfra/v1/certificates/results.go, openstack/containerinfra/v1/certificates/testing/fixtures.go, openstack/containerinfra/v1/certificates/testing/requests_test.go, openstack/containerinfra/v1/certificates/urls.go
For #1062 
https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/certificate.py#L152
=> Magnum certificates create

acceptance/openstack/containerinfra/v1/clustertemplates_test.go, acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clustertemplates/doc.go, openstack/containerinfra/v1/clustertemplates/requests.go, openstack/containerinfra/v1/clustertemplates/results.go, openstack/containerinfra/v1/clustertemplates/testing/fixtures.go, openstack/containerinfra/v1/clustertemplates/testing/requests_test.go, openstack/containerinfra/v1/clustertemplates/urls.go
[[clustertemplates:list]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster_template.py#L295)
=> Magnum: Manage Cluster Templates List

acceptance/openstack/containerinfra/v1/certificates_test.go, openstack/containerinfra/v1/certificates/doc.go, openstack/containerinfra/v1/certificates/requests.go, openstack/containerinfra/v1/certificates/results.go, openstack/containerinfra/v1/certificates/testing/fixtures.go, openstack/containerinfra/v1/certificates/testing/requests_test.go, openstack/containerinfra/v1/certificates/urls.go
For #1062 
https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/certificate.py#L171
=> Magnum Certificates Update implementation

acceptance/openstack/containerinfra/v1/clustertemplates_test.go, openstack/containerinfra/v1/clustertemplates/doc.go, openstack/containerinfra/v1/clustertemplates/requests.go, openstack/containerinfra/v1/clustertemplates/results.go, openstack/containerinfra/v1/clustertemplates/testing/fixtures.go, openstack/containerinfra/v1/clustertemplates/testing/requests_test.go, openstack/containerinfra/v1/clustertemplates/urls.go
[[clustertemplates:update]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster_template.py#L414)
=> Magnum: Manage Cluster Templates Update

acceptance/openstack/loadbalancer/v2/amphorae_test.go, openstack/loadbalancer/v2/amphorae/doc.go, openstack/loadbalancer/v2/amphorae/requests.go, openstack/loadbalancer/v2/amphorae/results.go, openstack/loadbalancer/v2/amphorae/testing/doc.go, openstack/loadbalancer/v2/amphorae/testing/fixtures.go, openstack/loadbalancer/v2/amphorae/testing/requests_test.go, openstack/loadbalancer/v2/amphorae/urls.go
For #1179
octavia doc: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html#list-amphora>
octavia source code: <https://github.com/openstack/octavia/blob/b0210e4312655423d8a58931e74d5e7b2ed4974c/octavia/api/v2/controllers/amphora.py#L57>
=> Octavia - List Amphoare

openstack/loadbalancer/v2/amphorae/requests.go, openstack/loadbalancer/v2/amphorae/results.go, openstack/loadbalancer/v2/amphorae/testing/fixtures.go, openstack/loadbalancer/v2/amphorae/testing/requests_test.go
For #1179
octavia doc: https://developer.openstack.org/api-ref/load-balancer/v2/index.html#show-amphora-details
octavia source code: https://github.com/openstack/octavia/blob/b0210e4312655423d8a58931e74d5e7b2ed4974c/octavia/api/v2/controllers/amphora.py#L41
=> Octavia - Get Amphora

openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go, openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
- Fix test TestGetLoadbalancerStatusesTree for check real request body instead part of structure.
- Fix C&P comment.
=> Fix test TestGetLoadbalancerStatusesTree

acceptance/clients/clients.go, acceptance/openstack/containerinfra/v1/clusters_test.go, acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clusters/doc.go, openstack/containerinfra/v1/clusters/requests.go, openstack/containerinfra/v1/clusters/results.go, openstack/containerinfra/v1/clusters/testing/doc.go, openstack/containerinfra/v1/clusters/testing/fixtures.go, openstack/containerinfra/v1/clusters/testing/requests_test.go, openstack/containerinfra/v1/clusters/urls.go
[[clusters:create]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L432)
=> Magnum: Manage Clusters Create

openstack/clustering/v1/policies/results.go, openstack/clustering/v1/profiles/results.go, openstack/compute/v2/extensions/secgroups/results.go, openstack/compute/v2/flavors/results.go, openstack/db/v1/configurations/results.go, openstack/imageservice/v2/images/results.go, openstack/objectstorage/v1/objects/results.go
=> go vet fixes

acceptance/openstack/containerinfra/v1/clusters_test.go, acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clusters/doc.go, openstack/containerinfra/v1/clusters/requests.go, openstack/containerinfra/v1/clusters/results.go, openstack/containerinfra/v1/clusters/testing/fixtures.go, openstack/containerinfra/v1/clusters/testing/requests_test.go, openstack/containerinfra/v1/clusters/urls.go
[[clusters:get]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L382)
[[clusters:list]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L318)
=> Magnum: Manage Clusters Get/List

acceptance/clients/clients.go, acceptance/openstack/workflow/v2/workflow.go, acceptance/openstack/workflow/v2/workflows_test.go, openstack/client.go, openstack/workflow/v2/workflows/doc.go, openstack/workflow/v2/workflows/requests.go, openstack/workflow/v2/workflows/results.go, openstack/workflow/v2/workflows/testing/requests_test.go, openstack/workflow/v2/workflows/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L141
=> Workflowv2 workflows create

acceptance/clients/conditions.go, acceptance/openstack/compute/v2/servers_test.go
=> Acc Tests: Fix compute v2 lock/unlock test

acceptance/openstack/workflow/v2/workflow.go, acceptance/openstack/workflow/v2/workflows_test.go, openstack/workflow/v2/workflows/requests.go, openstack/workflow/v2/workflows/results.go, openstack/workflow/v2/workflows/testing/requests_test.go, openstack/workflow/v2/workflows/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L177
=> Workflowv2 workflows delete

openstack/blockstorage/extensions/schedulerstats/results.go
(the letters t and l were transposed)
=> Fix blockstorage multiattach typo

acceptance/openstack/workflow/v2/workflow.go, acceptance/openstack/workflow/v2/workflows_test.go, openstack/workflow/v2/workflows/requests.go, openstack/workflow/v2/workflows/results.go, openstack/workflow/v2/workflows/testing/requests_test.go, openstack/workflow/v2/workflows/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L80
=> Workflowv2 workflows get

acceptance/openstack/workflow/v2/workflow.go, acceptance/openstack/workflow/v2/workflows_test.go, openstack/workflow/v2/workflows/doc.go, openstack/workflow/v2/workflows/requests.go, openstack/workflow/v2/workflows/results.go, openstack/workflow/v2/workflows/testing/requests_test.go, openstack/workflow/v2/workflows/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L201
=> Workflowv2 workflows list

acceptance/openstack/containerinfra/v1/clusters_test.go, openstack/containerinfra/v1/clusters/doc.go, openstack/containerinfra/v1/clusters/requests.go, openstack/containerinfra/v1/clusters/results.go, openstack/containerinfra/v1/clusters/testing/fixtures.go, openstack/containerinfra/v1/clusters/testing/requests_test.go, openstack/containerinfra/v1/clusters/urls.go
[[clusters:update]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L497)
=> Magnum: Manage Clusters Update

acceptance/openstack/loadbalancer/v2/loadbalancers_test.go, openstack/loadbalancer/v2/pools/doc.go, openstack/loadbalancer/v2/pools/requests.go, openstack/loadbalancer/v2/pools/results.go, openstack/loadbalancer/v2/pools/testing/fixtures.go, openstack/loadbalancer/v2/pools/testing/requests_test.go
For #1217
- API doc: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html#batch-update-members>
- Source code(stable/rocky): <https://github.com/openstack/octavia/blob/stable/rocky/octavia/api/v2/controllers/member.py#L294>
=> Support batch update members

acceptance/openstack/containerinfra/v1/clusters_test.go, acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clusters/doc.go, openstack/containerinfra/v1/clusters/requests.go, openstack/containerinfra/v1/clusters/results.go, openstack/containerinfra/v1/clusters/testing/fixtures.go, openstack/containerinfra/v1/clusters/testing/requests_test.go, openstack/containerinfra/v1/clusters/urls.go
[[clusters:delete]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L560)
=> Magnum: Manage Clusters Delete

acceptance/openstack/workflow/v2/crontrigger.go, acceptance/openstack/workflow/v2/crontriggers_test.go, acceptance/openstack/workflow/v2/workflow.go, openstack/workflow/v2/crontriggers/doc.go, openstack/workflow/v2/crontriggers/requests.go, openstack/workflow/v2/crontriggers/results.go, openstack/workflow/v2/crontriggers/testing/requests_test.go, openstack/workflow/v2/crontriggers/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L57
=> Workflowv2 crontriggers create

acceptance/openstack/workflow/v2/execution.go, acceptance/openstack/workflow/v2/executions_test.go, acceptance/openstack/workflow/v2/workflow.go, openstack/workflow/v2/executions/doc.go, openstack/workflow/v2/executions/requests.go, openstack/workflow/v2/executions/results.go, openstack/workflow/v2/executions/testing/requests_test.go, openstack/workflow/v2/executions/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/execution.py#L218
=> Workflowv2 executions create

acceptance/openstack/identity/v3/roles_test.go
=> Acc Tests: Create Roles instead of using existing ones

acceptance/openstack/blockstorage/extensions/schedulerstats_test.go, acceptance/openstack/blockstorage/extensions/services_test.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, script/acceptancetest
=> Acc Tests: Enable Block Storage extensions tests

acceptance/openstack/workflow/v2/crontrigger.go, acceptance/openstack/workflow/v2/crontriggers_test.go, openstack/workflow/v2/crontriggers/requests.go, openstack/workflow/v2/crontriggers/results.go, openstack/workflow/v2/crontriggers/testing/requests_test.go, openstack/workflow/v2/crontriggers/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L85
=> Workflowv2 crontriggers delete

acceptance/openstack/workflow/v2/execution.go, openstack/workflow/v2/executions/requests.go, openstack/workflow/v2/executions/results.go, openstack/workflow/v2/executions/testing/requests_test.go, openstack/workflow/v2/executions/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/execution.py#L88
=> Workflowv2 executions get

acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go
=> Acc Tests: Fixing Networking v2 Floating IP test

acceptance/openstack/workflow/v2/execution.go, acceptance/openstack/workflow/v2/executions_test.go, openstack/workflow/v2/executions/requests.go, openstack/workflow/v2/executions/results.go, openstack/workflow/v2/executions/testing/requests_test.go, openstack/workflow/v2/executions/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/execution.py#L284
=> Workflowv2 executions delete

acceptance/openstack/workflow/v2/crontrigger.go, acceptance/openstack/workflow/v2/crontriggers_test.go, openstack/workflow/v2/crontriggers/requests.go, openstack/workflow/v2/crontriggers/results.go, openstack/workflow/v2/crontriggers/testing/requests_test.go, openstack/workflow/v2/crontriggers/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L35
=> Workflowv2 crontriggers get

acceptance/openstack/networking/v2/extensions/provider_test.go, script/acceptancetest
=> Acc Tests: Enabling network extensions

openstack/networking/v2/extensions/security/rules/requests.go
=> Networking v2: Make Security Group Rule Description omitempty

openstack/loadbalancer/v2/listeners/requests.go, openstack/loadbalancer/v2/pools/requests.go, openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go, openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
=> Octavia v2: UDP Protocol support

acceptance/openstack/blockstorage/extensions/schedulerhints_test.go, openstack/blockstorage/extensions/schedulerhints/doc.go, openstack/blockstorage/extensions/schedulerhints/requests.go, openstack/blockstorage/extensions/schedulerhints/testing/doc.go, openstack/blockstorage/extensions/schedulerhints/testing/requests_test.go
=> Add support volume scheduler hint option

acceptance/openstack/workflow/v2/execution.go, acceptance/openstack/workflow/v2/executions_test.go, openstack/workflow/v2/executions/doc.go, openstack/workflow/v2/executions/requests.go, openstack/workflow/v2/executions/results.go, openstack/workflow/v2/executions/testing/requests_test.go, openstack/workflow/v2/executions/urls.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/execution.py#L321
=> Workflowv2 executions list

acceptance/openstack/workflow/v2/crontrigger.go, acceptance/openstack/workflow/v2/crontriggers_test.go, openstack/workflow/v2/crontriggers/doc.go, openstack/workflow/v2/crontriggers/requests.go, openstack/workflow/v2/crontriggers/results.go, openstack/workflow/v2/crontriggers/testing/requests_test.go, openstack/workflow/v2/crontriggers/urls.go, openstack/workflow/v2/workflows/doc.go, openstack/workflow/v2/workflows/testing/requests_test.go
For #1199 
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L106
=> Workflowv2 crontriggers list

acceptance/openstack/blockstorage/extensions/volumeactions_test.go, acceptance/openstack/clustering/v1/webhooktrigger_test.go, acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/flavors_test.go, acceptance/openstack/compute/v2/keypairs_test.go, acceptance/openstack/networking/v2/extensions/vpnaas/siteconnection_test.go, acceptance/openstack/orchestration/v1/orchestration.go, acceptance/openstack/orchestration/v1/stackevents_test.go, openstack/blockstorage/extensions/schedulerhints/testing/requests_test.go, openstack/clustering/v1/webhooks/testing/requests_test.go, openstack/compute/v2/extensions/quotasets/testing/fixtures.go, openstack/loadbalancer/v2/amphorae/testing/fixtures.go, openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/testing/fixtures.go, openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
=> gofmt fixes

openstack/networking/v2/extensions/lbaas_v2/pools/doc.go
Corrects errant reference to Monitors
For #1298
=> Fix lbaas_v2 pools docs

acceptance/openstack/networking/v2/extensions/attributestags_test.go, openstack/networking/v2/extensions/attributestags/doc.go, openstack/networking/v2/extensions/attributestags/requests.go, openstack/networking/v2/extensions/attributestags/results.go, openstack/networking/v2/extensions/attributestags/testing/requests_test.go, openstack/networking/v2/extensions/attributestags/urls.go
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-
https://developer.openstack.org/api-ref/network/v2/#confirm-a-tag
Issue: #1260
Code from neutron related to this PR: https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L103
=> Neutron std attr tags confirm

acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
For #1285 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/models.py#L49
=> Networking V2 - Trunk tags testing

script/acceptancetest
For #818 
For https://github.com/theopenlab/openlab/issues/92
=> Acc Tests: Enable networking trunks

acceptance/clients/clients.go, acceptance/openstack/containerinfra/v1/containerinfra.go, acceptance/openstack/containerinfra/v1/quotas_test.go, openstack/containerinfra/v1/quotas/doc.go, openstack/containerinfra/v1/quotas/requests.go, openstack/containerinfra/v1/quotas/results.go, openstack/containerinfra/v1/quotas/testing/doc.go, openstack/containerinfra/v1/quotas/testing/fixtures.go, openstack/containerinfra/v1/quotas/testing/requests_test.go, openstack/containerinfra/v1/quotas/urls.go
[[quotas:create]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/quota.py#L166)
=> Magnum: Manage Quotas Create

openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/containers/results.go
=> Enable versioning with X-History-Location

acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go, openstack/container/v1/capsules/template.go, openstack/orchestration/v1/stacks/utils.go
=> goimports fixes

openstack/sharedfilesystems/v2/securityservices/requests.go, openstack/sharedfilesystems/v2/securityservices/results.go
Available only for microversion >= 2.44
https://bugs.launchpad.net/manila/+bug/1696669
=> Add organizational unit (OU) support for the securityservices

openstack/networking/v2/extensions/layer3/floatingips/requests.go, openstack/networking/v2/extensions/layer3/floatingips/results.go, openstack/networking/v2/extensions/layer3/routers/requests.go, openstack/networking/v2/extensions/layer3/routers/results.go, openstack/networking/v2/extensions/security/groups/requests.go, openstack/networking/v2/extensions/security/rules/requests.go, openstack/networking/v2/networks/requests.go, openstack/networking/v2/networks/results.go, openstack/networking/v2/ports/requests.go, openstack/networking/v2/ports/results.go, openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/results.go
* security_group_rules
* security_groups
* ports
* subnets,
* networks
* routers
* floatingips
* subnetpools
Issue: #1342
=> Add description support for network resources

acceptance/README.md, acceptance/clients/clients.go, acceptance/openstack/sharedfilesystems/v2/sharenetworks.go, acceptance/openstack/sharedfilesystems/v2/sharenetworks_test.go, acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/results.go, openstack/sharedfilesystems/v2/shares/testing/fixtures.go, openstack/sharedfilesystems/v2/shares/testing/request_test.go, openstack/sharedfilesystems/v2/shares/urls.go, script/acceptancetest, script/stackenv
#129 - add share update action with tests
=> feature/shared file systems: update share

acceptance/openstack/loadbalancer/v2/loadbalancer.go, acceptance/openstack/loadbalancer/v2/loadbalancers_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/l7policies_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/lbaas_v2.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/listeners_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/monitors_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/pools_test.go, openstack/loadbalancer/v2/l7policies/requests.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/doc.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/requests.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/testing/doc.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/testing/fixtures.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/testing/requests_test.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/urls.go, openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/doc.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/testing/fixtures.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/testing/requests_test.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/urls.go, script/stackenv
I added missed l7 options and just copied these resources into extensions/lbaas_v2
Resolves #1348
=> Copy l7policies from loadbalancer/v2 to extensions/lbaas_v2

acceptance/openstack/loadbalancer/v2/loadbalancer.go, acceptance/openstack/loadbalancer/v2/loadbalancers_test.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/lbaas_v2.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go, openstack/loadbalancer/v2/l7policies/requests.go, openstack/loadbalancer/v2/l7policies/testing/fixtures.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/requests.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/testing/fixtures.go
=> LBaaS_v2: L7policy redirect_pool_id and redirect_url should not be omitted during update

openstack/loadbalancer/v2/listeners/results.go, openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
=> LBaaSv2/Octavia: add "L7Policies" member into the Listerner struct

openstack/loadbalancer/v2/l7policies/results.go, openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go
=> LBaaSv2 / Octavia: Add provisioning status struct member for l7policy and l7rule results

openstack/loadbalancer/v2/loadbalancers/results.go, openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
=> LBaaSv2 / Octavia: Add pools into the LB results structure

acceptance/openstack/sharedfilesystems/v2/messages/messages.go, acceptance/openstack/sharedfilesystems/v2/messages/messages_test.go, acceptance/openstack/sharedfilesystems/v2/messages/pkg.go, openstack/sharedfilesystems/v2/messages/requests.go, openstack/sharedfilesystems/v2/messages/results.go, openstack/sharedfilesystems/v2/messages/testing/fixtures.go, openstack/sharedfilesystems/v2/messages/testing/requests_test.go, openstack/sharedfilesystems/v2/messages/urls.go
=> Manila: add messages support

acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, script/acceptancetest
=> Manila share errors

openstack/sharedfilesystems/v2/errors/errors.go, openstack/sharedfilesystems/v2/errors/testing/fixtures.go, openstack/sharedfilesystems/v2/errors/testing/request_test.go
=> Manila: add response error messages support

acceptance/openstack/networking/v2/extensions/layer3/addressscopes_test.go, acceptance/openstack/networking/v2/extensions/layer3/layer3.go, openstack/networking/v2/extensions/layer3/addressscopes/doc.go, openstack/networking/v2/extensions/layer3/addressscopes/requests.go, openstack/networking/v2/extensions/layer3/addressscopes/results.go, openstack/networking/v2/extensions/layer3/addressscopes/testing/fixtures.go, openstack/networking/v2/extensions/layer3/addressscopes/testing/requests_test.go, openstack/networking/v2/extensions/layer3/addressscopes/urls.go
Add address-scopes acceptance tests helpers and implement the
TestAddressScopesCRUD test.
For #1375
=> NetworkingV2: implement Address scopes acc tests

acceptance/openstack/sharedfilesystems/v2/securityservices.go, acceptance/openstack/sharedfilesystems/v2/securityservices_test.go, acceptance/openstack/sharedfilesystems/v2/sharenetworks.go, acceptance/openstack/sharedfilesystems/v2/sharenetworks_test.go, acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, acceptance/openstack/sharedfilesystems/v2/sharetypes.go, acceptance/openstack/sharedfilesystems/v2/sharetypes_test.go, acceptance/openstack/sharedfilesystems/v2/snapshots.go, acceptance/openstack/sharedfilesystems/v2/snapshots_test.go, openstack/sharedfilesystems/v2/snapshots/requests.go, openstack/sharedfilesystems/v2/snapshots/results.go, openstack/sharedfilesystems/v2/snapshots/testing/fixtures.go, openstack/sharedfilesystems/v2/snapshots/testing/request_test.go, openstack/sharedfilesystems/v2/snapshots/urls.go
=> Manila: add share snapshot support (tests)

provider_client.go
=> ProviderClient: Dont panic

openstack/sharedfilesystems/v2/messages/requests.go
=> Manila: add sorting into the manila messages list options

acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go, openstack/networking/v2/extensions/layer3/floatingips/doc.go, openstack/networking/v2/extensions/layer3/floatingips/requests.go, openstack/networking/v2/extensions/layer3/floatingips/testing/requests_test.go
=> Networking: add omitempty for fip port_id

acceptance/openstack/networking/v2/extensions/layer3/routers_test.go, openstack/networking/v2/extensions/layer3/routers/results.go, openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go
=> Networking V2: omit empty ExternalFixedIP IPAddress for the router

auth_options.go, openstack/auth_env.go
Resolves #1365
Env requirements:
```
OS_APPLICATION_CREDENTIAL_SECRET:
OS_APPLICATION_CREDENTIAL_ID: done
OS_APPLICATION_CREDENTIAL_NAME:
OS_USERID: done
OS_USERNAME:
OS_DOMAIN_NAME: done
OS_DOMAIN_ID: done
```
=> Auth: update application credential requirements logic

openstack/loadbalancer/v2/listeners/requests.go, openstack/loadbalancer/v2/pools/requests.go
For #1322
https://github.com/openstack/octavia/blob/master/octavia/common/jinja/haproxy/templates/macros.j2#L180-L183
https://github.com/openstack/octavia/blob/a0112c4b378d02a4c3a0a86265859db54ce3de75/octavia/common/constants.py#L74-L76
=> Add PROXY protocol for listener/pool requests to LBaaS v2

.travis.yml, openstack/client.go, openstack/container/v1/capsules/testing/requests_test.go, openstack/imageservice/v2/images/testing/requests_test.go, provider_client.go, script/unittest, testing/provider_client_test.go
For #1434 
/cc @kayrus @zimnx @piotr-dulikowski
=> Core: Reauth Concurrency fixes

acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go, acceptance/openstack/networking/v2/extensions/layer3/layer3.go, acceptance/openstack/networking/v2/networking.go, openstack/networking/v2/extensions/layer3/floatingips/requests.go
=> Networking V2: add ability to update FIP port's fixed IP

acceptance/openstack/loadbalancer/v2/loadbalancer.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/lbaas_v2.go
=> Acc Tests: Increase timeouts for loadbalancers

openstack/loadbalancer/v2/loadbalancers/requests.go, openstack/loadbalancer/v2/loadbalancers/results.go
For #1176 
https://github.com/openstack/octavia/blob/fa0f0525e62a999aa14da46950c70cd741503179/octavia/api/v2/types/load_balancer.py#L52
=> Adding property VipNetworkId.

.zuul/playbooks/gophercloud-acceptance-test/run.yaml, script/acceptancetest
For #818 
For https://github.com/theopenlab/openlab/issues/192
=> Acc Tests: Temporarily disabling octavia/lbaas

.zuul/playbooks/gophercloud-acceptance-test/run.yaml, script/acceptancetest
For #818 
Related to: #1468 
Related to: #1469
=> Acc Tests: Disabling Zun/Containers temporarily

openstack/networking/v2/extensions/portsbinding/results.go
=> Networking V2: Fix nested struct unmarshaling for the port binding profile

openstack/networking/v2/extensions/layer3/routers/results.go
Issue: https://github.com/gophercloud/gophercloud/issues/1467
=> Networking V2: Fix deleting external gateway for router

acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
=> Acc Tests: Add test to clear external gateway

.zuul/playbooks/gophercloud-acceptance-test/run.yaml, acceptance/clients/clients.go, acceptance/openstack/container/v1/capsules.go, acceptance/openstack/container/v1/capsules_test.go, acceptance/openstack/container/v1/fixtures.go, openstack/container/v1/capsules/microversions.go, openstack/container/v1/capsules/results.go, openstack/container/v1/capsules/testing/fixtures.go, openstack/container/v1/capsules/testing/requests_test.go, script/acceptancetest
=> Containers v1: Implement Capsules Microversion 1.32

acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding_test.go, openstack/networking/v2/extensions/portsbinding/requests.go, openstack/networking/v2/extensions/portsbinding/testing/requests_test.go
=> Networking V2: Allow nested structs in port bindings create/update

openstack/identity/v3/applicationcredentials/requests.go, openstack/networking/v2/extensions/agents/requests.go
found within #1460 code review
=> Fix typos in tags for ListOpts

provider_client.go, testing/provider_client_test.go
=> support context.Context for outgoing HTTP requests

acceptance/openstack/identity/v3/credentials_test.go, openstack/identity/v3/credentials/requests.go, openstack/identity/v3/credentials/results.go, openstack/identity/v3/credentials/testing/fixtures.go, openstack/identity/v3/credentials/testing/requests_test.go, openstack/identity/v3/credentials/urls.go
* Identity V3: Add credentials package
For #1457
Adding the support for Keystone Credential package:
https://github.com/openstack/keystone/tree/master/keystone/credential
=> Identity V3: Add credentials package (#1457)

acceptance/clients/http.go
For cases when API returns an array
For #818
=> Acceptance: Allow JSON array unmarshalling in debug mode

acceptance/openstack/networking/v2/extensions/dns/dns.go, acceptance/openstack/networking/v2/extensions/dns/dns_test.go, openstack/networking/v2/extensions/dns/doc.go, openstack/networking/v2/extensions/dns/requests.go, openstack/networking/v2/extensions/dns/results.go, openstack/networking/v2/extensions/dns/testing/fixtures.go, openstack/networking/v2/extensions/dns/testing/requests_test.go, openstack/networking/v2/extensions/layer3/floatingips/requests.go, openstack/networking/v2/extensions/layer3/floatingips/results.go, openstack/networking/v2/extensions/layer3/floatingips/testing/fixtures.go, openstack/networking/v2/extensions/layer3/floatingips/testing/requests_test.go, openstack/networking/v2/networks/testing/fixtures.go, openstack/networking/v2/ports/testing/fixtures.go, script/acceptancetest
=> Networking V2: Add DNS extension support

openstack/blockstorage/v3/volumes/results.go, openstack/blockstorage/v3/volumes/testing/fixtures.go, openstack/blockstorage/v3/volumes/testing/requests_test.go
=> Block Storage V3: Add volume image metadata field.

acceptance/openstack/networking/v2/extensions/mtu/mtu.go, acceptance/openstack/networking/v2/extensions/mtu/mtu_test.go, openstack/networking/v2/extensions/mtu/requests.go, openstack/networking/v2/extensions/mtu/results.go, openstack/networking/v2/extensions/mtu/testing/fixtures.go, openstack/networking/v2/extensions/mtu/testing/requests_test.go, openstack/networking/v2/extensions/mtu/testing/results_test.go, openstack/networking/v2/networks/testing/fixtures.go, script/acceptancetest
=> Networking V2: Add network MTU extension support

.zuul/playbooks/gophercloud-acceptance-test/run.yaml, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, script/acceptancetest
=> Acc Tests: Enable Octavia

openstack/orchestration/v1/stacks/requests.go
For #1533 
https://developer.openstack.org/api-ref/orchestration/v1/?expanded=list-stacks-detail
Signed-off-by: Kien Nguyen <kiennt2609@gmail.com>
=> Add extra Heat list stacks function parameters

doc.go
=> Core: Updating docs

acceptance/openstack/networking/v2/subnets_test.go, openstack/networking/v2/subnets/doc.go, openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/testing/requests_test.go
=> Networking v2: Allow DNS Nameservers to be cleared

acceptance/openstack/keymanager/v1/keymanager.go, openstack/keymanager/v1/secrets/requests.go, openstack/keymanager/v1/secrets/testing/fixtures.go, openstack/keymanager/v1/secrets/testing/requests_test.go
For #1526 
Supersedes #1527 
/cc @kayrus
=> KeyManager v1: Adding Expiration to Secrets

acceptance/openstack/networking/v2/extensions/dns/dns_test.go, acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent.go, acceptance/openstack/networking/v2/networks_test.go, acceptance/openstack/networking/v2/subnets_test.go, openstack/networking/v2/extensions/dns/testing/requests_test.go, openstack/networking/v2/extensions/external/testing/results_test.go, openstack/networking/v2/extensions/mtu/testing/results_test.go, openstack/networking/v2/extensions/provider/testing/results_test.go, openstack/networking/v2/extensions/vlantransparent/testing/requests_test.go, openstack/networking/v2/networks/doc.go, openstack/networking/v2/networks/requests.go, openstack/networking/v2/networks/testing/requests_test.go, openstack/networking/v2/subnets/doc.go, openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/testing/requests_test.go
=> Networking v2: Ability to clear names

openstack/baremetal/noauth/doc.go, openstack/baremetal/v1/drivers/doc.go, openstack/baremetal/v1/nodes/doc.go, openstack/baremetal/v1/ports/doc.go, openstack/baremetalintrospection/noauth/doc.go, openstack/baremetalintrospection/v1/introspection/doc.go
=> Docs: Updating baremetal/inspector docs

openstack/baremetal/v1/nodes/requests.go
Inpsecting -> Inspecting
For #1429
=> Baremetal: Fix typo in state name

acceptance/openstack/dns/v2/recordsets_test.go, openstack/dns/v2/recordsets/requests.go
=> DNSv2: Fix recordsets TTL update

openstack/dns/v2/recordsets/testing/requests_test.go
For #1562 
Looks like Travis never ran on #1563
=> DNSv2: Fixing unit test

acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding.go, acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding_test.go, openstack/networking/v2/extensions/portsbinding/requests.go
=> Proper port binding unset

openstack/networking/v2/extensions/qos/rules/doc.go, openstack/networking/v2/extensions/qos/rules/requests.go, openstack/networking/v2/extensions/qos/rules/results.go, openstack/networking/v2/extensions/qos/rules/testing/fixtures.go, openstack/networking/v2/extensions/qos/rules/testing/requests_test.go, openstack/networking/v2/extensions/qos/rules/urls.go
Add an example of BW limit rule creation.
Fix client name in limit rule update.
For #1027
=> Networking V2: cleanup QoS BW limit rule docs

openstack/networking/v2/extensions/qos/policies/doc.go, openstack/networking/v2/extensions/qos/policies/requests.go, openstack/networking/v2/extensions/qos/policies/results.go, openstack/networking/v2/extensions/qos/policies/testing/fixtures.go, openstack/networking/v2/extensions/qos/policies/testing/requests_test.go, openstack/networking/v2/extensions/qos/policies/urls.go
Add method to List QoS policies.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L54
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L43
=> Networking V2: add QoS policies List

acceptance/openstack/compute/v2/diagnostics_test.go, openstack/compute/v2/extensions/diagnostics/results.go, openstack/compute/v2/extensions/diagnostics/testing/requests_test.go
=> Compute v2: Diagnostics return type and Acceptance Test

openstack/orchestration/v1/stackresources/results.go
=> Orchestration v1: Fix ordering of fields

openstack/networking/v2/extensions/qos/rules/doc.go, openstack/networking/v2/extensions/qos/rules/requests.go, openstack/networking/v2/extensions/qos/rules/results.go, openstack/networking/v2/extensions/qos/rules/testing/fixtures.go, openstack/networking/v2/extensions/qos/rules/testing/requests_test.go, openstack/networking/v2/extensions/qos/rules/urls.go
Use http.StatusOK code for Update call.
For #1027
=> Networking QoS DSCP Marking: fix Update call code

acceptance/openstack/networking/v2/extensions/qos/rules/rules.go, acceptance/openstack/networking/v2/extensions/qos/rules/rules_test.go, openstack/networking/v2/extensions/qos/rules/requests.go, openstack/networking/v2/extensions/qos/rules/testing/requests_test.go, script/acceptancetest
Implement TestBandwidthLimitRulesCRUD test and CreateBandwidthLimitRule
tests helper.
For #1027
=> Networking V2: add QoS bw limit rule acc tests

openstack/networking/v2/extensions/qos/rules/doc.go, openstack/networking/v2/extensions/qos/rules/requests.go, openstack/networking/v2/extensions/qos/rules/results.go, openstack/networking/v2/extensions/qos/rules/testing/fixtures.go, openstack/networking/v2/extensions/qos/rules/testing/requests_test.go, openstack/networking/v2/extensions/qos/rules/urls.go
Implement CreateMinimumBandwidthRule call with test.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L150
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L91
=> Networking V2: add QoS min bw rule Create call

acceptance/openstack/networking/v2/extensions/qos/rules/rules.go, acceptance/openstack/networking/v2/extensions/qos/rules/rules_test.go
Implement TestDSCPMarkingRulesCRUD and add CreateDSCPMarkingRule test
helper.
For #1027
=> Networking V2: add QoS DSCP marking acc test

acceptance/openstack/networking/v2/extensions/qos/rules/rules.go, acceptance/openstack/networking/v2/extensions/qos/rules/rules_test.go, openstack/networking/v2/extensions/qos/rules/doc.go, openstack/networking/v2/extensions/qos/rules/requests.go, openstack/networking/v2/extensions/qos/rules/results.go, openstack/networking/v2/extensions/qos/rules/testing/fixtures.go, openstack/networking/v2/extensions/qos/rules/testing/requests_test.go, openstack/networking/v2/extensions/qos/rules/urls.go
Implement TestMinimumBandwidthRulesCRUD and CreateMinimumBandwidthRule
test helper.
For #1027
=> Networking V2: add QoS min bw rules acc test

acceptance/openstack/keymanager/v1/containers_test.go, acceptance/openstack/keymanager/v1/keymanager.go, openstack/keymanager/v1/containers/requests.go, openstack/keymanager/v1/containers/results.go, openstack/keymanager/v1/containers/urls.go
=> Allow modification of the container secret refs

acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go, openstack/networking/v2/extensions/layer3/portforwarding/doc.go, openstack/networking/v2/extensions/layer3/portforwarding/requests.go, openstack/networking/v2/extensions/layer3/portforwarding/results.go, openstack/networking/v2/extensions/layer3/portforwarding/testing/fixtures.go, openstack/networking/v2/extensions/layer3/portforwarding/testing/requests_test.go
For #1637 
Source: 
https://github.com/openstack/neutron/blob/f21444f247108212dc835036c98e354d6e6f7ace/neutron/services/portforwarding/pf_plugin.py#L487
API:
https://docs.openstack.org/api-ref/network/v2/?expanded=create-port-forwarding-detail#list-floating-ip-port-forwardings
=> List Port Forwardings

acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/extensions/tags/doc.go, openstack/compute/v2/extensions/tags/requests.go, openstack/compute/v2/extensions/tags/results.go, openstack/compute/v2/extensions/tags/testing/fixtures.go, openstack/compute/v2/extensions/tags/testing/requests_test.go, openstack/compute/v2/extensions/tags/urls.go
Update Compute V2 acceptance tests to use Tags Check, List, ReplaceAll,
and Add methods.
For #1669
=> Compute V2: test Tags Check, List, ReplaceAll, Add

acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go, openstack/networking/v2/extensions/layer3/portforwarding/doc.go, openstack/networking/v2/extensions/layer3/portforwarding/requests.go, openstack/networking/v2/extensions/layer3/portforwarding/results.go, openstack/networking/v2/extensions/layer3/portforwarding/testing/requests_test.go
For #1637 
Source:
https://github.com/openstack/neutron/blob/f21444f247108212dc835036c98e354d6e6f7ace/neutron/services/portforwarding/pf_plugin.py#L469
API:
https://docs.openstack.org/api-ref/network/v2/?expanded=list-floating-ip-port-forwardings-detail#list-floating-ip-port-forwardings
=> Get Port Forwarding

openstack/identity/v3/tokens/results.go, openstack/identity/v3/tokens/testing/fixtures.go, openstack/identity/v3/tokens/testing/results_test.go
=> Identity V3: Add ExtractDomain method for the identity/v3/tokens package

script/acceptancetest, script/stackenv
For https://github.com/theopenlab/openlab/issues/360
=> Acc Tests: Fixing subnet creation and re-enabling sharedfilesystem

openstack/imageservice/v2/images/types.go
For #1724
https://opendev.org/openstack/glance/src/commit/c144ce5802b996fcaa0d81f38dd799a356ce7230/glance/api/v2/images.py#L1184
https://opendev.org/openstack/glance/src/commit/c144ce5802b996fcaa0d81f38dd799a356ce7230/glance/db/sqlalchemy/api.py#L64
=> Add importing status to ImageStatus enum

.travis.yml, go.mod, go.sum
=> Updating Go Modules

.zuul/playbooks/gophercloud-acceptance-test-ironic/run.yaml
=> Acc Tests: Fixing gophercloud-acceptance-test-ironic

openstack/client.go, openstack/identity/v3/tokens/results.go
Resolves #1566
Reference:
https://github.com/terraform-providers/terraform-provider-openstack/pull/861#issuecomment-531261745
=> Auth: Allow TokenID passthrough when the scope is not set

acceptance/openstack/networking/v2/extensions/fwaas_v2/fwaas_v2.go, acceptance/openstack/networking/v2/extensions/fwaas_v2/rule_test.go, openstack/networking/v2/extensions/fwaas_v2/doc.go, openstack/networking/v2/extensions/fwaas_v2/rules/requests.go, openstack/networking/v2/extensions/fwaas_v2/rules/results.go, openstack/networking/v2/extensions/fwaas_v2/rules/testing/doc.go, openstack/networking/v2/extensions/fwaas_v2/rules/testing/requests_test.go, openstack/networking/v2/extensions/fwaas_v2/rules/urls.go
For #514
https://github.com/openstack/neutron-fwaas/blob/27906d0acff349c9e5ac7955d203fb2233c295db/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L68-L82
=> [wip] FWaaS v2.0 Rule Create

acceptance/openstack/imageservice/v2/images_test.go
=> Acc Tests: Fix TestImagesUpdate

acceptance/openstack/containerinfra/v1/containerinfra.go, acceptance/openstack/containerinfra/v1/nodegroups_test.go, openstack/containerinfra/v1/nodegroups/doc.go, openstack/containerinfra/v1/nodegroups/requests.go, openstack/containerinfra/v1/nodegroups/results.go, openstack/containerinfra/v1/nodegroups/testing/fixtures.go, openstack/containerinfra/v1/nodegroups/testing/requests_test.go, openstack/containerinfra/v1/nodegroups/urls.go
For #1767
NodeGroup API representation:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L58-L127
List method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L226-L262
Get method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L265-L280
Waiting on https://review.opendev.org/#/c/694230/ to be merged to fix listing with limited number of results per page.
=> ContainerInfra: nodegroups Get 

acceptance/openstack/sharedfilesystems/v2/shares_test.go
=> Acc Tests: Disable Shared Filesystem access tests

acceptance/openstack/containerinfra/v1/nodegroups_test.go, openstack/containerinfra/v1/nodegroups/doc.go, openstack/containerinfra/v1/nodegroups/requests.go, openstack/containerinfra/v1/nodegroups/results.go, openstack/containerinfra/v1/nodegroups/testing/fixtures.go, openstack/containerinfra/v1/nodegroups/testing/requests_test.go, openstack/containerinfra/v1/nodegroups/urls.go
For #1767 
Create method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L283-L323
Available fields when creating node group:
https://github.com/openstack/python-magnumclient/blob/c0d368360831cd29affa47e77eba4e81e4c6f0f8/magnumclient/v1/nodegroups.py#L21-L23
Update method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L326-L338
Delete method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L341-L355
=> Containerinfra: nodegroups Create/Update/Delete

openstack/loadbalancer/v2/pools/requests.go
=> Allow for custom options in loadbalancer pool CreateMember api call

openstack/loadbalancer/v2/pools/requests.go
For #1823
https://docs.openstack.org/api-ref/load-balancer/v2/#create-member
=> Add missing options to CreateMemberOpts

acceptance/openstack/identity/v3/identity.go, acceptance/openstack/identity/v3/trusts_test.go, openstack/identity/v3/extensions/trusts/doc.go, openstack/identity/v3/extensions/trusts/requests.go, openstack/identity/v3/extensions/trusts/testing/fixtures.go, openstack/identity/v3/extensions/trusts/testing/requests_test.go
For #1642
Supersedes #1645 
/cc @ozerovandrei
=> Trust basic acc test

openstack/client.go
For https://github.com/gophercloud/gophercloud/issues/1828
=> Fixes edge case having an lb endpoint with trailing version number

acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
This PR adds an acceptance test to verify the pool members removal from the parent pool. Probably this case doesn't work and a pool stuck in a `PENDING_UPDATE` status. Relates to https://storyboard.openstack.org/#!/story/2006719
For #1830
=> Octavia: test batch members removal

.zuul.yaml
=> Acc Tests: Removing Trusty

openstack/baremetalintrospection/v1/introspection/results.go, openstack/baremetalintrospection/v1/introspection/testing/fixtures.go, openstack/baremetalintrospection/v1/introspection/testing/results_test.go
For #1825 
Supersedes #1833 
https://specs.openstack.org/openstack/ironic-inspector-specs/specs/NUMA_node_info.html
https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/numa_inspector.py
=> Introspection v1: Add NUMA Topology

acceptance/openstack/placement/v1/resourceproviders_test.go, openstack/placement/v1/resourceproviders/doc.go, openstack/placement/v1/resourceproviders/requests.go, openstack/placement/v1/resourceproviders/results.go, openstack/placement/v1/resourceproviders/testing/fixtures.go, openstack/placement/v1/resourceproviders/testing/requests_test.go
For #526
API doc:
https://docs.openstack.org/api-ref/placement/#create-resource-provider
API code:
https://github.com/openstack/placement/blob/master/placement/handlers/resource_provider.py#L77
=> Add resource provider create API for placement.

openstack/baremetalintrospection/v1/introspection/testing/fixtures.go, openstack/baremetalintrospection/v1/introspection/testing/results_test.go
=> Introspection v1: Cleaning up unit tests

params.go, testing/params_test.go
=> Core: Support for int64 headers

openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/containers/results.go, openstack/objectstorage/v1/objects/requests.go
Resolves #1863 
* https://github.com/openstack/swift/blob/9f1ef35630ebf9da53cbd061f89889e534803725/swift/common/middleware/tempurl.py#L726-L727
* https://github.com/openstack/swift/blob/9f1ef35630ebf9da53cbd061f89889e534803725/swift/common/middleware/tempurl.py#L354-L367
=> Object storage: add container temp-url-key support

openstack/imageservice/v2/images/requests.go, openstack/imageservice/v2/images/testing/fixtures.go, openstack/imageservice/v2/images/testing/requests_test.go
=> Glance V2: Add an image "min_ram" attribute modification support

openstack/objectstorage/v1/containers/requests.go
For #1863 
* https://github.com/openstack/swift/blob/9f1ef35630ebf9da53cbd061f89889e534803725/swift/common/middleware/tempurl.py#L726-L727
* https://github.com/openstack/swift/blob/9f1ef35630ebf9da53cbd061f89889e534803725/swift/common/middleware/tempurl.py#L354-L367
=> Object Storage v1: Add TempURL headers to Container CreateOpts

openstack/blockstorage/extensions/volumetransfers/doc.go, openstack/blockstorage/extensions/volumetransfers/requests.go, openstack/blockstorage/extensions/volumetransfers/results.go, openstack/blockstorage/extensions/volumetransfers/testing/fixtures.go, openstack/blockstorage/extensions/volumetransfers/testing/requests_test.go, openstack/blockstorage/extensions/volumetransfers/urls.go
=> Cinder V3: Add volume transport support

openstack/imageservice/v2/images/requests.go, openstack/imageservice/v2/images/testing/fixtures.go, openstack/imageservice/v2/images/testing/requests_test.go
=> Glance V2: Handle empty value in image update opts

openstack/blockstorage/v1/volumes/requests.go, openstack/blockstorage/v2/volumes/requests.go, openstack/blockstorage/v3/volumes/requests.go, openstack/imageservice/v2/images/requests.go
=> Glance V2: Introduce an IDFromName helper in images package

openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go
=> Cinder V3: Support "protected" and "visibility" parameters in "UploadImageOpts

openstack/compute/v2/extensions/extendedserverattributes/results.go, openstack/compute/v2/extensions/extendedserverattributes/testing/fixtures.go, openstack/compute/v2/extensions/extendedserverattributes/testing/requests_test.go
=> Compute V2: Fix userdata result extension

openstack/blockstorage/extensions/backups/doc.go, openstack/blockstorage/extensions/backups/requests.go, openstack/blockstorage/extensions/backups/results.go, openstack/blockstorage/extensions/backups/testing/fixtures.go, openstack/blockstorage/extensions/backups/testing/requests_test.go, openstack/blockstorage/extensions/backups/urls.go, openstack/blockstorage/v3/volumes/doc.go, openstack/blockstorage/v3/volumes/requests.go, openstack/blockstorage/v3/volumes/results.go, openstack/blockstorage/v3/volumes/testing/fixtures.go, openstack/blockstorage/v3/volumes/testing/requests_test.go
=> Cinder V3: Restore a volume from a backup

acceptance/openstack/container/v1/capsules_test.go
=> Acc Tests: Disable Capsule tests

acceptance/openstack/compute/v2/compute.go, acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/compute/v2/servers/testing/requests_test.go
=> Compute V2: Support VMs without a network

acceptance/openstack/blockstorage/extensions/extensions.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, openstack/blockstorage/extensions/volumeactions/doc.go, openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go, openstack/blockstorage/extensions/volumeactions/testing/fixtures.go, openstack/blockstorage/extensions/volumeactions/testing/requests_test.go
=> Cinder V3: Update a volume’s bootable status

openstack/blockstorage/extensions/backups/doc.go, openstack/blockstorage/extensions/backups/requests.go, openstack/blockstorage/extensions/backups/results.go, openstack/blockstorage/extensions/backups/testing/fixtures.go, openstack/blockstorage/extensions/backups/testing/requests_test.go, openstack/blockstorage/extensions/backups/urls.go
=> Cinder V3: Support a backup record export and import

acceptance/openstack/placement/v1/resourceproviders_test.go, openstack/placement/v1/resourceproviders/doc.go, openstack/placement/v1/resourceproviders/requests.go, openstack/placement/v1/resourceproviders/results.go, openstack/placement/v1/resourceproviders/testing/fixtures.go, openstack/placement/v1/resourceproviders/testing/requests_test.go, openstack/placement/v1/resourceproviders/urls.go
For #526
API doc:
https://docs.openstack.org/api-ref/placement/#list-resource-provider-traits
API code:
https://github.com/openstack/placement/blob/master/placement/handlers/trait.py#L184
=> Add resource provider traits API for placement

acceptance/openstack/identity/v3/ec2credentials_test.go, openstack/identity/v3/extensions/ec2credentials/doc.go, openstack/identity/v3/extensions/ec2credentials/requests.go, openstack/identity/v3/extensions/ec2credentials/results.go, openstack/identity/v3/extensions/ec2credentials/testing/fixtures.go, openstack/identity/v3/extensions/ec2credentials/testing/requests_test.go, openstack/identity/v3/extensions/ec2credentials/urls.go
=> Keystone V3: Support EC2 credentials CRD

openstack/identity/v3/tokens/testing/requests_test.go
For #1924
/cc @kayrus - you'll need to update the fixtures in #1922
=> Change password fixture

acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, openstack/sharedfilesystems/v2/shares/doc.go, openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/results.go, openstack/sharedfilesystems/v2/shares/testing/fixtures.go, openstack/sharedfilesystems/v2/shares/testing/request_test.go, openstack/sharedfilesystems/v2/shares/urls.go
Resolves #315
* [Revert To Snapshot](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/v2/shares.py#L55)
* [Status Reset](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/openstack/wsgi.py#L1241)
* [Force Delete](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/openstack/wsgi.py#L1258)
* [Unmanage](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/v1/share_unmanage.py#L32)
=> Manila V2: Introduce share actions

acceptance/openstack/blockstorage/v3/volumeattachments.go, acceptance/openstack/blockstorage/v3/volumeattachments_test.go, openstack/blockstorage/v3/attachments/doc.go, openstack/blockstorage/v3/attachments/requests.go, openstack/blockstorage/v3/attachments/results.go, openstack/blockstorage/v3/attachments/testing/fixtures.go, openstack/blockstorage/v3/attachments/testing/requests_test.go, openstack/blockstorage/v3/attachments/urls.go, openstack/blockstorage/v3/attachments/util.go
=> Cinder V3: Add support for Cinders Attachment API

openstack/compute/v2/servers/requests.go
=> Compute v2: Fix typo in the servers documentation

acceptance/openstack/identity/v3/trusts_test.go, openstack/identity/v3/extensions/trusts/requests.go, openstack/identity/v3/extensions/trusts/results.go, openstack/identity/v3/extensions/trusts/testing/fixtures.go, openstack/identity/v3/extensions/trusts/testing/requests_test.go, openstack/identity/v3/extensions/trusts/urls.go, provider_client.go
=> Keystone V3: Introduce trust roles list and get

openstack/objectstorage/v1/accounts/results.go, openstack/objectstorage/v1/containers/results.go, openstack/objectstorage/v1/objects/results.go
=> Swift: Simplify json unmarshal using ",string" struct tag

openstack/imageservice/v2/imagedata/doc.go, openstack/imageservice/v2/imagedata/requests.go, openstack/imageservice/v2/imagedata/results.go, openstack/imageservice/v2/imagedata/testing/requests_test.go, openstack/keymanager/v1/secrets/doc.go, openstack/keymanager/v1/secrets/requests.go, openstack/keymanager/v1/secrets/results.go, openstack/messaging/v2/claims/requests.go, openstack/messaging/v2/claims/testing/fixtures.go, openstack/messaging/v2/claims/testing/requests_test.go, openstack/messaging/v2/messages/requests.go, openstack/objectstorage/v1/objects/doc.go, openstack/objectstorage/v1/objects/requests.go, openstack/objectstorage/v1/objects/results.go, pagination/http.go, provider_client.go, testing/provider_client_test.go
=> Core: reuse HTTP connection when possible

acceptance/openstack/identity/v3/oauth1_test.go, auth_options.go, openstack/client.go, openstack/identity/v3/extensions/ec2tokens/requests.go, openstack/identity/v3/extensions/oauth1/doc.go, openstack/identity/v3/extensions/oauth1/requests.go, openstack/identity/v3/extensions/oauth1/results.go, openstack/identity/v3/extensions/oauth1/testing/fixtures.go, openstack/identity/v3/extensions/oauth1/testing/requests_test.go, openstack/identity/v3/extensions/oauth1/urls.go, openstack/identity/v3/tokens/requests.go, testhelper/http_responses.go
Resolves #1418 
@jtopjian let me know if you find something wrong in this code before I start code cleanup.
=> Keystone V3: Introduce OAuth1 auth support

acceptance/openstack/networking/v2/extensions/agents/agents_test.go, openstack/networking/v2/extensions/agents/doc.go, openstack/networking/v2/extensions/agents/requests.go, openstack/networking/v2/extensions/agents/results.go, openstack/networking/v2/extensions/agents/testing/fixtures.go, openstack/networking/v2/extensions/agents/testing/requests_test.go, openstack/networking/v2/extensions/agents/urls.go
Resolves #1389
https://github.com/openstack/neutron/blob/0cf41c75d50aa71d13f7391bbb91834d96d2068e/neutron/db/models/agent.py#L57-L58
https://github.com/openstack/neutron/blob/0cf41c75d50aa71d13f7391bbb91834d96d2068e/neutron/extensions/dhcpagentscheduler.py#L42-L63
=> Networking V2: Update/Delete/ScheduleDHCP/RemoveDHCP on network agents

openstack/blockstorage/extensions/volumetransfers/doc.go, openstack/blockstorage/v3/attachments/doc.go, openstack/clustering/v1/nodes/doc.go, openstack/clustering/v1/policies/doc.go, openstack/compute/v2/extensions/aggregates/doc.go, openstack/containerinfra/v1/certificates/doc.go, openstack/imageservice/v2/imageimport/doc.go, openstack/networking/v2/extensions/qos/policies/doc.go, openstack/networking/v2/extensions/trunks/doc.go, openstack/placement/v1/resourceproviders/doc.go, openstack/workflow/v2/crontriggers/doc.go, openstack/workflow/v2/executions/doc.go, openstack/workflow/v2/workflows/doc.go
Fixes https://github.com/gophercloud/gophercloud/issues/1956
=> Fix misleading/typo in openstack client docs

openstack/identity/v3/projects/requests.go, openstack/identity/v3/projects/results.go, openstack/identity/v3/projects/testing/fixtures.go, openstack/identity/v3/projects/testing/requests_test.go, openstack/identity/v3/users/testing/fixtures.go
For #1004
code in this PR: Most information is in the issue
=> Add extra and option fields to project

openstack/imageservice/v2/images/results.go, openstack/imageservice/v2/images/testing/fixtures.go, openstack/imageservice/v2/images/testing/requests_test.go
=> Glance V2: Add create action response headers support

openstack/identity/v3/extensions/oauth1/results.go, openstack/identity/v3/extensions/oauth1/testing/fixtures.go
For https://github.com/gophercloud/gophercloud/issues/1970
=> OAuth1: Variable name typo fix

.zuul.yaml
=> Acc Tests: Use Ubuntu Xenial for older releases

provider_client.go
=> fix: leak of goroutines on re-auth

.zuul.yaml, acceptance/openstack/blockstorage/extensions/extensions.go, acceptance/openstack/blockstorage/noauth/blockstorage.go, acceptance/openstack/blockstorage/noauth/pkg.go, acceptance/openstack/blockstorage/v1/blockstorage.go, acceptance/openstack/blockstorage/v2/blockstorage.go, acceptance/openstack/blockstorage/v2/volumes_test.go, acceptance/openstack/blockstorage/v3/blockstorage.go, acceptance/openstack/blockstorage/v3/volumes_test.go, acceptance/openstack/dns/v2/dns.go, acceptance/openstack/dns/v2/recordsets_test.go, acceptance/openstack/identity/v3/oauth1_test.go, acceptance/openstack/loadbalancer/v2/loadbalancer.go, acceptance/openstack/loadbalancer/v2/loadbalancers_test.go, acceptance/openstack/networking/v2/extensions/fwaas/fwaas.go, acceptance/openstack/networking/v2/extensions/layer3/layer3.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/lbaas_v2.go, acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go, acceptance/openstack/networking/v2/networking.go, acceptance/openstack/sharedfilesystems/v2/availabilityzones_test.go, acceptance/openstack/sharedfilesystems/v2/securityservices_test.go, acceptance/openstack/sharedfilesystems/v2/sharenetworks_test.go, acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, acceptance/openstack/sharedfilesystems/v2/sharetypes_test.go, acceptance/openstack/sharedfilesystems/v2/snapshots.go, acceptance/openstack/sharedfilesystems/v2/snapshots_test.go, acceptance/tools/tools.go, openstack/loadbalancer/v2/pools/requests.go
=> Acc Tests: Fix Insert Headers Usage

.zuul.yaml
=>  Updating Zuul jobs

acceptance/openstack/blockstorage/v3/volumeattachments_test.go, acceptance/openstack/compute/v2/quotaset_test.go, acceptance/openstack/compute/v2/services_test.go, acceptance/openstack/identity/v3/oauth1_test.go, acceptance/openstack/identity/v3/projects_test.go, acceptance/openstack/identity/v3/roles_test.go, acceptance/openstack/identity/v3/trusts_test.go, acceptance/openstack/placement/v1/resourceproviders_test.go, acceptance/openstack/sharedfilesystems/v2/messages/messages_test.go, openstack/blockstorage/v3/attachments/requests.go
=> Acc Tests: Skipping some tests on older OpenStack releases

openstack/objectstorage/v1/objects/requests.go
=> Swift: use int64 for DeleteAt and DeleteAfter opts

acceptance/openstack/identity/v3/oauth1_test.go
=> Acc Tests: Fix TestOAuth1CRUD ordering issues

openstack/identity/v3/endpoints/results.go, openstack/identity/v3/endpoints/testing/requests_test.go
=> Identity: add 'enabled' field on Endpoint

openstack/compute/apiversions/doc.go, openstack/compute/apiversions/errors.go, openstack/compute/apiversions/requests.go, openstack/compute/apiversions/results.go, openstack/compute/apiversions/testing/fixtures.go, openstack/compute/apiversions/testing/requests_test.go, openstack/compute/apiversions/urls.go
=> Compute v2: Adding apiversions package

acceptance/openstack/dns/v2/dns.go, acceptance/openstack/dns/v2/transfers_test.go, openstack/dns/v2/transfer/accept/doc.go, openstack/dns/v2/transfer/accept/requests.go, openstack/dns/v2/transfer/accept/results.go, openstack/dns/v2/transfer/accept/testing/accepts_test.go, openstack/dns/v2/transfer/accept/testing/doc.go, openstack/dns/v2/transfer/accept/testing/fixtures.go, openstack/dns/v2/transfer/accept/urls.go, openstack/dns/v2/transfer/request/doc.go, openstack/dns/v2/transfer/request/requests.go, openstack/dns/v2/transfer/request/results.go, openstack/dns/v2/transfer/request/testing/doc.go, openstack/dns/v2/transfer/request/testing/fixtures.go, openstack/dns/v2/transfer/request/testing/requests_test.go, openstack/dns/v2/transfer/request/urls.go
For #2040
https://github.com/openstack/designate/blob/056ceb7f4ba4a4b86fe212aa31a7506ac1b27f20/designate/api/v2/controllers/zones/tasks/transfer_accepts.py
https://github.com/openstack/designate/blob/056ceb7f4b/designate/api/v2/controllers/zones/tasks/transfer_requests.py
CRUD operations for `Zone Transfer Request` and `Zone Transfer Accept`
=> DNS v2: Zone Transfer Request/Accept

openstack/baremetal/v1/nodes/requests.go
For #2051 
https://github.com/openstack/ironic/blob/f118307e2bc94f9d524e21b44b9b64357dd7a417/ironic/common/states.py#L203
https://github.com/openstack/ironic/blob/f118307e2bc94f9d524e21b44b9b64357dd7a417/ironic/common/states.py#L216
=> Add RescueWait and Unrescuing ProvisionState states

README.md
=> Docs: Update README.md with note about clientconfig

acceptance/openstack/compute/v2/servergroup_test.go, openstack/compute/v2/extensions/servergroups/requests.go, openstack/compute/v2/extensions/servergroups/testing/requests_test.go
For #[2069]
[https://docs.openstack.org/api-ref/compute/?expanded=list-server-groups-detail#server-groups-os-server-groups]
=> add AllProjects LitsOps on ServerGroups

.github/workflows/unit.yml
=> Fixing goveralls/coveralls

.github/workflows/unit.yml
=> Changing how testing environment is set up

openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/containers/testing/fixtures.go
For #2074 
Fixes #2074
* https://github.com/openstack/swift/blob/ed990999170e7789dc6e32f299c0a3818636d9ea/swift/proxy/controllers/container.py#L64
=> Support storage policy on container create

openstack/imageservice/v2/images/requests.go, openstack/imageservice/v2/images/results.go, openstack/imageservice/v2/images/testing/fixtures.go, openstack/imageservice/v2/images/testing/requests_test.go
For #2093
Link to OpenStack code, Commit with explanation: https://github.com/openstack/glance/commit/a308c444065307e99f18b521ed8d95714be24da7
=> Glance: hide images from public list

.zuul/playbooks/gophercloud-acceptance-test-ironic/run.yaml, .zuul/playbooks/gophercloud-acceptance-test/run.yaml, .zuul/playbooks/gophercloud-unittest/run.yaml, doc.go, provider_client.go, testing/provider_client_test.go
=> Client: introduce the retry backoff

doc.go, provider_client.go, testing/provider_client_test.go
Tiny fixes for #2096
Support Swift 498 response code
=> Core: tiny fixes for retry logic

openstack/baremetal/v1/nodes/requests.go, openstack/baremetal/v1/nodes/testing/fixtures.go, openstack/baremetal/v1/nodes/testing/requests_test.go
=> Baremetal: support deploy_steps for the provisioning API

openstack/baremetal/v1/nodes/requests.go, openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures.go
For https://github.com/gophercloud/gophercloud/issues/2121
=> Baremetal: add nodes.automated_clean

openstack/networking/v2/extensions/security/rules/results.go
Descripton -> Description
For: #2161
=> Networking v2: Fix typo in results.go

provider_client.go, testing/provider_client_test.go
=> Fix ErrUnexpectedResponseCode expected OK codes

.zuul.yaml, .zuul/playbooks/gophercloud-acceptance-test-ironic/run.yaml, acceptance/openstack/blockstorage/apiversions_test.go, acceptance/openstack/blockstorage/extensions/schedulerstats_test.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, acceptance/openstack/blockstorage/v3/volumeattachments_test.go, acceptance/openstack/compute/v2/bootfromvolume_test.go, acceptance/openstack/compute/v2/volumeattach_test.go, script/acceptancetest
=> Acc Tests: Moving to Ubuntu Focal

acceptance/openstack/objectstorage/v1/containers_test.go, openstack/objectstorage/v1/containers/results.go, openstack/objectstorage/v1/containers/testing/requests_test.go
For #2170 
https://github.com/openstack/swift/blob/b79ca57fa98323b17f896af86c617d465066d544/swift/common/swob.py#L1014-L1039
=> Object Storage v1: Adding Timestamp to GetHeader results

acceptance/openstack/compute/v2/aggregates_test.go, acceptance/openstack/compute/v2/hypervisors_test.go, openstack/compute/v2/extensions/hypervisors/doc.go, openstack/compute/v2/extensions/hypervisors/requests.go, openstack/compute/v2/extensions/hypervisors/results.go, openstack/compute/v2/extensions/hypervisors/testing/fixtures.go, openstack/compute/v2/extensions/hypervisors/testing/requests_test.go
=> Compute v2: Implement Hypervisor request options 

provider_client.go, testing/provider_client_test.go
For #2183 
None - this is purely client-side.
=> Add general request retry mechanism

testing/provider_client_test.go
=> Core: Updating unit tests for retrybackoff

openstack/loadbalancer/v2/listeners/doc.go, openstack/loadbalancer/v2/listeners/requests.go, openstack/loadbalancer/v2/listeners/results.go
For: #2213
Octavia code: https://github.com/openstack/octavia/blob/69d975d62315624bf15c02f5dfefe30c013e63cf/octavia/api/v2/types/listener.py#L57
=> Octavia: Support listener tags

acceptance/openstack/objectstorage/v1/containers_test.go, acceptance/openstack/objectstorage/v1/objects_test.go, openstack/identity/v3/tokens/testing/requests_test.go, openstack/objectstorage/v1/accounts/requests.go, openstack/objectstorage/v1/accounts/testing/fixtures.go, openstack/objectstorage/v1/accounts/testing/requests_test.go, openstack/objectstorage/v1/containers/requests.go, openstack/objectstorage/v1/containers/testing/fixtures.go, openstack/objectstorage/v1/containers/testing/requests_test.go, openstack/objectstorage/v1/objects/requests.go, openstack/objectstorage/v1/objects/testing/fixtures.go, openstack/objectstorage/v1/objects/testing/requests_test.go, params.go, provider_client.go, testhelper/http_responses.go
=> Swift V1: fix setting empty headers

openstack/compute/v2/extensions/keypairs/requests.go, openstack/compute/v2/extensions/keypairs/results.go
=> nova: add support for keypair type

errors.go, provider_client.go
=> core: keep keystone reauth error on failed reauth

.github/workflows/codeql-analysis.yml
CodeQL is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.
This patch will add a new check that will analyze the code and look for security issues.
=> Add security checks with CodeQL

.gitignore
We don't need them commited in git anyway.
=> Add coverage files into .gitignore

CHANGELOG.md
=> CHANGELOG: update with recent PRs

openstack/blockstorage/v3/qos/doc.go
Nit fix for identation i came across when using it...
=> Fix identation on blockstorage/v3/qos/docs.go

CHANGELOG.md
=> Update changelog to prepare the next release (0.24)

.github/workflows/functional-basic.yaml, script/acceptancetest, script/collectlogs, script/stackenv
* Deploy Devstack with defaults (minimum services)
* Run acceptance/openstack which is a minimal set of tests
=> [CI-v2] Add functional-basic job

script/acceptancetest
This log file will be collected by Github Actions artifacts.
=> acceptance: store results into a log file

.github/workflows/functional-blockstorage.yaml, acceptance/clients/conditions.go, acceptance/openstack/blockstorage/extensions/backups_test.go, acceptance/openstack/blockstorage/extensions/schedulerhints_test.go, acceptance/openstack/blockstorage/extensions/schedulerstats_test.go, acceptance/openstack/blockstorage/extensions/services_test.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, acceptance/openstack/blockstorage/extensions/volumetenants_test.go, acceptance/openstack/blockstorage/noauth/blockstorage.go, acceptance/openstack/blockstorage/noauth/snapshots_test.go, acceptance/openstack/blockstorage/noauth/volumes_test.go, acceptance/openstack/blockstorage/v1/snapshots_test.go, acceptance/openstack/blockstorage/v1/volumes_test.go, acceptance/openstack/blockstorage/v1/volumetypes_test.go, acceptance/openstack/blockstorage/v2/snapshots_test.go, acceptance/openstack/blockstorage/v2/volumes_test.go, acceptance/openstack/blockstorage/v3/qos_test.go, acceptance/openstack/blockstorage/v3/quotaset_test.go, acceptance/openstack/blockstorage/v3/snapshots_test.go, acceptance/openstack/blockstorage/v3/volumeattachments_test.go, acceptance/openstack/blockstorage/v3/volumes_test.go, acceptance/openstack/blockstorage/v3/volumetypes_test.go
* Deploy Devstack with Cinder and Swift
* Run acceptance/openstack/blockstorage
* Unskip all the tests that were skipped
=> [CI-v2] Add blockstorage job with Github Action

.github/workflows/functional-imageservice.yaml, acceptance/openstack/imageservice/v2/imagedata_test.go, acceptance/openstack/imageservice/v2/imageimport_test.go
* Deploy Devstack with Glance
* Run acceptance/openstack/imageservice
* Unskip all the tests
* Post logs if any failure
=> [CI-v2] Add imageservice job with Github Action

.github/workflows/functional-keymanager.yaml, acceptance/openstack/keymanager/v1/acls_test.go, acceptance/openstack/keymanager/v1/containers_test.go, acceptance/openstack/keymanager/v1/orders_test.go, acceptance/openstack/keymanager/v1/secrets_test.go
* Deploy Barbican with Devstack
* Run keymanager acceptance tests
* Remove all the skips
* Logs failures if any
=> [CI-v2] Add keymanager job with Github Action

.github/workflows/functional-dns.yaml, acceptance/clients/conditions.go, acceptance/openstack/dns/v2/recordsets_test.go, acceptance/openstack/dns/v2/transfers_test.go, acceptance/openstack/dns/v2/zones_test.go
* Deploy Designate with Devstack
* Run dns acceptance tests
* Logs failures if any
=> [CI-v2] Add dns job with Github Action

.github/workflows/functional-objectstorage.yaml
Test Swift with a github action & devstack.
=> [CI-v2] Add objectstorage job with Github Action

acceptance/clients/clients.go, openstack/blockstorage/noauth/doc.go, openstack/blockstorage/noauth/requests.go, openstack/blockstorage/noauth/testing/requests_test.go
Fixes #[2342](https://github.com/gophercloud/gophercloud/issues/2342)
=> blockstorage/noauth: Add Client Type Support

acceptance/openstack/identity/v3/limits_test.go, openstack/identity/v3/limits/doc.go, openstack/identity/v3/limits/requests.go, openstack/identity/v3/limits/results.go, openstack/identity/v3/limits/testing/fixtures.go, openstack/identity/v3/limits/testing/requests_test.go, openstack/identity/v3/limits/urls.go
[Docs](https://docs.openstack.org/api-ref/identity/v3/?expanded=list-limits-detail#unified-limits)
Related to: #2289
=> Add List for identity v3 limits

.github/workflows/functional-sharedfilesystems.yaml, acceptance/openstack/sharedfilesystems/v2/messages/messages_test.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go, acceptance/openstack/sharedfilesystems/v2/snapshots_test.go
Adding a Github Action to cover Manila testing.
=> Adding CI job for testing sharedfilesystems (Manila)

openstack/compute/v2/extensions/servergroups/requests.go, openstack/compute/v2/extensions/servergroups/results.go
Fixes #2354
https://docs.openstack.org/api-ref/compute/?expanded=list-server-groups-detail#id340
https://docs.openstack.org/api-ref/compute/?expanded=list-server-groups-detail#id341
=> Compute servergroups

.github/workflows/functional-placement.yaml, acceptance/openstack/placement/v1/resourceproviders_test.go
* Deploy Placement with Devstack
* Run placement acceptance tests
* Logs failures if any
=> [CI-v2] Add placement job with Github Action

acceptance/openstack/placement/v1/placement.go, acceptance/openstack/placement/v1/resourceproviders_test.go, openstack/placement/v1/resourceproviders/doc.go, openstack/placement/v1/resourceproviders/requests.go, openstack/placement/v1/resourceproviders/results.go, openstack/placement/v1/resourceproviders/testing/fixtures.go, openstack/placement/v1/resourceproviders/testing/requests_test.go, openstack/placement/v1/resourceproviders/urls.go
[Docs](https://docs.openstack.org/api-ref/placement/?expanded=show-resource-provider-detail)
Relates to: https://github.com/gophercloud/gophercloud/issues/526
**PR-train**: requires #2357
=> Add Get to placement resourceproviders

acceptance/openstack/placement/v1/placement.go, acceptance/openstack/placement/v1/resourceproviders_test.go, openstack/placement/v1/resourceproviders/doc.go, openstack/placement/v1/resourceproviders/requests.go, openstack/placement/v1/resourceproviders/results.go, openstack/placement/v1/resourceproviders/testing/fixtures.go, openstack/placement/v1/resourceproviders/testing/requests_test.go, openstack/placement/v1/resourceproviders/urls.go
[Docs](https://docs.openstack.org/api-ref/placement/?expanded=update-resource-provider-detail)
Relates to: #526
**PR-train**: requires #2358
=> Add Update to placement resourceproviders

.github/workflows/functional-orchestration.yaml, acceptance/openstack/orchestration/v1/buildinfo_test.go, acceptance/openstack/orchestration/v1/stackevents_test.go, acceptance/openstack/orchestration/v1/stackresources_test.go, acceptance/openstack/orchestration/v1/stacks_test.go, acceptance/openstack/orchestration/v1/stacktemplates_test.go
* Deploy Heat with Devstack
* Run orchestration acceptance tests
* Logs failures if any
=> [CI-v2] Add orchestration job with Github Action

.github/workflows/functional-clustering.yaml, acceptance/openstack/clustering/v1/clusters_test.go, acceptance/openstack/clustering/v1/nodes_test.go
- Deploy Senlin with Devstack
- Run clustering acceptance tests
- Logs failures if any
=> [CI-v2] Add clustering job with Github Action

.github/workflows/functional-messaging.yaml, acceptance/openstack/messaging/v2/message_test.go, acceptance/openstack/messaging/v2/messaging.go
- Deploy Zaqar with Devstack
- Run messaging acceptance tests
- Logs failures if any
=> [CI-v2] Add messaging job with Github Action

acceptance/openstack/baremetal/v1/nodes_test.go, openstack/baremetal/v1/nodes/requests.go, openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures.go, openstack/baremetal/v1/nodes/testing/requests_test.go, openstack/baremetal/v1/nodes/urls.go
Fixes #2383
See https://docs.openstack.org/api-ref/baremetal/?expanded=set-maintenance-flag-detail,clear-maintenance-flag-detail#set-maintenance-flag for API reference.
=> baremetal: add API to set maintenance and maintenance reason

.github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-clustering.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-imageservice.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml
new release of OpenStack: Yoga
=> CI: add jobs for stable/yoga

.github/workflows/functional-containerinfra.yaml, acceptance/README.md, acceptance/openstack/containerinfra/v1/certificates_test.go, acceptance/openstack/containerinfra/v1/clusters_test.go, acceptance/openstack/containerinfra/v1/clustertemplates_test.go, acceptance/openstack/containerinfra/v1/nodegroups_test.go, script/stackenv
- Deploy Magnum with Devstack
- Run messaging acceptance tests
- Logs failures if any
=> [CI-v2] Add containerinfra job with Github Action

.github/workflows/functional-containerinfra.yaml
Update the containerinfra functional job to be on par with other functional jobs:
- add stable/yoga release to the test matrix
- bump dependent actions
=> Slight tweaks to containerinfra CI

acceptance/openstack/loadbalancer/v2/loadbalancers_test.go, openstack/loadbalancer/v2/listeners/results.go
The loadbalancer listener was missing a few fields.
https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=list-listeners-detail#list-listeners
Fixes #2402
=> Add missing lb listener fields

openstack/identity/v2/tokens/requests.go, openstack/identity/v3/tokens/requests.go, provider_client.go
=> Identity v2&v3: add RequestOpts.OmitHeaders, remove blank header

CHANGELOG.md
=> Prepare a new release: 0.25.0

openstack/networking/v2/ports/results.go
Fixes #2444
- https://github.com/openstack/neutron/blob/b7fad3dd35ad23303a5f52ec64478860a137775e/neutron/extensions/timestamp.py#L33
=> Add UpdatedAt to ports.Port

openstack/blockstorage/v3/attachments/doc.go
=> Fix typo in blockstorage/v3/attachments docs

acceptance/openstack/compute/v2/flavors_test.go, openstack/compute/v2/flavors/doc.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/results.go, openstack/compute/v2/flavors/testing/requests_test.go, openstack/compute/v2/flavors/urls.go
Fixes #2454 
[Docs](https://docs.openstack.org/api-ref/compute/?expanded=update-flavor-description-detail#flavors)
=> Add support for Update for flavors

acceptance/openstack/networking/v2/networking.go, acceptance/openstack/networking/v2/subnets_test.go, openstack/networking/v2/subnets/doc.go, openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/results.go, openstack/networking/v2/subnets/testing/fixtures.go, openstack/networking/v2/subnets/testing/requests_test.go
Fixes #2478 
[Docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=create-subnet-detail,update-subnet-detail#subnets)
=> Add service_types support for neutron subnet

openstack/db/v1/instances/requests.go, openstack/db/v1/instances/results.go, openstack/db/v1/instances/testing/fixtures.go, openstack/db/v1/instances/testing/requests_test.go
Fixes #2340
Openstack API Ref: 
https://docs.openstack.org/api-ref/database/?expanded=create-database-instance-detail#create-database-instance
=> Add support for volume type for db/v1/instance

.github/workflows/functional-clustering.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-messaging.yaml
This PR attempts at fixing some CI jobs that no longer work due to EOL upstream.
=> Fix some CI jobs

openstack/containerinfra/v1/clustertemplates/requests.go, openstack/containerinfra/v1/clustertemplates/results.go, openstack/containerinfra/v1/clustertemplates/testing/fixtures.go, openstack/containerinfra/v1/clustertemplates/testing/requests_test.go
=> Add field hidden in containerinfra/v1/clustertemplates

openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures.go
Fixes #2544
https://docs.openstack.org/api-ref/baremetal/?expanded=show-node-details-detail#show-node-details
=> baremetal: add inspection_{started,finished}_at to Node

openstack/baremetal/v1/nodes/requests.go
Added missing target state "rebuild" for Ironic nodes.
=> Added target state "rebuild" for Ironic nodes

openstack/objectstorage/v1/objects/requests.go
=> objects: Clarify ExtractContent usage

openstack/compute/v2/servers/doc.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/fixtures.go, openstack/compute/v2/servers/testing/requests_test.go
=> nova: introduce servers.ListDetails along with a simple servers.List

openstack/baremetalintrospection/httpbasic/requests.go, openstack/baremetalintrospection/noauth/requests.go, openstack/client.go
=> Fix invalid baremetal-introspection service type

acceptance/openstack/networking/v2/extensions/layer3/extraroutes_test.go, openstack/networking/v2/extensions/layer3/extraroutes/requests.go, openstack/networking/v2/extensions/layer3/extraroutes/results.go, openstack/networking/v2/extensions/layer3/extraroutes/testing/doc.go, openstack/networking/v2/extensions/layer3/extraroutes/testing/requests_test.go, openstack/networking/v2/extensions/layer3/extraroutes/urls.go
=> networking v2: add extraroutes Add and Remove methods

openstack/networking/v2/extensions/provider/requests.go, openstack/networking/v2/extensions/provider/testing/results_test.go
=> [neutron v2]: Add support for network segments update

acceptance/openstack/objectstorage/v1/objects_test.go, openstack/objectstorage/v1/objects/requests.go, openstack/objectstorage/v1/objects/testing/requests_test.go
=> [swift v1]: introduce a TempURLKey argument for objects.CreateTempURLOpts struct

acceptance/clients/conditions.go, acceptance/openstack/identity/v3/registeredlimits_test.go, openstack/identity/v3/registeredlimits/doc.go, openstack/identity/v3/registeredlimits/requests.go, openstack/identity/v3/registeredlimits/results.go, openstack/identity/v3/registeredlimits/testing/fixtures.go, openstack/identity/v3/registeredlimits/testing/requests_test.go, openstack/identity/v3/registeredlimits/urls.go
[docs](https://docs.openstack.org/api-ref/identity/v3/#unified-limits)
[code](https://github.com/openstack/keystone/blob/master/keystone/api/registered_limits.py#L49)
=> Add CRUD support for register limit APIs

acceptance/openstack/identity/v3/limits_test.go
Since we have API to create a registered limit, we can use it in the acceptance test to create and then override the same in project.
Also simplified fetching service logic since we didn't be depending on glance service anymore.
=> Limits: Fix ToDo to create registered limit and use it

acceptance/openstack/sharedfilesystems/v2/shares.go, acceptance/openstack/sharedfilesystems/v2/shares_test.go
This PR adds a functional test that restores a snapshot into a bigger share. Primarily this test is required to check whether Manila in devstack is capable to perform such an action.
=> [manila]: Add share from snapshot restore functional test

acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go, openstack/networking/v2/extensions/fwaas_v2/groups/requests.go, openstack/networking/v2/extensions/fwaas_v2/groups/testing/requests_test.go
Add RemoveIngressPolicy, RemoveEgressPolicy functions.
Add acceptance tests.
Add unit tests.
Fixes #2622
=> Add the ability to remove ingress/egress policies from fwaas_v2 groups

CHANGELOG.md, provider_client.go
Prepare the `v.1.4.0` release.
=> Prepare 1.4.0

openstack/baremetalintrospection/v1/introspection/results.go, openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
=> baremetal: update inspection inventory with recent additions

acceptance/clients/conditions.go, acceptance/openstack/sharedfilesystems/v2/sharetransfers.go, acceptance/openstack/sharedfilesystems/v2/sharetransfers_test.go, openstack/sharedfilesystems/v2/replicas/requests.go, openstack/sharedfilesystems/v2/replicas/results.go, openstack/sharedfilesystems/v2/sharetransfers/requests.go, openstack/sharedfilesystems/v2/sharetransfers/results.go, openstack/sharedfilesystems/v2/sharetransfers/testing/fixtures.go, openstack/sharedfilesystems/v2/sharetransfers/testing/requests_test.go, openstack/sharedfilesystems/v2/sharetransfers/urls.go
=> [manila]: implement share transfer API

openstack/networking/v2/extensions/fwaas_v2/policies/requests.go, openstack/networking/v2/extensions/fwaas_v2/policies/results.go, openstack/networking/v2/extensions/fwaas_v2/policies/testing/requests_test.go
nit fix that came across while working on tf side
[docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=create-firewall-policy-detail#create-firewall-policy)
=> Add projectID to fwaas_v2 policy CreateOpts and ListOpts

openstack/networking/v2/extensions/fwaas_v2/rules/requests.go, openstack/networking/v2/extensions/fwaas_v2/rules/testing/requests_test.go
nit fix that came across while working on tf side
[api docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=create-firewall-rule-detail#create-firewall-rule)
=> Add projectID to fwaas_v2 CreateOpts

.github/backport-labels.yaml
This removes a file that is no longer used and should have been cleaned up in https://github.com/gophercloud/gophercloud/pull/2661.
=> Remove unused backport-labels.yaml file

.github/labels.yaml
This PR also reorders them by name, which is how Github [shows them](https://github.com/gophercloud/gophercloud/labels)
=> labels: Add Dependabot labels

acceptance/openstack/blockstorage/extensions/extensions.go, acceptance/openstack/blockstorage/extensions/volumeactions_test.go, acceptance/openstack/blockstorage/v3/blockstorage.go, acceptance/openstack/blockstorage/v3/quotaset_test.go, acceptance/openstack/blockstorage/v3/snapshots_test.go, openstack/blockstorage/extensions/volumeactions/requests.go, openstack/blockstorage/extensions/volumeactions/results.go, openstack/blockstorage/extensions/volumeactions/testing/fixtures.go, openstack/blockstorage/extensions/volumeactions/testing/requests_test.go, openstack/blockstorage/v3/snapshots/requests.go, openstack/blockstorage/v3/snapshots/results.go, openstack/blockstorage/v3/snapshots/testing/fixtures.go, openstack/blockstorage/v3/snapshots/testing/requests_test.go, openstack/blockstorage/v3/snapshots/urls.go, openstack/compute/v2/extensions/remoteconsoles/testing/fixtures.go
=> [cinder]: add reset and force delete actions to volumes and snapshots

README.md
Minor change in the README so we can see if the backport workflow is now working end to end.
=> README: minor change to test backport workflow

.github/workflows/backport_v1.yaml
I created the secrets and the right permissions for this app.
=> backport: use github app instead of PAT

openstack/orchestration/v1/stacks/template.go, openstack/orchestration/v1/stacks/template_test.go
This PR introduces a test where multiple templates are composed, using relative paths. This test currently fails as explained in issue #2735. A second commit fixes the issue.
Fixes #2735
=> Composable templates

.github/workflows/semver-auto.yaml
In my previous commit, I didn't read the output, fixing now.
=> Fix semver-auto

acceptance/openstack/compute/v2/bootfromvolume_test.go, acceptance/openstack/compute/v2/compute.go, openstack/compute/v2/extensions/bootfromvolume/requests.go, openstack/compute/v2/extensions/bootfromvolume/testing/fixtures.go, openstack/compute/v2/extensions/bootfromvolume/testing/requests_test.go
Fixes #2776 
https://github.com/openstack/nova/blob/master/nova/objects/block_device.py#L94
=> Add tag field to compute block_device_v2

.github/workflows/functional-baremetal.yaml
Reverts gophercloud/gophercloud#2805
=> Revert "Fix baremetal jobs on Ubuntu 20.04"

openstack/baremetal/inventory/plugindata.go, openstack/baremetal/inventory/testing/fixtures.go
=> baremetal: implemented ParsedLLDP in the standard PluginData

.github/workflows/semver-auto.yaml
=> Bump go_apidiff

.github/workflows/semver-auto.yaml
=> Fix go-apidiff commit ID

pagination/http.go, pagination/pager.go
to enable dependant packages to build ListWithContext.
=> pager: Add WithContext functions

provider_client.go
The change to `v2.0.0-beta.1` should have happened in the v2 branch.
=> Set the user agent to `v2-unreleased`

openstack/config/clouds/clouds.go, params.go
I changed the coding style to be a little more golang-like.
=> change coding style

CHANGELOG.md
Sorry, I forgot the changelog addition in #2936
=> CHANGELOG: Add context

.github/workflows/codeql-analysis.yml, .github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-clustering.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-imageservice.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml, .github/workflows/gomod.yml, .github/workflows/reauth-retests.yaml, .github/workflows/semver-auto.yaml, .github/workflows/unit.yml, script/stackenv
Manually backports changes from master that failed backporting due to conflicts.
=> [v1] CI backports

openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/fixtures_test.go, openstack/compute/v2/servers/testing/requests_test.go
=> compute: Allow setting the hostname when creating a server

.github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-networking.yaml
Another attempt at fixing #2983. Clearly, I was tired when I submitted the first PR and got everything wrong.
=> [CI] Fix portbiding tests

testhelper/convenience.go
=> testhelper: mark all helpers with t.Helper

README.md
Provide examples that only use this repository and reframe the examples in terms of what the user has (clouds.yaml, openrc etc.).
=> README: Document the auth options of v2

docs/MIGRATING.md
This is a start and should be updated as we merge more breaking changes.
=> Update migration guide for v2

.github/workflows/functional-baremetal.yaml, internal/acceptance/openstack/baremetal/v1/baremetal.go, internal/acceptance/openstack/baremetal/v1/nodes_test.go, openstack/baremetal/v1/nodes/requests.go, openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures_test.go, openstack/baremetal/v1/nodes/testing/requests_test.go
Adds provision states and parametes for the new "service" provisioning
action. Adds hold states introduced as part of the same effort.
=> baremetal: add support for servicing

.github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-clustering.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-image.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml
This isn't maintained anymore, this could break anytime.
=> CI: remove Zed from testing coverage

.gitignore, Makefile
Does what it says on this tin.
=> Add minimal Makefile

README.md
=> README: Add matrix of supported services

internal/acceptance/openstack/baremetal/httpbasic/pkg.go, internal/acceptance/openstack/baremetal/noauth/pkg.go, internal/acceptance/openstack/baremetal/v1/pkg.go, internal/acceptance/openstack/blockstorage/noauth/pkg.go, internal/acceptance/openstack/blockstorage/v2/pkg.go, internal/acceptance/openstack/blockstorage/v3/pkg.go, internal/acceptance/openstack/compute/v2/pkg.go, internal/acceptance/openstack/container/v1/pkg.go, internal/acceptance/openstack/containerinfra/v1/pkg.go, internal/acceptance/openstack/db/v1/pkg.go, internal/acceptance/openstack/dns/v2/pkg.go, internal/acceptance/openstack/identity/v2/pkg.go, internal/acceptance/openstack/identity/v3/pkg.go, internal/acceptance/openstack/image/v2/pkg.go, internal/acceptance/openstack/keymanager/v1/pkg.go, internal/acceptance/openstack/loadbalancer/v2/pkg.go, internal/acceptance/openstack/messaging/v2/pkg.go, internal/acceptance/openstack/networking/v2/pkg.go, internal/acceptance/openstack/objectstorage/v1/pkg.go, internal/acceptance/openstack/orchestration/v1/pkg.go, internal/acceptance/openstack/pkg.go, internal/acceptance/openstack/placement/v1/pkg.go, internal/acceptance/openstack/sharedfilesystems/v2/pkg.go, internal/acceptance/openstack/workflow/v2/pkg.go, internal/acceptance/tools/pkg.go
godoc is pretty strict about how these are formatted.
These changes initially suggested by @pierreprinetti on #3001 but I later split that doc changes out to a different PR and missed the comments.
=> Fix godoc strings

docs/MIGRATING.md
=> Updates to v2 migration doc

docs/MIGRATING.md
A follow-up to https://github.com/gophercloud/gophercloud/pull/3074
=> migrating.md: Document utils error handling

.github/workflows/functional-networking.yaml, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/bgpvpns.go, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/bgpvpns_test.go, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/doc.go, openstack/networking/v2/extensions/bgpvpns/doc.go, openstack/networking/v2/extensions/bgpvpns/requests.go, openstack/networking/v2/extensions/bgpvpns/results.go, openstack/networking/v2/extensions/bgpvpns/testing/doc.go, openstack/networking/v2/extensions/bgpvpns/testing/fixture.go, openstack/networking/v2/extensions/bgpvpns/testing/requests_test.go, openstack/networking/v2/extensions/bgpvpns/urls.go
Fixes #2209 
* https://github.com/openstack/neutron-lib/blob/cbf17ddb0ee729ce88996daf29004ffa29efd270/neutron_lib/api/definitions/bgpvpn_routes_control.py
* https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/bgpvpn.py
* https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/bgpvpn_vni.py
=> [networking]: add BGP VPNs support

.github/workflows/functional-networking.yaml, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/bgpvpns.go, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/bgpvpns_test.go, internal/acceptance/openstack/networking/v2/extensions/bgpvpns/doc.go, openstack/networking/v2/extensions/bgpvpns/doc.go, openstack/networking/v2/extensions/bgpvpns/requests.go, openstack/networking/v2/extensions/bgpvpns/results.go, openstack/networking/v2/extensions/bgpvpns/testing/doc.go, openstack/networking/v2/extensions/bgpvpns/testing/fixture.go, openstack/networking/v2/extensions/bgpvpns/testing/requests_test.go, openstack/networking/v2/extensions/bgpvpns/urls.go
Backport of the #3078
Fixes #2209
=> [networking]: add BGP VPNs support (backport to 1.x)

docs/MIGRATING.md
=> MIGRATING: Add additional context on removed services, APIs

docs/MIGRATING.md
=> MIGRATING.md: Mention compute limits

internal/acceptance/openstack/networking/v2/extensions/layer3/layer3.go, internal/acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go, openstack/networking/v2/extensions/layer3/portforwarding/requests.go, openstack/networking/v2/extensions/layer3/portforwarding/results.go
Fixes #3093 
Backport of the #3094
=> [neutron]: introduce Description argument for the portforwarding

openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/results.go, openstack/networking/v2/subnets/testing/fixtures_test.go, openstack/networking/v2/subnets/testing/requests_test.go
Fixes #3089
https://github.com/openstack/neutron/blob/df02d0dfecc057e021b8e9c19270645c07f8cb79/neutron/objects/subnet.py#L233C10-L233C30
=> Adding support for  field dns_publish_fixed_ip in a subnet

openstack/networking/v2/subnets/requests.go, openstack/networking/v2/subnets/results.go, openstack/networking/v2/subnets/testing/fixtures_test.go, openstack/networking/v2/subnets/testing/requests_test.go
Fixes #3089
Backport of the #3090
=> [networking]: subnet add field dns_publish_fixed_ip

.github/labels.yaml, .github/workflows/backport_v2.yaml
Introduce the logic to backport master changes to v2 branch.
=> [gophercloud v2]: introduce v2 branch with a backport functionality

openstack/config/clouds/clouds.go, openstack/config/clouds/types.go
=> clouds: Parse trust_id from clouds.yaml

.github/labels.yaml
=> chore: Sync labels with master

openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures_test.go
Fixes #3135 
https://github.com/openstack/ironic/blob/1e52143f07266b53ad47d49a5be04cbf85cccc8b/ironic/objects/node.py#L178
=> Added node.Retired

provider_client.go
Set a special header value to identify user agents built from the development branch.
=> chore: Set UNRELEASED user-agent

openstack/networking/v2/extensions/security/rules/requests.go, openstack/networking/v2/extensions/security/rules/results.go, openstack/networking/v2/extensions/security/rules/testing/requests_test.go
=> fix: create security group rule with any protocol

openstack/loadbalancer/v2/monitors/requests.go, openstack/loadbalancer/v2/monitors/results.go
=> octavia: add new options to health monitors

openstack/loadbalancer/v2/listeners/requests.go, openstack/loadbalancer/v2/listeners/results.go, openstack/loadbalancer/v2/pools/requests.go, openstack/loadbalancer/v2/pools/results.go
=> octavia: add new security options to pools and listeners

openstack/networking/v2/extensions/fwaas_v2/groups/requests.go, openstack/networking/v2/extensions/fwaas_v2/policies/requests.go
=> [fwaas_v2]: proper ParseResponse handling

openstack/loadbalancer/v2/flavorprofiles/requests.go, openstack/loadbalancer/v2/flavors/requests.go, openstack/loadbalancer/v2/flavors/testing/requests_test.go
=> [octavia] add an ability to filter flavors and flavorprofiles

openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/testing/fixtures_test.go, openstack/sharedfilesystems/v2/shares/testing/request_test.go
=> [manila] add scheduler_hints to the shares CreateOpts

openstack/sharedfilesystems/v2/shares/requests.go, openstack/sharedfilesystems/v2/shares/results.go
=> [manila] add share_group_id to share's CreateOpts

.github/workflows/backport.yaml
Supersedes https://github.com/gophercloud/gophercloud/pull/3229
=> actions: Replace external dependency with gh

internal/acceptance/openstack/compute/v2/aggregates_test.go, internal/acceptance/openstack/compute/v2/flavors_test.go, internal/acceptance/openstack/compute/v2/secgroup_test.go, internal/acceptance/openstack/compute/v2/servers_test.go, internal/acceptance/openstack/loadbalancer/v2/flavorprofiles_test.go, internal/acceptance/openstack/loadbalancer/v2/flavors_test.go, internal/acceptance/openstack/loadbalancer/v2/loadbalancer.go, internal/ptr/ptr.go, openstack/compute/v2/aggregates/requests.go, openstack/compute/v2/aggregates/testing/requests_test.go, openstack/compute/v2/flavors/requests.go, openstack/compute/v2/flavors/testing/requests_test.go, openstack/compute/v2/secgroups/requests.go, openstack/compute/v2/secgroups/testing/requests_test.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/requests_test.go, openstack/loadbalancer/v2/flavorprofiles/requests.go, openstack/loadbalancer/v2/flavorprofiles/testing/requests_test.go, openstack/loadbalancer/v2/flavors/requests.go, openstack/loadbalancer/v2/flavors/testing/fixtures.go, openstack/loadbalancer/v2/flavors/testing/requests_test.go
=> [core]: allow empty struct member updates

internal/acceptance/openstack/networking/v2/extensions/extensions.go, internal/acceptance/openstack/networking/v2/extensions/security_test.go, openstack/networking/v2/extensions/security/rules/requests.go, openstack/networking/v2/extensions/security/rules/results.go, openstack/networking/v2/extensions/security/rules/testing/requests_test.go, params.go
Implement bulk creation of security group rules [1].
[1] https://docs.openstack.org/api-ref/network/v2/#bulk-create-security-group-rule
=> SG rules: implement bulk create

internal/acceptance/openstack/networking/v2/extensions/extensions.go
**Backport**: https://github.com/gophercloud/gophercloud/pull/3277
=> [v2] test: Ensure that randomly created secgroup rules don't conflict

internal/acceptance/openstack/identity/v3/endpoint_test.go, openstack/identity/v3/endpoints/requests.go, openstack/identity/v3/endpoints/results.go, openstack/identity/v3/endpoints/testing/requests_test.go, openstack/identity/v3/projects/doc.go
This is a rebase of #2750 
Closes #2748
=> identity: Add Get endpoint by ID

CHANGELOG.md, provider_client.go
Prepare a release for this month: 2.6.0.
=> Prepare v2.6.0

openstack/db/v1/quotas/doc.go, openstack/db/v1/quotas/requests.go, openstack/db/v1/quotas/results.go, openstack/db/v1/quotas/testing/doc.go, openstack/db/v1/quotas/testing/fixtures_test.go, openstack/db/v1/quotas/testing/requests_test.go, openstack/db/v1/quotas/urls.go
Fixes https://github.com/gophercloud/gophercloud/issues/3208
API:
https://docs.openstack.org/api-ref/database/#quotas
Get:
https://github.com/openstack/trove/blob/1526b20826bb7bfcc3c62ec3ce7c44a90b78f46f/trove/extensions/mgmt/quota/service.py#L32
=> Database V1 quotas get

internal/acceptance/openstack/baremetal/v1/nodes_test.go, openstack/baremetal/v1/nodes/requests.go, openstack/baremetal/v1/nodes/results.go, openstack/baremetal/v1/nodes/testing/fixtures_test.go, openstack/baremetal/v1/nodes/testing/requests_test.go
=> Baremetal virtual media Get API

openstack/config/clouds/clouds.go
Fixes a simple typo I noticed when reading the docs
=> Fix a small typo

.github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-sharedfilesystems.yaml
Fixes https://bugs.launchpad.net/devstack/+bug/2109604
=> tests: fix devstack master branch tests

internal/acceptance/openstack/containerinfra/v1/containerinfra.go, openstack/containerinfra/v1/clustertemplates/testing/fixtures_test.go
Fixes https://bugs.launchpad.net/magnum/+bug/2109685
=> tests: fix containerinfra template creation

.github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-image.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml, .github/workflows/functional-workflow.yaml
Bobcat is EOL. Stop testing it.
=> CI: Remove Bobcat

openstack/blockstorage/v2/backups/requests.go, openstack/blockstorage/v2/transfers/requests.go, openstack/blockstorage/v2/volumes/requests.go, openstack/blockstorage/v3/backups/requests.go, openstack/blockstorage/v3/transfers/requests.go, openstack/blockstorage/v3/volumes/requests.go, openstack/compute/v2/aggregates/requests.go, openstack/compute/v2/services/requests.go, openstack/identity/v3/ec2credentials/requests.go, openstack/identity/v3/oauth1/requests.go, openstack/identity/v3/projects/requests.go, openstack/loadbalancer/v2/flavorprofiles/requests.go, openstack/loadbalancer/v2/flavors/requests.go, openstack/loadbalancer/v2/l7policies/requests.go, openstack/loadbalancer/v2/listeners/requests.go, openstack/loadbalancer/v2/loadbalancers/requests.go, openstack/networking/v2/extensions/bgp/peers/requests.go, openstack/networking/v2/extensions/bgp/speakers/requests.go, openstack/networking/v2/extensions/bgpvpns/requests.go, openstack/networking/v2/extensions/layer3/routers/requests.go, openstack/networking/v2/extensions/security/rules/requests.go, openstack/sharedfilesystems/v2/sharetransfers/requests.go
Manual cherry-pick of the #3363 PR
=> [v2] core: add missing Builder interfaces

.github/workflows/functional-networking.yaml, internal/acceptance/openstack/networking/v2/extensions/agents/agents_test.go
- **Revert "[tests]: increase timeout for the TestBGPAgentRUD test"**
- **tests: Fix TestBGPAgentCRUD**
=> tests: Fix TestBGPAgentCRUD

.github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-image.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml, .github/workflows/functional-workflow.yaml
=> Move master CI jobs to Ubuntu 24.04

openstack/identity/v3/users/results.go, openstack/identity/v3/users/testing/fixtures_test.go
=> identity: add support for string boolean in users' enabled member

openstack/identity/v2/tenants/requests.go, openstack/networking/v2/extensions/layer3/routers/requests.go, openstack/networking/v2/extensions/security/rules/requests.go
**Manual Backport:** https://github.com/gophercloud/gophercloud/pull/3097
This is a follow-up for the #3070
=> [v2] Adjust List func to accept a Builder in tenants, routers and security groups packages

internal/acceptance/openstack/blockstorage/v3/blockstorage.go, openstack/blockstorage/v3/manageablevolumes/testing/fixtures_test.go, openstack/blockstorage/v3/manageablevolumes/testing/requests_test.go, openstack/blockstorage/v3/volumes/testing/fixtures_test.go, openstack/blockstorage/v3/volumes/testing/requests_test.go, script/getenvvar
I forgot that we merge directly here rather than letter Tide/Zuul handle it for us. #3332 was recently merged and should have been rebased first. Address the issues introduced.
=> Fix broken build from #3332

.github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-image.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml, .github/workflows/functional-workflow.yaml
=> [v2] tests: bump devstack-action

internal/acceptance/openstack/dns/v2/quotas_test.go, openstack/dns/v2/quotas/doc.go, openstack/dns/v2/quotas/requests.go, openstack/dns/v2/quotas/results.go, openstack/dns/v2/quotas/testing/doc.go, openstack/dns/v2/quotas/testing/fixtures_test.go, openstack/dns/v2/quotas/testing/requests_test.go, openstack/dns/v2/quotas/urls.go
This is a rebase of #2399 and #3186
Closes #2398
=> dns: add support for /v2/quotas

internal/acceptance/openstack/compute/v2/servers_test.go, openstack/compute/v2/servers/requests.go, openstack/compute/v2/servers/testing/fixtures_test.go, openstack/compute/v2/servers/testing/requests_test.go
Manual backport of the #3445
Fixes #3444
=> nova: add support for hostname updates

.github/workflows/codeql-analysis.yaml, .github/workflows/functional-baremetal.yaml, .github/workflows/functional-basic.yaml, .github/workflows/functional-blockstorage.yaml, .github/workflows/functional-compute.yaml, .github/workflows/functional-containerinfra.yaml, .github/workflows/functional-dns.yaml, .github/workflows/functional-fwaas_v2.yaml, .github/workflows/functional-identity.yaml, .github/workflows/functional-image.yaml, .github/workflows/functional-keymanager.yaml, .github/workflows/functional-loadbalancer.yaml, .github/workflows/functional-messaging.yaml, .github/workflows/functional-networking.yaml, .github/workflows/functional-objectstorage.yaml, .github/workflows/functional-orchestration.yaml, .github/workflows/functional-placement.yaml, .github/workflows/functional-sharedfilesystems.yaml, .github/workflows/functional-workflow.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml
=> [v2] tests: shorten GH-A job names

openstack/blockstorage/v3/volumetypes/testing/fixtures_test.go, openstack/blockstorage/v3/volumetypes/testing/requests_test.go
tests are not executed after the base branch is updated
=> [v2] tests: fix volumetypes unit tests

internal/acceptance/openstack/loadbalancer/v2/flavors_test.go, internal/acceptance/openstack/loadbalancer/v2/loadbalancer.go, openstack/loadbalancer/v2/flavors/doc.go, openstack/loadbalancer/v2/flavors/requests.go, openstack/loadbalancer/v2/flavors/results.go, openstack/loadbalancer/v2/flavors/testing/fixtures.go, openstack/loadbalancer/v2/flavors/testing/requests_test.go
to align with the rest of the code base
=> lbaas: fix FlavorProfileId with a FlavorProfileID struct member name

.github/workflows/check-pr-labels.yaml
Things are currently timing out due to this being missing.
=> Trigger "hold" workflow on merge groups

.github/workflows/functional-baremetal.yaml
Addressing https://github.com/gophercloud/gophercloud/pull/3500#issuecomment-3271229855
=> Added comment addressing IRONIC_BAREMETAL_BASIC_OPS=false

docs/contributor-tutorial/step-04-acceptance-testing.md, internal/acceptance/openstack/loadbalancer/v2/quotas_test.go, internal/acceptance/openstack/networking/v2/extensions/quotas/quotas_test.go, openstack/loadbalancer/v2/quotas/doc.go, openstack/loadbalancer/v2/quotas/requests.go, openstack/loadbalancer/v2/quotas/results.go, openstack/loadbalancer/v2/quotas/testing/fixtures_test.go, openstack/loadbalancer/v2/quotas/testing/requests_test.go, openstack/loadbalancer/v2/quotas/urls.go, openstack/networking/v2/extensions/quotas/doc.go, openstack/networking/v2/extensions/quotas/requests.go, openstack/networking/v2/extensions/quotas/results.go, openstack/networking/v2/extensions/quotas/testing/fixtures_test.go, openstack/networking/v2/extensions/quotas/testing/requests_test.go, openstack/networking/v2/extensions/quotas/urls.go
=> Enable deletion for network and loadbalancer quotas
