gophercloud/gophercloud

- openstack/client.go
- openstack/testing/client_test.go
When I use the AuthenticatedClient to authenticate using identity v3 and a project scope is specified (i.e. TenantName), I receive the following error
```go
auth := gophercloud.AuthOptions{
IdentityEndpoint: "http://example.com/v3",
Username:  "carolyn",
Password: "secret",
TenantName: "admin",
DomainName: "default",
}
identityService, authErr := openstack.AuthenticatedClient(auth)
```
```
The base Identity V3 API does not accept authentication by TenantName
```
I have updated the client to use the modified auth options, so that the Tenant ID/Name is cleared out to pass validation. I've also updated the v3 auth test so that without this fix, the test fails with the error above.
> Fix v3 auth with project scope

- openstack/blockstorage/v1/volumes/results.go
- openstack/blockstorage/v1/volumes/testing/fixtures.go
- openstack/blockstorage/v1/volumes/testing/requests_test.go
This commit changes the Volume.CreatedAt type from
gophercloud.JSONRFC3339Milli to gophercloud.JSONRFC3339MilliNoZ.
For #22
> Change Block Storage v1 Volume.CreatedAt Type

- openstack/blockstorage/v1/snapshots/results.go
- openstack/blockstorage/v1/snapshots/testing/fixtures.go
- openstack/blockstorage/v1/snapshots/testing/requests_test.go
This commit changes the Snapshots.CreatedAt type from
gophercloud.JSONRFC3339Milli to gophercloud.JSONRFC3339MilliNoZ.
For #30
> Change Block Storage v1 Snapshots.CreatedAt Type

- openstack/objectstorage/v1/swauth/requests.go
- openstack/objectstorage/v1/swauth/results.go
- openstack/objectstorage/v1/swauth/testing/doc.go
- openstack/objectstorage/v1/swauth/testing/fixtures.go
- openstack/objectstorage/v1/swauth/testing/requests_test.go
- openstack/objectstorage/v1/swauth/urls.go
Swauth is an internal authentication system for Swift. This commit adds
support for Swauth in a way that still enables the resulting
*gophercloud.ServiceClient to still be able to use the existing ObjectStorage
API calls.
For #34
> Swauth Support

- openstack/networking/v2/extensions/lbaas/members/requests.go
> Make TenantID not required for lbaas member creation

- openstack/client.go
Magnum has changed the endpoint type in the service catalog from "container" to "container-infra".
> Use new endpoint type for magnum

- acceptance/openstack/compute/v2/compute.go
- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/results.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
This commit updates the Server Metadata so it can be parsed and
translated using JSON tags.
The Server Metadata result has been changed to map[string]string to
match the request.
A unit test was added to verify the above and a piece of metadata has
been added to the server creation acceptance test.
For #86
> Server Metadata Update

- acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go
- acceptance/openstack/networking/v2/extensions/layer3/layer3.go
- acceptance/openstack/networking/v2/networking.go
- openstack/networking/v2/extensions/layer3/floatingips/requests.go
- openstack/networking/v2/extensions/layer3/floatingips/testing/requests_test.go
This commit fixes floating IP disassociation by changing the PortID to a
string pointer rather than a string. This allows a value of "null" to be
passed which is what the Networking API is looking for.
For #99
> Fix Floating IP Disassociation

- openstack/identity/v3/tokens/requests.go
- openstack/testing/client_test.go
If there was a network error, this needs to be
handled to avoid nil pointer derferences later.
For #109
> Check that Create token request succeeded

- openstack/identity/v3/tokens/results.go
- openstack/identity/v3/tokens/testing/requests_test.go
This avoid a potential nil pointer dereference since
JSON decoding can succeed with missing fields.
For #108
> Check for token not being returned in JSON response

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/subnets_test.go
- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/testing/requests_test.go
This commit enables all three behaviors of a gateway during subnet creation and
updating.
If a GatewayIP is omitted, Neutron will provision a default gateway.
If a GatewayIP is set to an empty string, no gateway will be provisioned.
If a GatewayIP is specified, it will be used as the gateway IP.
A convenience function of `StringToPointer` was added to help pass empty
strings as pointers.
For #101
> Update Subnet Gateway Behavior

- openstack/blockstorage/extensions/volumeactions/requests.go
- openstack/blockstorage/extensions/volumeactions/results.go
- openstack/blockstorage/extensions/volumeactions/testing/fixtures.go
- openstack/blockstorage/extensions/volumeactions/testing/requests_test.go
- openstack/blockstorage/extensions/volumeactions/urls.go
Per Cinder API, os-begin_detaching action needs to
be called prior to os-terminate_connection. For #117 
Corresponding Cinder code: https://github.com/openstack/cinder/blob/stable/newton/cinder/api/contrib/volume_actions.py#L138
> Add BeginDetaching call for Cinder v2

- acceptance/openstack/networking/v2/extensions/fwaas/fwaas.go
- openstack/networking/v2/extensions/fwaas/rules/requests.go
- openstack/networking/v2/extensions/fwaas/rules/testing/requests_test.go
This commit enables FWaaS Rules to allow any protocols. It does this
by creating constants for each valid type of protocol, and upon the
type of ProtocolAny being used, the request's protocol parameter will
be null.
For #161
> Allow Any Protocol in FWaaS Rules

- openstack/containerorchestration/v1/baymodels/results.go
- openstack/containerorchestration/v1/baymodels/testing/requests_test.go
Server type specifies if a bay (cluster) is vm or lxc.
> Expose server type on baymodels

- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
This PR implements [`deleting`][1] a Manila [`share`][2].
Manila implementation of delete can be found:
https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/share/api.py#L675
For #129 
[1]: http://developer.openstack.org/api-ref/shared-file-systems/?expanded=delete-share-detail#delete-share
[2]: http://docs.openstack.org/admin-guide/shared-file-systems-key-concepts.html#share
> feature/shared file systems: delete a share

- acceptance/openstack/compute/v2/limits_test.go
- openstack/compute/v2/extensions/limits/requests.go
- openstack/compute/v2/extensions/limits/results.go
- openstack/compute/v2/extensions/limits/testing/fixtures.go
- openstack/compute/v2/extensions/limits/testing/requests_test.go
- openstack/compute/v2/extensions/limits/urls.go
This commit adds support for the /limits API. It includes the ability
to query limits for the currently scoped user as well as to query the
limits for a specific tenant.
For #113
> Compute Limits

- params.go
- testing/params_test.go
This commit modifies the isZero function so it checks to see if
a pointer is actually set rather than if it points to a zero value.
For #168
> Update how isZero handles Pointers

- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
Currently, the `UserData` field is always Base64 encoded, even if it could already be Base64 encoded. 
This improves the behaviour by checking if the current value is already Base64 encoded, and skips the encoding if it is. 
Otherwise, it will Base64 encode before submitting the request.
> computer/v2/servers: Check if opts.UserData is already Base64 Encoded

- openstack/identity/v2/tokens/results.go
- openstack/identity/v3/endpoints/results.go
- openstack/identity/v3/tokens/results.go
> Removing unused createErr functions from Identity packages

- openstack/db/v1/instances/results.go
- openstack/db/v1/instances/testing/fixtures.go
Changes parsing of time fields for database instances to match the non-Z format returned by trove.
Trove stores the times as `datetime` objects:
(created) https://github.com/openstack/trove/blob/stable/newton/trove/db/models.py#L35
(updated) https://github.com/openstack/trove/blob/stable/newton/trove/db/models.py#L60
The `datetime` is converted to a string using `isoformat()`, meaning no Z:
https://github.com/openstack/trove/blob/stable/newton/trove/common/base_wsgi.py#L453
This PR solves the same issue as #155 but keeps using `time.Time` in the `Instance` struct.
For #159
> db/instances: expect non-Z time format

- openstack/db/v1/flavors/results.go
- openstack/db/v1/flavors/testing/fixtures.go
- openstack/db/v1/flavors/testing/requests_test.go
- openstack/db/v1/instances/results.go
- openstack/db/v1/instances/testing/fixtures.go
* Trove flavor IDs returned with instances are always strings
https://github.com/openstack/trove/blob/stable/newton/trove/instance/models.py#L212
* Trove flavor IDs returned with flavors are integers or null, there is a
str_id parameter that contains the ID in string format
https://github.com/openstack/trove/blob/stable/newton/trove/flavor/views.py#L33
Because of the differing return types this PR solves #160 by not referring to `flavor.Flavors` from instance. Instead instance uses its own struct with the ID as type string.
For #160
> db: fix flavor id parsing

- openstack/db/v1/instances/results.go
For #198 
Parses IP addresses returned by Trove when no hostname is available:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/views.py#L46
> db/instance: add support for IPs in response body

- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/quotaset_test.go
- openstack/compute/v2/extensions/quotasets/requests.go
- openstack/compute/v2/extensions/quotasets/results.go
- openstack/compute/v2/extensions/quotasets/testing/fixtures.go
- openstack/compute/v2/extensions/quotasets/testing/requests_test.go
- openstack/compute/v2/extensions/quotasets/urls.go
For #207
https://github.com/openstack/nova/blob/stable/liberty/nova/api/openstack/compute/schemas/quota_sets.py#L28
Also while coding this I found and fixed two small errors in the Get-Method.
- The ssh-key-quota should be "key_pairs" instead of "keypairs"
- The quotas "server_groups" and "server_group_members" where missing
Unit and acceptance tests added and succeeding.
> Added functionality for updating and resetting compute quotas.

- acceptance/openstack/networking/v2/extensions/fwaas/firewall_test.go
- acceptance/openstack/networking/v2/extensions/fwaas/fwaas.go
- openstack/networking/v2/extensions/fwaas/routerinsertion/doc.go
- openstack/networking/v2/extensions/fwaas/routerinsertion/requests.go
- openstack/networking/v2/extensions/fwaas/routerinsertion/testing/doc.go
- openstack/networking/v2/extensions/fwaas/routerinsertion/testing/requests_test.go
For #219 
https://github.com/openstack/neutron-fwaas/blob/d2938b247104ac6d7c945167b246cfcfed8393e8/neutron_fwaas/extensions/firewallrouterinsertion.py
This is an extension, so it could probably go under `gophercloud/openstack/networking/v2/extensions/fwaas/extensions/routerinsertion`, but I felt the 2 extensions made the package name too long.
> FWaaS Router Insertion

- testing/util_test.go
- util.go
This commit modifies WaitFor in a few ways:
It replaces time.Now().Second() with time.Now().Unix() in order to
account for rolling minutes (for example, when WaitFor starts at 59
seconds, every timeout check will result in a negative number).
A "retry" timer has also been added. This will cause the predicate
to be retried every n seconds if there hasn't been a response. This
is to account for server or network issues that would cause the
predicate to be lost or hang indefinitely.
A combination of using both timeout and retry can be effective in
handling faulty requests as well as a master kill switch to stop.
For #116 
Should supersede #83  
`ticks` and `tocks` have been left in for review purposes. They can be removed once confirmed that this implementation looks good.
> Refactor WaitFor

- acceptance/openstack/networking/v2/ports_test.go
- openstack/networking/v2/ports/requests.go
- openstack/networking/v2/ports/testing/requests_test.go
This commit enables security groups and address pairs to be removed
from a port. This is done by allowing an empty value to be passed
for either attribute in the port update request.
For #226
> Ports: Remove Security Groups and Address Pairs

- openstack/blockstorage/v1/volumes/requests.go
- openstack/blockstorage/v1/volumes/testing/fixtures.go
- openstack/blockstorage/v1/volumes/testing/requests_test.go
This commit updates the Block Storage v1 create request to use
AvailabilityZone instead of Availability.
For #245
> Use AvailabilityZone instead of Availability

- openstack/imageservice/v2/images/results.go
For #251 
If I get some time, I'll write up some acceptance tests for the ImageService package. As an interim, [Terraform image data source](https://github.com/jtopjian/terraform/blob/e077dd1e7be407a41cb8cab664db64d9b7fe2969/builtin/providers/openstack/data_source_openstack_images_image.go) I'm working on was able to succeed with this patch, so it kind of acts like an acceptance test.
side note: I'll probably be writing more data sources in the future. They map very well with ListOpts, so they might prove useful for finding other bugs in the List areas.
> ImageService v2: Fix paging when next URL is blank

- pagination/pager.go
When building the single page in `AllPages`, if the result is a `map[string]interface{}`, we need the key to the `[]map[string]interface{}`, but we don't know what it is a priori. So we iterate over the keys in the `map[string]interface{}` and look for a field of type `[]interface{}`. In this search, there was a case for a field of type `map[string]interface{}` which I don't think is possible, and which also was causing non-deterministic behavior in `AllPages` (because we are iterating over `map` fields, which are not guaranteed to be ordered).
For #275
> remove case for map[string]interface from switch statement in AllPages

- openstack/compute/v2/images/results.go
- openstack/compute/v2/images/testing/requests_test.go
The Compute API will attempt to parse JSON values for the image metadata values of `block_device_mapping` and `mappings`.
For #216 
@jrperritt I can't seem to get this to work. Do you mind taking a look when you have time? The unit tests are set up with the current error I'm seeing.
> Compute v2: Handle JSON Image Metadata

- openstack/networking/v2/extensions/layer3/floatingips/requests.go
- openstack/networking/v2/extensions/layer3/floatingips/results.go
- openstack/networking/v2/extensions/layer3/floatingips/testing/requests_test.go
For #273
Source: https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/l3.py
Docs: https://developer.openstack.org/api-ref/networking/v2/index.html?expanded=list-floating-ips-detail
> Added RouterID field to floatingip

- README.md
- auth_options.go
- doc.go
- openstack/compute/v2/extensions/keypairs/results.go
- openstack/db/v1/instances/testing/fixtures.go
For #252
I was reading through some of the docs and just noticed a few things. Most of them are trivial, but I figured I'd make a PR anyway. It's possible that some of the words in this might help with the situation described in 252 (cross-domain scoping should work fine if projects are specified by ID. specifying domain information is only useful if the user wants to specify both user and project by name - but since both can be specified by id, then it's really not an actual issue)
> Update some docs for some nits found

- auth_options.go
For #255 
code in this PR: Um, not sure.
I am unable to reauth in my project. The issue is that the scope is not generated correctly after the first auth. All subsequent auth lose access to the TenantId because it is mutated and set to `""`.
```golang
scope.ProjectID = opts.TenantID
-               opts.TenantID = ""
-               opts.TenantName = ""
```
to support that change I also comment out a sanity check. I'm not sure if that sanity check is necessary for other environments but my standalone script works fine without it.
> Remove checks for TenantId

- acceptance/openstack/client_test.go
- auth_options.go
This commit stops auth_options.go from clearing the TenantName.
It also adds an acceptance test for reauthentication.
For #255
> Continue reauth fixes

- openstack/compute/v2/extensions/schedulerhints/requests.go
- openstack/compute/v2/extensions/schedulerhints/testing/requests_test.go
Some OpenStack installation[[1](https://www.chameleoncloud.org/
)] use a lease system.  Leases are usually
provided by blazar[[2](https://wiki.openstack.org/wiki/Blazar
)] and each lease is composed of a list of
reservations. When creating servers, one must pass a valid reservation
id in order to indicate to the system which reservation will be used by
the future resource.
For #317
> Add arbitrary key/value scheduler hints ( was add reservation in scheduler hints)

- acceptance/README.md
Enforce `$GOPATH` instead of `~/go` in `gophercloudest()` bash function. Everyone should have `$GOPATH` set, but it may not point to ~/go.
For #296
> use $GOPATH in the readme of acceptance tests

- acceptance/openstack/dns/v2/recordsets_test.go
- openstack/dns/v2/recordsets/doc.go
- openstack/dns/v2/recordsets/requests.go
- openstack/dns/v2/recordsets/results.go
- openstack/dns/v2/recordsets/testing/doc.go
- openstack/dns/v2/recordsets/testing/fixtures.go
- openstack/dns/v2/recordsets/testing/requests_test.go
- openstack/dns/v2/recordsets/urls.go
For #57 
Supersedes #175 
URLs:
https://github.com/openstack/designate/blob/master/designate/api/v2/controllers/recordsets.py
https://github.com/openstack/designate/blob/master/designate/api/v2/controllers/common.py
https://github.com/openstack/designate/blob/master/designate/objects/recordset.py
https://github.com/openstack/designate/blob/master/designate/objects/adapters/api_v2/recordset.py
https://github.com/openstack/designate/tree/stable/newton/api-ref/source/samples/recordsets
> DNS v2: RecordSet List, Get

- acceptance/openstack/networking/v2/extensions/security_test.go
- openstack/networking/v2/extensions/security/groups/requests.go
- openstack/networking/v2/extensions/security/groups/testing/requests_test.go
Fixes incorrect implementation of security group update.
For #347
200 response code is defined [here](https://github.com/openstack/neutron/blob/19a069d99f7249854fab9ff2706a38fe8b66bb1e/neutron/wsgi.py#L689). Since there's a result returned, the code is 200.
> Networking v2: Security Group Update Fix

- acceptance/openstack/blockstorage/v2/blockstorage.go
- acceptance/openstack/blockstorage/v2/snapshots_test.go
- openstack/blockstorage/v2/snapshots/doc.go
- openstack/blockstorage/v2/snapshots/requests.go
- openstack/blockstorage/v2/snapshots/results.go
- openstack/blockstorage/v2/snapshots/testing/doc.go
- openstack/blockstorage/v2/snapshots/testing/fixtures.go
- openstack/blockstorage/v2/snapshots/testing/requests_test.go
- openstack/blockstorage/v2/snapshots/urls.go
- openstack/blockstorage/v2/snapshots/util.go
Note that there is little difference between V1 and V2, and
subsequently even V3.
For #349
Links to source code regarding the API additions that include params:
* Create
https://github.com/openstack/cinder/blob/master/cinder/api/v2/snapshots.py#L135
* ViewBuilder for snapshots (API Snapshot object from Cinder)
https://github.com/openstack/cinder/blob/master/cinder/api/views/snapshots.py#L45
* Snapshot Metadata controller
https://github.com/openstack/cinder/blob/master/cinder/api/v2/snapshot_metadata.py
Example usage from the cinderclient to show options and url's used (note
the client does hacky things like import other version objects,
fortunately there's no delta between base V3.0 and v2):
* Create
https://github.com/openstack/python-cinderclient/blob/master/cinderclient/v3/volume_snapsh …
> Add Cinder V2 Snapshot support

- internal/testing/util_test.go
- internal/util.go
This commit adds the RemainingKeys function which can be used to
detect fields returned in response bodies but are not defined in
the resource's result struct.
For #350
> internal: Add RemainingKeys function

- openstack/client.go
- service_client.go
For #53
https://github.com/openstack/manila/blob/stable/newton/manila/common/config.py#L196
https://github.com/openstack/nova/blob/acfbec7db9a3df5a3183a2730510fa1f0fea92bf/nova/api/openstack/wsgi.py#L68
I think those are the only 2 services that Gophercloud currently supports that offer microversions. It does look like the `X-OpenStack-<SERVICE>-API-Version` headers are being replaced by `OpenStack-API-Version`, but are still around for backwards-compatibility, so I'm adding both. Hopefully that won't cause a problem.
This is an alternative implementation to the ones in #341 and #352 . I think it's cleaner and doesn't force users to identify the service type.
It also refactors some of the common …
> fix microversion header

- openstack/blockstorage/v2/snapshots/requests.go
Snapshot create opts are using map[string]interface{} for the
metadata opt.  This is doable, but we should be consistent with
other objects/resources and use map[string]string.
I missed this on the initial commit, so this patch just modifies
the CreateOption struct to make it match the types we use in Volumes.
For #367
> Use map[string]string for snapshot createopt

- acceptance/openstack/imageservice/v2/images_test.go
- openstack/imageservice/v2/images/results.go
- openstack/imageservice/v2/images/testing/fixtures.go
- openstack/imageservice/v2/images/testing/requests_test.go
For #260 
While investigating this, I discovered that `virtual_size` was a first-class field:
* https://github.com/openstack/glance/blob/48ee8ef4793ed40397613193f09872f474c11abe/glance/db/sqlalchemy/migrate_repo/versions/034_add_virtual_size.py
* https://github.com/openstack/glance/blob/61046c8f247d52d5cd506ad465dcd0e70b2cb4b2/glance/domain/__init__.py#L51
`self` is being deleted from the JSON response since it's included in every response and part of the pagination system of Glance.
> ImageService v2: Collect all properties of images

- acceptance/openstack/identity/v3/projects_test.go
- openstack/identity/v3/projects/requests.go
- openstack/identity/v3/projects/testing/requests_test.go
> Identity v3: Remove GetOpts/GetOptsBuilder from Projects

- pagination/http.go
FIX #384
According to [this line](https://github.com/openstack/cinder/blob/master/api-ref/source/v1/volumes-v1-versions.inc#list-api-versions-v1) in Cinder, HTTP status 300 could return when blockstorage list API versions.
> support HTTP status 300 in pagination

- openstack/identity/v2/tenants/requests.go
- openstack/identity/v2/tenants/results.go
- openstack/identity/v2/tenants/testing/fixtures.go
- openstack/identity/v2/tenants/testing/requests_test.go
- openstack/identity/v2/tenants/urls.go
For #397
create_tenant general implementation 
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/core.py#L293
create_tenant sql driver implementation 
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/backends/sql.py#L331
> Add tenants V2 create support

- openstack/identity/v2/tenants/requests.go
- openstack/identity/v2/tenants/results.go
- openstack/identity/v2/tenants/testing/fixtures.go
- openstack/identity/v2/tenants/testing/requests_test.go
- openstack/identity/v2/tenants/urls.go
For #397
get_tenant general implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/core.py#L283
get_tenant sql driver implementation
https://github.com/openstack/keystone/blob/5c8dcd2f2f1a7645f93f39c3f5784920e2099998/keystone/identity/backends/sql.py#L161
> Add tenants V2 get support

- openstack/compute/v2/servers/requests.go
A very simple change that allows listing of servers for any particular tenant.
Issue #410
Here is how the server listing would work:
```
serverOpts := servers.ListOpts{AllTenants: true, TenantID: <tenant-id>}
pager := servers.List(client, serverOpts)
```
> Allows a user with privilege to list servers for any particular tenant

- openstack/networking/v2/extensions/layer3/floatingips/requests.go
It lets `floatingips.List()` filter by `Status` (which can be `ACTIVE`,
`DOWN` or `ERROR`).
For #418
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/l3.py#L134-L135
> floatingips: Add Status field to ListOpts

- openstack/sharedfilesystems/apiversions/doc.go
- openstack/sharedfilesystems/apiversions/errors.go
- openstack/sharedfilesystems/apiversions/requests.go
- openstack/sharedfilesystems/apiversions/results.go
- openstack/sharedfilesystems/apiversions/testing/doc.go
- openstack/sharedfilesystems/apiversions/testing/fixtures.go
- openstack/sharedfilesystems/apiversions/testing/requests_test.go
- openstack/sharedfilesystems/apiversions/urls.go
For #408 
@jrperritt There's some discussion here:
https://github.com/jtopjian/gophercloud/commit/5bf58ab1beb18b3220bd0b63f74104a56e1f273e
https://github.com/jtopjian/gophercloud/commit/7f48e23cca311be0fb1796e61bbded54cfefb7d6
This implementation could definitely use some critique when you have time.
Should proper error types be created?
The most notable oddity is that when retrieving a major version, an array is returned. I can't see why more than one result would be returned, but is that a safe assumption?
If it's best to handle multiple results, then this gets a little weird. The way I see it, a Get should be treated like a List and there should then be some convenience functions to extract the best result (or specify the type of result). But since there's no example of what multiple …
> SharedFileSystems: apiversions package

- acceptance/openstack/blockstorage/extensions/extensions.go
- acceptance/openstack/blockstorage/extensions/volumeactions_test.go
- openstack/blockstorage/extensions/volumeactions/requests.go
- openstack/blockstorage/extensions/volumeactions/results.go
- openstack/blockstorage/extensions/volumeactions/testing/fixtures.go
- openstack/blockstorage/extensions/volumeactions/testing/requests_test.go
I've added response body to UploadImageResults and added method Extract to extract the response into an object.
For #416 
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/volume_actions.py#L304
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/volume_actions.py#L290-L293
https://github.com/openstack/cinder/blob/master/cinder/volume/api.py#L1272-L1281
> Added method to get info from Volume actions volume_upload_image method response

- openstack/compute/v2/extensions/suspendresume/doc.go
- openstack/compute/v2/extensions/suspendresume/requests.go
- openstack/compute/v2/extensions/suspendresume/testing/doc.go
- openstack/compute/v2/extensions/suspendresume/testing/fixtures.go
- openstack/compute/v2/extensions/suspendresume/testing/requests_test.go
For #432
https://github.com/openstack/nova/blob/stable/ocata/nova/api/openstack/compute/suspend_server.py
https://github.com/openstack/nova/blob/stable/ocata/nova/compute/api.py#L3381
The forked gophercloud repository is missing in #433 , recreate a new PR.
> support suspend/resume for compute instance

- acceptance/openstack/compute/v2/servers_test.go
- openstack/compute/v2/extensions/attachinterfaces/doc.go
- openstack/compute/v2/extensions/attachinterfaces/requests.go
- openstack/compute/v2/extensions/attachinterfaces/results.go
- openstack/compute/v2/extensions/attachinterfaces/testing/doc.go
- openstack/compute/v2/extensions/attachinterfaces/testing/fixtures.go
- openstack/compute/v2/extensions/attachinterfaces/testing/requests_test.go
- openstack/compute/v2/extensions/attachinterfaces/urls.go
Add support to list interface for a server
through a GET on: /v2.1/{tenant_id}/servers/{server_id}/os-interface
The same operation with OpenStack CLI is done with:
nova interface-list <server_id>
Fix gophercloud issue:
https://github.com/gophercloud/gophercloud/issues/431
Fix kubernetes issue: 
https://github.com/kubernetes/kubernetes/issues/43909
> Add Nova interface-list support

- acceptance/openstack/identity/v3/users_test.go
- openstack/identity/v3/groups/results.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
Adds a method to v3 bindings to retrieve groups user belongs to,
based on his/her ID.
For #382 
groups resource definition in keystone request router: https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/routers.py#L77-L84
list_group_for_users general implementation https://github.com/openstack/keystone/blob/16f6ed14df136eb9c283a5415b9f18fcb0834350/keystone/identity/core.py#L1281
list_group_for_users SQL driver implementation https://github.com/openstack/keystone/blob/7754f170aa0eb42bea356e7f912bc241832eb1f3/keystone/identity/backends/sql.py#L312
Based on: https://developer.openstack.org/api-ref/identity/v3/?expanded=list-groups-to-which-a-user-bel …
> Add ListGroups method to Retrieve groups user belongs to

- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #380
https://github.com/openstack/manila/blob/master/manila/api/v2/share_export_locations.py#L25
> Shared Filesystems: Share Export Locations

- auth_options.go
- doc.go
- endpoint_search.go
- params.go
For #446 
@jrperritt This was just a quick update to the godoc found in the `gophercloud` top-level directory. The main focus of #446 will be adding documentation for the various services found in `gophercloud/openstack`.
> Docs: Top level doc updates

- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
> SharedFileSystems v2: Restrict ExtractExportLocations to only GetExportLocationsResults

- openstack/common/README.md
- openstack/common/extensions/doc.go
- openstack/common/extensions/errors.go
- openstack/common/extensions/results.go
This commit cleans up the common package by removing unused files
as well as adds more detailed documentation.
For #446
> Common: Clean up common package

- acceptance/openstack/compute/v2/migrate_test.go
- openstack/compute/v2/extensions/migrate/doc.go
- openstack/compute/v2/extensions/migrate/requests.go
- openstack/compute/v2/extensions/migrate/results.go
- openstack/compute/v2/extensions/migrate/testing/doc.go
- openstack/compute/v2/extensions/migrate/testing/fixtures.go
- openstack/compute/v2/extensions/migrate/testing/requests_test.go
- openstack/compute/v2/extensions/migrate/urls.go
For #82 
Supersedes #84 
https://github.com/openstack/nova/blob/77b11a9e31e265c338857326418bfe8cd135c1f8/nova/api/openstack/compute/migrate_server.py
Note that this only implements what would be handled in the `_migrate` function, not the `_migrate_live` function.
> Compute v2: Adding Migrate Action

- acceptance/openstack/networking/v2/extensions/extensions.go
- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/ports_test.go
- openstack/networking/v2/extensions/portsbinding/testing/fixtures.go
- openstack/networking/v2/extensions/portsbinding/testing/requests_test.go
- openstack/networking/v2/ports/doc.go
- openstack/networking/v2/ports/requests.go
- openstack/networking/v2/ports/testing/requests_test.go
Port `SecurityGroups` and `AllowedAddressPairs` have a tertiary type of behavior.
During creation, if `security_groups` is omitted from the request body, then Neutron will apply the default security group. If an empty array is passed, no security groups will be applied to the port. If an array of security groups is passed, those security groups will be applied to the port.
For update, if `security_groups` is omitted from the request body, existing security groups on the port are unchanged. If an empty array is passed, all security groups are removed. If an array of security groups is passed, then the port will have those groups applied.
`allowed_address_pairs` has the same behavior, but only for updates.
For #509 
Amends #236
#236 has the appropriate links to the API code, but the client …
> Networking v2: Port Fixes

- openstack/blockstorage/extensions/volumetenants/doc.go
- openstack/blockstorage/extensions/volumetenants/results.go
- openstack/blockstorage/v2/volumes/testing/requests_test.go
For #455 
For #446 
`VolumeExt` is renamed to `VolumeTenantExt` since `VolumeExt` is rather generic and having two extensions named `VolumeExt` cannot be used together.
The `UnmarshalJSON` function is not needed, so it has been removed.
Example documentation has also been added.
> BlockStorage v2: Clean-up volumetenants

- acceptance/openstack/identity/v3/users_test.go
- openstack/identity/v3/users/doc.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
For #528
Details: Add ListUsers function for Gophercloud's OpenStack Identity v3 API
- Allows a caller to get the list of projects that a specified user has access to
- Effectively wraps OpenStack Identity v3 API function /v3/users/{user_id}/projects
- Based on implementation of ListGroups
https://developer.openstack.org/api-ref/identity/v3/#list-projects-for-user
https://github.com/openstack/keystone/blob/stable/pike/keystone/common/policies/user.py#L39
https://github.com/openstack/keystone/blob/stable/pike/keystone/auth/controllers.py#L363-L381
**Update** Source link identified by maintainer: https://github.com/openstack/keystone/blob/6b6e1a7322666fb4da871281bb8c58db199c7f49/keystone/assignment …
> Identity v3 - Add Get Projects by User

- openstack/identity/v3/users/doc.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
Adding ability to list users belonging to a group given the group id.
Although this is logically a group operation, mixing this operation into groups creates a circular dependency between groups and users OR requires adding packages for common components. This approach was deemed the least offensive.
For #385
groups resource definition in keystone request router: 
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/routers.py#L50-L57
list_group_for_users general implementation 
https://github.com/openstack/keystone/blob/16f6ed14df136eb9c283a5415b9f18fcb0834350/keystone/identity/core.py#L1314
list_group_for_users SQL driver implementation …
> Adding ability to list users for a group.

- openstack/compute/v2/extensions/resetstate/doc.go
- openstack/compute/v2/extensions/resetstate/requests.go
- openstack/compute/v2/extensions/resetstate/results.go
- openstack/compute/v2/extensions/resetstate/testing/doc.go
- openstack/compute/v2/extensions/resetstate/testing/fixtures.go
- openstack/compute/v2/extensions/resetstate/testing/requests_test.go
- openstack/compute/v2/extensions/resetstate/urls.go
For #521
Links to the line numbers/files in the OpenStack source code (Nova API service) that support the
https://github.com/openstack/nova/blob/c2aa30b102808882c85d3d3f53d531c4510218cd/nova/api/openstack/compute/admin_actions.py#L74
https://github.com/openstack/nova/blob/c2aa30b102808882c85d3d3f53d531c4510218cd/nova/api/openstack/compute/admin_actions.py#L29-L32
> Compute v2: Add Reset State Action

- acceptance/openstack/identity/v3/groups_test.go
- acceptance/openstack/identity/v3/identity.go
- openstack/identity/v3/groups/doc.go
- openstack/identity/v3/groups/requests.go
- openstack/identity/v3/groups/results.go
- openstack/identity/v3/groups/testing/fixtures.go
- openstack/identity/v3/groups/testing/requests_test.go
- openstack/identity/v3/groups/urls.go
Changing group acceptance tests to a CRUD based test now that
create exists. This also reduces the risks of errant test failures
as group existence is not required in an openstack v3 deployment. The
Update and Delete will be added as the functionality is merged.
For #539 
Create:
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/controllers.py#L316
https://github.com/openstack/keystone/blob/master/keystone/identity/backends/sql.py#L346
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/schema.py#L106
> Identity v3: Add Group create

- acceptance/openstack/identity/v3/groups_test.go
- acceptance/openstack/identity/v3/identity.go
- openstack/identity/v3/groups/doc.go
- openstack/identity/v3/groups/requests.go
- openstack/identity/v3/groups/results.go
- openstack/identity/v3/groups/testing/fixtures.go
- openstack/identity/v3/groups/testing/requests_test.go
- openstack/identity/v3/groups/urls.go
For #539
Delete:
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/controllers.py#L354
https://github.com/openstack/keystone/blob/stable/pike/keystone/identity/backends/sql.py#L394
> Identity v3: group delete

- acceptance/openstack/identity/v3/domains_test.go
- openstack/identity/v3/domains/doc.go
- openstack/identity/v3/domains/requests.go
- openstack/identity/v3/domains/results.go
- openstack/identity/v3/domains/testing/fixtures.go
- openstack/identity/v3/domains/testing/requests_test.go
- openstack/identity/v3/domains/urls.go
For #555 
List:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/resource/controllers.py#L123
Get:
General project model/schema:
https://github.com/openstack/keystone/blob/master/keystone/resource/schema.py#L51
Controller / router:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/resource/controllers.py#L189
> Identity v3 domain list / get

- openstack/compute/v2/extensions/evacuate/doc.go
- openstack/compute/v2/extensions/evacuate/requests.go
- openstack/compute/v2/extensions/evacuate/results.go
- openstack/compute/v2/extensions/evacuate/testing/doc.go
- openstack/compute/v2/extensions/evacuate/testing/fixtures.go
- openstack/compute/v2/extensions/evacuate/testing/requests_test.go
- openstack/compute/v2/extensions/evacuate/urls.go
For #519 
https://github.com/openstack/nova/blob/stable/ocata/nova/api/openstack/compute/evacuate.py
cc @jtopjian
> Compute v2: Add Evacuate Action

- acceptance/openstack/identity/v3/roles_test.go
- openstack/identity/v3/roles/doc.go
- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
- openstack/identity/v3/roles/testing/fixtures.go
- openstack/identity/v3/roles/testing/requests_test.go
- openstack/identity/v3/roles/urls.go
For #550 
List:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L335
Get:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L349
Renamed Role struct used in RoleAssignment to AssignedRole as the scope of the Role field in RoleAssignment is a subset of the full v3 role API result. 
Ideally, I would move the previous role_assignment code to a role_assignment package, but as that code has existed for over 2 years, that could break existing users/implementations.
I can also see refactoring the role_assignment tests to match the rest of the identity v3 test …
> Identity v3 role list / get

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/roles_test.go
- openstack/identity/v3/roles/doc.go
- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
- openstack/identity/v3/roles/testing/fixtures.go
- openstack/identity/v3/roles/testing/requests_test.go
- openstack/identity/v3/roles/urls.go
Adding create role. This also updates the result structure of `Role` to add an `Extra` field as this patch allowed testing/validation of support for the `Extra` field.
For #571 
Schema:
https://github.com/openstack/keystone/blob/stable/pike/keystone/assignment/role_backends/sql.py#L196
https://github.com/openstack/keystone/blob/stable/pike/keystone/assignment/role_backends/sql.py#L201
Create:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L319
> Identity v3: role create

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/roles_test.go
- openstack/identity/v3/roles/doc.go
- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
- openstack/identity/v3/roles/testing/fixtures.go
- openstack/identity/v3/roles/testing/requests_test.go
- openstack/identity/v3/roles/urls.go
This is an implementation for assigning/unassining a role to a user on a project for #566.
* [api doc for assigning](https://developer.openstack.org/api-ref/identity/v3/#assign-role-to-user-on-project)
* [api doc for unassining](https://developer.openstack.org/api-ref/identity/v3/#unassign-role-from-user-on-project)
* https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L638
* https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L677
This is a contribution from [Salesforce](https://www.salesforce.com/)
> Identity v3: Add assigning a role to a user on a project

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/roles_test.go
- openstack/identity/v3/roles/doc.go
- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
- openstack/identity/v3/roles/testing/fixtures.go
- openstack/identity/v3/roles/testing/requests_test.go
- openstack/identity/v3/roles/urls.go
For #571 
Update:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L367
Note that the API for roles does not support updating the domain ID per https://developer.openstack.org/api-ref/identity/v3/#update-role
> Identity v3 Role update

- acceptance/openstack/identity/v3/regions_test.go
- openstack/identity/v3/regions/doc.go
- openstack/identity/v3/regions/requests.go
- openstack/identity/v3/regions/results.go
- openstack/identity/v3/regions/testing/fixtures.go
- openstack/identity/v3/regions/testing/requests_test.go
- openstack/identity/v3/regions/urls.go
For #583
API:
https://developer.openstack.org/api-ref/identity/v3/#regions
Schema:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/backends/sql.py#L34
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/schema.py#L22
List:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L70
Get:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L78
> Identity v3: Region list / get

- .zuul.yaml
I'd like to request to integrate a new CI system which built based on
zuul[1] and nodepool[2] tools to Gophercloud repo. It is for running
Gophercloud tests(both unit tests and acceptance tests) based on a
devstack[3] environment. For now, my colleagues and I have basicially
finish the CI system building, and have tested with Gophercloud, it can
work OK, please see[4]. We will long-term maintain the CI system and would
like to propose to intergrate with Gophercloud official repo.
FYI, the zuul jobs definition can be found in [5], the zuul jobs status web
page is [6], the test jobs log server is [7].
[1] https://docs.openstack.org/infra/zuul/
[2] https://docs.openstack.org/infra/nodepool/
[3] https://docs.openstack.org/devstack/latest/
[4] https://github.com/theopenlab/gophercloud/pull/5 …
> Request integrating a new CI system to Gophercloud

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/regions_test.go
- openstack/identity/v3/regions/doc.go
- openstack/identity/v3/regions/requests.go
- openstack/identity/v3/regions/results.go
- openstack/identity/v3/regions/testing/fixtures.go
- openstack/identity/v3/regions/testing/requests_test.go
- openstack/identity/v3/regions/urls.go
For #583 
Note region create is unique from most of the rest of the identity resources in that you can directly specify the ID, but providing the ID string is optional.
API:
https://developer.openstack.org/api-ref/identity/v3/#create-region
Schema:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/backends/sql.py#L161
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/schema.py#L36
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/schema.py#L22
Create:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/cat …
> Identity v3 region create

- openstack/compute/v2/extensions/diskconfig/doc.go
- openstack/compute/v2/extensions/diskconfig/requests.go
- openstack/compute/v2/extensions/diskconfig/results.go
- openstack/compute/v2/servers/testing/requests_test.go
For #470 
For #446 
A unit test for the extension can be added after #466 is merged since it modifies the same area of code. I tested it locally and it works as expected.
> Compute v2: Clean up diskconfig package

- acceptance/openstack/identity/v3/regions_test.go
- openstack/identity/v3/regions/doc.go
- openstack/identity/v3/regions/requests.go
- openstack/identity/v3/regions/results.go
- openstack/identity/v3/regions/testing/fixtures.go
- openstack/identity/v3/regions/testing/requests_test.go
- openstack/identity/v3/regions/urls.go
Note that ID cannot be updated even though it is settable on create.
There is also currently an issue with updating the Extra field. This I believe is
a bug in keystone. I have posted a bug and patch to fix. https://bugs.launchpad.net/keystone/+bug/1729933
For #583
API:
https://developer.openstack.org/api-ref/identity/v3/#update-region
Schema:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/backends/sql.py#L175
Update:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L83
> Identity v3 Region update

- provider_client.go
For #232 
```go
// get client latest token and add to header
for k, v := range client.AuthenticatedHeaders() {
req.Header.Add(k, v)
}
// Set the User-Agent header
req.Header.Set("User-Agent", client.UserAgent.Join())
if options.MoreHeaders != nil {
// MoreHeaders holds one old token which is set by caller
for k, v := range options.MoreHeaders {
if v != "" {
req.Header.Set(k, v) // override the latest token which is refreshed by re-auth
} else {
req.Header.Del(k)
}
}
}
```
> fix token issue which results in endless loop on reauth

- openstack/compute/v2/servers/results.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
For #601 
Fault server field: https://github.com/openstack/nova/blob/d79f79abc2c6d457fc88ff3f2e6eaeb478fb5981/nova/api/openstack/compute/views/servers.py#L157-L160
Fault schema: https://github.com/openstack/nova/blob/d79f79abc2c6d457fc88ff3f2e6eaeb478fb5981/nova/api/openstack/compute/views/servers.py#L318-L342
> Compute v2: Server Fault field

- openstack/compute/v2/extensions/quotasets/doc.go
- openstack/compute/v2/extensions/quotasets/requests.go
- openstack/compute/v2/extensions/quotasets/results.go
- openstack/compute/v2/extensions/quotasets/testing/fixtures.go
- openstack/compute/v2/extensions/quotasets/testing/requests_test.go
- openstack/compute/v2/extensions/quotasets/urls.go
* Add GetQuotaDetailed function for the os-quota-sets extension in Gophercloud's OpenStack Compute v2 API
- Allows a caller to get the list of quota types with in_use, reserved, and limit values for each
- Effectively wraps OpenStack Compute v2 API function /v2/os-quota-sets/{tenant_id}/detail
- Based on implementation of GetQuota
Note: In line with "GetQuota" uses sample response body from https://developer.openstack.org/api-ref/compute/#show-the-detail-of-quota for test
Code citation: https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/quota_sets.py#L119
For #549
> Compute v2 - Add Get Detailed Quota for Tenant (#549)

- acceptance/clients/clients.go
- openstack/blockstorage/noauth/doc.go
- openstack/blockstorage/noauth/requests.go
- openstack/blockstorage/noauth/testing/requests_test.go
- openstack/blockstorage/v3/snapshots/doc.go
- openstack/blockstorage/v3/snapshots/requests.go
- openstack/blockstorage/v3/snapshots/results.go
- openstack/blockstorage/v3/snapshots/testing/doc.go
- openstack/blockstorage/v3/snapshots/testing/fixtures.go
- openstack/blockstorage/v3/snapshots/testing/requests_test.go
- openstack/blockstorage/v3/snapshots/urls.go
- openstack/blockstorage/v3/snapshots/util.go
- openstack/blockstorage/v3/volumes/doc.go
- openstack/blockstorage/v3/volumes/requests.go
- openstack/blockstorage/v3/volumes/results.go
- openstack/blockstorage/v3/volumes/testing/doc.go
- openstack/blockstorage/v3/volumes/testing/fixtures.go
- openstack/blockstorage/v3/volumes/testing/requests_test.go
- openstack/blockstorage/v3/volumes/urls.go
- openstack/blockstorage/v3/volumes/util.go
- openstack/client.go
- service_client.go
This change pulls the existing V2 implementations into V3. Note that
the base V3 version (3.0) is a direct map back to V2. As a result to
use the base V3 endpoint for Cinder we can don't need to change anything
other than the URL. Also clean up some simple lint errors in
requests.go
One thing that the base V3 version does buy us here though is
Microversions (for better or worse). So, this change also adds in the
ability to specify MicroVersion in the additional-header of the
ServiceClient. This will be important going forward and so we can now
add things like the new standalone Attachment API.
For #412
Volume V3 just points to V2 unless a microversioned call is issued:
https://github.com/openstack/cinder/blob/master/cinder/api/v3/volumes.py#L25 …
> Add Cinder V3 and MicroVersion Support

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/service_test.go
- openstack/identity/v3/services/doc.go
- openstack/identity/v3/services/requests.go
- openstack/identity/v3/services/results.go
- openstack/identity/v3/services/testing/fixtures.go
- openstack/identity/v3/services/testing/requests_test.go
- openstack/identity/v3/services/urls.go
This updates how service creation is done. It is a backward incompatible change. That said, I tested the current implementation and it fails as the body does not contain a service object. So there should not be a lot of users being broken by this change.
I've tried to break up updating Services in logical chunks. This PR got a little more of the bulk so that I could get the tests to pass and try to make it more DRY.
The API doc for this is interesting: 
- https://developer.openstack.org/api-ref/identity/v3/#create-service
There are two named parameters, name and description, that only reside in extra. And enabled gets set to True by default whether passed or not.
For #605
Schema:
- …
> Identity v3 fix/update Service define and create

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/service_test.go
- openstack/identity/v3/services/doc.go
- openstack/identity/v3/services/requests.go
- openstack/identity/v3/services/results.go
- openstack/identity/v3/services/testing/fixtures.go
- openstack/identity/v3/services/testing/requests_test.go
- openstack/identity/v3/services/urls.go
This updates how service update is done. It is a backward incompatible change.
For #605 
Schema:
https://github.com/openstack/keystone/blob/master/keystone/catalog/backends/sql.py#L53
https://github.com/openstack/keystone/blob/master/keystone/catalog/schema.py#L52
Note here name is in the schema but not in the backend, as thus it's stored in extra.
https://github.com/openstack/keystone/blob/master/keystone/catalog/schema.py#L65
Update:
- https://github.com/openstack/keystone/blob/master/keystone/catalog/controllers.py#L130
> Identity v3: Services update

- acceptance/openstack/identity/v3/identity.go
- acceptance/openstack/identity/v3/service_test.go
- openstack/identity/v3/services/doc.go
- openstack/identity/v3/services/requests.go
- openstack/identity/v3/services/results.go
- openstack/identity/v3/services/testing/fixtures.go
- openstack/identity/v3/services/testing/requests_test.go
- openstack/identity/v3/services/urls.go
This updates how service list is done. It is a backward incompatible change in that it removes two paging parameters that don't exist.
For #605 
Schema:
- https://github.com/openstack/keystone/blob/master/keystone/catalog/backends/sql.py#L53
- https://github.com/openstack/keystone/blob/master/keystone/catalog/schema.py#L52
Note here name is in the schema but not in the backend, as thus it's stored in extra.
- https://github.com/openstack/keystone/blob/master/keystone/catalog/schema.py#L65
List:
- https://github.com/openstack/keystone/blob/master/keystone/catalog/controllers.py#L116
> Identity v3: Services list

- openstack/compute/v2/servers/requests.go
This commit changes the VERIFY status for the resize operation.
The correct VERIFY_RESIZE status was gotten from:
https://developer.openstack.org/api-guide/compute/server_concepts.html
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>
For #629
https://github.com/openstack/nova/blob/master/nova/api/openstack/common.py#L76
> Fix wrong status on Resize function comment

- openstack/auth_env.go
For #461 
This change should not affect scoping due to the underlying variable names not being changed, so the logic to determine scope stays the same.
> Support project env vars

- openstack/blockstorage/v2/snapshots/requests.go
- openstack/blockstorage/v2/volumes/requests.go
- openstack/blockstorage/v3/snapshots/requests.go
- openstack/blockstorage/v3/volumes/requests.go
Query parameter `tenant` is required in a multi-tenants environment. Add this support
in blockstorage V3 APIs.
For #627
Code in Cinder:
Volumes: https://github.com/openstack/cinder/blob/master/cinder/volume/api.py#L581-L595
Snapshots: https://github.com/openstack/cinder/blob/master/cinder/volume/api.py#L638-L647
> Add 'tenant' support in volume&snapshot API

- openstack/client.go
- provider_client.go
- testing/provider_client_test.go
For #310 
- adds a `mut` field and `UseTokenLock`, `Token`, and `SetToken` methods to `ProviderClient`
- adds a unit test for concurrent reauth
- removes the `Debug` field from `ProviderClient`, which was a relic and isn't used anywhere
Intended to be backwards-compatible (with the exception of the unused and now-removed `Debug` field).
> add UseTokenLock method in ProviderClient to allow safe concurrent access

- openstack/compute/v2/extensions/attachinterfaces/doc.go
- openstack/compute/v2/extensions/attachinterfaces/requests.go
- openstack/compute/v2/extensions/attachinterfaces/results.go
- openstack/compute/v2/extensions/attachinterfaces/testing/fixtures.go
- openstack/compute/v2/extensions/attachinterfaces/testing/requests_test.go
- openstack/compute/v2/extensions/attachinterfaces/urls.go
Add support to get interface of a server through a GET on: /v2.1/{tenant_id}/servers/{server_id}/os-interface/{port_id}
For #641 
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L75
> Add support to get interface of a server

- provider_client.go
- testing/provider_client_test.go
> fix reauth deadlock by not calling Token() during reauth

- openstack/compute/v2/extensions/attachinterfaces/doc.go
- openstack/compute/v2/extensions/attachinterfaces/requests.go
- openstack/compute/v2/extensions/attachinterfaces/results.go
- openstack/compute/v2/extensions/attachinterfaces/testing/fixtures.go
- openstack/compute/v2/extensions/attachinterfaces/testing/requests_test.go
- openstack/compute/v2/extensions/attachinterfaces/urls.go
Add support to attach interface to a server through a POST on: /v2.1/{tenant_id}/servers/{server_id}/os-interface
The same operation with the OpenStack CLI is done with:
nova interface-attach <server>
For #641 
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L104
> Add Nova interface-attach support

- openstack/blockstorage/extensions/volumeactions/requests.go
- openstack/blockstorage/extensions/volumeactions/urls.go
Replace volume action's xxxxURL method with actionURL
Volume actions' url is always in the format of ``/{project}/volumes/{volume_id}/action``, there is no need
to define new xxxxURL individually.
For: #640 
**side node**: This change may be discussable or already been discussed before :smile: 
Cinder API [Document](https://developer.openstack.org/api-ref/block-storage/v3/#volume-actions-volumes-action)
> Refactor volume actions' action URL method

- openstack/compute/v2/extensions/attachinterfaces/doc.go
- openstack/compute/v2/extensions/attachinterfaces/requests.go
- openstack/compute/v2/extensions/attachinterfaces/results.go
- openstack/compute/v2/extensions/attachinterfaces/testing/fixtures.go
- openstack/compute/v2/extensions/attachinterfaces/testing/requests_test.go
- openstack/compute/v2/extensions/attachinterfaces/urls.go
Add support to detach interface from a server through a DELETE on: /v2.1/{tenant_id}/servers/{server_id}/os-interface/{port_id}
The same operation with the OpenStack CLI is done with:
nova interface-detach <server_id> <port_id>
For #641 
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L161
> Add Nova interface-detach support

- acceptance/openstack/compute/v2/servers_test.go
- openstack/compute/v2/extensions/extendedstatus/doc.go
- openstack/compute/v2/extensions/extendedstatus/results.go
- openstack/compute/v2/servers/testing/requests_test.go
I added the extended status information API as ServerExtendedStatusExt result extension.
For #658 
* [/nova/api/openstack/compute/extended_status.py](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/extended_status.py)
* OpenStack compute API doc
* [List Server Details](https://developer.openstack.org/api-ref/compute/#list-servers-detailed)
* [Show Server Details](https://developer.openstack.org/api-ref/compute/#show-server-details)
> Compute v2: Add the extended status information API

- acceptance/openstack/networking/v2/extensions/provider_test.go
When try to run the TestNetworksProviderCRUD test, the test will extract
info of a new created network and then print it, it extracts the network
info by "provider.ExtractGet" function, which is undefined. This change
use
the "Extract" method of returned network object to instead.
For #663
> Fix the undefined function error of TestNetworksProviderCRUD test

- acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding_test.go
The is a "portsbinding.Update" function will be called when run the test
TestPortsbindingCRUD, but the function is undefined, this change use the
ports.UpdateOpts to instead.
For #665
> Fix the undefined function error of TestPortsbindingCRUD test

- openstack/blockstorage/v3/volumetypes/doc.go
- openstack/blockstorage/v3/volumetypes/requests.go
- openstack/blockstorage/v3/volumetypes/results.go
- openstack/blockstorage/v3/volumetypes/testing/doc.go
- openstack/blockstorage/v3/volumetypes/testing/fixtures.go
- openstack/blockstorage/v3/volumetypes/testing/requests_test.go
- openstack/blockstorage/v3/volumetypes/urls.go
Add List/Get support for volume type in volume V3.
For #649 
**Document:**
Volume type get [V3](https://developer.openstack.org/api-ref/block-storage/v3/#show-volume-type-detail)
Volume type list [V3](https://developer.openstack.org/api-ref/block-storage/v3/#list-all-volume-types)
**Code:**
Volume type get [V3](https://github.com/openstack/cinder/blob/master/cinder/api/v2/types.py#L41)
Volume type list [V3](https://github.com/openstack/cinder/blob/master/cinder/api/v2/types.py#L35)
**Model:**
[Link](https://github.com/openstack/cinder/blob/master/cinder/db/sqlalchemy/models.py#L378)
> Add List/Get support for volume type in volume V3

- acceptance/openstack/sharedfilesystems/v2/sharetypes_test.go
This test try to init a sharetypes.SetExtraSpecsOpts object with a wrong
field name, this change fix it.
For #670
> Fix a small syntax error of TestShareTypeExtraSpecs test

- acceptance/openstack/blockstorage/v3/volumetypes_test.go
- openstack/blockstorage/v3/volumetypes/doc.go
- openstack/blockstorage/v3/volumetypes/requests.go
- openstack/blockstorage/v3/volumetypes/results.go
- openstack/blockstorage/v3/volumetypes/testing/fixtures.go
- openstack/blockstorage/v3/volumetypes/testing/requests_test.go
- openstack/blockstorage/v3/volumetypes/urls.go
Add Create support for volume type in volume V3.
For #649 
**Document:**
Volume type create [V3](https://developer.openstack.org/api-ref/block-storage/v3/#create-a-volume-type)
**Code:**
Volume type create [V3](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/types_manage.py#L51)
**Model:**
[Link](https://github.com/openstack/cinder/blob/master/cinder/db/sqlalchemy/models.py#L378)
> Add CREATE support in V3 volume types

- acceptance/openstack/blockstorage/v3/volumes_test.go
- openstack/blockstorage/v3/volumes/requests.go
- openstack/blockstorage/v3/volumes/results.go
- openstack/blockstorage/v3/volumes/testing/fixtures.go
Pagniation is supported in blockstorage's [volume ](https://developer.openstack.org/api-ref/block-storage/v3/#list-accessible-volumes-with-details) resource.
Code: [Volume](https://github.com/openstack/cinder/blob/master/cinder/api/v3/volumes.py#L99)
For #676
> Support pagination in volume resources

- acceptance/openstack/blockstorage/v3/snapshots_test.go
- openstack/blockstorage/v3/snapshots/requests.go
- openstack/blockstorage/v3/snapshots/results.go
- openstack/blockstorage/v3/snapshots/testing/fixtures.go
Pagniation is supported in blockstorage's [snapshot ](https://developer.openstack.org/api-ref/block-storage/v3/#list-snapshots-and-details) resource.
Code: [Snapshot](https://github.com/openstack/cinder/blob/master/cinder/api/v3/snapshots.py#L78)
For #676
> Support pagination in snapshot resources 

- acceptance/openstack/blockstorage/v3/volumetypes_test.go
- openstack/blockstorage/v3/volumetypes/doc.go
- openstack/blockstorage/v3/volumetypes/requests.go
- openstack/blockstorage/v3/volumetypes/results.go
- openstack/blockstorage/v3/volumetypes/testing/fixtures.go
- openstack/blockstorage/v3/volumetypes/testing/requests_test.go
- openstack/blockstorage/v3/volumetypes/urls.go
Add Delete support for volume type in volume V3.
For #649 
Volume type delete [V3](https://developer.openstack.org/api-ref/block-storage/v3/#delete-a-volume-type)
> Add DELETE support in V3 volume types

- acceptance/openstack/compute/v2/flavors_test.go
- openstack/compute/v2/flavors/doc.go
- openstack/compute/v2/flavors/requests.go
- openstack/compute/v2/flavors/results.go
- openstack/compute/v2/flavors/testing/fixtures.go
- openstack/compute/v2/flavors/testing/requests_test.go
- openstack/compute/v2/flavors/urls.go
For #540
API reference:
* List
https://developer.openstack.org/api-ref/compute/#list-extra-specs-for-a-flavor
* Get
https://developer.openstack.org/api-ref/compute/#show-an-extra-spec-for-a-flavor
Nova implementation:
* List
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py#L50
* Get
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py#L98
Schema:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/schemas/flavors_extraspecs.py
https://github.com/openstack/nova/blob/stable/pike/nova/api/validation/parameter_types.py#L363-L371
> Flavor Extra Specs: List / Get

- acceptance/openstack/compute/v2/flavors_test.go
- openstack/compute/v2/flavors/doc.go
- openstack/compute/v2/flavors/requests.go
- openstack/compute/v2/flavors/results.go
- openstack/compute/v2/flavors/testing/fixtures.go
- openstack/compute/v2/flavors/testing/requests_test.go
- openstack/compute/v2/flavors/urls.go
For #540 
API reference:
https://developer.openstack.org/api-ref/compute/#create-extra-specs-for-a-flavor
Nova implementation:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py#L61
Schema:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/schemas/flavors_extraspecs.py#L24
https://github.com/openstack/nova/blob/stable/pike/nova/api/validation/parameter_types.py#L363-L371
> Flavor Extra Specs Create 

- acceptance/openstack/blockstorage/v3/volumetypes_test.go
- openstack/blockstorage/v3/volumetypes/doc.go
- openstack/blockstorage/v3/volumetypes/requests.go
- openstack/blockstorage/v3/volumetypes/results.go
- openstack/blockstorage/v3/volumetypes/testing/fixtures.go
- openstack/blockstorage/v3/volumetypes/testing/requests_test.go
- openstack/blockstorage/v3/volumetypes/urls.go
Add Update support for volume type in volume V3.
For #649 
Volume type update in [V3](https://developer.openstack.org/api-ref/block-storage/v3/#update-a-volume-type)
Volume type update [Code](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/types_manage.py#L101)
> Add UPDATE support in V3 volume types

- acceptance/openstack/blockstorage/v3/volumetypes_test.go
- openstack/blockstorage/v3/volumetypes/requests.go
- openstack/blockstorage/v3/volumetypes/testing/fixtures.go
- openstack/blockstorage/v3/volumetypes/testing/requests_test.go
This commit renames the VolumeType CreateOpts PublicAccess field
to IsPublic.
For #649 
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/types_manage.py#L63-L64
> BlockStorage v3: Rename VolumeType PublicAccess to IsPublic

- openstack/client.go
For #645 
This change uses a stripped `ProviderClient` and `AuthOptions` to make the re-auth request. The intent is to only try to re-authenticate once to avoid deadlock with the `ProviderClient.mutex`. The deadlock can occur if the first re-auth attempt fails; this is due to the recursive use of the `ProviderClient`, which this PR aims to fix.
> Only try to re-auth once

- acceptance/openstack/compute/v2/aggregates_test.go
- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/results.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #690 
Add support for the Nova host aggregates to list host aggregates.
API reference:
https://developer.openstack.org/api-ref/compute/#list-aggregates
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/aggregates.py#L44
> Add os-aggregates support

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
- openstack/networking/v2/extensions/subnetpools/doc.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/doc.go
- openstack/networking/v2/extensions/subnetpools/testing/fixtures.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
- openstack/networking/v2/extensions/subnetpools/urls.go
Add support to list Neutron subnetpools through a GET request on `/v2.0/subnetpools`
`openstack subnet pool list`
or
`neutron subnetpool-list`
For #672 
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L707
https://github.com/openstack/neutron/blob/stable/pike/neutron/ipam/subnet_alloc.py#L244
> Add Neutron subnetpool list support.

- openstack/objectstorage/v1/containers/results.go
- openstack/objectstorage/v1/containers/testing/fixtures.go
- openstack/objectstorage/v1/containers/testing/requests_test.go
The X-Storage-Policy header is missing from the
container's GetHeader struct.
For #696
> Add X-Storage-Policy to GetHeader struct

- openstack/networking/v2/extensions/subnetpools/doc.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/fixtures.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
- openstack/networking/v2/extensions/subnetpools/urls.go
Add support to show a Neutron subnetpool through a GET request on
/v2.0/subnetpools/{subnetpool_id}.
`openstack subnet pool show`
or
`neutron subnetpool-show`
For #672 
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L707
https://github.com/openstack/neutron/blob/stable/pike/neutron/ipam/subnet_alloc.py#L244
> Add Neutron subnetpool get support

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools.go
- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
- openstack/networking/v2/extensions/subnetpools/doc.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/fixtures.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
- openstack/networking/v2/extensions/subnetpools/urls.go
Add support to create a Neutron subnetpool through a POST request on
/v2.0/subnetpools.
`openstack subnet pool create`
or
`neutron subnetpool-create`
For #672 
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L1117
> Add Neutron subnetpool creation support

- acceptance/openstack/compute/v2/flavors_test.go
- openstack/compute/v2/flavors/doc.go
- openstack/compute/v2/flavors/requests.go
- openstack/compute/v2/flavors/results.go
- openstack/compute/v2/flavors/testing/fixtures.go
- openstack/compute/v2/flavors/testing/requests_test.go
- openstack/compute/v2/flavors/urls.go
For #540
API reference:
https://developer.openstack.org/api-ref/compute/#delete-an-extra-spec-for-a-flavor
Nova implementation:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py#L111
There is a note in the above that the error _should_ be 204, rather than the 200 that is returned. The value in the API spec is also 200. Testing proved that the return code is 200 rather than 204.
> Flavor Extra Spec Delete

- openstack/orchestration/v1/stacks/environment_test.go
Fix "Content-Type" in orchestration environment unit tests ("application/jason" -> "application/json").
Fix environments unit test "TestGetRRFileContents" by updating the "expectedParsed" to be a valid representation of a Heat's resource_registry definition.
Also update environment's fileMaps to sucessfully apply the "fixFileRefs" method.
For #707 
A valid representation of a resource registry can be viewed for example in the [docs/heat/environment.html](https://docs.openstack.org/heat/pike/template_guide/environment.html#override-a-resource-with-a-custom-resource)
> Fix Orchestration TestGetRRFileContents

- openstack/orchestration/v1/stacks/fixtures.go
- openstack/orchestration/v1/stacks/template_test.go
Fix "Content-Type" in orchestration templates unit tests ("application/jason" -> "application/json").
Set "default" field to be a string in "ValidJSONTemplate", "ValidYAMLTemplate", "InvalidTemplateNoVersion", "InvalidEnvironment", "ValidJSONTemplateParsed" orchestration templates test fixtures.
That automatically fixes the TestTemplateParsing unit test.
For #707 
Default field in the flavor is a reference to the default flavor that will be used in the template. It can't be an `int` as it represents the name (or maybe ID) of the flavor.
There are some examples in the official [heat-templates](https://github.com/openstack/heat-templates) repo: [autohealing_group.yaml#L17](https://github.com/openstack/heat-templates/blob/master/hot/autohealing/autohealing_group.yaml#L17).
> Fix Orchestration TestTemplateParsing

- acceptance/openstack/compute/v2/flavors_test.go
- openstack/compute/v2/flavors/doc.go
- openstack/compute/v2/flavors/requests.go
- openstack/compute/v2/flavors/results.go
- openstack/compute/v2/flavors/testing/fixtures.go
- openstack/compute/v2/flavors/testing/requests_test.go
- openstack/compute/v2/flavors/urls.go
For #540
API reference:
https://developer.openstack.org/api-ref/compute/#update-an-extra-spec-for-a-flavor
Nova implementation:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py#L79
Schema:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/schemas/flavors_extraspecs.py#L24
https://github.com/openstack/nova/blob/stable/pike/nova/api/validation/parameter_types.py#L363-L371
The API will return an error if more than one key-value pair is passed and also if the key differs from the key parameter on the URL. As the API accepts more than one key-value pair and then properly returns an error, per the discussion on #689, the …
> Flavor Extra Spec Update

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
- openstack/networking/v2/extensions/subnetpools/doc.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/fixtures.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
- openstack/networking/v2/extensions/subnetpools/urls.go
Add support to update a Neutron subnetpool through a PUT request on /v2.0/subnetpools.
`openstack subnet pool set`
or
`neutron subnetpool-update`
For [#672](https://github.com/gophercloud/gophercloud/issues/672)
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L1146
> Add Neutron subnetpool update support

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools.go
- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
- openstack/networking/v2/extensions/subnetpools/doc.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
- openstack/networking/v2/extensions/subnetpools/urls.go
Add a Delete request, unit test and acceptance tests with acceptance
reusable "DeleteSubnetPool" function.
`openstack subnet pool delete`
or
`neutron subnetpool-delete`
For #672 
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L1211
> Add Neutron subnetpool delete support

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
It would be better if we will test the `GET` request inside the `TestSubnetPoolsCRUD` acceptance test.
For #672 
Support for `Get` was implemented in PR [#701](https://github.com/gophercloud/gophercloud/pull/701) and for `Update` in [#706](https://github.com/gophercloud/gophercloud/pull/706).
> Add get request in subnetpools acceptance tests

- acceptance/openstack/compute/v2/services_test.go
- openstack/compute/v2/extensions/services/doc.go
- openstack/compute/v2/extensions/services/requests.go
- openstack/compute/v2/extensions/services/results.go
- openstack/compute/v2/extensions/services/testing/fixtures.go
- openstack/compute/v2/extensions/services/testing/requests_test.go
- openstack/compute/v2/extensions/services/urls.go
For #715 
Add support for the running Compute service list.
API reference:
https://developer.openstack.org/api-ref/compute/#list-compute-services
https://github.com/openstack/nova/blob/stable/ocata/nova/api/openstack/compute/services.py#L200
> Compute service list support

- acceptance/openstack/compute/v2/hypervisors_test.go
- openstack/compute/v2/extensions/hypervisors/doc.go
- openstack/compute/v2/extensions/hypervisors/requests.go
- openstack/compute/v2/extensions/hypervisors/results.go
- openstack/compute/v2/extensions/hypervisors/testing/fixtures.go
- openstack/compute/v2/extensions/hypervisors/testing/requests_test.go
- openstack/compute/v2/extensions/hypervisors/urls.go
For #721
The same for Openstack CLI:
- `openstack hypervisor show <hypervisor-id>`
- `nova hypervisor-show hypervisor-show <hypervisor-id>` 
API doc:
- [https://developer.openstack.org/api-ref/compute/#show-hypervisor-details](https://developer.openstack.org/api-ref/compute/#show-hypervisor-details)
Source code:
- [https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/hypervisors.py#L302](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/hypervisors.py#L302)
> Compute v2: Get Hypervisor Details

- params.go
- testing/params_test.go
For #729 
@jrperritt I felt more comfortable adding the check for `"-"` after all of the other validation field checks were done. I wasn't sure if there are cases of something like this floating around:
```go
Username username `json:"-" required:"true"`
```
> Prevent Recursive BuildRequestBody

- acceptance/clients/clients.go
- acceptance/openstack/compute/v2/migrate_test.go
- openstack/compute/v2/extensions/migrate/doc.go
- openstack/compute/v2/extensions/migrate/requests.go
- openstack/compute/v2/extensions/migrate/testing/fixtures.go
- openstack/compute/v2/extensions/migrate/testing/requests_test.go
For #520 
The same for Openstack CLI:
- `openstack server migrate --live <hostname> <server-name-or-id>`
API doc:
- [https://developer.openstack.org/api-ref/compute/#live-migrate-server-os-migratelive-action](https://developer.openstack.org/api-ref/compute/#live-migrate-server-os-migratelive-action)
Source code:
- [https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/migrate_server.py#L77](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/migrate_server.py#L77)
> Compute v2: Add Live Migration Action

- acceptance/openstack/blockstorage/extensions/services_test.go
- openstack/blockstorage/extensions/services/doc.go
- openstack/blockstorage/extensions/services/requests.go
- openstack/blockstorage/extensions/services/results.go
- openstack/blockstorage/extensions/services/testing/fixtures.go
- openstack/blockstorage/extensions/services/testing/requests_test.go
- openstack/blockstorage/extensions/services/urls.go
For #732 
API reference:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#list-all-cinder-services
https://github.com/openstack/cinder/blob/stable/ocata/cinder/api/contrib/services.py#L46-L102
> Blockstorage service list support

- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/results.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc: 
- https://developer.openstack.org/api-ref/compute/#create-aggregate 
Source code:
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L56
> Compute v2: Create aggregate

- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/results.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc: 
- https://developer.openstack.org/api-ref/compute/#delete-aggregate
Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L124
> Compute v2: Delete aggregate

- acceptance/openstack/compute/v2/aggregates_test.go
- acceptance/openstack/compute/v2/compute.go
For #738 
Related to PRs:
- #739 
- #740 
- #746
> Acceptance test for create, get and delete aggregate

- acceptance/openstack/compute/v2/aggregates_test.go
- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/results.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc: 
- https://developer.openstack.org/api-ref/compute/#add-host
Source code:
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L141
> Compute v2: Add host to aggregate

- acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go
- openstack/networking/v2/extensions/layer3/floatingips/requests.go
- openstack/networking/v2/extensions/layer3/floatingips/testing/requests_test.go
> Networking v2: Create Floating IP with Subnet

- acceptance/openstack/compute/v2/aggregates_test.go
- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc: 
- https://developer.openstack.org/api-ref/compute/#remove-host
Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L164
> Compute v2: Remove host

- acceptance/openstack/compute/v2/aggregates_test.go
- openstack/compute/v2/extensions/aggregates/doc.go
- openstack/compute/v2/extensions/aggregates/requests.go
- openstack/compute/v2/extensions/aggregates/testing/fixtures.go
- openstack/compute/v2/extensions/aggregates/testing/requests_test.go
- openstack/compute/v2/extensions/aggregates/urls.go
For #738 
API doc:
- https://developer.openstack.org/api-ref/compute/#create-or-update-aggregate-metadata
Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L186
> Compute v2: Create Or Update Aggregate Metadata

- acceptance/clients/clients.go
- acceptance/openstack/container/experimental/capsules_test.go
- openstack/client.go
- openstack/container/experimental/capsules/doc.go
- openstack/container/experimental/capsules/requests.go
- openstack/container/experimental/capsules/results.go
- openstack/container/experimental/capsules/testing/doc.go
- openstack/container/experimental/capsules/testing/fixtures.go
- openstack/container/experimental/capsules/testing/requests_test.go
- openstack/container/experimental/capsules/urls.go
- results.go
For #700
[zun capsule API](https://github.com/openstack/zun/blob/master/zun/api/controllers/experimental/capsules.py)
> Add support for Zun experimental API "Capsule"Get

- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/results.go
- openstack/networking/v2/subnets/testing/fixtures.go
- openstack/networking/v2/subnets/testing/requests_test.go
Add ability to populate subnet's subnetpool_id field from GET requests.
Also add this field to GET and LIST unit tests.
For #763 
https://github.com/openstack/neutron/blob/stable/pike/neutron/objects/subnet.py#L179
> Add SubnetPoolID into the Subnet struct and GET requests

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/subnets_test.go
- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/testing/fixtures.go
- openstack/networking/v2/subnets/testing/requests_test.go
Add the "subnetpool_id" field to the subnet creation request with an acceptance test.
Also update the unit test.
For #763 
Here you can see a subnetpool_id in the subnet collection of a resource map:
https://github.com/openstack/neutron/blob/stable/pike/neutron/api/v2/attributes.py#L149
it's provided into this method:
https://github.com/openstack/neutron/blob/master/neutron/neutron_plugin_base_v2.py#L33
> Add the SubnetPoolID to the Subnet Create request

- acceptance/openstack/networking/v2/extensions/vpnaas/service_test.go
- acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go
- openstack/networking/v2/extensions/vpnaas/services/doc.go
- openstack/networking/v2/extensions/vpnaas/services/requests.go
- openstack/networking/v2/extensions/vpnaas/services/results.go
- openstack/networking/v2/extensions/vpnaas/services/testing/requests_test.go
- openstack/networking/v2/extensions/vpnaas/services/urls.go
For #723
* https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L473
* https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L459
API:
https://developer.openstack.org/api-ref/network/v2/#create-vpn-service
> Vpnaas: Create VPN service

- acceptance/openstack/networking/v2/extensions/vpnaas/service_test.go
- acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go
- openstack/networking/v2/extensions/vpnaas/services/doc.go
- openstack/networking/v2/extensions/vpnaas/services/requests.go
- openstack/networking/v2/extensions/vpnaas/services/results.go
- openstack/networking/v2/extensions/vpnaas/services/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L512
API:
https://developer.openstack.org/api-ref/network/v2/#remove-vpn-service
> Vpnaas: Delete service

- acceptance/openstack/networking/v2/extensions/rbacpolicies/rbacpolicies.go
- acceptance/openstack/networking/v2/extensions/rbacpolicies/rbacpolicies_test.go
- openstack/networking/v2/extensions/rbacpolicies/doc.go
- openstack/networking/v2/extensions/rbacpolicies/requests.go
- openstack/networking/v2/extensions/rbacpolicies/results.go
- openstack/networking/v2/extensions/rbacpolicies/testing/requests_test.go
- openstack/networking/v2/extensions/rbacpolicies/urls.go
For #731
Delete RBAC policy by ID.
API:
https://developer.openstack.org/api-ref/network/v2/#delete-rbac-policy
Schema:
https://github.com/openstack/neutron/blob/8f79a92e45c84819cfc4d1cda99c9320ae78bbaf/neutron/db/rbac_db_models.py
Delete:
https://github.com/openstack/neutron/blob/59e2c40f14157e0f2f64c340070cf46758d522e1/neutron/db/rbac_db_mixin.py#L85
> Network v2: RBAC-Delete

- acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go
- acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/requests.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/results.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/testing/requests_test.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/urls.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L396
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L377
API:
https://developer.openstack.org/api-ref/network/v2/#create-ipsec-policy
> Vpnaas: Create IPSec Policy

- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/extensions/subnetpools/testing/fixtures.go
- openstack/networking/v2/extensions/subnetpools/testing/requests_test.go
For #788 
The following fixes have been applied:
* Removal of Prefixes from ListOpts
* Changing ListOpts Shared to *bool
* Changing ListOpts IsDefault to *bool
* Changing the result CreatedAt to time.Time
* Changing the result UpdatedAt to time.Time
/cc @dklyle 
I've tested these fixes pretty extensively to make sure they're correct. 
I'm not a fan of including `ID` and `tenant_id` in `ListOpts`, but since they were already merged and since they _do_ work, I'm going to leave them.
If someone has time to do a review of this, it would help move the Terraform PRs along.
> Networking v2: Fix subnetpools

- acceptance/openstack/networking/v2/extensions/rbacpolicies/rbacpolicies_test.go
- openstack/networking/v2/extensions/rbacpolicies/doc.go
- openstack/networking/v2/extensions/rbacpolicies/requests.go
- openstack/networking/v2/extensions/rbacpolicies/results.go
- openstack/networking/v2/extensions/rbacpolicies/testing/fixtures.go
- openstack/networking/v2/extensions/rbacpolicies/testing/requests_test.go
- openstack/networking/v2/extensions/rbacpolicies/urls.go
For #731
Update RBAC policy by ID.
API:
https://developer.openstack.org/api-ref/network/v2/#update-rbac-policy
Schema:
https://github.com/openstack/neutron/blob/8f79a92e45c84819cfc4d1cda99c9320ae78bbaf/neutron/db/rbac_db_models.py
Update:
https://github.com/openstack/neutron/blob/59e2c40f14157e0f2f64c340070cf46758d522e1/neutron/db/rbac_db_mixin.py#L69
Code reference for update fields:
https://github.com/openstack/neutron/blob/master/neutron/extensions/rbac.py
> Network v2: RBAC-Update

- acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicy_test.go
- acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go
- acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/urls.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L312
API:
https://developer.openstack.org/api-ref/network/v2/#create-ike-policy
> Vpnaas: Create IKE policy

- acceptance/openstack/networking/v2/extensions/vpnaas/ikepolicy_test.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/requests.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/results.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L367
> Vpnaas: Show IKE policy details

- acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/requests.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/results.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L454
>  Vpnaas: List IPSec Policies

- openstack/compute/v2/extensions/keypairs/doc.go
Minor documentation fix.
For #800
> Corrects example to create a server with a key pair

- openstack/endpoint_location.go
- openstack/identity/v3/tokens/results.go
- openstack/identity/v3/tokens/testing/fixtures.go
- openstack/testing/endpoint_location_test.go
For #343 
I was looking at older issues and came across #343. After digging around in the Keystone code, I determined two things:
1. The catalog endpoints in a token contain _both_ region and region_id:
https://github.com/openstack/keystone/blob/master/keystone/catalog/backends/sql.py#L360
I double confirmed this by modifying the above line to read `regionnnn` and, sure enough, the token response contained the malformed name. Secondly, our test fixtures already had both `region` and `region_id`.
2. "region" is still properly handled as of the current Keystone master branch. #343 mentions that OVH has dropped the `region` parameter. If this is true, then:
a. Perhaps it was only temporary or else I think we would have heard from more users by now.
b. They are deviating from "vanilla" …
> Identity v3: Add support for RegionID in token catalog endpoints

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/networks_test.go
- acceptance/openstack/networking/v2/ports_test.go
- openstack/networking/v2/extensions/portsecurity/requests.go
- openstack/networking/v2/networks/testing/fixtures.go
- openstack/networking/v2/networks/testing/requests_test.go
- openstack/networking/v2/ports/testing/fixtures.go
- openstack/networking/v2/ports/testing/requests_test.go
For #298 
Continuing with catching up on old work.
This is a rather large PR since it handles Create for both networks and ports, but since they're identical in implementation, I added them both here. The bulk of the additions are tests, though.
One thing to confirm with @jrperritt is the name `PortCreateOptsExt` and `NetworkCreateOptsExt`. I waffled on using either that form or `CreatePortOptsExt` and `CreateNetworkOptsExt`. This is the first occurrence of an extension being able to support extending multiple `CreateOpts`, so the name is new.
/cc @dklyle
> Networking v2: Port Security Create

- openstack/networking/v2/extensions/fwaas/firewalls/requests.go
- openstack/networking/v2/extensions/fwaas/firewalls/results.go
- openstack/networking/v2/extensions/fwaas/policies/requests.go
- openstack/networking/v2/extensions/fwaas/policies/results.go
- openstack/networking/v2/extensions/fwaas/rules/requests.go
- openstack/networking/v2/extensions/fwaas/rules/results.go
- openstack/networking/v2/extensions/layer3/floatingips/requests.go
- openstack/networking/v2/extensions/layer3/floatingips/results.go
- openstack/networking/v2/extensions/layer3/routers/requests.go
- openstack/networking/v2/extensions/layer3/routers/results.go
- openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
- openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
- openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go
- openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
- openstack/networking/v2/extensions/rbacpolicies/requests.go
- openstack/networking/v2/extensions/security/groups/requests.go
- openstack/networking/v2/extensions/security/groups/results.go
- openstack/networking/v2/extensions/security/rules/requests.go
- openstack/networking/v2/extensions/security/rules/results.go
- openstack/networking/v2/networks/requests.go
- openstack/networking/v2/networks/results.go
- openstack/networking/v2/ports/requests.go
- openstack/networking/v2/ports/results.go
- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/results.go
For #790 
Per discussion in #790, this PR adds `ProjectID` support to the network resources which support it.
I've updated the inline documentation where applicable, notably rewording `TenantID` to be described as a "project". My intention was to imply that tenant and project are the same without having a paragraph in each resource explicitly laying that out.
This has been tested to the best of my ability. There's always a chance _something_ slipped by me.
/cc @dklyle 
_edit_: In #790 I mentioned that LBaaS does not send `project_id`. To amend that statement, LBaaS will gladly accept `ProjectID` in other calls. It just does not set it in the response.
> Networking v2: Support both TenantID and ProjectID where applicable

- acceptance/openstack/networking/v2/extensions/vpnaas/ipsecpolicy_test.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/requests.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/results.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L420
> Vpnaas: Update IPSec Policy

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/ports_test.go
- openstack/networking/v2/extensions/extradhcpopts/doc.go
- openstack/networking/v2/extensions/extradhcpopts/requests.go
- openstack/networking/v2/extensions/extradhcpopts/results.go
- openstack/networking/v2/ports/testing/fixtures.go
- openstack/networking/v2/ports/testing/requests_test.go
For #511 
This commit renames the `ExtraDHCPOpts` struct to `ExtraDHCPOpt`. It also makes some minor doc changes.
> Networking v2: Port Extra DHCP Options fixes

- acceptance/openstack/imageservice/v2/images_test.go
- acceptance/openstack/imageservice/v2/imageservice.go
- openstack/imageservice/v2/images/requests.go
- openstack/imageservice/v2/images/testing/fixtures.go
- openstack/imageservice/v2/images/testing/requests_test.go
- openstack/imageservice/v2/images/types.go
For #779 
The first commit is the most notable and deserves a good review. I don't mind changing the names of the new types or consts:
https://github.com/gophercloud/gophercloud/commit/b364a87bb579aa578e8ae95721546e3acaba191e
The second commit, changing `Tag` to `Tags` will be a breaking change for some. I thought about keeping `Tag` for backwards compatibility, but that felt awkward.
The third commit is pretty standard.
/cc @dklyle
> Image Service v2: Add Missing Fields to ListOpts

- acceptance/openstack/networking/v2/extensions/vpnaas/group_test.go
- openstack/networking/v2/extensions/vpnaas/endpointgroups/doc.go
- openstack/networking/v2/extensions/vpnaas/endpointgroups/requests.go
- openstack/networking/v2/extensions/vpnaas/endpointgroups/results.go
- openstack/networking/v2/extensions/vpnaas/endpointgroups/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L626
>  Vpnaas: List Endpoint groups

- acceptance/openstack/networking/v2/extensions/vpnaas/siteconnection_test.go
- openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/services/doc.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/doc.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/requests.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/results.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L263
I also added some documentation fixes into this PR, let me know if I should open a separate PR for this @jtopjian
> Vpnaas: Show IPSec site connection details

- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/secgroup_test.go
- openstack/compute/v2/extensions/secgroups/requests.go
- openstack/compute/v2/extensions/secgroups/testing/fixtures.go
For #206 
This commit modifies the `AddServer` and `RemoveServer` actions so a response body is not parsed.
I'll admit I haven't done an exhaustive review of the code, but from what I can tell, the lack of a return statement here:
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/security_groups.py#L441-L456
Is probably good enough.
Note how other functions are returning some object, such as here:
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/security_groups.py#L340
Also note that the explicit EOF check in the acceptance test was added by me (which I'm removing in this PR). This is because I _swear_ I was seeing intermittent EOFs and not steady ones. But it's been so long since I was working on that, I can't be sure if my testing was …
> Compute v2: Fix EOF errors in compute secgroups

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/ports_test.go
- openstack/networking/v2/extensions/extradhcpopts/doc.go
- openstack/networking/v2/extensions/extradhcpopts/requests.go
- openstack/networking/v2/extensions/extradhcpopts/results.go
- openstack/networking/v2/ports/testing/fixtures.go
- openstack/networking/v2/ports/testing/requests_test.go
This commit fixes updating of extra DHCP options on a Networking
port. The fix entails creating two new structs: one for create
and one for update. The update struct is able to take a string
pointer as a dhcp value so a nil/null string can be provided.
This nil/null value will cause a dhcp option to be remove if
requested.
For #816 
/cc @dklyle
> Networking v2: Fix Extra DHCP Options Updates

- acceptance/clients/clients.go
- acceptance/clients/conditions.go
- acceptance/openstack/blockstorage/v2/blockstorage.go
- acceptance/openstack/compute/v2/aggregates_test.go
- acceptance/openstack/compute/v2/attachinterfaces_test.go
- acceptance/openstack/compute/v2/availabilityzones_test.go
- acceptance/openstack/compute/v2/bootfromvolume_test.go
- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/defsecrules_test.go
- acceptance/openstack/compute/v2/extension_test.go
- acceptance/openstack/compute/v2/flavors_test.go
- acceptance/openstack/compute/v2/floatingip_test.go
- acceptance/openstack/compute/v2/hypervisors_test.go
- acceptance/openstack/compute/v2/images_test.go
- acceptance/openstack/compute/v2/keypairs_test.go
- acceptance/openstack/compute/v2/limits_test.go
- acceptance/openstack/compute/v2/migrate_test.go
- acceptance/openstack/compute/v2/network_test.go
- acceptance/openstack/compute/v2/quotaset_test.go
- acceptance/openstack/compute/v2/secgroup_test.go
- acceptance/openstack/compute/v2/servergroup_test.go
- acceptance/openstack/compute/v2/servers_test.go
- acceptance/openstack/compute/v2/services_test.go
- acceptance/openstack/compute/v2/tenantnetworks_test.go
- acceptance/openstack/compute/v2/usage_test.go
- acceptance/openstack/compute/v2/volumeattach_test.go
> Acc Compute v2: Updating the Compute v2 Acceptance Tests

- provider_client.go
If a user wants to do their own HTTP requests and reauthenticate in case of 401 responses, they can already use `ProviderClient.ReauthFunc()`, but that function is not thread-safe. This commit provides a safer alternative by pulling the relevant piece of code out of `ProviderClient.Request()`.
For #742.
> add ProviderClient.Reauthenticate() function

- openstack/networking/v2/extensions/vpnaas/ikepolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/ipsecpolicies/doc.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/doc.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/requests.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/results.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/testing/requests_test.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L202
https://github.com/openstack/neutron-vpnaas/blob/871d933bf1645aed2185f92a80cfe6ba642618eb/neutron_vpnaas/extensions/vpnaas.py#L236
I also put some doc fixes for IKE and IPSec policies in there, hope that's ok.
This PR does not contain acceptance tests as discussed in #784
> Vpnaas: Update Site connection

- acceptance/openstack/networking/v2/extensions/vpnaas/vpnaas.go
- openstack/networking/v2/extensions/vpnaas/services/doc.go
- openstack/networking/v2/extensions/vpnaas/services/requests.go
- openstack/networking/v2/extensions/vpnaas/services/results.go
- openstack/networking/v2/extensions/vpnaas/services/testing/requests_test.go
- openstack/networking/v2/extensions/vpnaas/siteconnections/requests.go
For #723 
https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L502
API:
https://developer.openstack.org/api-ref/network/v2/#update-vpn-service
> Vpnaas: Update Service

- acceptance/clients/clients.go
- acceptance/openstack/clustering/v1/pkg.go
- acceptance/openstack/clustering/v1/policytypes_test.go
- openstack/client.go
- openstack/clustering/v1/policytypes/doc.go
- openstack/clustering/v1/policytypes/requests.go
- openstack/clustering/v1/policytypes/results.go
- openstack/clustering/v1/policytypes/testing/doc.go
- openstack/clustering/v1/policytypes/testing/fixtures.go
- openstack/clustering/v1/policytypes/testing/requests_test.go
- openstack/clustering/v1/policytypes/urls.go
For #823 
API doc:
https://developer.openstack.org/api-ref/clustering/#list-policy-types
API code:
https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/policy_types.py#L30
> Clustering policytype list

- acceptance/openstack/identity/v3/endpoint_test.go
- acceptance/openstack/identity/v3/projects_test.go
- acceptance/openstack/identity/v3/service_test.go
- acceptance/openstack/identity/v3/token_test.go
> Fix Identity V3 Acceptance Tests

- acceptance/openstack/identity/v3/users_test.go
- openstack/identity/v3/users/doc.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/results.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
For #862
API reference:
[Identity API v3 - Change password for user](https://developer.openstack.org/api-ref/identity/v3/index.html#change-password-for-user)
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/routers.py#L31
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/core.py#L1381
https://github.com/openstack/python-keystoneclient/blob/40642d597deecce4dd81428449353bbd0c2ad5be/keystoneclient/v3/users.py#L203
> Identity V3: Change user password

- acceptance/openstack/identity/v3/users_test.go
- openstack/identity/v3/users/doc.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/results.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
For #866
API reference:
[Identity API v3 - Add user to group](https://developer.openstack.org/api-ref/identity/v3/#add-user-to-group)
Python source code:
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/routers.py#L49
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/core.py#L1248
https://github.com/openstack/python-keystoneclient/blob/40642d597deecce4dd81428449353bbd0c2ad5be/keystoneclient/v3/users.py#L228
> Identity V3: add user to group

- acceptance/openstack/loadbalancer/v2/loadbalancer.go
- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/doc.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
- openstack/loadbalancer/v2/l7policies/urls.go
For #832
L7policy functionality in Octavia is backward compatible with
Neutron-LBaaS.
Octavia L7 policy create API:
https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-an-l7-policy
> LBaaS v2 l7 policy support [Part 1]: create l7policy

- acceptance/openstack/loadbalancer/v2/l7policies_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
For #832
Octavia L7 policy list API:
https://developer.openstack.org/api-ref/load-balancer/v2/index.html#list-l7-policies
> LBaaS v2 l7 policy support - part 2: list l7policy

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
- openstack/loadbalancer/v2/l7policies/urls.go
For #832
Neutron-LBaaS l7 policy get API implementation:
https://github.com/openstack/neutron-lbaas/blob/8e8a6c47c7d38fa7b61850ff9ea2cf130718ded3/neutron_lbaas/services/loadbalancer/plugin.py#L971
Octavia l7 policy get API implementation:
https://github.com/openstack/octavia/blob/54a4cf00cf304b108013ca4487c138c13f30983d/octavia/api/v2/controllers/l7policy.py#L47
> LBaaS v2 l7 policy support - part 3: get l7policy

- testing/provider_client_test.go
For #855 
This [I think] turned out not to be a race condition, but instead just a product of adding the `Reauthenticate` method. The previous token wasn't getting set, causing a non-deterministic number of goroutines to think they needed to reauthenticate.
> simulate previous token existing in reauth test

- acceptance/openstack/loadbalancer/v2/loadbalancer.go
- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
- openstack/loadbalancer/v2/l7policies/urls.go
For #832
Neutron-LBaaS l7 policy delete API implementation:
https://github.com/openstack/neutron-lbaas/blob/8e8a6c47c7d38fa7b61850ff9ea2cf130718ded3/neutron_lbaas/services/loadbalancer/plugin.py#L954
Octavia l7 policy delete API implementation:
https://github.com/openstack/octavia/blob/54a4cf00cf304b108013ca4487c138c13f30983d/octavia/api/v2/controllers/l7policy.py#L253
> LBaaS v2 l7 policy support - part 4: delete l7policy

- auth_options.go
- openstack/identity/v3/tokens/requests.go
This commit adds a Scope field to the base AuthOptions struct. This
allows an explicit scope to be passed to AuthOptions which will
enable detailed scoping configurations.
For #252
> Add Scope to AuthOptions

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
For #832
Neutron-LBaaS l7 policy update API implementation:
https://github.com/openstack/neutron-lbaas/blob/ac720b2a49720fb99e4189f93d5a83cfb295ccb3/neutron_lbaas/services/loadbalancer/plugin.py#L931
Octavia l7 policy update API implementation:
https://github.com/openstack/octavia/blob/06bf5c58d5845f684fcaf933605ed112586eefc3/octavia/api/v2/controllers/l7policy.py#L204
> LBaaS v2 l7 policy support - part 5: update l7policy

- acceptance/openstack/compute/v2/compute.go
There might be occasions when the API will return an actual
DELETED status. This is a short window of time, but it
could happen.
The `TestSecGroupsAddGroupToServer` is still flapping from time to time. This is the only reason I can think of for it to still be failing.
For #818
> Acc Tests: Fix Server Delete

- acceptance/clients/clients.go
- acceptance/openstack/clustering/v1/webhooktrigger_test.go
- openstack/clustering/v1/webhooks/doc.go
- openstack/clustering/v1/webhooks/requests.go
- openstack/clustering/v1/webhooks/results.go
- openstack/clustering/v1/webhooks/testing/doc.go
- openstack/clustering/v1/webhooks/testing/requests_test.go
- openstack/clustering/v1/webhooks/urls.go
Add webhooks trigger for senlin clustering
[[webhooks:trigger]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/webhooks.py#L28)
> Senlin: Webhook Trigger

- acceptance/openstack/blockstorage/v3/quotaset_test.go
- openstack/blockstorage/extensions/quotasets/requests.go
- openstack/blockstorage/extensions/quotasets/urls.go
For #234
Pending #877 
\## API:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#quota-sets-extension-os-quota-sets
\## Schema:
I'm not showing the actual DB schema here because it makes more sense from a
request parameter validation standpoint to show the chain of calls and data
structures involved in validating a request.
Here is an example of [PUT/update request parameter validation](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L218-L219).
So the data structure that ultimately specifies the correct parameter names is [cinder.quotas.QUOTAS](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1234) which is a module constant initialized with [cinder.quotas.VolumeTypeQuotaEngine](https://github.com/openstack/cinder/blob/master …
> Blockstorage v3 quota-set support - part 2, Get Defaults

- acceptance/openstack/loadbalancer/v2/l7policies_test.go
- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
For #832
Octavia l7 rule list API implementation:
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/controllers/l7rule.py#L59
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/types/l7rule.py#L26
> Octavia l7 rule support - part 2: list

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
- openstack/loadbalancer/v2/l7policies/urls.go
For #832
Octavia l7 rule Get API implementation:
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/controllers/l7rule.py#L45
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/types/l7rule.py#L26
> Octavia l7 rule support - part 3: get

- acceptance/openstack/blockstorage/v3/quotaset_test.go
- openstack/blockstorage/extensions/quotasets/doc.go
- openstack/blockstorage/extensions/quotasets/requests.go
- openstack/blockstorage/extensions/quotasets/results.go
- openstack/blockstorage/extensions/quotasets/testing/fixtures.go
- openstack/blockstorage/extensions/quotasets/testing/requests_test.go
- openstack/blockstorage/extensions/quotasets/urls.go
For #234
Pending #878
\## API:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#quota-sets-extension-os-quota-sets
\## Schema:
I'm not showing the actual DB schema here because it makes more sense from a
request parameter validation standpoint to show the chain of calls and data
structures involved in validating a request.
Here is an example of [PUT/update request parameter validation](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L218-L219).
So the data structure that ultimately specifies the correct parameter names is [cinder.quotas.QUOTAS](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1234) which is a module constant initialized with [cinder.quotas.VolumeTypeQuotaEngine](https://github.com/openstack/cinder/blob/master/ …
> Blockstorage v3 quota-set support - part 3, Get Details

- acceptance/openstack/loadbalancer/v2/loadbalancer.go
- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
For #832
Octavia l7 rule Delete API implementation:
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/controllers/l7rule.py#L228
> Octavia l7 rule support - part 4: delete

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/l7policies/doc.go
- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/results.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
For #832
Octavia l7 rule PUT API implementation:
- https://github.com/openstack/octavia/blob/69a45c254be854dbdbff946dbe2564711cdecec3/octavia/api/v2/controllers/l7rule.py#L189
> Octavia l7 rule support - part 5(final): update

- openstack/loadbalancer/v2/pools/requests.go
For #937
Octavia does not support to filter pools by listener_id.
Pool database model definiation in Octavia:
https://github.com/openstack/octavia/blob/be505cdfba0543dc6d9722f5c8779e34de84fe57/octavia/db/models.py#L260
> Remove 'listener_id' from Pool ListOpts

- acceptance/openstack/identity/v3/users_test.go
- openstack/identity/v3/users/doc.go
- openstack/identity/v3/users/requests.go
- openstack/identity/v3/users/results.go
- openstack/identity/v3/users/testing/fixtures.go
- openstack/identity/v3/users/testing/requests_test.go
- openstack/identity/v3/users/urls.go
For #886
API reference:
[Identity API v3 - Check whether user belongs to group](https://developer.openstack.org/api-ref/identity/v3/#check-whether-user-belongs-to-group)
Python source code:
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/routers.py#L49
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/core.py#L1361
https://github.com/openstack/python-keystoneclient/blob/40642d597deecce4dd81428449353bbd0c2ad5be/keystoneclient/v3/users.py#L247
> Identity V3: Check Whether User Belongs to Group

- openstack/networking/v2/subnets/requests.go
For #931 
https://github.com/openstack/neutron-lib/blob/3ee0386c314b409c3f5969fdf0b463efa6cca660/neutron_lib/api/definitions/subnet.py#L58-L63
> Networking v2: CIDR is not required for subnets

- openstack/objectstorage/v1/swauth/testing/requests_test.go
- params.go
- testing/params_test.go
This commit fixes how the required tag is set for query and header
parameters. Instead of using
x:"name,required"
as before, it now uses
x:"name" required:"true"
For #910
> Fix required tag for queries and headers

- acceptance/openstack/blockstorage/v3/quotaset_test.go
- openstack/blockstorage/extensions/quotasets/doc.go
- openstack/blockstorage/extensions/quotasets/requests.go
- openstack/blockstorage/extensions/quotasets/results.go
- openstack/blockstorage/extensions/quotasets/testing/fixtures.go
- openstack/blockstorage/extensions/quotasets/testing/requests_test.go
- openstack/blockstorage/extensions/quotasets/urls.go
For #234
Pending #879
\## API:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#quota-sets-extension-os-quota-sets
\## Schema:
I'm not showing the actual DB schema here because it makes more sense from a
request parameter validation standpoint to show the chain of calls and data
structures involved in validating a request.
Here is an example of [PUT/update request parameter validation](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L218-L219).
So the data structure that ultimately specifies the correct parameter names is [cinder.quotas.QUOTAS](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1234) which is a module constant initialized with [cinder.quotas.VolumeTypeQuotaEngine](https://github.com/openstack/cinder/blob/master/ …
> Blockstorage v3 quota-set support - part 4, Update

- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/subnets_test.go
- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/testing/fixtures.go
- openstack/networking/v2/subnets/testing/requests_test.go
For #931 
Of course I should learn that there are no easy fixes :)
The only notable change here is:
https://github.com/gophercloud/gophercloud/compare/master...jtopjian:networkingv2-subnet-cidr-omitempty?expand=1#diff-204ba5cafb491fe49ec624dbd245dce3
The rest of the changes are supporting tests.
> Networking v2: omitempty when CIDR not specified

- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
- openstack/loadbalancer/v2/loadbalancers/requests.go
- openstack/loadbalancer/v2/loadbalancers/results.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/monitors/results.go
- openstack/loadbalancer/v2/monitors/testing/fixtures.go
- openstack/loadbalancer/v2/monitors/testing/requests_test.go
- openstack/loadbalancer/v2/pools/requests.go
- openstack/loadbalancer/v2/pools/results.go
- openstack/loadbalancer/v2/pools/testing/fixtures.go
- openstack/loadbalancer/v2/pools/testing/requests_test.go
For #963
According to Octavia API document
https://developer.openstack.org/api-ref/load-balancer/v2/index.html
'tenant_id' is no longer supported.
> Use 'project_id' for octavia resources

- acceptance/openstack/clustering/v1/policies_test.go
- openstack/clustering/v1/policies/requests.go
[[policies:create]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/policies.py#L57)
> Senlin: Policy Create. Returns headers for senlin's policy create

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/profiles/doc.go
- openstack/clustering/v1/profiles/requests.go
- openstack/clustering/v1/profiles/results.go
- openstack/clustering/v1/profiles/testing/doc.go
- openstack/clustering/v1/profiles/testing/requests_test.go
- openstack/clustering/v1/profiles/urls.go
[[profiles:create]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L59)
> Senlin: Profiles Create

- acceptance/openstack/clustering/v1/policies_test.go
- openstack/clustering/v1/policies/doc.go
- openstack/clustering/v1/policies/requests.go
- openstack/clustering/v1/policies/results.go
- openstack/clustering/v1/policies/testing/fixtures.go
- openstack/clustering/v1/policies/testing/requests_test.go
- openstack/clustering/v1/policies/urls.go
[[policies:update]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/policies.py#L74)
> Clustering Policy Update Implementation

- acceptance/openstack/identity/v3/policies_test.go
- openstack/identity/v3/policies/doc.go
- openstack/identity/v3/policies/requests.go
- openstack/identity/v3/policies/results.go
- openstack/identity/v3/policies/testing/doc.go
- openstack/identity/v3/policies/testing/fixtures.go
- openstack/identity/v3/policies/testing/requests_test.go
- openstack/identity/v3/policies/urls.go
For #972 
API reference:
[Identity API v3 - List Policies](https://developer.openstack.org/api-ref/identity/v3/#list-policies)
Python source code:
https://github.com/openstack/keystone/blob/master/keystone/policy/routers.py#L21
https://github.com/openstack/keystone/blob/master/keystone/policy/controllers.py#L51
https://github.com/openstack/keystone/blob/master/keystone/policy/core.py#L57
https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/v3/policies.py#L82
Acceptance testing will be added after other policy APIs are supported.
> Identity V3: List Policies

- .zuul.yaml
- .zuul/playbooks/gophercloud-acceptance-test/run.yaml
- .zuul/playbooks/gophercloud-unittest/run.yaml
Add the jobs definition to .zuul.yaml, and the ansible playbooks.
For #974
> Move CI job definition to gophercloud repo

- acceptance/openstack/sharedfilesystems/v2/shares.go
- acceptance/openstack/sharedfilesystems/v2/shares_test.go
- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #985
This PR implements `ListAccessRights`. According to https://developer.openstack.org/api-ref/shared-file-system/#list-access-rules , it seems `access-list` doesn't support pagination and that's why I didn't use it in the implementation, hope it's ok.
> openstack shares: add ListAccessRights

- .zuul/playbooks/gophercloud-acceptance-test/run.yaml
The previous PR #976 overwritten the container tests job
theopenlab/openlab-zuul-jobs#190, add it to avoid regression.
Closed #974
> Run container tests in gophercloud

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/profiles/doc.go
- openstack/clustering/v1/profiles/requests.go
- openstack/clustering/v1/profiles/results.go
- openstack/clustering/v1/profiles/testing/requests_test.go
- openstack/clustering/v1/profiles/urls.go
[[profiles:get]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L75)
> Senlin: Profiles Get

- openstack/client.go
- openstack/utils/base_endpoint.go
- openstack/utils/testing/base_endpoint_test.go
This commit ensures IdentityV3 clients have the right endpoint
upon creation. This handles both versionless endpoints and
v2.0 endpoints being returned when doing an endpoint search.
For #947
> Ensure IdentityV3 clients have the right endpoint

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/results.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:get]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L81)
> Senlin: Clusters Get

- errors.go
This change expose the error message of BadRequest error from openstack
API, this is helpful to find out the reason of request failure.
For #243
> Expose the real error message of BadRequest error

- acceptance/openstack/networking/v2/networks_test.go
- openstack/networking/v2/extensions/external/doc.go
- openstack/networking/v2/extensions/external/requests.go
- openstack/networking/v2/extensions/external/testing/fixtures.go
- openstack/networking/v2/extensions/external/testing/requests_test.go
This commit adds the ability to list external networks. It does this by
way of creating an extention to the networks package's ListOpts struct.
For #1009
> Networking v2: Add ability to list external networks

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/results.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:update]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L90)
> Senlin: Clusters Update

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/results.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:delete]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L315)
> Senlin: Clusters Delete

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/profiles/doc.go
- openstack/clustering/v1/profiles/requests.go
- openstack/clustering/v1/profiles/results.go
- openstack/clustering/v1/profiles/testing/requests_test.go
- openstack/clustering/v1/profiles/urls.go
[[profiles:update]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L83)
> Senlin: Profiles Update

- acceptance/openstack/clustering/v1/autoscaling_test.go
- openstack/clustering/v1/profiles/doc.go
- openstack/clustering/v1/profiles/requests.go
- openstack/clustering/v1/profiles/results.go
- openstack/clustering/v1/profiles/testing/requests_test.go
- openstack/clustering/v1/profiles/urls.go
[[profiles:delete]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L99)
> Senlin: Profiles Delete

- openstack/objectstorage/v1/accounts/results.go
- openstack/objectstorage/v1/accounts/testing/fixtures.go
- openstack/objectstorage/v1/accounts/testing/requests_test.go
For #312
https://github.com/openstack/swift/blob/stable/newton/swift/common/middleware/account_quotas.py
The only part that might be controversial is the usage of `-1` to encode "no quota". I'm being consistent with other OpenStack services' quota handling here. Swift is a special snowflake because it does not report JSONs, but stuffs everything in headers. If you don't like `quota == -1`, I can also change the type of `GetHeader.Quota` to `*int64`, so that `nil` would indicate absence of a quota.
> ObjectStorage v1: recognize X-Account-Meta-Quota-Bytes header in accounts.GetHeader

- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/results.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
For #319 
* [openstack compute api doc on `os-getConsoleOutput`](https://developer.openstack.org/api-ref/compute/?expanded=show-console-output-os-getconsoleoutput-action-detail#show-console-output-os-getconsoleoutput-action)
* [novaclient/v2/servers.py `get_console_output`](https://github.com/openstack/python-novaclient/blob/master/novaclient/v2/servers.py#L1680-L1693)
> get the raw console output from the server instance

- .zuul.yaml
- .zuul/playbooks/gophercloud-acceptance-test/run.yaml
- .zuul/playbooks/gophercloud-unittest/run.yaml
This change expose the OS_BRANCH environment variable for running acceptance tests, that allow specific tests can be skipped according to specific OpenStack branch. The `openlab-zuul-jobs` have made some refactors in https://github.com/theopenlab/openlab-zuul-jobs/pull/237, this PR is based on that change.
For https://github.com/gophercloud/gophercloud/pull/1013#issuecomment-395633308
> Expose OS_BRANCH var based on refactors on openlab-zuul-jobs

- openstack/blockstorage/extensions/schedulerstats/results.go
The MaxOverSubscriptionRatio type should be string because max_over_subscription_ratio returned by cinder is a string, not float.
Fix:  #1046
> Fix the issue of unmarshal string into Go struct field MaxOverSubscriptionRatio 

- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/monitors/results.go
- openstack/loadbalancer/v2/pools/results.go
Add missing ProvisioningStatus fields to each model in /v2/loadbalancer
For #1066 
* listener https://github.com/openstack/neutron-lbaas/blob/stable/ocata/neutron_lbaas/services/loadbalancer/data_models.py#L676
* member https://github.com/openstack/neutron-lbaas/blob/stable/ocata/neutron_lbaas/services/loadbalancer/data_models.py#L497
* pool https://github.com/openstack/neutron-lbaas/blob/stable/ocata/neutron_lbaas/services/loadbalancer/data_models.py#L412
* health monitor https://github.com/openstack/neutron-lbaas/blob/stable/ocata/neutron_lbaas/services/loadbalancer/data_models.py#L354
> Add ProvisioningStatus fields to /v2/loadbalancer

- pagination/pager.go
For #1054
This is the quickest way I found to fix the issue. Other ways I found generate a bigger rewriting.
The goal is to change the "testPage" as a "firstPage". Once it has been already fetched, there is no need to fetch it again.
It avoids N+1 calls on each usage of AllPages()
> AllPages() - Do not fetch twice the first page

- acceptance/openstack/sharedfilesystems/v2/shares.go
- acceptance/openstack/sharedfilesystems/v2/shares_test.go
- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #1076
- revoke access request https://github.com/openstack/manila/blob/master/api-ref/source/samples/share-actions-revoke-access-request.json
- removing an access rule from DB https://github.com/openstack/manila/blob/master/manila/share/access.py#L224
> Add revoke access to Manila

- openstack/clustering/v1/receivers/results.go
- openstack/clustering/v1/receivers/testing/fixtures.go
For #[1079 [Senlin: Receiver result should use ClusterID instead of Cluster]](https://github.com/gophercloud/gophercloud/issues/1079)
[[receivers]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/receivers.py#L35)
> Changed from Cluster to ClusterID

- script/acceptancetest
Reverts #1012 
For #818 
@hongbin I'm seeing occasional Octavia/LBaaS failures so I'm going to revert the merge of #1012 
```
2018-07-03 02:52:03.283510 | ubuntu-xenial | === RUN   TestLoadbalancersCRUD
2018-07-03 02:57:16.357985 | ubuntu-xenial | --- FAIL: TestLoadbalancersCRUD (312.86s)
2018-07-03 02:57:16.369474 | ubuntu-xenial | 	networking.go:25: Attempting to create network: TESTACC-x3Qg134f
2018-07-03 02:57:16.378072 | ubuntu-xenial | 	networking.go:32: Successfully created network.
2018-07-03 02:57:16.378183 | ubuntu-xenial | 	networking.go:185: Attempting to create subnet: TESTACC-Zl3jexiL
2018-07-03 02:57:16.378243 | ubuntu-xenial | 	networking.go:192: Successfully created subnet.
2018-07-03 02:57:16.378364 | ubuntu-xenial | 	loadbalancer.go:55: Attempting to create loadbalancer …
```
> Acc Tests: Disabling Octavia

- acceptance/openstack/clustering/v1/profiletypes_test.go
- openstack/clustering/v1/profiletypes/doc.go
- openstack/clustering/v1/profiletypes/requests.go
- openstack/clustering/v1/profiletypes/results.go
- openstack/clustering/v1/profiletypes/testing/doc.go
- openstack/clustering/v1/profiletypes/testing/fixtures.go
- openstack/clustering/v1/profiletypes/testing/requests_test.go
- openstack/clustering/v1/profiletypes/urls.go
[[profiletypes:get/list]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profile_types.py#L42)
> Senlin: ProfileTypes Get/List

- openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
- openstack/networking/v2/extensions/lbaas_v2/loadbalancers/testing/fixtures.go
- openstack/networking/v2/extensions/lbaas_v2/monitors/results.go
- openstack/networking/v2/extensions/lbaas_v2/pools/results.go
Add missing ProvisioningStatus fields to each model in /networking/v2/extensions/lbaas_v2
For #1087
> Add ProvisioningStatus fields to lbaas_v2 models in the extensions pkg

- .zuul.yaml
Periodic check will be triggered at UTC-0 0:00 and 12:00 of everyday
automatically, unit and acceptance tests will be executed, results will
be shown in OpenLab CI dashboard http://status.openlabtesting.org/t/openlab/builds.html
For theopenlab/openlab#63
> Enable OpenLab periodic check

- acceptance/openstack/clustering/v1/profiletypes_test.go
- openstack/clustering/v1/profiletypes/doc.go
- openstack/clustering/v1/profiletypes/requests.go
- openstack/clustering/v1/profiletypes/results.go
- openstack/clustering/v1/profiletypes/testing/fixtures.go
- openstack/clustering/v1/profiletypes/testing/requests_test.go
- openstack/clustering/v1/profiletypes/urls.go
[[profiletypes:ops]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profile_types.py#L57)
> Senlin: ProfileTypes Ops

- openstack/container/v1/capsules/results.go
- openstack/container/v1/capsules/testing/fixtures.go
The field 'command' of container resource is changed from string
to list [1]. This change should not break API consumer if they
pin a specific API version. However, Gophercloud doesn't support
API microversion yet, so the CI is complaining. This patch attempts
to fix it.
[1] https://review.openstack.org/#/c/575709/
> Convert type of 'command' from string to list

- acceptance/openstack/sharedfilesystems/v2/shares.go
- acceptance/openstack/sharedfilesystems/v2/shares_test.go
- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #1094
- example response: https://github.com/openstack/manila/blob/master/api-ref/source/samples/shares-list-detailed-response.json
- `get_all` function: https://github.com/openstack/manila/blob/master/manila/share/api.py#L1469
> Manila: added ListDetail for detailed Share listing 

- acceptance/openstack/container/v1/capsules_test.go
- openstack/container/v1/capsules/testing/fixtures.go
Zun has moved 'start_policy' to 'spec' [1]. This is the corresponding
change in gophercloud.
[1] https://review.openstack.org/#/c/571398/
> zun: move 'restart_policy' under 'spec'

- acceptance/openstack/container/v1/capsules.go
- acceptance/openstack/container/v1/capsules_test.go
- openstack/container/v1/capsules/requests.go
- openstack/container/v1/capsules/results.go
- openstack/container/v1/capsules/testing/fixtures.go
- openstack/container/v1/capsules/testing/requests_test.go
In the Zun acceptance test, add a step to wait for the capsule
to become 'Running' after it is created.
Fixes: #1098
> Zun: assert capsule become 'Running' after create

- openstack/container/v1/capsules/results.go
- openstack/container/v1/capsules/testing/fixtures.go
* Remove the following fields from Capsule: ID
* Remove the following fields from Container: ContainerID, WebsocketUrl,
WebsocketToken, CapsuleID, Meta, ID.
All those fields are for internal usage and should not be exposed via API.
There is a plan (https://review.openstack.org/#/c/575610/) to remove those
fields from the server side. This is the corresponding change in Gophercloud.
Fixed: #1107
> Zun: remove internal fields from Capsule/Container

- openstack/compute/v2/extensions/attachinterfaces/requests.go
- openstack/compute/v2/extensions/attachinterfaces/results.go
> Compute v2: cannot pass SubnetID when attaching an interface

- openstack/orchestration/v1/stacks/doc.go
- openstack/orchestration/v1/stacks/errors.go
- openstack/orchestration/v1/stacks/requests.go
- openstack/orchestration/v1/stacks/testing/fixtures.go
- openstack/orchestration/v1/stacks/testing/requests_test.go
- provider_client.go
For #[[1101](https://github.com/gophercloud/gophercloud/issues/1101)]
Related Openstack code:
https://github.com/openstack/heat/blob/master/heat/api/openstack/v1/stacks.py#L494
https://github.com/openstack/heat/blob/master/heat/api/openstack/v1/__init__.py#L218
Some notes on the implementation:
Both PUT and PATCH update verbs are acceptable, but the PATCH verb allows template parameter updates without needing to specify the template to the API call, where as PUT does require the template.  PATCH does accept a template, but does not delete the environment overlay as PUT does.  See `openstack/orchestration/v1/stacks/doc.go` for more information on PUT vs PATCH functionality.
I ran this implementation by my colleagues and gophercloud contributors @problemv, @JackKuei  and @dkt26111 and we …
> Implements heat/orchestration stack update PATCH verb.

- openstack/blockstorage/v2/volumes/requests.go
- openstack/blockstorage/v2/volumes/results.go
For #1138. Tested against Cinder Mitaka.
https://github.com/openstack/cinder/blob/32e14499e735376e27e723f77f3cf3d81456eb6b/cinder/api/v2/views/volumes.py#L164-L165
https://developer.openstack.org/api-ref/block-storage/v2/index.html#list-volumes-with-details
> fix pagination for Cinder volumes

- acceptance/openstack/imageservice/v2/tasks_test.go
- openstack/imageservice/v2/tasks/doc.go
- openstack/imageservice/v2/tasks/requests.go
- openstack/imageservice/v2/tasks/results.go
- openstack/imageservice/v2/tasks/testing/doc.go
- openstack/imageservice/v2/tasks/testing/fixtures.go
- openstack/imageservice/v2/tasks/testing/requests_test.go
- openstack/imageservice/v2/tasks/urls.go
Implement Get method for the Imageservice tasks.
Add unit test with documentation example.
For #1143
API
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L121
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L309
DB
https://github.com/openstack/glance/blob/stable/queens/glance/db/sqlalchemy/api.py#L1559
> Imageservice V2: implement tasks Get method

- acceptance/openstack/compute/v2/servers_test.go
- docs/MIGRATING.md
- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/testing/requests_test.go
For #1151 
Documentation: [link](https://godoc.org/github.com/gophercloud/gophercloud/openstack/compute/v2/servers)
Example to Reboot a Server
``` go
rebootOpts := servers.RebootOpts{
Type: servers.SoftReboot,
}
serverID := "d9072956-1560-487c-97f2-18bdf65ec749"
err := servers.Reboot(computeClient, serverID, rebootOpts).ExtractErr()
if err != nil {
panic(err)
}
```
> Fix ToServerRebootMap() method

- acceptance/openstack/imageservice/v2/imageservice.go
- acceptance/openstack/imageservice/v2/tasks_test.go
- openstack/imageservice/v2/tasks/doc.go
- openstack/imageservice/v2/tasks/requests.go
- openstack/imageservice/v2/tasks/results.go
- openstack/imageservice/v2/tasks/testing/fixtures.go
- openstack/imageservice/v2/tasks/testing/requests_test.go
- openstack/imageservice/v2/tasks/urls.go
Implement Create method for the Imageservice tasks.
Add unit and acceptance tests with documentation.
For #1143 
API
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L69
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L216
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L304
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/tasks.py#L430
DB
https://github.com/openstack/glance/blob/stable/queens/glance/db/sqlalchemy/api.py#L1397
> Imageservice V2: implement tasks Create method

- openstack/compute/v2/flavors/requests.go
Add SortKey and SortDir fields for the compute/v2/flavors package.
For #1155 
Parameters `sort_key` and `sort_dir` are parsed in:
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/flavors.py#L86
Then they're passed into:
https://github.com/openstack/nova/blob/stable/queens/nova/objects/flavor.py#L647
And finally they're passed into the `sqlalchemy` methods:
https://github.com/openstack/nova/blob/stable/queens/nova/objects/flavor.py#L625
> Compute V2: SortDir and SortKey for flavors

- acceptance/openstack/networking/v2/extensions/networkipavailabilities/networkipavailabilities_test.go
- acceptance/openstack/networking/v2/extensions/networkipavailabilities/pkg.go
- openstack/networking/v2/extensions/networkipavailabilities/doc.go
- openstack/networking/v2/extensions/networkipavailabilities/requests.go
- openstack/networking/v2/extensions/networkipavailabilities/results.go
- openstack/networking/v2/extensions/networkipavailabilities/testing/doc.go
- openstack/networking/v2/extensions/networkipavailabilities/testing/fixtures.go
- openstack/networking/v2/extensions/networkipavailabilities/testing/requests_test.go
- openstack/networking/v2/extensions/networkipavailabilities/urls.go
Add Get method in the Networking service extensions "networkipavailabilities" package.
Add unit test with documentation.
For #1144
API definition:
https://github.com/openstack/neutron-lib/blob/stable/queens/neutron_lib/api/definitions/network_ip_availability.py
DB structs populations (network and subnet availability):
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/network_ip_availability_db.py#L153
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/network_ip_availability_db.py#L170
> Networking V2: Implement IP availabilities Get

- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/rescueunrescue_test.go
- openstack/compute/v2/extensions/rescueunrescue/doc.go
- openstack/compute/v2/extensions/rescueunrescue/requests.go
- openstack/compute/v2/extensions/rescueunrescue/results.go
- openstack/compute/v2/extensions/rescueunrescue/testing/doc.go
- openstack/compute/v2/extensions/rescueunrescue/testing/fixtures.go
- openstack/compute/v2/extensions/rescueunrescue/testing/requests_test.go
- openstack/compute/v2/extensions/rescueunrescue/urls.go
- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/results.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
Add Unrescue request to the "rescueunrescue" package.
Update TestServerRescueUnrescue acceptance test to also run Unrescue call.
Provide documentation and unit test.
For #1164
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/rescue.py#L85
>  Compute V2: add Unrescue action

- acceptance/openstack/clustering/v1/clustering.go
- openstack/clustering/v1/policies/results.go
- openstack/clustering/v1/policies/testing/fixtures.go
- openstack/clustering/v1/policies/testing/requests_test.go
For #[1171 [Senlin Bug: Policies Delete Should Use ExtractErr Instead Of Extract]](https://github.com/gophercloud/gophercloud/issues/1171)
[[policies::delete]](https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/policies.py#L89)
> Senlin Bug: Policies Delete Should Use ExtractErr Instead Of Extract

- acceptance/openstack/sharedfilesystems/v2/shares.go
- acceptance/openstack/sharedfilesystems/v2/shares_test.go
- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #1174 
Extend:
* example request: https://github.com/openstack/manila/blob/master/api-ref/source/samples/share-actions-extend-request.json
* API v2 `extend`: https://github.com/openstack/manila/blob/master/manila/api/v2/shares.py#L385
* `extend` implementation: https://github.com/openstack/manila/blob/master/manila/share/api.py#L1765
Shrink:
* example request: https://github.com/openstack/manila/blob/master/api-ref/source/samples/share-actions-shrink-request.json
* API v2 `shrink`: https://github.com/openstack/manila/blob/master/manila/api/v2/shares.py#L397
* `shrink` implementation: https://github.com/openstack/manila/blob/master/manila/share/api.py#L1823
/cc @jtopjian 
Ready for review
> Manila: add extend and shrink share functionality

- acceptance/openstack/containerinfra/v1/clustertemplates_test.go
- openstack/containerinfra/v1/clustertemplates/requests.go
- openstack/containerinfra/v1/clustertemplates/results.go
- openstack/containerinfra/v1/clustertemplates/testing/fixtures.go
- openstack/containerinfra/v1/clustertemplates/testing/requests_test.go
- openstack/containerinfra/v1/clustertemplates/urls.go
[[clustertemplates:get]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster_template.py#L336)
> Magnum: Manage Cluster Templates Get

- openstack/containerinfra/v1/clustertemplates/results.go
- openstack/containerinfra/v1/clustertemplates/testing/fixtures.go
OpenStack Magnum Cluster template response uses int type instead of string.
This commit fixes ClusterTemplate field type and unit tests.
For #1185 
https://github.com/openstack/magnum/blob/stable/rocky/magnum/api/controllers/v1/cluster_template.py#L82
> Magnum: fix Cluster templates APIServerPort type

- acceptance/openstack/imageservice/v2/images_test.go
- openstack/imageservice/v2/images/requests.go
- openstack/imageservice/v2/images/testing/fixtures.go
- openstack/imageservice/v2/images/testing/requests_test.go
This commit adds support to update image properties. Technically it can
update any image field with a string value, so this duplicates the
functionality of some existing Update calls. However, there's no other
way to implement this since the OpenStack Image Service treats all
properties as first-class fields.
For #1187
> Image Service v2: Support Updating Properties

- acceptance/openstack/identity/v3/roles_test.go
> Acc Tests: Skip role filtering when testing on master

- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/loadbalancers/urls.go
Change GetStatuses method to use "/status" instead alias "/statuses" when
get information from Octavia's API (see: https://review.openstack.org/#/c/560179/). Octavia's code with alias: https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/load_balancer.py#L547
> Fix loadbalancer's status request

- provider_client.go
- testing/provider_client_test.go
For #1182 
This patch avoids infinite loop on reauthentication process in case of component is always answering 401.
> Set reauth func to nil before making a new request

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/listeners/doc.go
- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
- openstack/loadbalancer/v2/listeners/urls.go
- openstack/loadbalancer/v2/loadbalancers/doc.go
- openstack/loadbalancer/v2/loadbalancers/requests.go
- openstack/loadbalancer/v2/loadbalancers/results.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
- openstack/loadbalancer/v2/loadbalancers/urls.go
In this PR:
1. Add GetStats method for a loadbalancer. See API guide: https://developer.openstack.org/api-ref/load-balancer/v2/#get-load-balancer-statistics. Data structure defined in https://github.com/openstack/octavia/blob/master/octavia/api/v2/types/load_balancer.py#L176
2. Add GetStats method for a listener. See API guide: https://developer.openstack.org/api-ref/load-balancer/v2/#get-listener-statistics. Data structure defined in https://github.com/openstack/octavia/blob/master/octavia/api/v2/types/listener.py#L230
For #1189
> Add support to getting statistics for loadbalancer and listener

- openstack/objectstorage/v1/objects/results.go
Recent versions of OpenStack (post Newton) now return a different
timestamp format for the Last-Modified response header. Update
the unmarshal logic to support either format.
For #1150 
??? - Not sure. Change based on observed values in https://github.com/gophercloud/gophercloud/issues/1150#issuecomment-415929528
> Update objectstorage object unmarshal

- openstack/loadbalancer/v2/loadbalancers/doc.go
- openstack/loadbalancer/v2/loadbalancers/requests.go
- openstack/loadbalancer/v2/loadbalancers/results.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
- openstack/loadbalancer/v2/loadbalancers/urls.go
For #1219
- Doc: 
https://developer.openstack.org/api-ref/load-balancer/v2/index.html#failover-a-load-balancer
- Source Code:
https://github.com/openstack/octavia/blob/96b9450e6032e65923df9216763b98a1bd2d74c5/octavia/api/v2/controllers/load_balancer.py#L633
> Octavia: Failover Loadbalancer

- openstack/networking/v2/extensions/security/rules/requests.go
- openstack/networking/v2/extensions/security/rules/results.go
- openstack/networking/v2/extensions/security/rules/testing/requests_test.go
For #1230 
A security group rule has standard attributes, i.e also a description field: 
see issue [comment](https://github.com/gophercloud/gophercloud/issues/1230#issuecomment-419957244) or below.
URLS for description field of SecurityGroupRule
https://github.com/openstack/neutron/blob/24c8f952b27e3bfaabad7f41edf283145cce7600/neutron/db/standard_attr.py#L56
https://github.com/openstack/neutron/blob/master/doc/source/contributor/internals/api_extensions.rst
https://github.com/openstack/neutron/blob/a388701ddfe628e9a5bd16a78422164799b11ef8/neutron/db/models/securitygroup.py#L68
https://developer.openstack.org/api-ref/network/v2/index.html#create-security-group-rule
> Networking v2: Security Group Rule Description

- auth_options.go
- errors.go
- openstack/auth_env.go
- openstack/identity/v3/tokens/requests.go
- openstack/identity/v3/tokens/testing/requests_test.go
For #1214 
- https://github.com/openstack/keystoneauth/blob/stable/rocky/keystoneauth1/identity/v3/application_credential.py#L48-L67
- https://github.com/openstack/keystone/blob/stable/rocky/keystone/conf/constants.py#L20
- https://github.com/openstack/python-keystoneclient/blob/stable/rocky/keystoneclient/v3/application_credentials.py#L42
> Add support to authenticate with application credential

- acceptance/openstack/blockstorage/v3/volumes_test.go
- openstack/blockstorage/v2/volumes/requests.go
- openstack/blockstorage/v3/volumes/requests.go
Add missing fields for multiattach support
For #1228 
https://github.com/openstack/cinder/blob/master/cinder/objects/volume.py#L111
> Block Storage: Add additional multiattach support (#1228)

- openstack/blockstorage/v2/volumes/requests.go
Add missing fields for multiattach support - to avoid support
issues, remove multiattach field from blockstorage v2.
"In Cinder the functionality is available from microversion '3.50' or higher."
For #1228
https://docs.openstack.org/cinder/latest/admin/blockstorage-volume-multiattach.html
> Block Storage v2: Remove multiattach field from volumes

- acceptance/openstack/networking/v2/extensions/trunks/trunks.go
- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/doc.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for Create and Delete operations.
The reason for having both create and delete together is because otherwise the acceptance tests can't remove any resources that are added to the trunk (ports, subnet and network).
For #1257
> Networking trunk extension support Create/Delete

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/attributestags/doc.go
- openstack/networking/v2/extensions/attributestags/requests.go
- openstack/networking/v2/extensions/attributestags/results.go
- openstack/networking/v2/extensions/attributestags/testing/fixtures.go
- openstack/networking/v2/extensions/attributestags/testing/requests_test.go
- openstack/networking/v2/extensions/attributestags/urls.go
This initial patch adds only the ability to Replace all tags on
a given resource, as described in the API docs:
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-extension
https://developer.openstack.org/api-ref/network/v2/#replace-all-tags
If this approach is acceptable subsequent PRs can add the other
operations supported by this API.
For #1260
Note this isn't …
> Neutron Standard Attributes Tag Extension - ReplaceAll support

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/attributestags/doc.go
- openstack/networking/v2/extensions/attributestags/requests.go
- openstack/networking/v2/extensions/attributestags/results.go
- openstack/networking/v2/extensions/attributestags/testing/fixtures.go
- openstack/networking/v2/extensions/attributestags/testing/requests_test.go
- openstack/networking/v2/extensions/attributestags/urls.go
This patch adds the ability to List all tags on a given resource.
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-extension
https://developer.openstack.org/api-ref/network/v2/#obtain-tag-list
Issue: #1260
Code from neutron related to this PR:
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L98
> Neutron attributestags List support

- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for the Get
operation.
For #1257 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L183-L185
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L393-L399
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/models.py#L26-L49
> Networking v2 Trunk support - Get

- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for the Update
operation.
For #1257 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L237-L259
https://github.com/openstack/neutron/blob/master/neutron/objects/base.py#L785-L800
https://github.com/openstack/neutron/blob/master/neutron/objects/trunk.py#L91-L101
> Networking v2 Trunk support - Update

- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for the
GetSubports operation.
For #1257 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L388-L391
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/models.py#L52-L69
> Networking v2 Trunk support - Get Subports

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/attributestags/doc.go
- openstack/networking/v2/extensions/attributestags/requests.go
- openstack/networking/v2/extensions/attributestags/results.go
- openstack/networking/v2/extensions/attributestags/testing/requests_test.go
- openstack/networking/v2/extensions/attributestags/urls.go
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-extension
https://developer.openstack.org/api-ref/network/v2/#remove-all-tags
Issue: #1260
Code from neutron related to this PR:
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L152
> Neutron attributestags DeleteAll support

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/attributestags/doc.go
- openstack/networking/v2/extensions/attributestags/requests.go
- openstack/networking/v2/extensions/attributestags/results.go
- openstack/networking/v2/extensions/attributestags/testing/requests_test.go
- openstack/networking/v2/extensions/attributestags/urls.go
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-
https://developer.openstack.org/api-ref/network/v2/#add-a-tag
Issue: #1260
Code from neutron related to this PR: https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L115
Note this PR depends on https://github.com/gophercloud/gophercloud/pull/1276
--
> Neutron std attr tags add

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/attributestags/doc.go
- openstack/networking/v2/extensions/attributestags/requests.go
- openstack/networking/v2/extensions/attributestags/results.go
- openstack/networking/v2/extensions/attributestags/testing/requests_test.go
- openstack/networking/v2/extensions/attributestags/urls.go
https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-
https://developer.openstack.org/api-ref/network/v2/#remove-a-tag
Issue: #1260
Code from neutron related to this PR: https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L140
> Neutron std attr tags delete

- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- params.go
builquery had a bug that made it overlook the required fields in slices
of structs. This patch addresses it and adds a unit test for trunk
creation.
For #1279
> Networking trunks - Verify subport missing fields

- acceptance/openstack/clustering/v1/profiles_test.go
- acceptance/openstack/clustering/v1/webhooktrigger_test.go
- openstack/clustering/v1/profiles/doc.go
- openstack/clustering/v1/profiles/requests.go
- openstack/clustering/v1/profiles/results.go
- openstack/clustering/v1/profiles/testing/fixtures.go
- openstack/clustering/v1/profiles/testing/requests_test.go
- openstack/clustering/v1/profiles/urls.go
- openstack/clustering/v1/webhooks/testing/requests_test.go
[[profiles:validate]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/profiles.py#L67)
> Senlin: Profiles Validate

- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/results.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for the
AddSubports operation.
For #1257 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L283-L333
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/models.py#L52-L69
> Networking v2 Trunk support - AddSubports

- acceptance/openstack/workflow/v2/workflow.go
- acceptance/openstack/workflow/v2/workflows_test.go
- openstack/workflow/v2/crontriggers/doc.go
- openstack/workflow/v2/crontriggers/requests.go
- openstack/workflow/v2/crontriggers/testing/requests_test.go
- openstack/workflow/v2/workflows/requests.go
- openstack/workflow/v2/workflows/testing/requests_test.go
For #1199
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L201-L252
Please notice that this is a breaking change with the current API, but impacted code was merged a couple of weeks ago (see #1205).
This allows to filter workflows according to filter accepted by Mistral API.
> Handle filters on list parameters

- acceptance/openstack/networking/v2/extensions/networkipavailabilities/networkipavailabilities_test.go
- openstack/networking/v2/extensions/networkipavailabilities/results.go
- openstack/networking/v2/extensions/networkipavailabilities/testing/fixtures.go
- openstack/networking/v2/extensions/networkipavailabilities/testing/requests_test.go
- script/acceptancetest
The networkipavailabilities extension requires an increase to the
upper limit for both Total IPs and Used IPs. This is to
accommodate a large amount of IPv6 addresses.
This commit changes the type of these fields from int to big.Int.
For #1242 
With this in place, the acceptance tests now passes:
```
=== RUN   TestNetworkIPAvailabilityList
--- PASS: TestNetworkIPAvailabilityList (0.13s)
tools.go:72: {
"network_id": "a8976812-bbaf-46f0-b534-d672e77b1cf8",
"network_name": "private",
"project_id": "29b363f3aca74d608757a51c23c36fad",
"tenant_id": "29b363f3aca74d608757a51c23c36fad",
"subnet_ip_availability": [
{
"subnet_id": "203ffe15-a1b5-424f-96d8-6dbb0e33d819",
"subnet_name": "private-subnet",
"cidr": "10.0.0.0/26",
"ip_version": 4,
"total_ips": 61,
"used_ips": 2
},
{
"subnet_id": …
```
> Network v2: Fix Upper Limit of IPs

- acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
- openstack/networking/v2/extensions/trunks/doc.go
- openstack/networking/v2/extensions/trunks/requests.go
- openstack/networking/v2/extensions/trunks/testing/fixtures.go
- openstack/networking/v2/extensions/trunks/testing/requests_test.go
- openstack/networking/v2/extensions/trunks/urls.go
This patch adds the Networking extension trunk support for the
RemoveSubports operation.
For #1257 
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/plugin.py#L336-L385
https://github.com/openstack/neutron/blob/master/neutron/services/trunk/models.py#L52-L69
> Networking v2 Trunk support - RemoveSubports

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/layer3/floatingips/results.go
- openstack/networking/v2/extensions/layer3/routers/results.go
- openstack/networking/v2/extensions/rbacpolicies/results.go
- openstack/networking/v2/extensions/security/groups/results.go
- openstack/networking/v2/extensions/subnetpools/results.go
- openstack/networking/v2/networks/results.go
- openstack/networking/v2/ports/results.go
- openstack/networking/v2/subnets/results.go
Since we added the ability to set resource tags via the attributestags
extensione, it is helpful to expose those tags as they are included
in the GET response for resources that support tagging ref:
https://docs.openstack.org/neutron/pike/contributor/internals/tag.html
Issue: #1285
Edit adding links to show the resources which have tag_support = True:
Router: https://github.com/openstack/neutron/blob/master/neutron/db/models/l3.py#L67
FloatingIP: https://github.com/openstack/neutron/blob/master/neutron/db/models/l3.py#L112
SecurityGroup: https://github.com/openstack/neutron/blob/master/neutron/db/models/securitygroup.py#L32
Port: https://github.com/openstack/neutron/blob/master/neutron/db/models_v2.py#L115
Subnet: https://github.com/openstack/neutron/blob/master/neutron/db/models_v2.py#L21 …
> Add Tags to resources that support std-attributes-tags

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
Discussion on #1286 highlighted some issues:
* The order of the DeepEquals is wrong, which means if the actual
result is an empty list no equivalence is tested
* The DeepEquals can't be used to test the result of DeleteAll, for the same reason
* On older OpenStack versions the tags aren't returned in a sorted order
Closes Issue: #1299
> Fix issues in attributestags acceptance test

- acceptance/openstack/networking/v2/extensions/attributestags_test.go
- openstack/networking/v2/extensions/layer3/floatingips/requests.go
- openstack/networking/v2/extensions/layer3/routers/requests.go
- openstack/networking/v2/extensions/rbacpolicies/requests.go
- openstack/networking/v2/extensions/security/groups/requests.go
- openstack/networking/v2/extensions/subnetpools/requests.go
- openstack/networking/v2/networks/requests.go
- openstack/networking/v2/ports/requests.go
- openstack/networking/v2/subnets/requests.go
For resources that support std-attribute-tags we can query by tag so
add the ability to do this, with an acceptance test showing the
interface working with Network resources.
Issue: #1289
These neutron code references show the resources which have tag_support = True:
Router: https://github.com/openstack/neutron/blob/master/neutron/db/models/l3.py#L67
FloatingIP: https://github.com/openstack/neutron/blob/master/neutron/db/models/l3.py#L112
SecurityGroup: https://github.com/openstack/neutron/blob/master/neutron/db/models/securitygroup.py#L32
Port: https://github.com/openstack/neutron/blob/master/neutron/db/models_v2.py#L115
Subnet: https://github.com/openstack/neutron/blob/master/neutron/db/models_v2.py#L210
SubnetPool: https://github.com/openstack/neutron/blob/master/neutron/db/models_v2.py …
> Enable list query by tag for Neutron resources

- acceptance/openstack/clustering/v1/clusters_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/testing/fixtures.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:addnodes]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L109)
> Senlin: Clusters AddNodes

- acceptance/openstack/blockstorage/extensions/volumetenants_test.go
- results.go
This commit fixes an unchecked type assertion when extracting results
into a slice pointer. The type assertion would previously fail when a
paged result was empty.
For #1269
> Core: Fix Unchecked Type Assertion

- acceptance/openstack/blockstorage/extensions/schedulerhints_test.go
- acceptance/openstack/blockstorage/extensions/volumeactions_test.go
- acceptance/openstack/blockstorage/noauth/blockstorage.go
- acceptance/openstack/blockstorage/v2/blockstorage.go
- acceptance/openstack/blockstorage/v2/volumes_test.go
- acceptance/openstack/blockstorage/v3/blockstorage.go
- acceptance/openstack/blockstorage/v3/volumes_test.go
- openstack/blockstorage/v2/volumes/requests.go
- openstack/blockstorage/v2/volumes/testing/requests_test.go
- openstack/blockstorage/v3/volumes/requests.go
- openstack/blockstorage/v3/volumes/testing/requests_test.go
For #1309
* https://github.com/openstack/cinder/blob/31a885c046a28f795cfc1e83ec5ceca4ef005301/cinder/api/v2/volumes.py#L71
* https://github.com/openstack/cinder/blob/3ef65dfaf3e9f8932c5bbe8cddb1a2a40855f625/cinder/volume/api.py#L379
* https://github.com/openstack/cinder/blob/3ef65dfaf3e9f8932c5bbe8cddb1a2a40855f625/cinder/volume/api.py#L479
* https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=delete-a-volume-detail#delete-a-volume
> Blockstorage v2, v3: Implement cascading volume deletion

- .zuul.yaml
- acceptance/openstack/compute/v2/quotaset_test.go
- acceptance/openstack/identity/v3/roles_test.go
- acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go
- acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
Input comment "recheck stable/rocky" in pull request comments, that
will trigger acceptance tests against OpenStack Rocky release. OpenLab
will report test result in followint comments automatically.
Related-Bug: theopenlab/openlab#82
> Support acceptance test against OpenStack Rocky release in OpenLab

- acceptance/openstack/clustering/v1/clustering.go
- acceptance/openstack/clustering/v1/clusters_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/testing/fixtures.go
- openstack/clustering/v1/clusters/testing/requests_test.go
[[clusters:removenodes]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/clusters.py#L115)
> Senlin: Clusters RemoveNodes

- provider_client.go
- testing/provider_client_test.go
This commit reverts PR #1192. The goal of #1192 was to set the reauth
function to nil when performing reauthentication in order to prevent an
infinite loop. However, this was not done in a concurrent-safe way.
Having reviewed the use-case in more detail, I feel that scenarios in
which this will happen are more site-specific rather than an issue with
Gophercloud and a custom reauth function should be used.
Included in this PR is a simple unit test which verifies that a custom
reauthentication function can be used for these scenarios. However, it's
important to not use this example in production. Rather, users should
use the example provided in the FAQ.
For #1244 
For #1324
> core: Revert setting reauth func to nil

- openstack/loadbalancer/v2/l7policies/requests.go
- openstack/loadbalancer/v2/l7policies/testing/fixtures.go
- openstack/loadbalancer/v2/l7policies/testing/requests_test.go
When the rule was initially created with `invert=true`, it is not possible to update it to `invert=false`, because json engine omits `false` value.
> lbaas: l7policies: don't omit invert: bool=false

- openstack/loadbalancer/v2/listeners/requests.go
- openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
Openstack v2 API supports `default_pool_id` update
https://developer.openstack.org/api-ref/load-balancer/v2/index.html?expanded=update-a-listener-detail#update-a-listener
> Add DefaultPoolID update support

- acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent.go
- acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent_test.go
- openstack/networking/v2/extensions/vlantransparent/doc.go
- openstack/networking/v2/extensions/vlantransparent/requests.go
- openstack/networking/v2/extensions/vlantransparent/results.go
- openstack/networking/v2/extensions/vlantransparent/testing/doc.go
- openstack/networking/v2/extensions/vlantransparent/testing/fixtures.go
- openstack/networking/v2/extensions/vlantransparent/testing/requests_test.go
Add a method to update an OpenStack Networking V2 Network with the
"vlan-transparent" attribute.
For #1304
[vlantransparent.py](https://github.com/openstack/neutron-lib/blob/stable/rocky/neutron_lib/api/definitions/vlantransparent.py)
> NetworkingV2: add vlan-transparent Update method

- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go
- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
- openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
- openstack/networking/v2/extensions/lbaas_v2/listeners/testing/fixtures.go
- openstack/networking/v2/extensions/lbaas_v2/listeners/testing/requests_test.go
Resolves #1355
Missed this field.
> LBaaS_v2: Listener's default_pool_id should not be omitted during update

- acceptance/openstack/clustering/v1/nodes_test.go
- openstack/clustering/v1/nodes/doc.go
- openstack/clustering/v1/nodes/requests.go
- openstack/clustering/v1/nodes/results.go
- openstack/clustering/v1/nodes/testing/fixtures.go
- openstack/clustering/v1/nodes/testing/requests_test.go
- openstack/clustering/v1/nodes/urls.go
[[nodes:op api]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/nodes.py#L197)
[[nodes:op engine]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/engine/node.py#L394)
[[nova op names]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/profiles/os/nova/server.py#L241)
[[heat op …
> Senlin: Nodes Op

- doc.go
For #1372 
Amend example code in doc.go
client := openstack.NewComputeV2(provider, opts) should be
client, err := openstack.NewComputeV2(provider, opts)
> Amend example code

- openstack/networking/v2/extensions/layer3/addressscopes/doc.go
- openstack/networking/v2/extensions/layer3/addressscopes/requests.go
- openstack/networking/v2/extensions/layer3/addressscopes/results.go
- openstack/networking/v2/extensions/layer3/addressscopes/testing/doc.go
- openstack/networking/v2/extensions/layer3/addressscopes/testing/fixtures.go
- openstack/networking/v2/extensions/layer3/addressscopes/testing/requests_test.go
- openstack/networking/v2/extensions/layer3/addressscopes/urls.go
Implement Create method for the "address-scopes" extension with tests and documentation example.
For #1375 
[API reference](https://developer.openstack.org/api-ref/network/v2/#address-scopes)
[Code reference(API)](https://github.com/openstack/neutron-lib/blob/stable/rocky/neutron_lib/api/definitions/address_scope.py)
[Code reference(DB)](https://github.com/openstack/neutron/blob/stable/rocky/neutron/db/address_scope_db.py#L71)
> NetworkingV2: add Address scopes Create method

- openstack/sharedfilesystems/v2/snapshots/requests.go
- openstack/sharedfilesystems/v2/snapshots/results.go
- openstack/sharedfilesystems/v2/snapshots/testing/fixtures.go
- openstack/sharedfilesystems/v2/snapshots/testing/request_test.go
- openstack/sharedfilesystems/v2/snapshots/urls.go
Part of the #1380 
* https://github.com/openstack/manila/blob/e96e46d0d826f4b654773d081094b05e79f33c09/manila/api/v1/share_snapshots.py#L88
* https://github.com/openstack/manila/blob/e96e46d0d826f4b654773d081094b05e79f33c09/manila/api/views/share_snapshots.py#L46
Acceptance tests don't make sense before create/delete methods are implemented.
@jtopjian not sure how exactly to name the package: `sharesnapshots` or `snapshots`
> Manila: add share snapshots support (list, get)

- acceptance/openstack/clustering/v1/nodes_test.go
- openstack/clustering/v1/nodes/doc.go
- openstack/clustering/v1/nodes/requests.go
- openstack/clustering/v1/nodes/testing/fixtures.go
- openstack/clustering/v1/nodes/testing/requests_test.go
- openstack/clustering/v1/nodes/urls.go
[[nodes:recover api]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/api/openstack/v1/nodes.py#L180)
[[nodes:recover engine]](https://github.com/openstack/senlin/blob/b30b2b8496b2b8af243ccd5292f38aec7a95664f/senlin/engine/node.py#L361)
[[recover const names]](https://github.com/openstack/senlin/blob/b30b2b8496b2b8af243ccd5292f38aec7a95664f/senlin/common/consts.py#L287) …
> Senlin: Node Recover

- acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools.go
- acceptance/openstack/networking/v2/networking.go
- acceptance/openstack/networking/v2/subnets_test.go
- openstack/networking/v2/subnets/requests.go
- openstack/networking/v2/subnets/testing/fixtures.go
- openstack/networking/v2/subnets/testing/requests_test.go
Add Prefixlen field into the Subnet Create call.
Provide unit and acceptance tests with additional helpers.
For #1373 
[API reference](https://developer.openstack.org/api-ref/network/v2/?expanded=create-subnet-detail,update-subnet-detail#create-subnet)
[Code reference(API)](https://github.com/openstack/neutron-lib/blob/stable/rocky/neutron_lib/api/definitions/subnet.py#L61)
[Code reference(IPAM)](https://github.com/openstack/neutron/blob/stable/rocky/neutron/ipam/requests.py#L289)
[Code reference(DB)](https://github.com/openstack/neutron/blob/stable/rocky/neutron/db/db_base_plugin_v2.py#L788)
> NetworkingV2: add prefixlen for Subnet Create

- acceptance/openstack/networking/v2/extensions/agents/agents_test.go
- acceptance/openstack/networking/v2/extensions/agents/doc.go
- openstack/networking/v2/extensions/agents/doc.go
- openstack/networking/v2/extensions/agents/requests.go
- openstack/networking/v2/extensions/agents/results.go
- openstack/networking/v2/extensions/agents/testing/doc.go
- openstack/networking/v2/extensions/agents/testing/fixtures.go
- openstack/networking/v2/extensions/agents/testing/requests_test.go
- openstack/networking/v2/extensions/agents/urls.go
Add Get method for the "networking/v2/extensions/agents" package.
Provide unit test and documentation.
Add TestAgentsRead for testing reading of real Networking V2 agents.
For #1389
[Code reference(API)](https://github.com/openstack/neutron-lib/blob/stable/rocky/neutron_lib/api/definitions/agent.py)
[Code reference(DB)](https://github.com/openstack/neutron/blob/stable/rocky/neutron/db/agents_db.py#L341)
> Networking V2: add Agent Get request

- acceptance/openstack/clustering/v1/nodes_test.go
- openstack/clustering/v1/nodes/doc.go
- openstack/clustering/v1/nodes/requests.go
- openstack/clustering/v1/nodes/testing/fixtures.go
- openstack/clustering/v1/nodes/testing/requests_test.go
[[nodes:check api]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/api/openstack/v1/nodes.py#L165)
[[nodes:check engine]](https://github.com/openstack/senlin/blob/b30b2b8496b2b8af243ccd5292f38aec7a95664f/senlin/engine/node.py#L319)
> Senlin: Node Check

- openstack/loadbalancer/v2/loadbalancers/results.go
For #1404
- API: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html?expanded=#show-load-balancer-details>
- source code: <https://github.com/openstack/octavia/blob/d0c499dbd6bd276ca3c8a4d3827734fed27f0643/octavia/api/v2/types/load_balancer.py#L58>
> [Octavia] Support tags for getting load balancer

- openstack/loadbalancer/v2/loadbalancers/doc.go
- openstack/loadbalancer/v2/loadbalancers/requests.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
For #1404
- API doc: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html?expanded=update-a-load-balancer-detail#update-a-load-balancer>
- Source code: <https://github.com/openstack/octavia/blob/3745e1f55d69fc370d405b0bac4f784d019409a4/octavia/api/v2/types/load_balancer.py#L143>
> Octavia: Update load balancer tags

- acceptance/openstack/clustering/v1/clusters_test.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/results.go
- openstack/clustering/v1/clusters/testing/fixtures.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:collect api]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/api/openstack/v1/clusters.py#L275)
[[clusters:collect engine]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/senlin/engine/service.py#L1364)
> Senlin: Cluster Collect Attributes Across A Cluster

- acceptance/openstack/clustering/v1/clusters_test.go
- openstack/clustering/v1/clusters/doc.go
- openstack/clustering/v1/clusters/requests.go
- openstack/clustering/v1/clusters/testing/fixtures.go
- openstack/clustering/v1/clusters/testing/requests_test.go
- openstack/clustering/v1/clusters/urls.go
[[clusters:operation api]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/api/openstack/v1/clusters.py#L290)
[[clusters:operation engine]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/senlin/engine/service.py#L1490)
[[profiles:op names]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/senlin/profiles/os/nova/server.py#L241)
> Senlin: Cluster Operations

- acceptance/openstack/loadbalancer/v2/loadbalancer.go
- acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
- openstack/loadbalancer/v2/loadbalancers/requests.go
For #1404
- API doc: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html#filtering-and-column-selection>
- Code: <https://github.com/openstack/octavia/blob/6f96401e9c9c0fbac879dc174f129cfcaafb5f09/octavia/api/common/pagination.py#L183>
> Octavia: filter load balancers by tags

- acceptance/openstack/compute/v2/servers_test.go
Swapped the arguments order, since the original
code was looking suspicious.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
For #818
> fix strings.Contains args order

- acceptance/openstack/clustering/v1/events_test.go
- openstack/clustering/v1/events/doc.go
- openstack/clustering/v1/events/requests.go
- openstack/clustering/v1/events/results.go
- openstack/clustering/v1/events/testing/doc.go
- openstack/clustering/v1/events/testing/fixtures.go
- openstack/clustering/v1/events/testing/requests_test.go
- openstack/clustering/v1/events/urls.go
[[events:get api]](https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/events.py#L63)
[[events:list api]](https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/events.py#L33)
[[events:get engine]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/senlin/engine/service.py#L2626)
[[events:list engine]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/sen …
> Senlin: Events Get/List

- auth_result.go
- openstack/client.go
- openstack/identity/v2/tokens/results.go
- openstack/identity/v3/tokens/results.go
- provider_client.go
For #1141.
I have not tested this yet since I first want to have some more eyes on the API design. I ended up doing it in a way that differs from all my previous proposals in #1141.
Pros:
- This does not require any new public API in the `openstack` package, and only small changes to packages `openstack/identity/{v2,v3}/tokens`.
- Using `ProviderClient.GetAuthResult` feels natural. There is no excessive casting between different result types.
Cons:
- Keeping the `ProviderClient.authResult` field private requires some additional API surface between `v2auth/v3auth` and ProviderClient, in the form of `CopyTokenFrom`.
- `IsAnAuthResult` is slightly awkward.
The new `SetTokenAndAuthResult` method is strictly required to ensure that the mutex gets used. (It could have been `SetAuthResult` …
> add gophercloud.AuthResult

- auth_result.go
Followup to #1226: When using the new AuthResult API in application code, I noticed a mistake in the example code snippet. The `AuthResult` interface is implemented by `CreateResult`, not by `*CreateResult`.
> papercut: fix example code for type AuthResult

- acceptance/openstack/imageservice/v2/images_test.go
- openstack/imageservice/v2/images/requests.go
- openstack/imageservice/v2/images/testing/fixtures.go
- openstack/imageservice/v2/images/testing/requests_test.go
This commit adds support to update image min disk.
For #1437
> Image Service v2: Add Updating MinDisk

- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/remoteconsoles_test.go
- openstack/compute/v2/extensions/remoteconsoles/doc.go
- openstack/compute/v2/extensions/remoteconsoles/requests.go
- openstack/compute/v2/extensions/remoteconsoles/results.go
- openstack/compute/v2/extensions/remoteconsoles/testing/doc.go
- openstack/compute/v2/extensions/remoteconsoles/testing/fixtures.go
- openstack/compute/v2/extensions/remoteconsoles/testing/requests_test.go
- openstack/compute/v2/extensions/remoteconsoles/urls.go
Add the new "remoteconsoles" Compute extension package with needed
structures and Create method.
Add unit and acceptance test with documentation.
For #1158
API create request handler:
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/remote_consoles.py#L160
API definitions:
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/schemas/remote_consoles.py#L91
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/schemas/remote_consoles.py#L115
Allowed protocols and types:
https://github.com/openstack/nova/blob/stable/queens/nova/api/openstack/compute/schemas/remote_consoles.py#L123 …
> Compute V2: implement remoteconsoles Create method

- acceptance/openstack/containerinfra/v1/clusters_test.go
- openstack/containerinfra/v1/clusters/doc.go
- openstack/containerinfra/v1/clusters/requests.go
- openstack/containerinfra/v1/clusters/testing/fixtures.go
- openstack/containerinfra/v1/clusters/testing/requests_test.go
- openstack/containerinfra/v1/clusters/urls.go
Add ListDetail method with documentation and tests.
This method uses different URL than List method.
For #1442
https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L347
> ContainerInfraV1: add ListDetail method

- acceptance/clients/clients.go
- acceptance/openstack/baremetal/v1/baremetal.go
- acceptance/openstack/baremetal/v1/nodes_test.go
- openstack/baremetal/v1/nodes/doc.go
- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/results.go
- openstack/baremetal/v1/nodes/testing/doc.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- openstack/baremetal/v1/nodes/urls.go
- openstack/client.go
- service_client.go
For #1429 
First PR to add support for Ironic to gophercloud.  This contains the basics for node support. Node management API will be done separately, along with the other API objects as listed in #1429.
General:
- [API Controller](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py)
Create:
- [API Reference](https://developer.openstack.org/api-ref/baremetal/?expanded=create-node-detail#create-node)
- [`Node` class definition code](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L885-L1080)
- [Create API endpoint code](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L1958-L2023)
List:
- [API …
> Baremetal v1 API: Nodes

- .travis.yml
- go.mod
- go.sum
This is in preparation to switching [Terraform OpenStack provider](https://github.com/terraform-providers/terraform-provider-openstack) to go modules (see https://github.com/terraform-providers/terraform-provider-openstack/issues/656).
Enabling go modules throughout the dependency tree of the provider will make the switch and future upgrades easier.
I ran all tests via `go test ./...` in Go `1.11.5`, but I don't have access to any OpenStack environment to test this thoroughly and some tests naturally failed because of that.
This PR is a result of the following commands (in a clean Go `1.11.5` environment):
```sh
go mod init
go get ./...
go mod tidy
```
> Enable go modules

- acceptance/clients/clients.go
- acceptance/openstack/baremetal/noauth/doc.go
- acceptance/openstack/baremetal/noauth/nodes_test.go
- openstack/baremetal/noauth/doc.go
- openstack/baremetal/noauth/requests.go
- openstack/baremetal/noauth/testing/requests_test.go
For #1429
- If Ironic is configured for noauth, then authorization is just entirely bypassed:
https://github.com/openstack/ironic/blob/master/ironic/common/policy.py#L513-L527
> Baremetal API: noauth support

- openstack/baremetal/v1/nodes/doc.go
- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/results.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- openstack/baremetal/v1/nodes/urls.go
For #1429  
This covers node management for boot devices, validation, and injecting non-masking interrupts. 
- [API Ref](https://developer.openstack.org/api-ref/baremetal/?expanded=validate-node-detail)
- Validation
- [API Controller](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L1951-L1976)
- [Conductor logic](https://github.com/openstack/ironic/blob/master/ironic/conductor/manager.py#L2166-L2221)
- Boot Devices
- [Get API](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L187-L205)
- [Put API](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L207-L233)
- [Get …
> Baremetal V1 API: Node management

- acceptance/openstack/containerinfra/v1/clusters_test.go
- openstack/containerinfra/v1/clusters/requests.go
- openstack/containerinfra/v1/clustertemplates/requests.go
This commit changes the Value field of UpdateOpts to be an interface{}
instead of a string. This is to send type-specific values to the API
service.
For #1458 
/cc @tghartland would you be able to test this and confirm it's working?
> Container Infra v1: Use interface for update value

- acceptance/openstack/identity/v3/reauth_test.go
- provider_client.go
This commit fixes a deadlock issue during reauthentication. It removes a
possibly unnecessary locking of the client's locking mechanism so the
reauthentication process can safely lock the client.
For #1459 
/cc @majewsky This resolves the problem for me. I think this fix also makes sense. I could be wrong :)
> Core: Fix deadlock with reauthentication

- acceptance/openstack/clustering/v1/clustering.go
- acceptance/openstack/clustering/v1/receivers_test.go
- acceptance/openstack/clustering/v1/webhooktrigger_test.go
- openstack/clustering/v1/receivers/doc.go
- openstack/clustering/v1/receivers/requests.go
- openstack/clustering/v1/receivers/results.go
- openstack/clustering/v1/receivers/testing/fixtures.go
- openstack/clustering/v1/receivers/testing/requests_test.go
- openstack/clustering/v1/receivers/urls.go
[[receivers:notify api]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/api/openstack/v1/receivers.py#L100)
[[service:receiver_notify engine]](https://github.com/openstack/senlin/blob/0700a8bf29217b8a24fff0912cd89c0c64fe416b/senlin/engine/service.py#L2496)
[[receivers:notify engine]](https://github.com/openstack/senlin/blob/8ba9f3f7b71c3895aa5e460b363b61d415fb99b0/senlin/engine/receivers/message.py#L249)
> Senlin: Receivers Notify

- openstack/compute/v2/servers/requests.go
- openstack/compute/v2/servers/testing/fixtures.go
- openstack/compute/v2/servers/testing/requests_test.go
For #1306 
API:
https://developer.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail#create-server
Schema:
https://github.com/openstack/nova/blob/5852bae034533129608dd24b58e33733e093e957/nova/api/openstack/compute/schemas/servers.py#L195
> Compute V2: Create multiple servers

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/results.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- openstack/baremetal/v1/nodes/urls.go
For #1429
This implements the code to adjust provisioning state.
- [API reference](https://developer.openstack.org/api-ref/baremetal/?expanded=change-node-provision-state-detail)
- [API endpoint for set provision state](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L605-L710)
- [Target states for provision state](https://github.com/openstack/ironic/blob/master/ironic/common/states.py#L42-L53)
- [Config drive storage from base64](https://github.com/openstack/ironic/blob/master/ironic/conductor/manager.py#L3545-L3583)
> Baremetal API v1: Node provision state

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
For #1429
Corrects the wrong annotation on json fields for required, and includes a test to verify.
> Baremetal API V1: Handle required opts correctly

- acceptance/openstack/baremetal/noauth/ports_test.go
- acceptance/openstack/baremetal/v1/baremetal.go
- acceptance/openstack/baremetal/v1/ports_test.go
- openstack/baremetal/v1/ports/doc.go
- openstack/baremetal/v1/ports/requests.go
- openstack/baremetal/v1/ports/results.go
- openstack/baremetal/v1/ports/testing/doc.go
- openstack/baremetal/v1/ports/testing/fixtures.go
- openstack/baremetal/v1/ports/testing/requests_test.go
- openstack/baremetal/v1/ports/urls.go
For #1429 
This PR covers the Ports API calls  according to the [Baremetal API reference](https://developer.openstack.org/api-ref/baremetal/?expanded=#ports-ports)
- List Ports (GET)
- Create Port (POST)
- List Detailed Ports (GET)
- Show Port Details (GET)
- Update a Port (PATCH)
- Delete Port (DELETE)
You can view the source code [here](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/port.py)
> Baremetal V1 API Ports

- openstack/compute/v2/flavors/requests.go
For: #1488 
The `ExtractFlavor` function doesn't exist.
> Correct reference to wrong function name

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/results.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- openstack/baremetal/v1/nodes/urls.go
For #1429
API's for changing a Node's power state.
- [API Ref](https://developer.openstack.org/api-ref/baremetal/?expanded=change-node-power-state-detail)
- [API endpoint](https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L500-L551)
> Baremetal API v1: Node Power State

- openstack/loadbalancer/v2/loadbalancers/requests.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
- openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
For #1489
- Source code: <https://github.com/openstack/octavia/blob/612b042e64d9fcffb983f958ed0d6de6a9f765d3/octavia/api/v2/types/load_balancer.py#L115>
- API doc: <https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-a-load-balancer>
> Octavia: Support to specify vip_port_id for creating load balancer

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
For #1429
The `Value` field for Updates can actually be any serializable value, depending on the `Path` you're modifying.  For example, `properties` can be a `map[string]interface{}`, `maintenance` can be just a boolean, etc.
- API ref: https://developer.openstack.org/api-ref/baremetal/?expanded=update-node-detail
> Baremetal API V1: Update can use any serializable value

- openstack/auth_env.go
Check extra params are set if project name is given
Setting project name is insufficient according to the spec for project scoped auth.
For #1491 
https://developer.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-scoped-authorization-detail#authenticating-with-an-application-credential
> check for project id if project name specified

- openstack/baremetal/v1/drivers/doc.go
- openstack/baremetal/v1/drivers/requests.go
- openstack/baremetal/v1/drivers/results.go
- openstack/baremetal/v1/drivers/testing/doc.go
- openstack/baremetal/v1/drivers/testing/fixtures.go
- openstack/baremetal/v1/drivers/testing/requests_test.go
- openstack/baremetal/v1/drivers/urls.go
For #1429
This patch adds the Drivers API calls according to [Baremetal API reference](https://developer.openstack.org/api-ref/baremetal/#drivers-drivers)
List Drivers (GET)
Show driver details (GET)
Show driver properties (GET)
Show driver logical disk properties (GET)
Source code reference:
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/driver.py
> Baremetal V1 API Drivers

- errors.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- provider_client.go
For #1497
Add ErrDefault409 and convert http.StatusConflict errors to ErrDefault409.
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L507
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L642
> baremetal v1: add support for 409 errors

- acceptance/openstack/compute/v2/servers_test.go
- openstack/compute/v2/extensions/extendedserverattributes/doc.go
- openstack/compute/v2/extensions/extendedserverattributes/microversions.go
- openstack/compute/v2/extensions/extendedserverattributes/results.go
- openstack/compute/v2/extensions/extendedserverattributes/testing/requests_test.go
Add microversions.go to extendedserverattributes extension with support
to retrieve the following fields from the servers responses:
- OS-EXT-SRV-ATTR:reservation_id
- OS-EXT-SRV-ATTR:launch_index
- OS-EXT-SRV-ATTR:ramdisk_id
- OS-EXT-SRV-ATTR:kernel_id
- OS-EXT-SRV-ATTR:hostname
- OS-EXT-SRV-ATTR:root_device_name
- OS-EXT-SRV-ATTR:userdata
Update unit tests and documentation.
For #1160
https://github.com/openstack/nova/blob/stable/rocky/nova/db/sqlalchemy/models.py#L253
> Compute V2: add 2.3 microversion OS-EXT-SRV-ATTR

- acceptance/openstack/compute/v2/hypervisors_test.go
- openstack/compute/v2/extensions/hypervisors/doc.go
- openstack/compute/v2/extensions/hypervisors/requests.go
- openstack/compute/v2/extensions/hypervisors/results.go
- openstack/compute/v2/extensions/hypervisors/testing/fixtures.go
- openstack/compute/v2/extensions/hypervisors/testing/requests_test.go
- openstack/compute/v2/extensions/services/results.go
- openstack/compute/v2/extensions/services/testing/fixtures.go
- openstack/compute/v2/extensions/services/testing/requests_test.go
This commit adds suport Compute API 2.53 microversion
services implementation by adding string UUIDs in the basic service
result structure.
It also updates unit tests.
For #1370 
https://github.com/openstack/nova/blob/stable/rocky/nova/api/openstack/compute/services.py#L84
> Compute V2: add support for service string UUID

- acceptance/openstack/imageservice/v2/imageimport_test.go
- acceptance/openstack/imageservice/v2/imageservice.go
- openstack/imageservice/v2/imageimport/doc.go
- openstack/imageservice/v2/imageimport/requests.go
- openstack/imageservice/v2/imageimport/results.go
- openstack/imageservice/v2/imageimport/testing/fixtures.go
- openstack/imageservice/v2/imageimport/testing/requests_test.go
- openstack/imageservice/v2/imageimport/urls.go
Implement Create method that allows to import image data to the existing image.
Add unit and acceptance tests with documentation.
For #1143
API route:
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/router.py#L428
Main method:
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/images.py#L92
Response code:
https://github.com/openstack/glance/blob/stable/queens/glance/api/v2/images.py#L976
> Imageservice V2: add Create to imageimport

- acceptance/clients/clients.go
- openstack/baremetalintrospection/v1/introspection/doc.go
- openstack/baremetalintrospection/v1/introspection/requests.go
- openstack/baremetalintrospection/v1/introspection/results.go
- openstack/baremetalintrospection/v1/introspection/testing/doc.go
- openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
- openstack/baremetalintrospection/v1/introspection/testing/requests_test.go
- openstack/baremetalintrospection/v1/introspection/urls.go
- openstack/client.go
- service_client.go
For #1485
This patch adds the Node Introspection API calls according to [1]
Start Introspection (POST)
Get Introspection status (GET)
List all Introspection statuses (GET)
Abort Introspection (POST)
Get Introspection Data (GET)
Reapply Introspection on stored data (POST)
Source code reference:
https://github.com/openstack/ironic-inspector/tree/master/ironic_inspector
[1] https://developer.openstack.org/api-ref/baremetal-introspection/#node-introspection
> Baremetal Inspector Client Node Introspection

- openstack/baremetal/v1/ports/results.go
- openstack/baremetal/v1/ports/testing/fixtures.go
For #1429
This PR updates the type of the variables `UpdatedAt` and `CreatedAt` to time.Time
and adds the `UnmarshalJSON` function
> Change UpdatedAt and CreatedAt to time.Time

- openstack/compute/v2/extensions/keypairs/requests.go
Added code 201 (accepted) to ok codes in keypair creation.
Without this fix, keypair creation fails with compute microversion "2.60" because it gets status 201.
For #1518
> Fix OK codes in keypair creation

- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
For #1513
- [API doc](https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-listener)
- [Source code](https://github.com/openstack/octavia/blob/68b9d06dae65c20b26aa63b78884f94b6642c542/octavia/api/v2/types/listener.py#L123)
> Octavia: Support insert_headers for creating listener

- openstack/containerinfra/v1/clusters/requests.go
- openstack/containerinfra/v1/clusters/results.go
- openstack/containerinfra/v1/clusters/testing/fixtures.go
- openstack/containerinfra/v1/clusters/testing/requests_test.go
- openstack/containerinfra/v1/clusters/urls.go
Recently in Magnum we introduced a new API v1/clusters/clusterID/actions/resize [1]
to enable the capability that consumer can resize the node count of the
cluster and meanwhile the API allows to pass in the node instance ID
so as to delete particular nodes. That's very useful for the auto-healing
and auto-scaling cases which Magnum will leverage k8s cluster Autoscaler
to achieve that.
Without this new API, the consumer has to call Heat API firstly to remove
the particular to remove the nodes and then call Magnum API again to
update the node count, which is not ideal obviously. Hence the new API
was proposed. More information please refer [2] [3].
For #1515
[1] https://review.openstack.org/638572
[2] https://review.openstack.org/631378
[3] kubernetes/autoscaler#1690
> Support Magnum resize API

- openstack/containerinfra/apiversions/doc.go
- openstack/containerinfra/apiversions/errors.go
- openstack/containerinfra/apiversions/requests.go
- openstack/containerinfra/apiversions/results.go
- openstack/containerinfra/apiversions/testing/doc.go
- openstack/containerinfra/apiversions/testing/fixtures.go
- openstack/containerinfra/apiversions/testing/requests_test.go
- openstack/containerinfra/apiversions/urls.go
New package "apiversions" is introducing so that the consumer of Magnum API can discovery the correct version of Magnum to leverage.
For #1520
[1] https://developer.openstack.org/api-ref/container-infrastructure-management/?expanded=list-api-versions-detail,show-v1-api-version-detail#api-versions
> Add apiversions package for Magnum

- openstack/loadbalancer/v2/apiversions/doc.go
- openstack/loadbalancer/v2/apiversions/requests.go
- openstack/loadbalancer/v2/apiversions/results.go
- openstack/loadbalancer/v2/apiversions/testing/doc.go
- openstack/loadbalancer/v2/apiversions/testing/fixture.go
- openstack/loadbalancer/v2/apiversions/testing/requests_test.go
- openstack/loadbalancer/v2/apiversions/urls.go
This PR adds apiversion package for load balancer resources, enabling API consumers to discover available versions. 
For #1523
[Octavia API version support ](https://developer.openstack.org/api-ref/load-balancer/?expanded=#)
> Add support to Load Balancer api version requests

- .zuul.yaml
We hope to move all of outside periodic jobs back to OpenLab
projects.yaml, so that we can plan the periodic testing resource
usage amount for OpenLab and avoid periodic jobs define confusion
in different project branch maintaining policy. Periodic jobs will
be moved to theopenlab/openlab-zuul-jobs#479 and will be triggered
at UTC-0 04:00 and 16:00 of everyday.
Related-Bug: theopenlab/openlab#173
> Move periodic jobs back to OpenLab

- acceptance/openstack/networking/v2/apiversion_test.go
- openstack/blockstorage/v1/apiversions/urls.go
- openstack/containerinfra/apiversions/urls.go
- openstack/loadbalancer/v2/apiversions/requests.go
- openstack/loadbalancer/v2/apiversions/urls.go
- openstack/networking/v2/apiversions/requests.go
- openstack/networking/v2/apiversions/urls.go
- openstack/orchestration/v1/apiversions/requests.go
- openstack/orchestration/v1/apiversions/urls.go
- openstack/sharedfilesystems/apiversions/urls.go
For #1529 
This commit updates the `apiversions` packages to account for a variety of base URLs which have been known to exist in the Keystone catalog: https://github.com/gophercloud/gophercloud/blob/master/openstack/utils/testing/base_endpoint_test.go
These packages should also be housed under a versionless directory. For example, `networking/v2/apiversions` _should_ be `networking/apiversions` since it should be possible to use this package to retrieve the API versions for _all_ major versions.
However, there is a catch: services such as Block Storage changed the format of the API results a while back. this is why `blockstorage/v1/apiversions` exists. I fell down a rabbit hole looking into this a while back (https://github.com/gophercloud/gophercloud/pull/458). I haven't reviewed all of …
> Fix apiversions base URLs

- acceptance/openstack/baremetal/noauth/allocations_test.go
- acceptance/openstack/baremetal/v1/allocations_test.go
- acceptance/openstack/baremetal/v1/baremetal.go
- acceptance/openstack/baremetal/v1/nodes_test.go
- openstack/baremetal/v1/allocations/requests.go
- openstack/baremetal/v1/allocations/results.go
- openstack/baremetal/v1/allocations/testing/fixtures.go
- openstack/baremetal/v1/allocations/testing/requests_test.go
- openstack/baremetal/v1/allocations/urls.go
This PR adds support for Ironic Allocations.
For #1429
- API Ref: https://developer.openstack.org/api-ref/baremetal/?expanded=create-allocation-detail,list-allocations-detail
- Base class: https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/allocation.py#L39-L70
- List https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/allocation.py#L274-L298
-  Get https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/allocation.py#L306-L318
- Create https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/allocation.py#L320-L378
> Baremetal API V1: Allocations

- openstack/compute/v2/extensions/hypervisors/results.go
- openstack/compute/v2/extensions/hypervisors/testing/fixtures.go
- openstack/compute/v2/extensions/hypervisors/testing/requests_test.go
> Compute v2: Account for empty cpu_info in hypervisors

- acceptance/openstack/objectstorage/v1/containers_test.go
- openstack/objectstorage/v1/containers/doc.go
- openstack/objectstorage/v1/containers/requests.go
This commit enables metadata to be removed from a container. Gophercloud
internally strips empty strings from headers to enable deletion of
headers before they are sent in the request. This conflicts with the
ability to actually send an empty string when needed. Thereforer, a new
UpdateOpt has been added that sends the special X-Remove header with a
dummy value of "remove".
For #1511
> Object Storage v1: Enable removal of container metadata

- acceptance/openstack/container/v1/fixtures.go
Zun is going to require admin privilege [1] to create resource
with this field specified. Gophercloud acceptance test should
use non-admin credential to test so we remove this field from
acceptance test.
[1] https://review.openstack.org/#/c/650585/
For #1545
> Remove imagePullPolicy from acceptance test

- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
For #1543
Base definition:
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/common/data_models.py#L384
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/common/data_models.py#L386
Create:
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/api/v2/types/listener.py#L120-L123
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/api/v2/types/listener.py#L128-L130
Update:
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/api/v2/types/listener.py#L154-L156
* https://github.com/openstack/octavia/blob/stable/rocky/octavia/api/v2/types/listener.py#L160-L162
> Loadbalancer v2: Listener createopts TimeoutMemberConnect & TimeoutTCPInspect

- openstack/baremetalintrospection/noauth/doc.go
- openstack/baremetalintrospection/noauth/requests.go
- openstack/baremetalintrospection/noauth/testing/requests_test.go
For #1485
Add noauth support for the baremetal introspection (ironic-inspector)
service.
This is heavily based on the equivalent noauth support already present for the main Ironic API.
Source reference:
https://github.com/openstack/ironic-inspector/tree/master/ironic_inspector
> Baremetal Inspector noauth support

- .zuul.yaml
Input comment "recheck stable/stein" in pull request comments, that
will trigger acceptance tests against OpenStack Stein release. OpenLab
will report test result in followint comments automatically.
Related-Bug: theopenlab/openlab#231
> Support acceptance test against OpenStack Stein release

- openstack/baremetalintrospection/v1/introspection/results.go
- openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
- openstack/baremetalintrospection/v1/introspection/testing/results_test.go
The LLDP data in the inventory doesn't appear as a JSON object, but as
a JSON array of [type, value] pairs such as:
[[1, "04112233aabbcc"], [2, "07373334"], ...]
(There can be multiple fields with the same type, which is why they are
not returned as a JSON object.)
There is a place where the raw LLDP data is processed into a JSON object
- under the `lldp_processed` key in the top-level `all_interfaces` list
(i.e. not in the inventory), here represented by BaseInterfaceType.
This patch corrects handling for LLDP data in the inventory (i.e. in
InterfaceType) and adds handling for it in BaseInterfaceType
For #1485 
https://github.com/openstack/ironic-inspector/blob/8.2.0/ironic_inspector/test/unit/t …
> Baremetal introspection: correct handling of LLDP data

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/ports/requests.go
Fix for #1554 
Use method `client.Patch` instead of `client.Request`
The problem with `client.Request` is in missing call to `initReqOpts`.
> Baremetal: Fix microversion headers in node.Update

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
Config drives may be a URL, a base64-encoded gzipped ISO9660 image, or beginning in Ironic API microversion 1.56, JSON with user, network, and meta data keys.
Users on earlier than 1.56 will need to encode user data themselves, or use gophercloud/utils' helper.
For #1429
- Ironic API ref: https://developer.openstack.org/api-ref/baremetal/?expanded=change-node-provision-state-detail
- Implementation https://github.com/openstack/ironic/commit/3e1e0c9d5e6e5753d0fe2529901986ea36934971#diff-0475f180604c34b6fe131ce1bd3c26a0
> Baremetal API V1: Support new config drive JSON for nodes

- acceptance/openstack/baremetal/noauth/nodes_test.go
- acceptance/openstack/baremetal/v1/baremetal.go
- acceptance/openstack/baremetal/v1/nodes_test.go
- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/testing/fixtures.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
- openstack/baremetal/v1/nodes/urls.go
For #1429
This adds support to set a node's RAID configuration.
- [API Ref](https://developer.openstack.org/api-ref/baremetal/?expanded=set-raid-config-detail#set-raid-config)
- [Target RAID Config](https://docs.openstack.org/ironic/latest/admin/raid.html)
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L466-L494
- Each driver (if it supports RAID) reads from the same format of the TargetRaidConfig data structure defined in the doc above. It's spread out in the case base, but for example - here's DRAC: https://github.com/openstack/ironic/blob/master/ironic/drivers/modules/drac/raid.py
> Baremetal API V1: Support set RAID config

- acceptance/clients/http.go
it is a part of the #1566
this PR prevents token to be printed. Same should be done for the terraform openstack provider in future.
> Don't print token on token auth method

- acceptance/clients/http.go
Relates to #1567. There is no need to replicate it in terraform, it is already there.
> Hide application credential auth while debug

- openstack/identity/v3/tokens/requests.go
For #1569.
It might be worthwhile to check if this problem also exists in other request methods in other packages.
> do not swallow connection errors in tokens.Get()

- openstack/orchestration/v1/stackresources/results.go
The attribute `parent_resource` is helpful when building a reverse mapping between the resource and their parents.
[1] https://github.com/openstack/heat/blob/master/heat/rpc/api.py#L76
For #1575
> Add parent_resource attribute for Heat stack resource

- acceptance/openstack/orchestration/v1/stackresources_test.go
- openstack/orchestration/v1/stackresources/requests.go
- openstack/orchestration/v1/stackresources/results.go
- openstack/orchestration/v1/stackresources/testing/fixtures.go
- openstack/orchestration/v1/stackresources/testing/requests_test.go
- openstack/orchestration/v1/stackresources/urls.go
Heat supports mark a resource as unhealthy via API, which is very
useful for auto healing use case. After marked a resource unhealthy,
the status of the resource will be 'CHECK_FAILED', then the resource
will be rebuilt as long as a Heat stack update triggered.
For #1573
Here is the API reference for resource mark unhealthy:
https://developer.openstack.org/api-ref/orchestration/v1/index.html?expanded=mark-a-resource-as-unhealthy-detail#mark-a-resource-as-unhealthy
> Support mark unhealthy action for stack resource

- openstack/networking/v2/extensions/qos/policies/doc.go
- openstack/networking/v2/extensions/qos/policies/requests.go
- openstack/networking/v2/extensions/qos/policies/testing/fixtures.go
- openstack/networking/v2/extensions/qos/policies/testing/requests_test.go
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L100
> Networking V2: add QoS policy extension for Net

- openstack/networking/v2/extensions/qos/rules/doc.go
- openstack/networking/v2/extensions/qos/rules/requests.go
- openstack/networking/v2/extensions/qos/rules/results.go
- openstack/networking/v2/extensions/qos/rules/testing/doc.go
- openstack/networking/v2/extensions/qos/rules/testing/fixtures.go
- openstack/networking/v2/extensions/qos/rules/testing/requests_test.go
- openstack/networking/v2/extensions/qos/rules/urls.go
Allow to create a bandwidth limit rule.
For #1027
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/qos.py#L30
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/qos.py#L115
> Networking V2: add bw limit rule Create

- openstack/networking/v2/extensions/qos/rules/doc.go
- openstack/networking/v2/extensions/qos/rules/requests.go
- openstack/networking/v2/extensions/qos/rules/results.go
- openstack/networking/v2/extensions/qos/rules/testing/requests_test.go
- openstack/networking/v2/extensions/qos/rules/urls.go
Allow to delete a bandwidth limit rule.
For #1027
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/qos.py#L30
https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/qos.py#L115
> Networking V2: add bw limit rule Delete

- acceptance/openstack/networking/v2/extensions/qos/policies/policies.go
- acceptance/openstack/networking/v2/extensions/qos/policies/policies_test.go
- openstack/networking/v2/extensions/qos/policies/doc.go
- openstack/networking/v2/extensions/qos/policies/requests.go
- openstack/networking/v2/extensions/qos/policies/results.go
- openstack/networking/v2/extensions/qos/policies/testing/fixtures.go
- openstack/networking/v2/extensions/qos/policies/testing/requests_test.go
- openstack/networking/v2/extensions/qos/policies/urls.go
Add Get function for QoS policies package.
Cleanup QoS extension documentation.
Add acceptance test for QoS policies CRUD that will be temporary
disabled.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L54
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L43
> Networking: add QoS policies Get, cleanup QoS doc

- openstack/networking/v2/extensions/qos/rules/doc.go
- openstack/networking/v2/extensions/qos/rules/requests.go
- openstack/networking/v2/extensions/qos/rules/results.go
- openstack/networking/v2/extensions/qos/rules/testing/fixtures.go
- openstack/networking/v2/extensions/qos/rules/testing/requests_test.go
- openstack/networking/v2/extensions/qos/rules/urls.go
Add QoS DSCP marking rules List function.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L137
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L84
> Networking V2: add QoS DSCP marking rules List

- acceptance/openstack/networking/v2/extensions/qos/policies/policies.go
- openstack/networking/v2/extensions/qos/policies/doc.go
- openstack/networking/v2/extensions/qos/policies/requests.go
- openstack/networking/v2/extensions/qos/policies/results.go
- openstack/networking/v2/extensions/qos/policies/testing/fixtures.go
- openstack/networking/v2/extensions/qos/policies/testing/requests_test.go
- openstack/networking/v2/extensions/qos/policies/urls.go
Implement QoS policy Create function.
Add tests, docs and acceptance test helper.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L54
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L43
> Networking V2: add QoS policy Create call

- openstack/compute/v2/extensions/diagnostics/doc.go
- openstack/compute/v2/extensions/diagnostics/requests.go
- openstack/compute/v2/extensions/diagnostics/results.go
- openstack/compute/v2/extensions/diagnostics/testing/fixtures.go
- openstack/compute/v2/extensions/diagnostics/testing/requests_test.go
- openstack/compute/v2/extensions/diagnostics/urls.go
For #1585
The call for diagnostics comes into the nova api[1], is sent over rpc to the compute manager[2], and finally ends up depending on the driver[3]. My env uses libvirt, which builds and returns a 'single-level' python dict[4]. The response is hard to map to a struct in this scenario because there are possible extra values for extra vnics and disks.
Future work needs to be done on adding diagnostics/microversions.go to provide extract methods for a better structured, 'multi-level' dict response that is available with nova microversion 2.48 or higher[1][5], but I don't feel comfortable working on that without having it available in my environment to fully test against.
[1] https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/server_diagnostics.py#L42-L47
[2] …
> Diagnostics Compute Extension

- acceptance/openstack/networking/v2/extensions/qos/policies/policies.go
- acceptance/openstack/networking/v2/extensions/qos/policies/policies_test.go
- openstack/networking/v2/extensions/qos/policies/doc.go
- openstack/networking/v2/extensions/qos/policies/requests.go
- openstack/networking/v2/extensions/qos/policies/results.go
- openstack/networking/v2/extensions/qos/policies/testing/fixtures.go
- openstack/networking/v2/extensions/qos/policies/testing/requests_test.go
- openstack/networking/v2/extensions/qos/policies/urls.go
- script/acceptancetest
Add TestPoliciesCRUD acceptance test and CreateQoSPolicy,
DeleteQoSPolicy helpers.
For #1027
> Networking V2: add QoS policies acceptance tests

- openstack/networking/v2/extensions/qos/rules/doc.go
- openstack/networking/v2/extensions/qos/rules/requests.go
- openstack/networking/v2/extensions/qos/rules/results.go
- openstack/networking/v2/extensions/qos/rules/testing/fixtures.go
- openstack/networking/v2/extensions/qos/rules/testing/requests_test.go
- openstack/networking/v2/extensions/qos/rules/urls.go
Implement QoS DSCPMarking rule Update call.
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos.py#L137
https://github.com/openstack/neutron/blob/stable/stein/neutron/extensions/qos.py#L84
> Networking V2: add QoS DSCPMarking rule Update

- openstack/baremetalintrospection/v1/introspection/results.go
A patch is being made to the Ironic Python Agent to return the hostname
that the introspected machine thinks it has. This enables Gophercloud
to pass that along.
For #1616 
https://review.opendev.org/#/c/663991/
> Baremetal Introspection: Add hostname to introspection data

- openstack/compute/v2/extensions/schedulerhints/requests.go
- openstack/compute/v2/extensions/schedulerhints/testing/requests_test.go
The "query" part of the scheduler_hints has never been correct. Instead
of sending a nested JSON structure, the Nova API actually expects a
marshalled JSON string which it will then decode.
Normally we would probably just change `Query` to a type `string` and make the application do the marshaling, but since this extension already has a lot of validation included, I opted to do the marshaling here.
For #1619
> Compute v2: Scheduler Hints Fix

- openstack/baremetalintrospection/v1/introspection/results.go
- openstack/baremetalintrospection/v1/introspection/testing/results_test.go
If the `extra_hardware` processing hook is enabled in ironic-inspector,
then additional data is provided as a top-level object named `"extra"`,
with a number of sections, each of which is also an object containing
objects with various key/value data.
For #1485
https://opendev.org/openstack/ironic-inspector/src/branch/master/ironic_inspector/plugins/extra_hardware.py
> Baremetal introspection: Read extra_hardware data

- acceptance/openstack/networking/v2/extensions/qos/ruletypes/ruletypes_test.go
- openstack/networking/v2/extensions/qos/ruletypes/doc.go
- openstack/networking/v2/extensions/qos/ruletypes/requests.go
- openstack/networking/v2/extensions/qos/ruletypes/results.go
- openstack/networking/v2/extensions/qos/ruletypes/testing/fixtures.go
- openstack/networking/v2/extensions/qos/ruletypes/testing/requests_test.go
- openstack/networking/v2/extensions/qos/ruletypes/urls.go
Implement GetRuleType function with unit test.
Update QoS rule types documentation.
Update QoS rule types acceptance test.
Extend RuleType struct with additional fields. Unfortunately the
ParameterValues field is implemented as interface{} given it's dynamic
behavior (it can be map or slice in different situtations).
For #1027
https://github.com/openstack/neutron-lib/blob/stable/stein/neutron_lib/api/definitions/qos_rule_type_details.py
https://github.com/openstack/neutron/blob/stable/stein/neutron/services/qos/drivers/manager.py#L88
https://github.com/openstack/neutron/blob/stable/stein/neutron/services/qos/qos_plugin.py#L369
> Networking V2: add QoS rule type Get call

- acceptance/openstack/blockstorage/extensions/extensions.go
- acceptance/openstack/blockstorage/extensions/volumeactions_test.go
- openstack/blockstorage/extensions/volumeactions/requests.go
- openstack/blockstorage/extensions/volumeactions/results.go
- openstack/blockstorage/extensions/volumeactions/testing/fixtures.go
- openstack/blockstorage/extensions/volumeactions/testing/requests_test.go
For #1610 
Adds support for setting image metadata for a volume in volumeactions.
- [Source Code](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/volume_image_metadata.py#L88-L101)
- [Docs](https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=upload-volume-to-image-detail,set-image-metadata-for-a-volume-detail#set-image-metadata-for-a-volume)
> Adds support for setting image metadata for a volume

- openstack/baremetalintrospection/v1/introspection/results.go
- openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
- openstack/baremetalintrospection/v1/introspection/testing/results_test.go
The IPA patch added the hostname to the Inventory field, not as a top-level
field. This moves the hostname into the InventoryType where it belongs.
For #1626
> Baremetal Introspection: Move hostname to InventoryType

- openstack/baremetal/apiversions/doc.go
- openstack/baremetal/apiversions/requests.go
- openstack/baremetal/apiversions/results.go
- openstack/baremetal/apiversions/testing/fixtures.go
- openstack/baremetal/apiversions/testing/requests_test.go
- openstack/baremetal/apiversions/urls.go
For #1429
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/version.py
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/versions.py
> Baremetal API: Return versions supported by the API

- openstack/baremetal/v1/nodes/requests.go
- openstack/baremetal/v1/nodes/testing/requests_test.go
Currently, the **Args** property in CleanStep struct has **map[string]string that
does not match with manual cleaning steps in Ironic. It should be dictionary in python[1][2] and interface{} in golang . For example:
BIOS setting for a node:
```
[
{
"interface": "bios",
"step": "apply_configuration",
"args": {
"settings": [{"name": "hyper_threading_enabled", "value": "false"}]
}
}
]
```
This PR aims to update **Args** in **CleanStep** struct.
[1] https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L76
[2] https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L624
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
> Baremetal API: Update CleanStep struct to support manual cleaning

- acceptance/openstack/compute/v2/compute.go
- acceptance/openstack/compute/v2/servergroup_test.go
- openstack/compute/v2/extensions/servergroups/doc.go
- openstack/compute/v2/extensions/servergroups/microversions.go
- openstack/compute/v2/extensions/servergroups/requests.go
- openstack/compute/v2/extensions/servergroups/results.go
- openstack/compute/v2/extensions/servergroups/testing/fixtures.go
- openstack/compute/v2/extensions/servergroups/testing/requests_test.go
Add "policy" and "rules" fields for servergroups Create call.
Those fields are available in 2.64 microversion.
Remove required attribute from the "policies" field.
Add "omitempty" attribute to the Rules.MaxServerPerHost field.
For #1600
https://github.com/openstack/nova/blob/stable/stein/nova/api/openstack/compute/server_groups.py#L186
> Compute: "policy", "rules" add servergroups Create

- openstack/loadbalancer/v2/monitors/requests.go
For #1639 
Octavia now supports defaults for when the url_path and expected_codes
are not supplied in the request body. This commit removes the local
validation for these fields to allow the API defaults to be used.
Users working with earlier versions of Octavia will need to be mindful
that they cannot rely on defaults being provided by the API and
therefore must provide explicit values.
https://github.com/openstack/octavia/blob/b2d40c1120727c68b570955413516290ad85f809/octavia/api/v2/controllers/health_monitor.py#L134-L143
> Load Balancer v2: Remove Health Monitor Validation

- openstack/identity/v3/extensions/trusts/doc.go
- openstack/identity/v3/extensions/trusts/requests.go
- openstack/identity/v3/extensions/trusts/results.go
- openstack/identity/v3/extensions/trusts/testing/fixtures.go
- openstack/identity/v3/extensions/trusts/testing/requests_test.go
- openstack/identity/v3/extensions/trusts/urls.go
Implement Delete function for the v3/extensions/trusts package with
tests and docs.
For #1642 
https://github.com/openstack/keystone/blob/stable/stein/keystone/trust/core.py#L190
https://github.com/openstack/keystone/blob/stable/stein/keystone/api/trusts.py#L242
> Identity V3: add Trust Delete function

- openstack/networking/v2/extensions/security/groups/results.go
- openstack/networking/v2/extensions/security/groups/testing/fixtures.go
- openstack/networking/v2/extensions/security/groups/testing/requests_test.go
for: #1648
* time.Time object
* mapped to existing json fields
General API reference: https://developer.openstack.org/api-ref/network/v2/?expanded=show-security-group-detail#show-security-group
that fields defined in standard_attr.py , that means that it should be applied to all neutron-resources though decorator:
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/standard_attr.py#L181
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/models/securitygroup.py#L26
> [Neutron][SecurityGroup] updated_at/created_at fields

- acceptance/openstack/sharedfilesystems/v2/shares_test.go
- openstack/sharedfilesystems/v2/shares/requests.go
- openstack/sharedfilesystems/v2/shares/results.go
- openstack/sharedfilesystems/v2/shares/testing/fixtures.go
- openstack/sharedfilesystems/v2/shares/testing/request_test.go
- openstack/sharedfilesystems/v2/shares/urls.go
For #1653
Manila API reference for Share metadata: https://docs.openstack.org/api-ref/shared-file-system/#share-metadata
* [Show metadata implementation](https://github.com/openstack/manila/blob/cec13b8057fa025fa1b1c3bef180687a394d6fd6/manila/api/v1/share_metadata.py#L42-L45)
* [Set metadata implementation](https://github.com/openstack/manila/blob/master/manila/api/v1/share_metadata.py#L98-L119)
* [Update metadata implementation](https://github.com/openstack/manila/blob/master/manila/api/v1/share_metadata.py#L98-L119)
* [Unset metadata implementation](https://github.com/openstack/manila/blob/master/manila/share/api.py#L1805-L1807)
> Manila: add support for share metadata modification

- openstack/sharedfilesystems/v2/sharetypes/results.go
For #1663 
This PR adds `IDFromName` convenience function for Manila share types.
> manila share-types: add IDFromName convenience function

- openstack/identity/v3/endpoints/requests.go
For #1665 
Region ID is a string, not an int
https://docs.openstack.org/api-ref/identity/v3/?expanded=list-endpoints-detail#service-catalog-and-endpoints
> Identity V3: Fix RegionID type

- acceptance/openstack/blockstorage/v3/quotaset_test.go
- openstack/blockstorage/extensions/quotasets/results.go
- openstack/blockstorage/extensions/quotasets/testing/fixtures.go
Allow to retrieve groups attribute for the Blockstorage quotaset.
Update tests.
For #1667 
https://github.com/openstack/cinder/blob/stable/stein/cinder/quota.py#L48
> Blockstorage: add groups to quotaset result

- openstack/containerinfra/v1/clusters/requests.go
- openstack/containerinfra/v1/clusters/results.go
- openstack/containerinfra/v1/clusters/testing/fixtures.go
- openstack/containerinfra/v1/clusters/testing/requests_test.go
For #1673
https://github.com/openstack/magnum/blob/04fd0470ad3b35c4af5212eee82431b1be43d64c/magnum/api/controllers/v1/cluster.py#L177
> Containerinfra: Allow setting fixed_network when creating cluster

- openstack/containerinfra/v1/clusters/requests.go
- openstack/containerinfra/v1/clusters/results.go
- openstack/containerinfra/v1/clusters/testing/fixtures.go
- openstack/containerinfra/v1/clusters/testing/requests_test.go
For #1673
https://github.com/openstack/magnum/blob/04fd0470ad3b35c4af5212eee82431b1be43d64c/magnum/api/controllers/v1/cluster.py#L180
> Containerinfra: Allow setting fixed_subnet when creating cluster

- openstack/loadbalancer/v2/loadbalancers/results.go
- openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
for: #1680
time.Time object
mapped to existing json fields
General API reference:https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=show-load-balancer-details-detail#show-load-balancer-details
that fields defined in:
https://github.com/openstack/octavia/blob/22df2e0f484b3560cbb47d33b7f2f62cb57519fd/octavia/api/v2/types/load_balancer.py#L46
>  [Octavia][Loadbalancers] updated_at/created_at fields

- openstack/baremetal/v1/nodes/requests.go
This PR aims to change the type of InterfaceType's enums from `DiskType` to `InterfaceType` to solve issue #1684
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
> Fix InterfaceType enums

- openstack/networking/v2/extensions/agents/requests.go
- openstack/networking/v2/extensions/agents/results.go
- openstack/networking/v2/extensions/agents/testing/fixtures.go
- openstack/networking/v2/extensions/agents/testing/requests_test.go
- openstack/networking/v2/extensions/agents/urls.go
this add the listDHCPNetworks call for agents, enabling them
to fetch a list of networks scheduled to a specific agent.
For #1389
https://github.com/openstack/neutron/blob/76754e06f56a7a9e4c23bef6a6e0e340e4110fa8/neutron/db/agentschedulers_db.py#L433-L443
https://docs.openstack.org/api-ref/network/v2/?expanded=list-networks-hosted-by-a-dhcp-agent-detail#list-networks-hosted-by-a-dhcp-agent
> Network v2: add listDHCPNetworks for agents extension

- openstack/compute/v2/extensions/tags/doc.go
- openstack/compute/v2/extensions/tags/requests.go
- openstack/compute/v2/extensions/tags/results.go
- openstack/compute/v2/extensions/tags/testing/doc.go
- openstack/compute/v2/extensions/tags/testing/fixtures.go
- openstack/compute/v2/extensions/tags/testing/requests_test.go
- openstack/compute/v2/extensions/tags/urls.go
Add Check method for tags extension.
Update docs and inline comments.
Provide unit tests.
For #1669
https://github.com/openstack/nova/blob/stable/stein/nova/api/openstack/compute/server_tags.py#L66
https://github.com/openstack/nova/blob/stable/stein/nova/objects/tag.py#L50
> Compute V2: add tags Check call

- acceptance/openstack/networking/v2/extensions/layer3/layer3.go
- acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go
- openstack/networking/v2/extensions/layer3/portforwarding/doc.go
- openstack/networking/v2/extensions/layer3/portforwarding/requests.go
- openstack/networking/v2/extensions/layer3/portforwarding/results.go
- openstack/networking/v2/extensions/layer3/portforwarding/testing/requests_test.go
Please merge #1651 first
For #1637 
Code:
https://github.com/openstack/neutron/blob/f21444f247108212dc835036c98e354d6e6f7ace/neutron/services/portforwarding/pf_plugin.py#L498
API:
https://docs.openstack.org/api-ref/network/v2/?expanded=create-port-forwarding-detail#delete-a-floating-ip-port-forwarding
> Delete Port Forwarding

- openstack/compute/v2/extensions/bootfromvolume/requests.go
- openstack/compute/v2/extensions/bootfromvolume/testing/fixtures.go
- openstack/compute/v2/extensions/bootfromvolume/testing/requests_test.go
For #1689 
* https://github.com/openstack/nova/blob/324db786c86eeb69278736c8e9db6d22f68080e6/nova/objects/block_device.py#L96
* https://github.com/openstack/nova/blob/c883f2201026b9237a1fba9a0a55ff607d57e787/nova/block_device.py#L44-L48
* https://github.com/openstack/nova/blob/b879f1b6dfe285c143dfee41dbb0c8d697a775b4/nova/api/openstack/compute/schemas/servers.py#L354-L356
> Compute v2: Adding VolumeType to bootfromvolume

- acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go
- openstack/networking/v2/extensions/layer3/portforwarding/doc.go
- openstack/networking/v2/extensions/layer3/portforwarding/requests.go
- openstack/networking/v2/extensions/layer3/portforwarding/results.go
- openstack/networking/v2/extensions/layer3/portforwarding/testing/requests_test.go
For #1637 
Source:
https://github.com/openstack/neutron/blob/f21444f247108212dc835036c98e354d6e6f7ace/neutron/services/portforwarding/pf_plugin.py#L368
https://github.com/openstack/neutron-lib/blob/56033ba643812a30577f6ab17648806c2ee494ba/neutron_lib/api/definitions/floating_ip_port_forwarding.py
API:
https://docs.openstack.org/api-ref/network/v2/?expanded=update-a-port-forwarding-detail#update-a-port-forwarding
> Update port forwarding

- openstack/loadbalancer/v2/listeners/requests.go
- openstack/loadbalancer/v2/listeners/results.go
- openstack/loadbalancer/v2/listeners/testing/fixtures.go
- openstack/loadbalancer/v2/listeners/testing/requests_test.go
For #1709
- API doc: <https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=create-listener-detail#id34>
- Source code (create listener): <https://github.com/openstack/octavia/blob/38ff0be1dc74fae3cf80cb4368edaf4f88febf88/octavia/api/v2/types/listener.py#L152>
- Source code (update listener): <https://github.com/openstack/octavia/blob/38ff0be1dc74fae3cf80cb4368edaf4f88febf88/octavia/api/v2/types/listener.py#L189>
> Octavia: Support allowed_cidrs for listener

- go.mod
- openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
- openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
Use the UpdateOptsBuilder instead of the specific UpdateOpts struct
type in extensions/lbaas_v2/loadbalancers/requests.Update.
For #1704
> Neutron LB V2: use UpdateOptsBuilder
