gophercloud/gophercloud

acceptance/openstack/compute/v2/servers_test.go
openstack/compute/v2/extensions/tags/doc.go
openstack/compute/v2/extensions/tags/requests.go
openstack/compute/v2/extensions/tags/results.go
openstack/compute/v2/extensions/tags/testing/requests_test.go
openstack/compute/v2/extensions/tags/urls.go

Add Delete and DeletAll checks into TestServersTags.
For #1669

Acc tests: update Compute V2 Tags test

---

go.mod

Remove go version to not break compatibility with old environments.
For #1714

Remove go version from go.mod

---

script/acceptancetest

For https://github.com/theopenlab/openlab/issues/360
I think the OpenLab issue is only affecting Manila/sharedfilesystem. If tests pass, I'll merge this for a temporary fix.

Acc Tests: Disabling sharedfilesystem temporarily

---

openstack/blockstorage/v1/volumes/requests.go

For #1718 
```
--- FAIL: TestVolumesCreateDestroy (1.18s)
blockstorage.go:54: Attempting to create volume: ACPTTESTdQOwXTKgIkUMe1iK
volumes_test.go:43: Unable to create volume: Expected HTTP response code [200 201] when accessing [POST http://10.1.2.177/volume/v3/5bfa04f074684d73b714df219457f327/volumes], but got 202 instead
```
Given this is for Block Storage v1, this is more of a legacy patch. I didn't do too much digging into the Cinder code to validate this change, but the acceptance tests can reproduce it, so that's probably good enough for this one.

Block Storage v1: Allow 202 when creating volumes

---

openstack/loadbalancer/v2/listeners/requests.go
openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go

LBaaSv2: Properly handle update TLS references

---

openstack/loadbalancer/v2/listeners/requests.go

For #1709
Octavia code: https://github.com/openstack/octavia/blob/master/octavia/api/v2/types/listener.py#L189
When using `*[]string{}`, the `listener.AllowedCIDRs` could be updated to `[]`

loadbalancer: Fix AllowedCIDRs for listener update

---

openstack/baremetalintrospection/v1/introspection/results.go

Disk by path (e.g. /dev/disk/by-path/pci-0000:00:07.0) is available in
ironic inspector results and may be required by some projects.
Tested and works as expected.
#1733

Add disk/by_path to available introspection data

---

acceptance/openstack/compute/v2/servers_test.go
openstack/compute/v2/extensions/tags/doc.go
openstack/compute/v2/extensions/tags/results.go

Add compute/v2/extensions/tags.ServerTagsExt to allow read tags right
from a Server body.
Fix compute/v2/extensions/tags to use the valid microversion.
Add ServerTagsExt usage example to compute/v2/extensions/tags docs.
Add ServerTagsExt into ServerTags acceptance test.
For #1669
https://github.com/openstack/nova/blob/stable/stein/nova/api/openstack/compute/servers.py#L353

Compute V2: allow to read Tags from Server body

---

openstack/loadbalancer/v2/pools/requests.go
openstack/loadbalancer/v2/pools/testing/fixtures.go
openstack/loadbalancer/v2/pools/testing/requests_test.go

Octavia LBaaSv2: Allow setting an empty members list

---

acceptance/openstack/networking/v2/extensions/quotas/quotas_test.go
openstack/networking/v2/extensions/quotas/doc.go
openstack/networking/v2/extensions/quotas/requests.go
openstack/networking/v2/extensions/quotas/results.go
openstack/networking/v2/extensions/quotas/testing/doc.go
openstack/networking/v2/extensions/quotas/testing/fixtures.go
openstack/networking/v2/extensions/quotas/testing/requests_test.go
openstack/networking/v2/extensions/quotas/urls.go
script/acceptancetest

Add openstack/networking/v2/extensions/quotas.Get.
Add unit and acceptance tests.
For #1666
https://github.com/openstack/neutron/blob/stable/train/neutron/quota/__init__.py#L102
https://github.com/openstack/neutron/blob/stable/train/neutron/extensions/quotasv2.py#L66

Networking V2: add quotas package

---

acceptance/openstack/networking/v2/extensions/quotas/quotas.go
acceptance/openstack/networking/v2/extensions/quotas/quotas_test.go
openstack/networking/v2/extensions/quotas/doc.go
openstack/networking/v2/extensions/quotas/requests.go
openstack/networking/v2/extensions/quotas/results.go
openstack/networking/v2/extensions/quotas/testing/fixtures.go
openstack/networking/v2/extensions/quotas/testing/requests_test.go
openstack/networking/v2/extensions/quotas/urls.go

Add openstack/networking/v2/extensions/quotas.Update.
Add unit and acceptance tests.
Update package docs.
For #1666
https://github.com/openstack/neutron/blob/stable/train/neutron/extensions/quotasv2.py#L116

Networking V2: add quotas.Update method

---

provider_client.go
testing/provider_client_test.go

It does not make sense to reauthenticate multiple times for a single request. When the backing service returns 401 for a brand-new token, reauthenticating again will just send us into an infinite loop.
Closes #1745.

avoid reauthentication loops

---

openstack/compute/v2/servers/requests.go

Server tags support was added in Nova API since 2.26, so we can implement it here as well.
For #1669
https://github.com/openstack/nova/blob/3b54979ae02cc74bcf215713c16916bbf4131443/nova/api/openstack/compute/schemas/servers.py#L645-L651
https://docs.openstack.org/api-ref/compute/?expanded=list-servers-detail,show-server-details-detail#list-servers

Compute V2: implement server tags filtering support

---

openstack/endpoint_location.go
openstack/errors.go
openstack/testing/endpoint_location_test.go

This commit changes the behvior when multiple endpoints are
discovered. Instead of returning an error, the first endpoint will
be used, discarding the other endpoints.
This change helps keep behavior in line with the Python SDK.
For #1764

Don't Error on Multiple Endpoints

---

acceptance/openstack/loadbalancer/v2/providers_test.go
openstack/loadbalancer/v2/providers/doc.go
openstack/loadbalancer/v2/providers/requests.go
openstack/loadbalancer/v2/providers/results.go
openstack/loadbalancer/v2/providers/testing/doc.go
openstack/loadbalancer/v2/providers/testing/fixtures.go
openstack/loadbalancer/v2/providers/testing/requests_test.go
openstack/loadbalancer/v2/providers/urls.go

This PR adds support for listing octavia providers
For #1773 
Octavia Providers API: https://docs.openstack.org/api-ref/load-balancer/v2/#providers
Octavia Providers API code (list providers) : 
* https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/provider.py#L41
* https://github.com/openstack/octavia/blob/4a5c24ef6fcd3b5f198a20d780dedd7f7976296d/octavia/api/v2/types/provider.py#L20

Add providers support to openstack loadbalancer

---

openstack/networking/v2/ports/testing/requests_test.go

For #1796 
This fixes a dropped test error in `openstack/networking/v2/ports/testing`.

openstack/networking/v2/ports/testing: fix dropped error

---

openstack/containerinfra/v1/clusters/results.go
openstack/containerinfra/v1/clusters/testing/fixtures.go
openstack/containerinfra/v1/clusters/testing/requests_test.go

The cluster resize result should contain just the cluster's ID, so it needs its own `Extract` method. Currently magnum is sending an empty response which is causing a different error in gophercloud, this will be fixed in magnum with [1].
Will keep as WIP until the fix is merged in magnum and I have been able to test with it.
For #1631 
[1] https://review.opendev.org/#/c/672600/

WIP ContainerInfra: extract ID from cluster resize result

---

acceptance/openstack/containerinfra/v1/clusters_test.go
acceptance/openstack/containerinfra/v1/containerinfra.go
acceptance/tools/tools.go

For #1767
Adds configurable timeouts to cluster creation which will be needed for kubernetes clusters, to be able to test node groups. A kubernetes cluster needs longer than 5 minutes to create.
There are also some fixes for the existing clusters API acceptance tests.
* Check timeout error when creating the cluster
* Fix update opts value type for replacing node count
* Change template storage driver
I have tried to make as few changes and additions as possible to the existing code, by making the existing functions just call to the versions that accept a timeout.
With these fixes, the cluster acceptance tests pass in my devstack on magnum master branch.
For the tests in CI, the timeouts may need to be tweaked.

Containerinfra: acceptance test timeout changes and fixes

---

openstack/compute/v2/extensions/evacuate/requests.go
openstack/compute/v2/extensions/evacuate/urls.go
openstack/compute/v2/extensions/lockunlock/requests.go
openstack/compute/v2/extensions/migrate/requests.go
openstack/compute/v2/extensions/migrate/urls.go
openstack/compute/v2/extensions/pauseunpause/requests.go
openstack/compute/v2/extensions/rescueunrescue/requests.go
openstack/compute/v2/extensions/resetstate/requests.go
openstack/compute/v2/extensions/resetstate/urls.go
openstack/compute/v2/extensions/shelveunshelve/doc.go
openstack/compute/v2/extensions/shelveunshelve/requests.go
openstack/compute/v2/extensions/shelveunshelve/results.go
openstack/compute/v2/extensions/shelveunshelve/testing/fixtures.go
openstack/compute/v2/extensions/shelveunshelve/testing/requests_test.go
openstack/compute/v2/extensions/startstop/requests.go
openstack/compute/v2/extensions/suspendresume/requests.go
openstack/compute/v2/extensions/urls.go

For #1798 
https://docs.openstack.org/api-guide/compute/server_concepts.html
https://docs.openstack.org/api-ref/compute/?expanded=shelve-server-shelve-action-detail,unshelve-restore-shelved-server-unshelve-action-detail,shelf-offload-remove-server-shelveoffload-action-detail
https://github.com/openstack/nova/blob/17b5a1ab85c358a1096788371849f0cccfe84972/nova/api/openstack/compute/shelve.py#L …

Added Shelve, Shelve-offload and Unshelve API

---

.zuul.yaml
.zuul/playbooks/gophercloud-acceptance-test/run.yaml
acceptance/openstack/sharedfilesystems/v2/shares_test.go

This change switch to install devstack on ubuntu
bionic, because openstack/devstack has dropped
xenial support.
Related-Bug: theopenlab/openlab#412

[WIP]Switch to install devstack on ubuntu 18.04

---

openstack/workflow/v2/crontriggers/requests.go

Just add missing s in sort_keys query param of cron triggers : 
https://docs.openstack.org/mistral/latest/api/v2.html#get--v2-workflows
For #1808
https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L119

Fix sort_key / sort_keys

---

acceptance/openstack/baremetal/v1/baremetal.go
acceptance/openstack/baremetal/v1/ports_test.go

For #1813 
The Ironic configuration being used in the tests enables only the iPXE
and Fake boot interfaces, so use those instead of PXE.

Fix ironic acceptance tests

---

openstack/orchestration/v1/resourcetypes/doc.go
openstack/orchestration/v1/resourcetypes/requests.go
openstack/orchestration/v1/resourcetypes/results.go
openstack/orchestration/v1/resourcetypes/testing/doc.go
openstack/orchestration/v1/resourcetypes/testing/fixtures.go
openstack/orchestration/v1/resourcetypes/testing/requests_test.go
openstack/orchestration/v1/resourcetypes/urls.go

Add client support for listing available resource types in Heat, getting
their schemata, and downloading example templates for use as provider
templates.
For #1805
* https://opendev.org/openstack/heat/src/branch/stable/train/heat/api/openstack/v1/stacks.py#L638-L659
* https://opendev.org/openstack/heat/src/branch/stable/train/heat/api/openstack/v1/stacks.py#L686-L707

Orchestration: Add support for resource_type endpoints

---

acceptance/openstack/keymanager/v1/acls_test.go
openstack/keymanager/v1/acls/requests.go
openstack/keymanager/v1/acls/testing/requests_test.go

Barbican V1: Allow multiple ACL types in one request

---

openstack/blockstorage/extensions/schedulerstats/results.go
openstack/blockstorage/extensions/schedulerstats/testing/fixtures.go

It appears that the max_over_subscription_ratio stat returned
by the schedulerstats extension can be both a string and float64
depending on the OpenStack release.
This commit enables both to be supported, converting either value
to a string.
For #1810

Block Storage: Fix Capabilities Parsing

---

acceptance/openstack/blockstorage/apiversions_test.go
openstack/blockstorage/apiversions/doc.go
openstack/blockstorage/apiversions/errors.go
openstack/blockstorage/apiversions/requests.go
openstack/blockstorage/apiversions/results.go
openstack/blockstorage/apiversions/testing/doc.go
openstack/blockstorage/apiversions/testing/fixtures.go
openstack/blockstorage/apiversions/testing/requests_test.go
openstack/blockstorage/apiversions/urls.go
openstack/blockstorage/v1/apiversions/doc.go

For #457 
If there's concern about leaving `v1/apiversions` for backwards compatibility, I can easily drop the deletion of `v1/apiversions` here. I'm on the fence about whether that would be worthwhile or not. The original `apiversions` seems to be expecting an old response format, but I suppose that might be useful for some very old environments.
/cc @j-griffith

BlockStorage: apiversions

---

errors.go
testing/errors_test.go

For #1632 
Supersedes #1633 
/cc @snigle I apologize for the delay following-up with this. After reviewing, I understand the need for the interface. However, I wanted to rename it from `GenericError` to something that describes the interface more specifically.

Add convenient access to error's status code

---

openstack/compute/v2/extensions/usage/requests.go

For #1641 
* https://github.com/openstack/nova/blob/c6218428e9b29a2c52808ec7d27b4b21aadc0299/nova/api/openstack/compute/views/usages.py#L27
* https://github.com/openstack/nova/blob/17b5a1ab85c358a1096788371849f0cccfe84972/nova/api/openstack/common.py#L419-L449
Acceptance tests for this API call are disabled due to issues we have running it in OpenLab. However, I tested this offline and can confirm it works.

Compute v2: Add Pagination Support to Usage

---

acceptance/openstack/blockstorage/extensions/volumeactions_test.go

For https://github.com/theopenlab/openlab/issues/222

Acc Tests: Re-enable TestVolumeActionsUploadImageDestroy

---

acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/listeners/testing/fixtures.go
openstack/loadbalancer/v2/listeners/testing/requests_test.go

Add openstack/loadbalancer/v2/listeners.UpdateOpts.InsertHeaders.
For #1834
https://github.com/openstack/octavia/blob/stable/train/octavia/api/v2/types/listener.py#L170

LoadBalancer V2: add InsertHeaders into UpdateOpts

---

acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/listeners/testing/requests_test.go

Use pointer to a map to allow unsetting headers for listener.
For #1834

LoadBalancer V2: use map ptr for insert headers

---

openstack/baremetal/v1/ports/requests.go
openstack/networking/v2/extensions/lbaas/vips/results.go

For #1839 
This fixes malformed JSON struct tags in `networking/v2/extensions/lbaas/vips` and `baremetal/v1/ports`.

Fix json struct tags

---

openstack/compute/v2/extensions/instanceactions/doc.go
openstack/compute/v2/extensions/instanceactions/request.go
openstack/compute/v2/extensions/instanceactions/results.go
openstack/compute/v2/extensions/instanceactions/testing/doc.go
openstack/compute/v2/extensions/instanceactions/testing/fixtures.go
openstack/compute/v2/extensions/instanceactions/testing/request_test.go
openstack/compute/v2/extensions/instanceactions/urls.go

For gophercloud#1845
https://docs.openstack.org/api-ref/compute/?expanded=list-actions-for-server-detail
https://github.com/openstack/nova/blob/51ed40a6a5fc046cef35337980a1fc5ad704a421/nova/api/openstack/compute/instance_actions.py#L83

List instance actions

---

openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/testing/requests_test.go

For gophercloud#1847
https://docs.openstack.org/api-ref/network/v2/?expanded=list-ports-detail
https://github.com/openstack/neutron-lib/blob/478502b3dfb8c3ff66318169377251826563a398/neutron_lib/api/validators/__init__.py#L514-L551
https://github.com/openstack/neutron-lib/blob/56033ba643812a30577f6ab17648806c2ee494ba/neutron_lib/api/definitions/port.py#L62-L69
https://github.com/openstack/neutron/blob/79e6da0004a0e4e6996d2443121fdf84ae0eb34d/neutron/plugins/ml2/plugin.py#L2241

add fixedIPs filter on network port

---

acceptance/openstack/compute/v2/compute.go

This fixes a dropped error in `acceptance/openstack/compute/v2`.
For #818

acceptance/openstack/compute/v2: Fix Dropped Error

---

acceptance/openstack/identity/v3/identity.go
acceptance/openstack/identity/v3/trusts_test.go
go.mod
openstack/identity/v3/extensions/trusts/doc.go
openstack/identity/v3/extensions/trusts/requests.go
openstack/identity/v3/extensions/trusts/results.go
openstack/identity/v3/extensions/trusts/testing/fixtures.go
openstack/identity/v3/extensions/trusts/testing/requests_test.go
openstack/identity/v3/extensions/trusts/urls.go

Implement Get and List functions for v3/extensions/trusts package
with unit tests and docs.
For #1642 
https://github.com/openstack/keystone/blob/stable/stein/keystone/trust/core.py#L118
https://github.com/openstack/keystone/blob/stable/stein/keystone/api/trusts.py#L197
https://github.com/openstack/keystone/blob/stable/stein/keystone/api/trusts.py#L156

Identity V3: add Trust Get and List funcions

---

acceptance/openstack/identity/v3/trusts_test.go
openstack/identity/v3/extensions/trusts/results.go
openstack/identity/v3/extensions/trusts/testing/fixtures.go
openstack/identity/v3/extensions/trusts/testing/requests_test.go

For #1642 
* `deleted_at`: https://github.com/openstack/keystone/blob/04316beecc0d20290fb36e7791eb3050953c1011/keystone/trust/backends/sql.py#L34
* `expires_at`: https://github.com/openstack/keystone/blob/589152d094b248da81dc88db2449fb560985ae8b/keystone/trust/schema.py#L42-L44
I'm not sure why `deleted_at` isn't in `schema.py`, but it's a valid field that shows up in the API response.

Identity v3: Adding ExpiresAt and DeletedAt fields to Trust results

---

openstack/compute/v2/extensions/instanceactions/results.go
openstack/compute/v2/extensions/instanceactions/testing/fixtures.go

For gophercloud#1845
https://docs.openstack.org/api-ref/compute/?expanded=show-server-action-details-detail,list-actions-for-server-detail#show-server-action-details

Get instance action fix

---

acceptance/openstack/compute/v2/compute.go
acceptance/openstack/compute/v2/instance_actions_test.go
acceptance/openstack/compute/v2/network_test.go
openstack/compute/v2/extensions/instanceactions/doc.go
openstack/compute/v2/extensions/instanceactions/request.go
openstack/compute/v2/extensions/instanceactions/results.go
openstack/compute/v2/extensions/instanceactions/testing/request_test.go
openstack/compute/v2/extensions/instanceactions/urls.go

For #1845 
This commit adds support for list params in the instanceactions extension. It also does some documentation cleanup and adds acceptance tests.
* https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/instance_actions.py#L106
* https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/instance_actions.py#L110
* https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/instance_actions.py#L120
/cc @snigle FYI on the breaking function signature for `List`.

Compute v2: InstanceActions ListOpts

---

openstack/networking/v2/extensions/trunks/testing/fixtures.go

For #1876
This fixes two dropped errors in `openstack/networking/v2/extensions/trunks/testing`.

openstack/networking/v2/extensions/trunks/testing: Fix Two Dropped Errors

---

openstack/compute/v2/servers/testing/results_test.go

For #1887
This fixes a dropped error in `openstack/compute/v2/servers/testing`.

openstack/compute/v2/servers/testing: Dropped Error

---

acceptance/openstack/identity/v3/projects_test.go
openstack/identity/v3/projects/doc.go
openstack/identity/v3/projects/requests.go
openstack/identity/v3/projects/results.go
openstack/identity/v3/projects/testing/fixtures.go
openstack/identity/v3/projects/testing/requests_test.go

For #1687
https://github.com/openstack/keystone/blob/fe39838f712880c336e18eadf320e7c9e2007448/keystone/api/projects.py#L111
https://github.com/openstack/keystone/blob/fe39838f712880c336e18eadf320e7c9e2007448/keystone/api/projects.py#L233
https://github.com/openstack/keystone/blob/fe39838f712880c336e18eadf320e7c9e2007448/keystone/api/projects.py#L265
https://github.com/openstack/keystone/blob/fe39838f712880c336e18eadf320e7c9e2007448/keystone/api/projects.py#L490
This pull request adds supports for assocaiting tags to projects using the idenetity v3 APIs. The tags are optional thua llowing backward compatibility with OpenStack versions older than Queens: it is enough to not specify tags when …

Add tags to the identity v3 project

---

acceptance/openstack/client_test.go
openstack/client.go
openstack/identity/v3/extensions/ec2tokens/doc.go
openstack/identity/v3/extensions/ec2tokens/requests.go
openstack/identity/v3/extensions/ec2tokens/testing/requests_test.go
openstack/identity/v3/extensions/ec2tokens/urls.go

Resolves #1898
@jtopjian before I introduce unit tests please take a look on this and let me know your opinion. It is hard to introduce unit tests, since token signature changes every call. I'd prefer to introduce an interface to create, list, delete ec2 credentials, then integrate them with ec2 auth.

Auth: introduce ec2 credentials auth support

---

auth_options.go
openstack/identity/v3/tokens/requests.go
openstack/identity/v3/tokens/testing/requests_test.go

For #1907
https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-scoped-authorization-detail#system-scoped-example
https://github.com/openstack/keystone/blob/f5c9b094af8442219e75265a87551873e058003b/keystone/auth/schema.py#L97-L102

Support system scope in v3 auth

---

acceptance/openstack/identity/v3/credentials_test.go
openstack/identity/v3/extensions/ec2tokens/requests.go
openstack/identity/v3/extensions/ec2tokens/testing/requests_test.go
openstack/identity/v3/extensions/ec2tokens/urls.go

Resolves #1905
@jtopjian this PR is a bit hacky, because if I put s3tokens into a separate package, I need to duplicate a lot of logic.

Keystone V3: Support S3 tokens signature validation

---

openstack/loadbalancer/v2/amphorae/doc.go
openstack/loadbalancer/v2/amphorae/requests.go
openstack/loadbalancer/v2/amphorae/results.go
openstack/loadbalancer/v2/amphorae/testing/fixtures.go
openstack/loadbalancer/v2/amphorae/testing/requests_test.go
openstack/loadbalancer/v2/amphorae/urls.go

For #1911
- Source code: https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/amphora.py#L96
- API doc: https://docs.openstack.org/api-ref/load-balancer/v2/index.html#failover-amphora

Octavia: Failover amphora

---

acceptance/openstack/orchestration/v1/orchestration.go
acceptance/openstack/orchestration/v1/stacktemplates_test.go
acceptance/openstack/orchestration/v1/testdata/samplefile
openstack/orchestration/v1/stacks/template.go
openstack/orchestration/v1/stacks/template_test.go
openstack/orchestration/v1/stacks/utils.go

When get_file is used in a template and the referenced file is not json/yaml,
gophercloud throws a cryptic error: "Data in neither json nor yaml format."
For #1914

Fix orchestration template parsing

---

errors.go
provider_client.go
testing/errors_test.go

Possible usecases include:
- including the X-Openstack-Request-Id when logging the error message
- respecting the Retry-After header when backing off after a 429 response
Solves #1918.

include response headers in ErrUnexpectedResponseCode

---

openstack/identity/v3/tokens/requests.go

The subjectTokenHeaders function accepts a ServiceClient, though
one is never used in the function.
For #1920

Fix subjectTokenHeaders Signature

---

auth_options.go
openstack/auth_env.go
openstack/identity/v3/tokens/requests.go
openstack/identity/v3/tokens/testing/requests_test.go

Resolves #1917
@jtopjian  I didn't find a way to perform tests in multi-step approach https://docs.openstack.org/api-ref/identity/v3/?expanded=multi-step-authentication-2-factor-password-and-totp-example-detail#multi-step-authentication-2-factor-password-and-totp-example
In my case passcodes are generated using a dongle and I can enter them in advance, therefore the auth request sends both password and totp auth requests in one call.
I'll try to add a receipt response handler in further PRs.

Keystone V3: Introduce TOTP (two factor) auth support

---

acceptance/openstack/sharedfilesystems/v2/shares_test.go
openstack/sharedfilesystems/v2/shares/requests.go
openstack/sharedfilesystems/v2/shares/results.go
openstack/sharedfilesystems/v2/shares/testing/fixtures.go
openstack/sharedfilesystems/v2/shares/testing/request_test.go
openstack/sharedfilesystems/v2/shares/urls.go

Resolves #380
[List](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/v2/share_export_locations.py#L44)
[Show](https://github.com/openstack/manila/blob/ea90fd17b8b8297ce79fc2d9afdb4da6138d227b/manila/api/v2/share_export_locations.py#L57)

Manila V2: Add get export location support

---

acceptance/openstack/objectstorage/v1/containers_test.go
acceptance/openstack/objectstorage/v1/objects_test.go
openstack/objectstorage/v1/accounts/results.go
openstack/objectstorage/v1/containers/requests.go
openstack/objectstorage/v1/containers/results.go
openstack/objectstorage/v1/containers/testing/fixtures.go
openstack/objectstorage/v1/containers/testing/requests_test.go
openstack/objectstorage/v1/containers/urls.go
openstack/objectstorage/v1/objects/requests.go
openstack/objectstorage/v1/objects/results.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go
openstack/objectstorage/v1/objects/urls.go
testhelper/convenience.go

Resolves #1721
https://github.com/openstack/swift/blob/a495f1e327fac17246a296721fb1eda8470e4773/swift/common/middleware/bulk.py#L740
Response dict: https://github.com/openstack/swift/blob/a495f1e327fac17246a296721fb1eda8470e4773/swift/common/middleware/bulk.py#L413

Swift: Add "bulk-delete" URL argument support

---

openstack/client.go
openstack/doc.go

For #1948
https://github.com/gophercloud/gophercloud/blob/master/openstack/doc.go#L10
https://github.com/gophercloud/gophercloud/blob/master/openstack/client.go#L72

Fix misleading/typo in openstack client doc

---

openstack/compute/v2/extensions/injectnetworkinfo/doc.go
openstack/compute/v2/extensions/injectnetworkinfo/requests.go
openstack/compute/v2/extensions/injectnetworkinfo/results.go
openstack/compute/v2/extensions/injectnetworkinfo/testing/fixtures.go
openstack/compute/v2/extensions/injectnetworkinfo/testing/requests_test.go
openstack/compute/v2/extensions/resetnetwork/doc.go
openstack/compute/v2/extensions/resetnetwork/requests.go
openstack/compute/v2/extensions/resetnetwork/results.go
openstack/compute/v2/extensions/resetnetwork/testing/fixtures.go
openstack/compute/v2/extensions/resetnetwork/testing/requests_test.go

Resolves #535
* `resetNetwork` - [API](https://docs.openstack.org/api-ref/compute/?expanded=inject-network-information-injectnetworkinfo-action-detail#inject-network-information-injectnetworkinfo-action) [code](https://github.com/openstack/nova/blob/stable/train/nova/api/openstack/compute/admin_actions.py#L40)
* `injectNetworkInfo` - [API](https://docs.openstack.org/api-ref/compute/?expanded=reset-networking-on-a-server-resetnetwork-action-detail#reset-networking-on-a-server-resetnetwork-action) [code](https://github.com/openstack/nova/blob/stable/train/nova/api/openstack/compute/admin_actions.py#L53)

Nova V2: Introduce injectNetworkInfo and resetNetwork server actions support

---

results.go

Core: Fix issue with decoding slices of composed structs

---

openstack/compute/v2/extensions/bootfromvolume/urls.go

according to
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/routes.py#L726
os-volumes_boot is identical to servers routes and it will be deprecated later
https://docs.openstack.org/api-ref/compute/
os-volumes_boot is not listed at all
so switch from os-volumes_boot to servers
For #1974

switch bootfromvolume from os-volumes_boot to servers

---

acceptance/openstack/baremetal/v1/nodes_test.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/testing/requests_test.go

For #1981 
https://github.com/openstack/ironic/blob/master/ironic/conductor/manager.py#L2999
https://github.com/openstack/ironic/blob/master/ironic/common/raid.py#L63
https://github.com/openstack/ironic/blob/master/ironic/drivers/raid_config_schema.json#L59

Modify PhysicalDisks's type to support physical disks hints

---

openstack/baremetalintrospection/httpbasic/doc.go
openstack/baremetalintrospection/httpbasic/requests.go
openstack/baremetalintrospection/httpbasic/testing/requests_test.go

For #1485 
Ironic Inspector introduced a new auth_type http_basic that can
be used in standalone deployments. The code was introduced by the change [1]
This commit adds the support to use the new authentication
type.
[1] https://review.opendev.org/#/c/729463/

Support http_basic auth_strategy for Ironic Inspector

---

acceptance/clients/clients.go
acceptance/clients/conditions.go
acceptance/openstack/baremetal/httpbasic/allocations_test.go
acceptance/openstack/baremetal/httpbasic/doc.go
acceptance/openstack/baremetal/httpbasic/nodes_test.go
acceptance/openstack/baremetal/httpbasic/ports_test.go
openstack/baremetal/httpbasic/doc.go
openstack/baremetal/httpbasic/requests.go
openstack/baremetal/httpbasic/testing/requests_test.go

For #1429 
This PR adds the support to use  Ironic when `auth_strategy` is `http_basic`.
Ironic introduced a new auth_type `http_basic` that can
be used in standalone deployments[1].
This commit adds the support to use the new authentication
type.
The code was introduced by the changes [2] and [3].
[1] https://docs.openstack.org/ironic/latest/install/standalone.html
[2] https://review.opendev.org/727467
[3] https://review.opendev.org/729070

Support http_basic auth_strategy for Ironic

---

openstack/containerinfra/v1/clusters/requests.go
openstack/containerinfra/v1/clusters/testing/requests_test.go

For #1984 
The feature was introduced in OpenStack Magnum by https://review.opendev.org/#/c/720221/

Support `merge_labels` when creating Magnum cluster

---

openstack/baremetalintrospection/v1/introspection/results.go

Fixes tests (and functionality I suspect!) on 32-bit systems.

make introspection.RootDiskType int64 rather than int (#1634)

---

openstack/loadbalancer/v2/listeners/requests.go

For [1991](https://github.com/gophercloud/gophercloud/issues/1991)
- [ListenerPOST](https://github.com/openstack/octavia/blob/f14ccb52ed004f1c30c49e87407f2ce569c045e9/octavia/api/v2/types/listener.py#L116)
- [supported-protocols octavia common](https://github.com/openstack/octavia/blob/77786595e5803488f46e9b4faae02b5bccdfe88d/octavia/common/constants.py#L152)
- [supported-protocol octavia lib common](https://github.com/openstack/octavia-lib/blob/ec7195d713d71370fa6a72d3839253b9789b3b4e/octavia_lib/common/constants.py#L141)

support TERMINATED_HTTPS protocol for listeners

---

openstack/compute/v2/servers/requests.go

Addresses https://github.com/gophercloud/gophercloud/issues/2003.

Remove unused ServiceClient from servers.CreateOpts

---

openstack/compute/v2/extensions/schedulerhints/requests.go
openstack/compute/v2/extensions/schedulerhints/testing/requests_test.go

The TargetCell filter from cells v1 is supported in the code base but
support for the DifferentCell filter was never added. DifferentCell
filter is part of cells v1 but for anyone still using cells v1 this is
useful.
For #2011
https://github.com/openstack/nova/commit/596ee8796a028596e5ea1ad0529aa3f14b6f5934

schedulerhints: support DifferentCell filter

---

acceptance/openstack/loadbalancer/v2/quotas_test.go
openstack/loadbalancer/v2/quotas/doc.go
openstack/loadbalancer/v2/quotas/requests.go
openstack/loadbalancer/v2/quotas/results.go
openstack/loadbalancer/v2/quotas/testing/doc.go
openstack/loadbalancer/v2/quotas/testing/fixtures.go
openstack/loadbalancer/v2/quotas/testing/requests_test.go
openstack/loadbalancer/v2/quotas/urls.go

Add openstack/loadbalancer/v2/quotas.Get.
Add unit and acceptance tests.
For #1826 
* https://github.com/openstack/octavia/blob/bf3d5372b9fc670ecd08339fa989c9b738ad8d69/octavia/api/v2/types/quotas.py
* https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/quotas.py#L43
* https://github.com/openstack/octavia/blob/0b1d8dd5e76edc4b3058a36b47f6c059f970e516/octavia/api/v2/controllers/base.py#L192
<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH,
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>

LoadBalancer V2: add quotas package

---

openstack/messaging/v2/queues/requests.go
openstack/messaging/v2/queues/results.go
openstack/messaging/v2/queues/testing/fixtures.go
openstack/messaging/v2/queues/testing/requests_test.go

For #2015 
https://docs.openstack.org/api-ref/message/?expanded=show-queue-details-detail

feat: update Messaging v2 API to support _enable_encrypt_messages field

---

openstack/messaging/v2/queues/requests.go
openstack/messaging/v2/queues/results.go
openstack/messaging/v2/queues/testing/fixtures.go
openstack/messaging/v2/queues/testing/requests_test.go

For #2017 
https://github.com/openstack/zaqar/blob/e12c65a369825ea5469bdb31f5c7151268d7926b/zaqar/transport/wsgi/v2_0/queues.py#L300-L301
https://github.com/openstack/zaqar/blob/e12c65a369825ea5469bdb31f5c7151268d7926b/zaqar/transport/wsgi/v2_0/queues.py#L260-L270

feat: add name and with_count params into listing queues

---

acceptance/openstack/loadbalancer/v2/quotas.go
acceptance/openstack/loadbalancer/v2/quotas_test.go
openstack/loadbalancer/v2/quotas/doc.go
openstack/loadbalancer/v2/quotas/requests.go
openstack/loadbalancer/v2/quotas/results.go
openstack/loadbalancer/v2/quotas/testing/fixtures.go
openstack/loadbalancer/v2/quotas/testing/requests_test.go
openstack/loadbalancer/v2/quotas/urls.go

Add `openstack/loadbalancer/v2/quotas.Update`.
Add unit and acceptance tests.
For #1826 
* https://github.com/openstack/octavia/blob/bf3d5372b9fc670ecd08339fa989c9b738ad8d69/octavia/api/v2/types/quotas.py#L108
* https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/quotas.py#L75
* https://github.com/openstack/octavia/blob/c3ad32d1a8b542adceaf095bbf0e5229cccb3316/octavia/common/data_models.py#L761
I did not implement any handling for `load_balancer` or `health_monitor` for now. Duplicating the values and adding these to the json request too leads to a `400` from API side.
However the not-deprecated way (`loadbalancer` and `healthmonitor`) did work for me on two different …

LoadBalancer V2: implement quotas.Update

---

acceptance/openstack/networking/v2/extensions/layer3/layer3.go
acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
go.sum
openstack/networking/v2/extensions/layer3/routers/doc.go
openstack/networking/v2/extensions/layer3/routers/requests.go
openstack/networking/v2/extensions/layer3/routers/results.go
openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go
openstack/networking/v2/extensions/layer3/routers/urls.go

For https://github.com/gophercloud/gophercloud/issues/2022
API doc:
https://docs.openstack.org/api-ref/network/v2/?expanded=list-l3-agents-hosting-a-router-detail#l3-agent-scheduler
Source code:
https://github.com/openstack/neutron/blob/fefd9a6bb1e5b685d56c75e7a538b0dfc0a959ec/neutron/db/l3_hascheduler_db.py#L44-L55

Add l3agent list for router with HA

---

openstack/containerinfra/v1/clusters/doc.go
openstack/containerinfra/v1/clusters/requests.go
openstack/containerinfra/v1/clusters/results.go
openstack/containerinfra/v1/clusters/testing/fixtures.go
openstack/containerinfra/v1/clusters/testing/requests_test.go
openstack/containerinfra/v1/clusters/urls.go

Currently there is no support for the cluster upgrade-action. This PR implements the missing api-call.
For #2031
API doc:
- https://docs.openstack.org/api-ref/container-infrastructure-management/?expanded=upgrade-a-cluster-detail#upgrade-a-cluster
source from cluster-actions controller:
- https://github.com/openstack/magnum/blob/e8467e94d88b6feb67ff7c167f5e167cd452c772/magnum/api/controllers/v1/cluster_actions.py#L58
- https://github.com/openstack/magnum/blob/e8467e94d88b6feb67ff7c167f5e167cd452c772/magnum/api/controllers/v1/cluster_actions.py#L132

Support Magnum upgrade API

---

openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go

For #2034 
This fixes a dropped test error in `openstack/networking/v2/extensions/layer3/routers/testing`.

openstack/networking: fix dropped test error

---

openstack/compute/v2/servers/requests.go

Add ip, ip6, and user_id to servers.ListOpts
As listed in https://docs.openstack.org/api-guide/compute/server_concepts.html#server-query:
* ip
* ip6 (New in version 2.5)
* user_id (New in version 2.83)
And the CLI documentation:
--ip <ip-address-regex>
Regular expression to match IP addresses
--ip6 <ip-address-regex>
Regular expression to match IPv6 addresses. Note that
this option only applies for non-admin users when
using ``--os-compute-api-version`` 2.5 or greater.
--user <user>         Search by user (admin only) (name or ID)
Note the difference between the user_id docs. My understanding is that
it’s the same as ip6: the option was initially admin-only, and became
generally available with API 2.83 (this is what I have documented).
For #2035
Links to the line numbers/files in the …

Add ip, ip6, and user_id to servers.ListOpts

---

openstack/networking/v2/extensions/layer3/routers/doc.go
openstack/networking/v2/extensions/layer3/routers/requests.go
openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go

This is helpful when it is necessary to rename a router,
but it is not desired by the user to touch the static routes.
The OpenStack API just allows to omit the static routes (e.g.
verifyable with `openstack router set --name new_name --debug`).
This change makes sure that static routes parameter can be omitted with
gophercloud as well.
Also added a unit test.
For #2044
(I could not find a specific line of code, but provided the openstack CLI command for quick verification that this works above)

Networking / routers: Allow updating routers, without specifying the static routes

---

acceptance/openstack/networking/v2/extensions/fwaas/fwaas.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/fwaas_v2.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go
openstack/networking/v2/extensions/fwaas_v2/groups/requests.go
openstack/networking/v2/extensions/fwaas_v2/groups/results.go
openstack/networking/v2/extensions/fwaas_v2/groups/testing/doc.go
openstack/networking/v2/extensions/fwaas_v2/groups/testing/requests_test.go
openstack/networking/v2/extensions/fwaas_v2/groups/urls.go

For #514
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L85-L103
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L307:L322
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/services/firewall/fwaas_plugin_v2.py#L313-L369
**this PR:
Acceptance test for fwaasv2 firewall groups**
kind regards, 
Georg
<sub>Georg Schreiber georg.g.schreiber@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

Fwaasv2 firewall groups acc tests (depends on #2049)

---

openstack/sharedfilesystems/v2/availabilityzones/results.go
openstack/sharedfilesystems/v2/shares/testing/fixtures.go

This removes an unused variable and an unused type from subpackages of `sharedfilesystems/v2`.
For #2034

Prune sharedfilesystems

---

openstack/loadbalancer/v2/pools/requests.go
openstack/loadbalancer/v2/pools/results.go

For #2055
This adds Backup, MonitorAddress, MonitorPort and Tags to member types.
**`CreateMemberOpts`**
[Documentation](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-member-detail#create-member)
[Code](https://github.com/openstack/octavia/blob/198980639cbe02820f90783fa04d5239717ed80d/octavia/api/v2/types/member.py#L87)
**`UpdateMemberOpts`**
[Documentation](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=update-a-member-detail#update-a-member)
[Code](https://github.com/openstack/octavia/blob/198980639cbe02820f90783fa04d5239717ed80d/octavia/api/v2/types/member.py#L100-L104)
**`BatchUpdateMemberOpts`** …

Add missing options to member types

---

openstack/networking/v2/extensions/quotas/doc.go
openstack/networking/v2/extensions/quotas/requests.go
openstack/networking/v2/extensions/quotas/results.go
openstack/networking/v2/extensions/quotas/testing/fixtures.go
openstack/networking/v2/extensions/quotas/testing/requests_test.go
openstack/networking/v2/extensions/quotas/urls.go

* Networking v2: Add Get Detailed Quota for Tenant
* Add GetDetail function for the quotas extension in Gophercloud's OpenStack Networking v2 API
* Add 'trunk' resource in Networking v2 quotas
- Allows a caller to get the list of quota types with in_use, reserved, and limit values for each
- Effectively wraps OpenStack Networking v2 API function /v2.0/quotas/{project_id}/details.json
- Inspired from the Compute API implementation.
- When the 'trunk' extension is enabled, it's possible to set quotas for 
trunks resources, the same way as other networking resources.
For #2060 (detailed quota)
For #2064 (trunk support)
API reference: https://docs.openstack.org/api-ref/network/v2/index.html?expanded=show-quota-details-for-a-tenant-detail#quotas-extension-quotas
Code references:
* (extension) …

Networking v2:  Add Get Detailed Quota for project + 'trunk' extension support

---

openstack/objectstorage/v1/accounts/requests.go
openstack/objectstorage/v1/accounts/testing/fixtures.go
openstack/objectstorage/v1/accounts/testing/requests_test.go
openstack/objectstorage/v1/objects/requests.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go

For #2062
Documentation about metadata handling in middlewares.
https://github.com/openstack/swift/blob/master/doc/source/development_middleware.rst#user-metadata
Actual code that handles `X-Remove-xxx-Meta-name` haders.
https://github.com/openstack/swift/blob/master/swift/proxy/controllers/base.py#L1647
Documentation update account.
https://docs.openstack.org/api-ref/object-store/#create-update-or-delete-account-metadata
> X-Remove-Account-name (Optional) | header | string | Removes the metadata item named name. For example, X-Remove-Account-Meta-Blue removes custom metadata.

Objectstore v1: allow to remove account and object metadata

---

acceptance/openstack/identity/v3/catalog_test.go
openstack/identity/v3/catalog/requests.go
openstack/identity/v3/catalog/results.go
openstack/identity/v3/catalog/testing/catalog_test.go
openstack/identity/v3/catalog/testing/fixtures.go
openstack/identity/v3/catalog/urls.go

For #1719 (one of four requested resources)
Add support of service catalog list
API reference:
https://docs.openstack.org/api-ref/identity/v3/?expanded=get-service-catalog-detail#get-service-catalog
https://github.com/openstack/keystone/blob/stable/victoria/keystone/catalog/core.py#L237

[Identity v3] Add service catalog listing

---

acceptance/openstack/networking/v2/extensions/fwaas_v2/fwaas_v2.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/policy_test.go
openstack/networking/v2/extensions/fwaas_v2/policies/requests.go
openstack/networking/v2/extensions/fwaas_v2/policies/results.go
openstack/networking/v2/extensions/fwaas_v2/policies/testing/doc.go
openstack/networking/v2/extensions/fwaas_v2/policies/testing/requests_test.go
openstack/networking/v2/extensions/fwaas_v2/policies/urls.go
openstack/networking/v2/extensions/fwaas_v2/rules/results.go
openstack/networking/v2/extensions/fwaas_v2/rules/testing/requests_test.go

follow up PR for  #1789 by @Elethiomel (I asked for the permission to get this done)
contains 2 cherry-picks from https://github.com/Daimler/gophercloud/commits/fwaas-v2 by @chrischdi 
For #514
https://github.com/openstack/neutron-lib/blob/56033ba643812a30577f6ab17648806c2ee494ba/neutron_lib/api/definitions/firewall_v2.py#L159
https://github.com/openstack/neutron-fwaas/blob/27906d0acff349c9e5ac7955d203fb2233c295db/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L148
<sub>Georg Schreiber georg.g.schreiber@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

FWaaSv2.0 Policy CRUD

---

acceptance/openstack/blockstorage/v3/snapshots_test.go
openstack/blockstorage/v3/snapshots/doc.go
openstack/blockstorage/v3/snapshots/requests.go
openstack/blockstorage/v3/snapshots/results.go
openstack/blockstorage/v3/snapshots/testing/doc.go
openstack/blockstorage/v3/snapshots/testing/fixtures.go
openstack/blockstorage/v3/snapshots/testing/requests_test.go
openstack/blockstorage/v3/snapshots/urls.go

For #2066 
API:
https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=update-a-snapshot-detail#update-a-snapshot
Schema:
https://github.com/openstack/cinder/blob/482e6a3cc5cca697b54ee1d853a4eca6e6f3cfc7/cinder/api/schemas/snapshots.py#L45
It seems that v3 uses the same method as v2 under the hood:
https://github.com/openstack/cinder/blob/482e6a3cc5cca697b54ee1d853a4eca6e6f3cfc7/cinder/api/v3/snapshots.py#L26
Update api:
https://github.com/openstack/cinder/blob/482e6a3cc5cca697b54ee1d853a4eca6e6f3cfc7/cinder/api/v2/snapshots.py#L148
Additional information:
Acceptance tests were ran against live OpenStack API(Ussuri). Here are logs from its run: …

Block storage: adding support of update snapshot api call

---

acceptance/openstack/loadbalancer/v2/loadbalancer.go
acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
openstack/loadbalancer/v2/l7policies/requests.go
openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/listeners/results.go
openstack/loadbalancer/v2/loadbalancers/doc.go
openstack/loadbalancer/v2/loadbalancers/requests.go
openstack/loadbalancer/v2/loadbalancers/testing/fixtures.go
openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
openstack/loadbalancer/v2/monitors/requests.go
openstack/loadbalancer/v2/pools/requests.go

This adds fully populated load balancer support for Octavia, thus enabling the user to create all entities (lb, pool, member, monitor etc) with a single API call. 
For #1740
https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/load_balancer.py#L500
https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-a-load-balancer-detail#creating-a-fully-populated-loa …

loadbalancer/v2 Support fully populated load balancer

---

openstack/loadbalancer/v2/l7policies/requests.go
openstack/loadbalancer/v2/listeners/requests.go

For #2086
https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/load_balancer.py#L500
https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-a-load-balancer-detail#creating-a-fully-populated-load-balancer

Fixes fully-populated loadbalancer creation without default_pool, l7policies or l7rules

---

acceptance/openstack/clustering/v1/clusters_test.go
openstack/clustering/v1/clusters/requests.go
openstack/clustering/v1/clusters/testing/requests_test.go

For #2088 
https://github.com/openstack/senlin/blob/master/senlin/conductor/service.py#L970
https://docs.openstack.org/api-ref/clustering/?expanded=remove-nodes-from-a-cluster-detail#remove-nodes-from-a-cluster

Return actionID for Node Remove API

---

acceptance/openstack/identity/v3/projects_test.go
openstack/identity/v3/projects/requests.go
openstack/identity/v3/projects/testing/fixtures.go
openstack/identity/v3/projects/testing/requests_test.go
openstack/identity/v3/projects/urls.go

For #1719
Refers
- API Documentation
- https://docs.openstack.org/api-ref/identity/v3/#get-available-project-scopes
- OpenStack Source Code
- https://github.com/openstack/keystone/blob/master/keystone/api/auth.py#L116-L145
Add available project listing
I'm not sure about word `available`, but if this PR is accepted, I think [ListCatalog](https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/catalog/requests.go#L9) should be renamed too 🤔

[Identity v3] Add available project listing

---

openstack/blockstorage/extensions/backups/requests.go
openstack/blockstorage/extensions/backups/testing/fixtures.go
openstack/blockstorage/extensions/backups/testing/requests_test.go
openstack/blockstorage/extensions/backups/urls.go

For #2083 
Here's the API docs:
https://docs.openstack.org/api-ref/block-storage/v3/?expanded=list-backups-with-detail-detail#list-backups-with-detail
Sorry, I'm not sure where to find this in the openstack source.
Also I modified the List tests to not include additional information like `status` - this is what I observed against OVH, and appears to match the docs here: https://docs.openstack.org/api-ref/block-storage/v3/?expanded=list-backups-for-project-detail#list-backups-for-project

Backups list detail #2083

---

openstack/networking/v2/extensions/fwaas_v2/groups/requests.go
openstack/networking/v2/extensions/fwaas_v2/groups/testing/requests_test.go

For #2099
make UpdateOpts.Ports to pointer to allow unsetting it explicitly.
By this change it will be possible to do the same as `openstack firewall group unset --all-ports <id>`.
As long as the Ports field is only a `[]string`:
* whenever I want to set the empty array, the attribute will get dropped due to `omitempty` resulting in not unsetting the value.
* however removing the `omitempty` will result in always having to set the value (and implicitly do a unset, if not setting the attribute, when only updating other values is wanted).
The struct was introduced in https://github.com/gophercloud/gophercloud/pull/2050
We need to be able to unset the value in our openstack, because on our openstack the fwaas group will only be able to get deleted when we get a status of `DOWN`. So we have …

openstack/networking/v2/extensions/fwaas_v2/groups/requests.go 

---

openstack/containerinfra/v1/clusters/doc.go
openstack/containerinfra/v1/clusters/requests.go
openstack/containerinfra/v1/clusters/testing/requests_test.go

Closes https://github.com/gophercloud/gophercloud/issues/2101
* [magnum/api/controllers/v1/cluster.py#L205](https://github.com/openstack/magnum/blob/1cdc0628a28da32ef52324244a4c97b0794c2542/magnum/api/controllers/v1/cluster.py#L205)
* https://github.com/openstack/magnum/commit/946c1d67c73a1b325dadd27018c38555acfee52f

Add support for master_lb_enabled field for clusters

---

openstack/baremetal/v1/nodes/requests.go

For #2105 
ironic now have "JBOD" in raid_config_schema.json. 
https://github.com/openstack/ironic/blob/master/ironic/drivers/raid_config_schema.json#L13

Add RaidLevel "JBOD"

---

openstack/objectstorage/v1/objects/requests.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go

For https://github.com/gophercloud/gophercloud/issues/2107
API doc: 
https://docs.openstack.org/api-ref/object-store/?expanded=get-object-content-and-metadata-detail,show-container-details-and-list-objects-detail#get-object-content-and-metadata
Source code: https://github.com/openstack/swift/blob/ed990999170e7789dc6e32f299c0a3818636d9ea/swift/common/swob.py#L903-L904

swift: support modified-since for cache

---

acceptance/openstack/blockstorage/v3/quotaset_test.go
openstack/blockstorage/extensions/quotasets/doc.go
openstack/blockstorage/extensions/quotasets/requests.go
openstack/blockstorage/extensions/quotasets/results.go
openstack/blockstorage/extensions/quotasets/testing/fixtures.go

For #2072 
Api docs:
- https://docs.openstack.org/api-ref/block-storage/v3/?expanded=update-quotas-for-a-project-detail#quota-sets-extension-os-quota-sets
- https://github.com/openstack/cinder/blob/0fe910f130161edf5025d59020093ae163dfcba5/cinder/quota.py#L1157
- https://github.com/openstack/cinder/blob/0fe910f130161edf5025d59020093ae163dfcba5/cinder/quota.py#L1242
- https://github.com/openstack/cinder/blob/0fe910f130161edf5025d59020093ae163dfcba5/cinder/api/contrib/quotas.py#L31
- https://github.com/openstack/cinder/blob/0fe910f130161edf5025d59020093ae163dfcba5/cinder/api/contrib/quotas.py#L192-L275

Add support for blockstorage volume_type quota

---

acceptance/openstack/blockstorage/extensions/extensions.go
acceptance/openstack/blockstorage/extensions/volumeactions_test.go
acceptance/openstack/blockstorage/v3/blockstorage.go
openstack/blockstorage/extensions/volumeactions/doc.go
openstack/blockstorage/extensions/volumeactions/requests.go
openstack/blockstorage/extensions/volumeactions/results.go
openstack/blockstorage/extensions/volumeactions/testing/fixtures.go
openstack/blockstorage/extensions/volumeactions/testing/requests_test.go

For #2110 
Add support for the "os-retype" volumeaction that changes the volume_type of a volume.
The lowe-level implementation of the os-retype is driver specific on cinder. The links below are blobs on the api level.
- [volumeaction](https://github.com/openstack/cinder/blob/876ac4e79fe14887ee3902ef833be5e2273d800b/cinder/api/contrib/volume_actions.py#L293-L303)
- [schema](https://github.com/openstack/cinder/blob/876ac4e79fe14887ee3902ef833be5e2273d800b/cinder/api/schemas/volume_actions.py#L87-L104)
- [volume-api](https://github.com/openstack/cinder/blob/876ac4e79fe14887ee3902ef833be5e2273d800b/cinder/volume/api.py#L1633)

Add support for os-retype volumeaction

---

acceptance/openstack/blockstorage/v3/volumetypes_test.go
openstack/blockstorage/v3/volumetypes/doc.go
openstack/blockstorage/v3/volumetypes/requests.go
openstack/blockstorage/v3/volumetypes/results.go
openstack/blockstorage/v3/volumetypes/testing/fixtures.go
openstack/blockstorage/v3/volumetypes/testing/requests_test.go
openstack/blockstorage/v3/volumetypes/urls.go

Add support for blockstoragev3 volumetype extra_spec operations
such as:
- create extra specs for volume type
- list all extra specs of volume type
- get specific extra spec of volume type
- update specific extra spec of volume type
- delete specific extra spec of volume type
For #649 
CreateExtraSpecs:
- [api_docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-or-update-extra-specs-for-volume-type-detail#volume-types-types)
- [code](https://github.com/openstack/cinder/blob/8456d86c6b9f2f03de4b2b95d56d16d1884ce220/cinder/api/contrib/types_extra_specs.py#L82)
ListExtraSpecs:
- [api_docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=show-a …

blockstoragev3: support extra_spec for volumetypes

---

openstack/networking/v2/extensions/quotas/results.go
openstack/networking/v2/extensions/quotas/testing/fixtures.go

In some conditions, Neutron will JSON-encode quota values as strings
instead of integers.
With this patch, the unmarshaling method is overridden to accept
integers as strings.
See https://bugs.launchpad.net/neutron/+bug/1918565
Fixes #2125

Neutron quota: int-as-string workaround

---

openstack/blockstorage/v3/volumetypes/requests.go

For #649 
Minor patch to volume_type CreateOpts for extra_specs.
[docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-a-volume-type-detail)

blockstorage/v3/volumetypes Extra_specs omitempty

---

openstack/identity/v3/roles/requests.go
openstack/identity/v3/roles/results.go
openstack/identity/v3/roles/testing/fixtures.go
openstack/identity/v3/roles/testing/requests_test.go

Keystone may include names into RoleAssignment entity, if provide include_names=true as query arguemnt
For #2124
https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=id627-detail#id627

Identity: Support include_names query arg in /role_assignments

---

openstack/blockstorage/extensions/availabilityzones/doc.go
openstack/blockstorage/extensions/availabilityzones/requests.go
openstack/blockstorage/extensions/availabilityzones/results.go
openstack/blockstorage/extensions/availabilityzones/testing/doc.go
openstack/blockstorage/extensions/availabilityzones/testing/fixtures.go
openstack/blockstorage/extensions/availabilityzones/testing/requests_test.go
openstack/blockstorage/extensions/availabilityzones/urls.go

For #2134
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/availability_zones.py
https://github.com/openstack/cinder/blob/master/cinder/api/views/availability_zones.py

Add availabilityzones extension for blockstorage

---

openstack/baremetal/apiversions/doc.go
openstack/blockstorage/apiversions/doc.go
openstack/sharedfilesystems/apiversions/doc.go

For #2137 
This is a documentation-only patch.
* The **baremetal** apiversions `doc.go` documented a non-existant "AllPages" method of `ListResult`.
* The **blockstorage** apiversions `doc.go` called `panic` with multiple arguments.
* The **sharedfilesystem** apiversions `doc.go` did not provide an example call.

apiversions: Fix documentation

---

acceptance/openstack/blockstorage/v3/blockstorage.go
acceptance/openstack/blockstorage/v3/volumetypes_test.go
openstack/blockstorage/v3/volumetypes/doc.go
openstack/blockstorage/v3/volumetypes/requests.go
openstack/blockstorage/v3/volumetypes/results.go
openstack/blockstorage/v3/volumetypes/testing/requests_test.go
openstack/blockstorage/v3/volumetypes/urls.go

ListAccesses: List accesses of private volume type
[api docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-private-volume-type-access-detail-detail#volume-type-access-types-action-types-os-volume-type-access)
[code](https://github.com/openstack/cinder/blob/facc1fc014a2f94a9e2767588da7e2f4ff73e3c5/cinder/api/contrib/volume_type_access.py#L41)
AddAccess: Add access of project to volume type
[api docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=add-private-volume-type-access-to-project-detail#volume-type-access-types-action-types-os-volume-type-access)
[code](https://github.com/openstack/cinder/blob/facc1fc014a2f94a9e2767588da7e2f4ff73e3c5/cinder/api/contrib/volume_type_access.py#L99)
RemoveAccess: Remove access of project from …

Add support for volume type access

---

acceptance/openstack/blockstorage/v3/blockstorage.go
acceptance/openstack/blockstorage/v3/qos_test.go
openstack/blockstorage/v3/qos/doc.go
openstack/blockstorage/v3/qos/requests.go
openstack/blockstorage/v3/qos/results.go
openstack/blockstorage/v3/qos/testing/doc.go
openstack/blockstorage/v3/qos/testing/fixtures.go
openstack/blockstorage/v3/qos/testing/requests_test.go
openstack/blockstorage/v3/qos/urls.go

For #2139 
Create:
Return code on doc is wrong, and parameters other than `name` are missing. Code showcases more how consumer and specs are used.
[docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-a-qos-specification-detail#quality-of-service-qos-specifications-qos-specs)
[code_schema](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/api/schemas/qos_specs.py#L19) [code_api](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/api/contrib/qos_specs_manage.py#L79) [code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L36)
Delete:
[docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=delete-a-qos- …

blockstorage/v3: Add support for create/delete qos

---

openstack/networking/v2/extensions/networkipavailabilities/doc.go

This is a documentation-only patch.
For #2144

networking/v2: fix documentation for extensions/networkipavailabilities

---

openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/listeners/results.go

For #2148 
Add support for SCTP protocol on octavia listener.
[api-ref-docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#create-listener)
[code](https://github.com/openstack/octavia/blob/4e53676b2a4f8e97b8c2412436813d890b67672f/octavia/common/constants.py#L218) [code](https://github.com/openstack/octavia-lib/blob/3208f7fbcae31f84f0d8b0ff05ef63f5f7f2a075/octavia_lib/common/constants.py#L141-L145) [code](https://github.com/openstack/octavia/blob/4e53676b2a4f8e97b8c2412436813d890b67672f/octavia/api/v2/types/listener.py#L114)

Add SCTP protocol on octavia listener

---

acceptance/openstack/loadbalancer/v2/loadbalancer.go
openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/listeners/results.go
openstack/loadbalancer/v2/listeners/testing/fixtures.go
openstack/loadbalancer/v2/listeners/testing/requests_test.go

For #2128 
Update Create, Update to support tls_versions
[docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#create-listener)
[microversion](https://github.com/openstack/octavia/blob/4e53676b2a4f8e97b8c2412436813d890b67672f/octavia/api/root_controller.py#L118) 
[create type](https://github.com/openstack/octavia/blob/9389d5c0d94cb0575f34e800c5b77a982aac9546/octavia/api/v2/types/listener.py#L153) [update_type](https://github.com/openstack/octavia/blob/9389d5c0d94cb0575f34e800c5b77a982aac9546/octavia/api/v2/types/listener.py#L194)
[validate func](https://github.com/openstack/octavia/blob/9389d5c0d94cb0575f34e800c5b77a982aac9546/octavia/common/validate.py#L466) [validate const](https://github.com/openstack/octavia/blob/9389d5c0d94cb0575f34e800c5b77a982aa …

Add support for loadbalancer listener tls versions

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go

This field was added in microversion 1.66 and appears in the Victoria release.
For #2153
https://opendev.org/openstack/ironic/src/branch/master/ironic/api/controllers/v1/node.py#L161-L165
https://review.opendev.org/c/openstack/ironic/+/687910/

baremetal: add network_data to Node interface

---

openstack/loadbalancer/v2/pools/requests.go

For #2157 
[docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-pool-detail#create-pool)
[code version](https://github.com/openstack/octavia/blob/16e83eef0154a30ef91fb09842bf009c540f1c66/octavia/api/root_controller.py#L133-L138)
[type check](https://github.com/openstack/octavia/blob/16e83eef0154a30ef91fb09842bf009c540f1c66/octavia/api/v2/types/pool.py#L207), [type check](https://github.com/openstack/octavia/blob/16e83eef0154a30ef91fb09842bf009c540f1c66/octavia/api/v2/types/pool.py#L153)
[const](https://github.com/openstack/octavia-lib/blob/3208f7fbcae31f84f0d8b0ff05ef63f5f7f2a075/octavia_lib/common/constants.py#L148-L150)

Add SCTP and PROXYV2 protocol for octavia pools

---

acceptance/openstack/placement/v1/resourceproviders_test.go
openstack/placement/v1/resourceproviders/doc.go
openstack/placement/v1/resourceproviders/requests.go
openstack/placement/v1/resourceproviders/results.go
openstack/placement/v1/resourceproviders/testing/fixtures.go
openstack/placement/v1/resourceproviders/testing/requests_test.go
openstack/placement/v1/resourceproviders/urls.go

For #526
API doc:
https://docs.openstack.org/api-ref/placement/?expanded=list-resource-provider-usages-detail#list-resource-provider-allocations
API code:
https://github.com/openstack/placement/blob/2150dbf6880c379b52035b604c51048743c446a5/placement/handlers/allocation.py#L271

Add resource provider allocations API for placement

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go

A few bios interface fields are in the Ironic API but were missing from
the Ironic API documentation and not included in gophercloud. This
change adds in the bios interface to the node create, node list,
and node driver validation APIs.
For #[2163]
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L143
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L1225
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/utils.py#L1262

Add missing bios interface fields to Ironic API

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/nodes/urls.go

For #2165.
The baremetal bios endpoint has been available in the Ironic API since
version 1.40 and is documented in the API reference here -
https://docs.openstack.org/api-ref/baremetal/?expanded=#node-bios-nodes.
It provides a list of all bios settings by node or a particular setting on a node.
The ironic API code is here:
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/bios.py#L57

Add support for baremetal bios endpoint

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go
openstack/baremetal/v1/nodes/testing/requests_test.go

For #2166
A recent change to Ironic
(https://review.opendev.org/c/openstack/ironic/+/786707) has added
support for bios registry fields in the Ironic API for microversion 1.74. 
These can be retrieved using the `?detail=True` option when listing
all settings. The fields are also included when getting individual
settings without any options.

Add support for additional bios settings fields in Ironic

---

acceptance/openstack/blockstorage/v3/qos_test.go
openstack/blockstorage/v3/qos/doc.go
openstack/blockstorage/v3/qos/requests.go
openstack/blockstorage/v3/qos/results.go
openstack/blockstorage/v3/qos/testing/fixtures.go
openstack/blockstorage/v3/qos/testing/requests_test.go
openstack/blockstorage/v3/qos/urls.go

For #2139 
[docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-qos-specifications-detail#quality-of-service-qos-specifications-qos-specs)
[code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/api/contrib/qos_specs_manage.py#L58) [code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L233)

blockstorage/v3: Add support for list qos

---

acceptance/openstack/compute/v2/compute.go
acceptance/openstack/compute/v2/volumeattach_test.go
openstack/compute/v2/extensions/volumeattach/requests.go
openstack/compute/v2/extensions/volumeattach/results.go
openstack/compute/v2/extensions/volumeattach/testing/fixtures.go
openstack/compute/v2/extensions/volumeattach/testing/requests_test.go

For #2176 
Add 2 new request and respond fields for volumeattach.
tag => added on 2.49 =>https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#id45
delete_on_termination => added on 2.79 => https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-train
[docs](https://docs.openstack.org/api-ref/compute/?expanded=attach-a-volume-to-an-instance-detail#attach-a-volume-to-an-instance)
[schema](https://github.com/openstack/nova/blob/052cf963583ab7c6bbe4fcbf7bfe69f8f6733bdb/nova/api/openstack/compute/schemas/volumes.py#L87) [schema](https://github.com/openstack/nova/blob/052cf963583ab7c6bbe4fcbf7bfe69f8f6733bdb/nova/api/validation/parameter_types.py#L463)
[create](https://github.com/openstack/nova/blob/052cf963583ab7c6bbe4fcbf7bfe69f8f6733 …

Add tag and delete_on_termination for nova volumeattach

---

openstack/db/v1/instances/results.go
openstack/db/v1/instances/testing/fixtures.go
openstack/db/v1/instances/testing/requests_test.go

Closes: #2178
- API response example for getting trove instance :
https://docs.openstack.org/api-ref/database/?expanded=show-database-instance-details-detail#id52
- Trove code for getting instance addresses:
https://github.com/openstack/trove/blob/b050996b9f6df738a0f68ac36a5b5f17f8bb2bc2/trove/instance/models.py#L170

Trove: Support to return Trove instance addresses

---

openstack/compute/v2/servers/requests.go

For #2188 
nova: add support query hosts with availability-zone parameter
Filter the server list result by server availability zone.
This parameter is restricted to administrators until microversion 2.83. If non-admin users specify this parameter on a microversion less than 2.83, it will be ignored.

nova: support query hosts with availability-zone

---

acceptance/openstack/sharedfilesystems/v2/shares_test.go

For #1801 
This PR is to troubleshoot the issues seen with the Shared Filesystem access tests.

Acc Tests: Enable Shared Filesystem access tests

---

openstack/compute/v2/servers/requests.go

Closes #2192.
code in this PR: Links are given in the issue.
---
I was going to extend the tests to handle this attribute, but there are no tests at all that actually cover the `networks` attribute of server creation requests, so I hope this change is okay as-is.

add `tag` attribute to servers.Network

---

openstack/baremetal/v1/nodes/doc.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/nodes/urls.go

For #1429 
This PR adds support for the following vendor passthru methods:
- create_subscription
- delete_subscription
- get_subscription
- get_all_subscriptions
This methods are only supported by redfish implementations in ironic
that are using the vendor passthru.
Introduced in Ironic in  [change 801064](https://review.opendev.org/c/openstack/ironic/+/801064)

Vendor Passthru support for Subscriptions

---

openstack/blockstorage/extensions/volumehost/doc.go
openstack/blockstorage/extensions/volumehost/results.go
openstack/blockstorage/v3/volumes/testing/fixtures.go
openstack/blockstorage/v3/volumes/testing/requests_test.go

The os-vol-host-attr is returned by OpenStack API;
let's add an extension to allow using this value.
Fixes #2211.

Add block volume extension for os-vol-host-attr

---

openstack/compute/v2/servers/results.go

Add to the Server type the list of server groups the server is part of,
as exposed in microversions 1.71 and above as "server_groups".
For #2216
Here are the docs describing the property of the API object "server": https://docs.openstack.org/api-ref/compute/?expanded=show-server-details-detail#show-server-details
* https://github.com/openstack/nova/blob/d2a5fe5621d6ff1ae8ba5087049e0c4347592cf6/nova/api/openstack/compute/servers.py#L454-L455
* https://github.com/openstack/nova/blob/52cae8801de9229d6cfb7871c2073b83b3e41b81/nova/api/openstack/compute/views/servers.py#L420-L423

compute: Add ServerGroup property to Server

---

acceptance/openstack/imageservice/v2/images_test.go
openstack/imageservice/v2/images/requests.go
openstack/imageservice/v2/images/testing/fixtures.go
openstack/imageservice/v2/images/testing/requests_test.go

Now we should be able to do something like:
```
updateOpts := images.UpdateOpts{
images.ReplaceImageProtected{
NewProtected: false,
},
}
image, err = images.Update(client, imageID, updateOpts).Extract()
```
Fixes https://github.com/gophercloud/gophercloud/issues/2220

Image Service v2: Add Updating image.Protected field

---

errors.go

This change exposes the error message of NotFound error from openstack
API, this is helpful to find out the reason of request failure.
For #2222

Expose the real error message of NotFound error

---

openstack/baremetal/v1/nodes/doc.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/testing/fixtures.go
openstack/baremetal/v1/nodes/testing/requests_test.go

For #1429
This commit adds support for HttpHeaders in the create_subscription. (#2201)
It was added during the Xena release of Ironic in [1] after the
initial support for create subscriptions [2]
We don't need to modify the response of get_subscription because
redfish doesn't return the value of the HttpHeaders for the enduser.
[1] https://review.opendev.org/c/openstack/ironic/+/806859
[2] https://review.opendev.org/c/openstack/ironic/+/801064

Support HttpHeaders in create_subscription

---

README.md

For the better or for the worse, the Go ecosystem has now migrated to
using modules.
For #2247

README: Remove reference to godep

---

go.sum

This is the result of running `go mod tidy`.

go.mod: Remove unused packages

---

openstack/loadbalancer/v2/monitors/requests.go
openstack/loadbalancer/v2/monitors/results.go

octavia: add new pool monitor types

---

.github/PULL_REQUEST_TEMPLATE

There are multiple keywords to close related issue when merging a pull
request [1], and `For` wasn't one of them.
[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Fixes #2269

Use keyword to automatically close related issue

---

acceptance/openstack/blockstorage/v3/qos_test.go
openstack/blockstorage/v3/qos/doc.go
openstack/blockstorage/v3/qos/requests.go
openstack/blockstorage/v3/qos/results.go
openstack/blockstorage/v3/qos/testing/fixtures.go
openstack/blockstorage/v3/qos/testing/requests_test.go
openstack/blockstorage/v3/qos/urls.go

Partially implements: #2139 
Implements `Get`, `Update` and `DeleteKeys`
`Get`: [api docs](https://docs.openstack.org/api-ref/block-storage/v3/?expanded=show-a-qos-specification-details-detail#quality-of-service-qos-specifications-qos-specs), [code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L241)
`Update`: [api docs](https://docs.openstack.org/api-ref/block-storage/v3/?expanded=set-keys-in-a-qos-specification-detail#quality-of-service-qos-specifications-qos-specs) [schema](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/api/schemas/qos_specs.py#L40), …

blockstorage/v3/qos Add Get, Update and Delete Keys

---

.zuul.yaml

It'll be useful when we'll start testing
https://github.com/gophercloud/gophercloud/pull/2241.
This patch will install devstack with dynamic routing on the networking
job.

zuul/networking job: enable Neutron Dynamic Routing service

---

acceptance/openstack/blockstorage/v3/qos_test.go
openstack/blockstorage/v3/qos/doc.go
openstack/blockstorage/v3/qos/requests.go
openstack/blockstorage/v3/qos/results.go
openstack/blockstorage/v3/qos/testing/fixtures.go
openstack/blockstorage/v3/qos/testing/requests_test.go
openstack/blockstorage/v3/qos/urls.go

Fixes #2139 
- [docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-attachment-detail,associate-qos-specification-with-a-volume-type-detail#quality-of-service-qos-specifications-qos-specs)
- [code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L150-L230) => Note: Docs are wrong on the return type of ListAssociations, its `association_type` instead of `type` as shown [here](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L165)

Associate, Disassociate, Disassociate_all and ListAssociations for blockstorage/v3/qos

---

.github/workflows/gomod.yml

Errors if dependencies were modified and `go mod tidy` was not run
before push.

actions: add a go mod tidy check

---

openstack/networking/v2/extensions/security/rules/requests.go

Add option "Any" in security group rules, according the [documentation](https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/security-group-rule.html#cmdoption-openstack-security-group-rule-create-protocol):
```bash
Network version 2:
IP protocol (ah, dccp, egp, esp, gre, icmp, igmp, ipv6-encap, ipv6-frag, ipv6-icmp, ipv6-nonxt, ipv6-opts, ipv6-route, ospf, pgm, rsvp, sctp, tcp, udp, udplite, vrrp and integer representations [0-255] or any; default: any (all protocols))
```
Fixes #2309
In code neutron `None` - wildcard, but in documentation it mention as  `any`
https://github.com/openstack/python-openstackclient/commit/82f45d9bd203aee77914c1f9e300f7dbedf673c8 …

Add Missing Neutron v2 Protocol Constant "any"

---

acceptance/openstack/identity/v3/projectendpoint_test.go
openstack/identity/v3/extensions/projectendpoints/doc.go
openstack/identity/v3/extensions/projectendpoints/requests.go
openstack/identity/v3/extensions/projectendpoints/results.go
openstack/identity/v3/extensions/projectendpoints/testing/doc.go
openstack/identity/v3/extensions/projectendpoints/testing/requests_test.go
openstack/identity/v3/extensions/projectendpoints/urls.go

Fixes #2303
https://docs.openstack.org/api-ref/identity/v3-ext/?expanded=list-associations-by-project-detail#list-associations-by-project
https://github.com/openstack/keystone/blob/ba2e4b83e88d5c1576e9d2cd6a760367deef3a62/keystone/api/os_ep_filter.py#L145-L154

Identity v3: add support for OS-EP-FILTER (endpoint) extension #2303

---

script/acceptancetest

Since we now redirect the output to a log file, we need to enable
pipefail otherwise RC will always be 0 which is wrong if tests fail.

acceptance: add pipefail to `acceptancetest` script

---

.github/workflows/functional-baremetal.yaml
.zuul.yaml
acceptance/clients/conditions.go
acceptance/openstack/baremetal/httpbasic/nodes_test.go
acceptance/openstack/baremetal/noauth/nodes_test.go
acceptance/openstack/baremetal/v1/nodes_test.go

* Deploy Devstack with Ironic
* Run acceptance/openstack/baremetal
* Replace the previous CI job managed in Zuul

[CI-v2] Replace baremetal job with Github Action

---

.github/workflows/functional-identity.yaml
acceptance/openstack/identity/v3/applicationcredentials_test.go
acceptance/openstack/identity/v3/identity.go
acceptance/openstack/identity/v3/oauth1_test.go
acceptance/openstack/identity/v3/projects_test.go
acceptance/openstack/identity/v3/roles_test.go
acceptance/openstack/identity/v3/trusts_test.go

* Deploy Devstack with Keystone
* Run acceptance/openstack/identity/v3
* Fix test for roles: we were creating a role with a random name and not
taking in consideration that CreateOpts could contain a Name. Also, we
were creating the role in the default domain but this is problematic
because right now Gophercloud is not able to delete a role in a
specific domain. This is a feature that will need to be added (issue
#2321)
Note: we don't have CI coverage for v2 API because it was removed long
time ago (in Pike): https://docs.openstack.org/releasenotes/keystone/pike.html#deprecation-notes

[CI-v2] Add identity job with Github Action

---

.github/workflows/functional-compute.yaml
acceptance/openstack/compute/v2/aggregates_test.go
acceptance/openstack/compute/v2/instance_actions_test.go
acceptance/openstack/compute/v2/keypairs_test.go
acceptance/openstack/compute/v2/migrate_test.go
acceptance/openstack/compute/v2/quotaset_test.go
acceptance/openstack/compute/v2/servergroup_test.go
acceptance/openstack/compute/v2/servers_test.go
acceptance/openstack/compute/v2/services_test.go
acceptance/openstack/compute/v2/usage_test.go

* Deploy Devstack with Nova and Cinder
* Run acceptance/openstack/compute
* Fix aggregate test to a hostname instead of the FQDN. Nova takes
hostname: https://github.com/openstack/nova/blob/master/nova/compute/api.py#L6454
* Skip UsageTest and will fix later. The test doesn't pass for now, the
usage is null everywhere we need to figure out why.
* Switch QuotaSet tests to use API v3 of Keystone instead of v2, which
was removed in previous versions of OpenStack.
* Unskip all tests except `TestUsageSingleTenant` which seems complicated and potentially broken at API level, so we test almost everything :-)

[CI-v2] Add compute job with Github Action

---

openstack/loadbalancer/v2/l7policies/requests.go
openstack/loadbalancer/v2/l7policies/results.go

Add REDIRECT_PREFIX and REDIRECT_HTTP_CODE to l7policy
CreateOpts and UpdateOpts.
Docs: https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-an-l7-policy-detail,update-a-l7-policy-detail#create-an-l7-policy
Fixes: #2322

Update loadbalancer/v2/l7policies create and update

---

.github/workflows/functional-networking.yaml
acceptance/openstack/networking/v2/extensions/agents/agents_test.go
acceptance/openstack/networking/v2/extensions/attributestags_test.go
acceptance/openstack/networking/v2/extensions/dns/dns.go
acceptance/openstack/networking/v2/extensions/dns/dns_test.go
acceptance/openstack/networking/v2/extensions/fwaas/firewall_test.go
acceptance/openstack/networking/v2/extensions/fwaas/policy_test.go
acceptance/openstack/networking/v2/extensions/fwaas/rule_test.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/fwaas_v2.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/policy_test.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/rule_test.go
acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
acceptance/openstack/networking/v2/extensions/lbaas/members_test.go
acceptance/openstack/networking/v2/extensions/lbaas/monitors_test.go
acceptance/openstack/networking/v2/extensions/lbaas/pools_test.go
acceptance/openstack/networking/v2/extensions/lbaas/vips_test.go
acceptance/openstack/networking/v2/extensions/lbaas_v2/l7policies_test.go
acceptance/openstack/networking/v2/extensions/lbaas_v2/listeners_test.go
acceptance/openstack/networking/v2/extensions/lbaas_v2/loadbalancers_test.go
acceptance/openstack/networking/v2/extensions/lbaas_v2/monitors_test.go
acceptance/openstack/networking/v2/extensions/lbaas_v2/pools_test.go
acceptance/openstack/networking/v2/extensions/mtu/mtu_test.go
acceptance/openstack/networking/v2/extensions/qos/policies/policies_test.go
acceptance/openstack/networking/v2/extensions/qos/rules/rules_test.go
acceptance/openstack/networking/v2/extensions/qos/ruletypes/ruletypes_test.go
acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent_test.go
acceptance/openstack/networking/v2/extensions/vpnaas/service_test.go
acceptance/openstack/networking/v2/extensions/vpnaas/siteconnection_test.go

* Deploy Devstack with Neutron
* Run acceptance/openstack/networking
* Unskip a lot of tests
* Do not test FWaaS v1, too old and will be removed from Gophercloud via #2320
* Skip FWAAS v2 testing after Ussuri (service was removed); and deploy it only on
Ussuri and Train, so it can still be tested.
* Fix a test for FWAAS, where ICMP rule can't have a port in source
* Skip TestAgentsRUD because it can't work with OVN (default in devstack
now). This test will have to be reworked in the future.
* Fix TestDNSPortCRUDL test (some typos)
* Skip TestLayer3RouterAgents because it can't work with OVN (default
in devstack now). This test will have to be rewored in the future.
* Skip TestDNSFloatingIPCRDL which doesn't work with ML2/OVN
* Skip LBAAS (v1 and v2) from …

[CI-v2] Add networking job with Github Action

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml

We thought Github supported usual REGEX syntax but it's not, see:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
So we update the functional workflows so the jobs run when the right
files are modified.

Github workflows: update REGEX to trigger jobs

---

.github/workflows/functional-basic.yaml
.github/workflows/functional-dns.yaml

It's not using regex but instead bash style globbing [1].
Follow-up to #2334.
[1] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

Fix triggers for basic and dns functional workflows

---

acceptance/clients/conditions.go

Re-use a function instead of duplicating the conditions.

conditions: use IsReleases* from SkipReleases*

---

openstack/blockstorage/extensions/schedulerstats/results.go

Fixes #2347
https://docs.openstack.org/cinder/xena/admin/blockstorage-driver-filter-weighing.html#host-stats-for-a-back-end
https://docs.openstack.org/cinder/latest/contributor/api/cinder.scheduler.host_manager.html#cinder.scheduler.host_manager.BackendState.update_from_volume_capability
https://github.com/openstack/cinder/blob/master/cinder/scheduler/host_manager.py#L126

Add allocated_capacity_gb to blockstorage/extensions/schedulerstats

---

openstack/dns/v2/recordsets/results.go

Fixes #2352
https://docs.openstack.org/api-ref/dns/?expanded=list-recordsets-in-a-zone-detail#id81

dns/v2/recordsets: add missing metadata field

---

.zuul.yaml

We've replaced all of the storage jobs with github actions.

zuul: drop storage jobs

---

.github/workflows/functional-dns.yaml

The previous filter would not run the functional-dns job when files
touching the DNS service, under the openstack/dns path, were modified.
This commit fixes it.
We can't use the simpler `**dns**` filter as this would match the files
for the neutron DNS extension which is a different thing.

Fix trigger of functional-dns job

---

acceptance/openstack/placement/v1/placement.go
acceptance/openstack/placement/v1/resourceproviders_test.go
openstack/placement/v1/resourceproviders/doc.go
openstack/placement/v1/resourceproviders/requests.go
openstack/placement/v1/resourceproviders/testing/requests_test.go

Add ParentProviderUUID to placement/v1/resourceproviders createOpts.
Moreover restructure acceptance tests for consistency and for future
additions.
[Docs](https://docs.openstack.org/api-ref/placement/?expanded=create-resource-provider-detail)
Relates to: #526

Add ParentProviderUUID to resourceProvider

---

acceptance/openstack/placement/v1/placement.go
acceptance/openstack/placement/v1/resourceproviders_test.go
openstack/placement/v1/resourceproviders/doc.go
openstack/placement/v1/resourceproviders/requests.go
openstack/placement/v1/resourceproviders/results.go
openstack/placement/v1/resourceproviders/testing/fixtures.go
openstack/placement/v1/resourceproviders/testing/requests_test.go
openstack/placement/v1/resourceproviders/urls.go

[Docs](https://docs.openstack.org/api-ref/placement/?expanded=delete-resource-provider-detail)
Relates to: https://github.com/gophercloud/gophercloud/issues/526
**PR-train**: requires #2356

Add Delete to placement resourceproviders 

---

.github/workflows/unit.yml

See release notes: https://go.dev/doc/go1.18
```
go get no longer builds or installs packages in module-aware mode.
go get is now dedicated to adjusting dependencies in go.mod.
Effectively, the -d flag is always enabled.
To install the latest version of an executable outside the context of the current module,
use go install example.com/cmd@latest.
```
Note: we fallback to `go get` if `go install` didn't work as expected,
since we still run it on Go 1.14.

Stop using `go get` as required by latest golang

---

.github/workflows/greetings.yml

The greetings workflow template for github action didn't have the
permission to comment when the PR originated from a fork [1].
It would return a `Resource not accessible by integration` error as seen
in [2].
We need to use the `pull_request_target` [3] trigger rather than
`pull_request` to allow the workflow to execute in the context of the
target repository.
[1] https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
[2] https://github.com/gophercloud/gophercloud/runs/5881926600?check_suite_focus=true
[3] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

Fix greetings workflow on PRs

---

openstack/loadbalancer/v2/pools/requests.go

This commit added SOURCE_IP_PORT to lb_algorithm options. It is the only
load balancer algorithm supported by OVN.
Fixes https://github.com/gophercloud/gophercloud/issues/2299
[Reference Doc](https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html)

Add SOURCE_IP_PORT as lb_algorithm

---

openstack/networking/v2/extensions/bgp/peers/doc.go
openstack/networking/v2/extensions/bgp/peers/requests.go
openstack/networking/v2/extensions/bgp/peers/results.go
openstack/networking/v2/extensions/bgp/peers/testing/doc.go
openstack/networking/v2/extensions/bgp/peers/testing/fixture.go
openstack/networking/v2/extensions/bgp/peers/testing/requests_test.go
openstack/networking/v2/extensions/bgp/peers/urls.go

Neutron V2: BGP VPNs
For #2209
Add List/Get method for bgp/peers
```
[CL-DESKTOP] 09:51:44 ~/src/github.com/shhgs/gophercloud $ git diff --stat official/master                                                                                                                         
openstack/networking/v2/extensions/bgp/peers/doc.go                   | 32 ++++++++++++++++++++++++++++++++                                                                                                       
openstack/networking/v2/extensions/bgp/peers/requests.go              | 21 +++++++++++++++++++++
openstack/networking/v2/extensions/bgp/peers/results.go               | 78 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ …
```

Neutron v2: BGP Peer list / get

---

.github/workflows/gomod.yml
.github/workflows/reauth-retests.yaml
.github/workflows/unit.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go
acceptance/openstack/networking/v2/extensions/bgp/speakers/doc.go
openstack/networking/v2/extensions/bgp/speakers/doc.go
openstack/networking/v2/extensions/bgp/speakers/requests.go
openstack/networking/v2/extensions/bgp/speakers/results.go
openstack/networking/v2/extensions/bgp/speakers/testing/fixture.go
openstack/networking/v2/extensions/bgp/speakers/testing/requests_test.go
openstack/networking/v2/extensions/bgp/speakers/urls.go

Neutron V2: BGP Dynamic Routing 
For #2208
```
$ git diff --stat HEAD^                                                                    
acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go | 72 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++                                                      
acceptance/openstack/networking/v2/extensions/bgp/speakers/doc.go              |  2 ++
openstack/networking/v2/extensions/bgp/speakers/doc.go                         | 30 ++++++++++++++++++++++++++++++
openstack/networking/v2/extensions/bgp/speakers/requests.go                    | 40 ++++++++++++++++++++++++++++++++++++++++
openstack/networking/v2/extensions/bgp/speakers/results.go                     | 12 ++++++++++++ …
```

Neutron v2: BGP Speaker create / delete 

---

acceptance/openstack/sharedfilesystems/v2/schedulerstats_test.go
acceptance/openstack/sharedfilesystems/v2/services_test.go
acceptance/openstack/sharedfilesystems/v2/shares.go
openstack/sharedfilesystems/v2/schedulerstats/doc.go
openstack/sharedfilesystems/v2/schedulerstats/requests.go
openstack/sharedfilesystems/v2/schedulerstats/results.go
openstack/sharedfilesystems/v2/schedulerstats/testing/fixtures.go
openstack/sharedfilesystems/v2/schedulerstats/testing/requests_test.go
openstack/sharedfilesystems/v2/schedulerstats/urls.go
openstack/sharedfilesystems/v2/services/doc.go
openstack/sharedfilesystems/v2/services/requests.go
openstack/sharedfilesystems/v2/services/results.go
openstack/sharedfilesystems/v2/services/testing/fixtures.go
openstack/sharedfilesystems/v2/services/testing/requests_test.go
openstack/sharedfilesystems/v2/services/urls.go

Fixes #2349
https://docs.openstack.org/api-ref/shared-file-system/?expanded=#list-back-end-storage-pools
https://docs.openstack.org/api-ref/shared-file-system/?expanded=#list-services

Add support for shared-file-system `/v2/services` and `/v2/scheduler-stats/pools`

---

openstack/containerinfra/v1/clusters/results.go
openstack/containerinfra/v1/nodegroups/requests.go
openstack/containerinfra/v1/nodegroups/results.go
openstack/containerinfra/v1/nodegroups/testing/requests_test.go

Fixes #2376
https://github.com/openstack/magnum/blob/20413d0c45dc7a6426072bd889bfb71c73fa62b1/magnum/api/controllers/v1/nodegroup.py#L129-L145
https://github.com/openstack/magnum/blob/20413d0c45dc7a6426072bd889bfb71c73fa62b1/magnum/api/controllers/v1/cluster.py#L187-L203

containerinfra: add a few missing labels fields

---

acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go
openstack/networking/v2/extensions/bgp/peers/doc.go
openstack/networking/v2/extensions/bgp/peers/requests.go
openstack/networking/v2/extensions/bgp/peers/results.go
openstack/networking/v2/extensions/bgp/peers/testing/fixture.go
openstack/networking/v2/extensions/bgp/peers/testing/requests_test.go
openstack/networking/v2/extensions/bgp/peers/urls.go

Neutron V2: BGP Dynamic Routing
For #2208
```
$ git diff --stat official/master                                                                                                                      
acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go | 35 ++++++++++++++++++++++++-----------                                                                                                 
openstack/networking/v2/extensions/bgp/peers/doc.go                      | 14 ++++++++++++++
openstack/networking/v2/extensions/bgp/peers/requests.go                 | 33 ++++++++++++++++++++++++++++++++-
openstack/networking/v2/extensions/bgp/peers/results.go                  |  6 ++++++
openstack/networking/v2/extensions/bgp/peers/testing/fixture.go          | 23 …
```

Neutron v2: BGP Peer Update

---

acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go
acceptance/openstack/networking/v2/extensions/bgp/peers/peers.go
acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go
acceptance/openstack/networking/v2/extensions/bgp/speakers/speakers.go
openstack/networking/v2/extensions/bgp/speakers/doc.go
openstack/networking/v2/extensions/bgp/speakers/requests.go
openstack/networking/v2/extensions/bgp/speakers/results.go
openstack/networking/v2/extensions/bgp/speakers/testing/fixture.go
openstack/networking/v2/extensions/bgp/speakers/testing/requests_test.go
openstack/networking/v2/extensions/bgp/speakers/urls.go

Neutron V2: BGP Dynamic Routing
For #2208
```
$ git diff --stat HEAD^ 
acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go       | 28 +++-------------------------
acceptance/openstack/networking/v2/extensions/bgp/peers/peers.go               | 32 ++++++++++++++++++++++++++++++++
acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go | 89 +++++++++++++++++++++++++++++++++++++++++------------------------------------------------
acceptance/openstack/networking/v2/extensions/bgp/speakers/speakers.go         | 38 ++++++++++++++++++++++++++++++++++++++
openstack/networking/v2/extensions/bgp/speakers/doc.go                         | 42 ++++++++++++++++++++++++++++++++++++++++--
openstack/networking/v2/extensions/bgp/speakers/requests.go …
```

Neutron v2: BGP Speaker Update and Add/Remove BGP Peer

---

errors.go
provider_client.go
testing/errors_test.go

This change introduces additional types to handle 502 Bad Gateway and 504 Gateway Timeout http errors
For #2244 
Related terraform-provider-openstack/terraform-provider-openstack#1303

Add ability to handle 502 and 504 errors

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

That will help to disable Tempest (not needed in our jobs) and therefore
bring back the Ussuri job in good shape.
Issue #2408

CI: Bump devstack-action to v0.7

---

.github/workflows/functional-networking.yaml

The `stable/train` branch no longer exist on opendev's
neutron-dynamic-routing repository, and it caused devstack to fail
installing. Use the github mirror instead that still has the desired
branch.

CI: fix networking job for train release

---

acceptance/openstack/identity/v3/roles_test.go
openstack/identity/v3/roles/requests.go
openstack/identity/v3/roles/testing/fixtures.go
openstack/identity/v3/roles/testing/requests_test.go

Add to Identity v3 role assignments list request `include_subtree` parameter, which allows to get a list of assignments for all projects in the project hierarchy below specified projectID or domainID.
`scope.project.id` is required if `include_subtree` is specified.
[Keystone code with include_subtree query parameter](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/role_assignments.py#L43) .
[API documentation](https://docs.openstack.org/api-ref/identity/v3/?expanded=id627-detail#id627).

Identity v3: add role assignments list param include_subtree

---

.github/workflows/functional-networking.yaml

A follow-up to https://github.com/gophercloud/gophercloud/pull/2413.
It was only a matter of time before the branch sync happened on github
and stable/train disappeared. Let's use the train-eol tag instead.

CI: Fix train networking job

---

LICENSE

Credit the Gophercloud authors

---

.github/workflows/functional-sharedfilesystems.yaml

Because `MANILA_INSTALL_TEMPEST_PLUGIN_SYSTEMWIDE` defaults to true in
manila's devstack plugin [1], we're getting tempest plugin. This is
problematic for us because:
- we don't want to spend extra time installing unneeded dependencies
- this makes it more likely to break, as shown with #2440.
This commit sets `MANILA_INSTALL_TEMPEST_PLUGIN_SYSTEMWIDE` to false in
the Share Filesystems job.
Fixes #2440.
[1] https://opendev.org/openstack/manila/src/commit/205d716/devstack/settings#L208

Do not install tempest in sharedfilesystems jobs

---

acceptance/openstack/networking/v2/networks_test.go
acceptance/openstack/networking/v2/ports_test.go
acceptance/openstack/networking/v2/subnets_test.go
openstack/networking/v2/networks/requests.go
openstack/networking/v2/networks/results.go
openstack/networking/v2/networks/testing/requests_test.go
openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/results.go
openstack/networking/v2/ports/testing/requests_test.go
openstack/networking/v2/subnets/requests.go
openstack/networking/v2/subnets/results.go
openstack/networking/v2/subnets/testing/requests_test.go

The Resource revision numbers extension allows tracking if an object was
updated since it was last retrieved. Add support for revision numbers
for the 3 core networking objects (networks, subnets, ports).
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
Fixes https://github.com/gophercloud/gophercloud/issues/2438
https://docs.openstack.org/api-ref/network/v2/index.html?expanded=list-api-ver …

Add support for standard-attr-revisions to core network components

---

.github/workflows/functional-networking.yaml

neutron-vpnaas recently removed stable/ussuri and stable/train branches.
We now need to use the ussuri-eol and train-eol tags instead when pulling
from the project.
Fixes #2447

Fix train and ussuri networking jobs

---

acceptance/openstack/compute/v2/compute.go
openstack/compute/v2/flavors/requests.go
openstack/compute/v2/flavors/results.go
openstack/compute/v2/flavors/testing/requests_test.go

Add description to flavors which has been added as an optional
attribute since nova 2.55 (Queens).
Fixes #2452 
[Docs](https://docs.openstack.org/api-ref/compute/#create-flavor)

Add description to flavor

---

.github/semver-labels.yaml
.github/workflows/semver-labels.yaml
.github/workflows/semver-require.yaml
.github/workflows/semver-unlabel.yaml

* Define three new labels: `semver:major`, `semver:minor`, `semver:patch`
* Only allow merge if one of the `semver:` labels is present
* Remove the `semver:` label upon new push to the pull request

actions: Add semver tools

---

openstack/networking/v2/extensions/dns/testing/requests_test.go
openstack/networking/v2/extensions/portsbinding/testing/requests_test.go
openstack/networking/v2/ports/results.go
openstack/networking/v2/ports/testing/fixtures.go
openstack/networking/v2/ports/testing/requests_test.go

Older versions of neutron returned times as RFC 3339 "no Z" format. While gophercloud currently supports OpenStack versions from Train and above, all returning the new RFC 3339 time format, there's no reasons to be hostile against older OpenStack releases.
This commit makes the Port.CreatedAt and Port.UpdatedAt fields compatible with older OpenStack releases.
Fixes #2469

Support old time format for port CreatedAt and UpdatedAt

---

openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go

Fixes #2481
- https://github.com/openstack/ironic/blob/9e9a23ef0c06dda467fc275c00c6988e4bcb5ba2/ironic/objects/base.py#L80
- https://github.com/openstack/ironic/blob/master/ironic/objects/node.py#L128

Add createdAt, updatedAt and provisionUpdatedAt fields in Baremetal V1 nodes

---

openstack/networking/v2/ports/results.go

Removing them in 48581dacb7ec726e2ea5ed5094e0bf91db20751b was not necessary. Removing them might break client-side serialisation.

Port CreatedAt and UpdatedAt: add back JSON tags

---

acceptance/openstack/blockstorage/extensions/extensions.go
acceptance/openstack/blockstorage/extensions/volumeactions_test.go
openstack/blockstorage/extensions/volumeactions/requests.go
openstack/blockstorage/extensions/volumeactions/results.go
openstack/blockstorage/extensions/volumeactions/testing/fixtures.go
openstack/blockstorage/extensions/volumeactions/testing/requests_test.go

Fixes #2473
https://github.com/openstack/cinder/blob/d69e89ea3ba63d305f2a344f6c43b83a74d731fc/cinder/api/schemas/volume_actions.py#L206
Support for re-image volume action added.

Implementing re-image volumeaction

---

acceptance/openstack/identity/v3/limits_test.go
openstack/identity/v3/limits/doc.go
openstack/identity/v3/limits/requests.go
openstack/identity/v3/limits/results.go
openstack/identity/v3/limits/testing/fixtures.go
openstack/identity/v3/limits/testing/requests_test.go
openstack/identity/v3/limits/urls.go

For #2289
[docs](https://docs.openstack.org/api-ref/identity/v3/#get-enforcement-model)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L131)

keystone: add v3 limits GetEnforcementModel operation

---

acceptance/openstack/identity/v3/federation_test.go
openstack/identity/v3/extensions/federation/doc.go
openstack/identity/v3/extensions/federation/requests.go
openstack/identity/v3/extensions/federation/results.go
openstack/identity/v3/extensions/federation/testing/fixtures.go
openstack/identity/v3/extensions/federation/testing/requests_test.go
openstack/identity/v3/extensions/federation/urls.go

For #2461
[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#list-mappings)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L267)
After this is reviewed and merged other operations will follow.

keystone: add v3 OS-FEDERATION extension List Mappings

---

openstack/loadbalancer/v2/listeners/requests.go

Prometheus protocol was added for octavia listeners on 2.25
[docs](https://docs.openstack.org/api-ref/load-balancer/v2/#create-listener)
[code](https://github.com/openstack/octavia/blob/master/octavia/api/root_controller.py#L142)

Add Prometheus protocol for octavia listeners

---

openstack/loadbalancer/v2/pools/requests.go

Session persistance can be updated on Octavia. Add it to UpdateOpts
[Docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=update-a-pool-detail#update-a-pool)

Add Persistance for octavia pools.UpdateOpts

---

.github/workflows/functional-loadbalancer.yaml
acceptance/openstack/loadbalancer/v2/loadbalancer.go
acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
openstack/loadbalancer/v2/loadbalancers/requests.go
openstack/loadbalancer/v2/loadbalancers/results.go

VipQosPolicyID can be defined for loadbalancers during creation and update. Moreover add the `neutron-qos` service to loadbalancer workflow.
[Docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-a-load-balancer-detail,update-a-load-balancer-detail#create-a-load-balancer)

Add VipQosPolicyID to loadbalancer Create and Update

---

.github/workflows/unit.yml

We use "go get" to install test dependencies in Go v1.14. As a side
effect, `go.sum` was polluted and `golang.org/x/crypto` was bumped to a
version that is incompatible with Go v1.14.
With this change, installing test dependencies no longer changes the
state of the checked-out repository.

tests: Fix Go v1.14 "go vet"

---

acceptance/openstack/sharedfilesystems/v2/shareaccessrules.go
acceptance/openstack/sharedfilesystems/v2/shareaccessrules_test.go
openstack/sharedfilesystems/v2/shareaccessrules/requests.go
openstack/sharedfilesystems/v2/shareaccessrules/results.go
openstack/sharedfilesystems/v2/shareaccessrules/testing/fixtures.go
openstack/sharedfilesystems/v2/shareaccessrules/testing/requests_test.go
openstack/sharedfilesystems/v2/shareaccessrules/urls.go

This PR adds `Get` for `share-access-rules` Manila API.
Part of https://github.com/gophercloud/gophercloud/issues/2495
https://github.com/openstack/manila/blob/stable/yoga/manila/db/sqlalchemy/api.py#L2591-L2601
https://github.com/openstack/manila/blob/stable/yoga/manila/api/v2/share_accesses.py#L39-L45
https://github.com/openstack/manila/blob/stable/yoga/manila/api/views/share_accesses.py#L50-L62

Manila: add Get for share-access-rules API

---

acceptance/openstack/identity/v3/domains_test.go
openstack/identity/v3/domains/requests.go
openstack/identity/v3/domains/testing/fixtures.go
openstack/identity/v3/domains/testing/requests_test.go
openstack/identity/v3/domains/urls.go

For #1719
Add support to list available domains for user.
API reference:
https://docs.openstack.org/api-ref/identity/v3/#get-available-domain-scopes
https://github.com/openstack/keystone/blob/master/keystone/api/auth.py#L148-L178

[Identity v3] Add available domain listing

---

openstack/objectstorage/v1/containers/results.go
openstack/objectstorage/v1/containers/testing/fixtures.go
openstack/objectstorage/v1/containers/testing/requests_test.go
openstack/objectstorage/v1/objects/results.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go
pagination/http.go
results.go

Some Swift instances respond with HTTP status code 204 when asked to list containers and there are no containers, or when asked to list objects on an empty container. Before this patch, Gophercloud would error because the header `content-type` is absent on the response.
With this patch, objectstorage responses with HTTP status code 204 are immediately recognised as empty and their body is not read.
Potentially supersedes https://github.com/gophercloud/gophercloud/pull/2510

objectstorage: Do not parse NoContent responses

---

openstack/objectstorage/v1/containers/testing/requests_test.go
openstack/objectstorage/v1/objects/testing/requests_test.go
openstack/objectstorage/v1/swauth/testing/requests_test.go

Fix confusing error messages on failing tests. The assertions all required "expected" before "actual" in their arguments.

objectstorage testing: Fix order of assertions

---

CHANGELOG.md

The changelog for v1.1.0 is the curated output of:
```
gh pr list \
--state merged \
--search 'milestone:v1.1.0' \
--json number,title \
--template \
'{{range .}}* {{ printf "[GH-%v](https://github.com/gophercloud/gophercloud/pull/%v)" .number .number }} {{ .title }}
{{end}}'
```

Prepare v1.1.0

---

README.md

Some notes are outdated, we don't use openlab nor vexxhost anymore, we
can remove the notes here to avoid confusion on where our CI is located
now.

README: remove some notes

---

openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/results.go
openstack/networking/v2/ports/testing/fixtures.go
openstack/networking/v2/ports/testing/requests_test.go

Fixes https://github.com/gophercloud/gophercloud/issues/2532
Docs: https://docs.openstack.org/heat/zed/template_guide/openstack.html#OS::Neutron::Port-prop-value_specs
This replaces #2535 because a branch name with `/` is [hard to use with go modules](https://github.com/golang/go/issues/32955#issuecomment-511860346)...

Support value_specs for Ports

---

provider_client.go
testing/provider_client_test.go

Fixes #2511
In addition to this change a new github action will be required to ensure there is no version drift.
This version should stay in-line with the current release of gophercloud

Modify user-agent header to ensure current gophercloud version is provided

---

acceptance/openstack/identity/v3/federation_test.go
openstack/identity/v3/extensions/federation/doc.go
openstack/identity/v3/extensions/federation/requests.go
openstack/identity/v3/extensions/federation/results.go
openstack/identity/v3/extensions/federation/testing/fixtures.go
openstack/identity/v3/extensions/federation/testing/requests_test.go
openstack/identity/v3/extensions/federation/urls.go

For https://github.com/gophercloud/gophercloud/issues/2461
[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#create-a-mapping)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L275)

keystone: add v3 OS-FEDERATION mappings create operation

---

CHANGELOG.md
provider_client.go

* Convert CHANGELOG to Unix EOL
* Add v1.2.0 release notes
* Bump the `DefaultUserAgent` as required by https://github.com/gophercloud/gophercloud/pull/2539

Prepare v1.2.0

---

acceptance/openstack/identity/v3/federation_test.go
openstack/identity/v3/extensions/federation/doc.go
openstack/identity/v3/extensions/federation/requests.go
openstack/identity/v3/extensions/federation/results.go
openstack/identity/v3/extensions/federation/testing/fixtures.go
openstack/identity/v3/extensions/federation/testing/requests_test.go

For https://github.com/gophercloud/gophercloud/issues/2461
[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#get-a-mapping)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L258)

keystone: add v3 OS-FEDERATION mappings get operation

---

.github/workflows/functional-baremetal.yaml

Upstream had EOL-ed the train branch and is no longer accepting fixes. Our patch to fix the installation of virtualbmc with python 3.6 [1] was abandoned. We have no choice than dropping our train job as it's going to permafail and we can't fix it.
[1] https://review.opendev.org/c/openstack/ironic/+/847436
Close #2439

Drop train job for baremetal

---

openstack/objectstorage/v1/containers/errors.go
openstack/objectstorage/v1/containers/requests.go
openstack/objectstorage/v1/containers/testing/fixtures.go
openstack/objectstorage/v1/containers/testing/requests_test.go
openstack/objectstorage/v1/containers/urls.go
openstack/objectstorage/v1/objects/requests.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go
openstack/objectstorage/v1/objects/urls.go
pagination/pager.go
testhelper/convenience.go

As per the [OpenStack object-storage docs](https://docs.openstack.org/api-ref/object-store/#create-container), container names must not contain a slash (`/`).
By accepting them, some functions change their meaning. For example, by passing a container name with a slash to `containers.Create`, it is possible to actually create an object (if the container exists already).
With this patch, objectstorage functions error when called with a containerName containing a slash.
Fixes #2551

objectstorage: Reject container names with a slash

---

README.md

Even though this is a separate package, it's helpful to include some minimal documentation for same here rather than insisting folks root through the gophercloud/utils docs.
Fixes #2557

Expand docs on 'clientconfig' usage

---

openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/results.go
openstack/networking/v2/ports/testing/fixtures.go
openstack/networking/v2/ports/testing/requests_test.go

Fixes #2562 
Docs: https://docs.openstack.org/heat/zed/template_guide/openstack.html#OS::Neutron::Port-prop-propagate_uplink_status

Support propagate_uplink_status for Ports

---

acceptance/openstack/sharedfilesystems/v2/shareaccessrules.go
acceptance/openstack/sharedfilesystems/v2/shareaccessrules_test.go
openstack/sharedfilesystems/v2/shareaccessrules/requests.go
openstack/sharedfilesystems/v2/shareaccessrules/results.go
openstack/sharedfilesystems/v2/shareaccessrules/testing/fixtures.go
openstack/sharedfilesystems/v2/shareaccessrules/testing/requests_test.go
openstack/sharedfilesystems/v2/shareaccessrules/urls.go

This PR adds `List` for `share-access-rules` Manila API.
Part of #2495
https://github.com/openstack/manila/blob/stable/yoga/manila/db/sqlalchemy/api.py#L2621-L2636
https://github.com/openstack/manila/blob/stable/yoga/manila/api/v2/share_accesses.py#L54-L77
https://github.com/openstack/manila/blob/stable/yoga/manila/api/views/share_accesses.py#L32-L35

Manila: add List for share-access-rules API

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

The jobs are running in the Github infra and we should prefer github repos when possible.
Bump devstack-action to v0.10 that changes the default GIT_BASE to point to github repos rather than opendev.
Also change the URL of devstack-plugins to prefer github mirrors over opendev repos.
Hopefully mitigates #2565.

Prefer github mirrors over opendev repos

---

acceptance/openstack/objectstorage/v1/versioning_test.go
openstack/objectstorage/v1/containers/requests.go
openstack/objectstorage/v1/containers/results.go
openstack/objectstorage/v1/containers/testing/fixtures.go
openstack/objectstorage/v1/containers/testing/requests_test.go
openstack/objectstorage/v1/objects/requests.go
openstack/objectstorage/v1/objects/results.go
openstack/objectstorage/v1/objects/testing/fixtures.go
openstack/objectstorage/v1/objects/testing/requests_test.go

Fixes #2181
I focused on functional tests for objects versioning checks, since it requires a lot of duplicate checks in objects unit tests. Hope this is fine.

Swift V1: support object versioning

---

.github/workflows/functional-objectstorage.yaml
acceptance/openstack/objectstorage/v1/versioning_test.go
script/collectlogs

The devstack environment was not setup properly to enable acceptance tests developed for https://github.com/gophercloud/gophercloud/pull/2571.

Enable tests for object versioning

---

acceptance/openstack/identity/v3/federation_test.go
openstack/identity/v3/extensions/federation/doc.go
openstack/identity/v3/extensions/federation/requests.go
openstack/identity/v3/extensions/federation/results.go
openstack/identity/v3/extensions/federation/testing/fixtures.go
openstack/identity/v3/extensions/federation/testing/requests_test.go

For https://github.com/gophercloud/gophercloud/issues/2461
[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#update-a-mapping)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L275)

keystone: add v3 OS-FEDERATION mappings update operation

---

acceptance/openstack/identity/v3/federation_test.go
openstack/identity/v3/extensions/federation/doc.go
openstack/identity/v3/extensions/federation/requests.go
openstack/identity/v3/extensions/federation/results.go
openstack/identity/v3/extensions/federation/testing/fixtures.go
openstack/identity/v3/extensions/federation/testing/requests_test.go

For https://github.com/gophercloud/gophercloud/issues/2461
[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#delete-a-mapping)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L301)

keystone: add v3 OS-FEDERATION mappings delete operation

---

openstack/networking/v2/extensions/provider/doc.go

fix
[issue link](https://github.com/gophercloud/gophercloud/issues/2586)
`Example` are currently missing [Equal sign](https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.2.0/openstack/networking/v2/extensions/provider) in the CreateOpts.
```
createOpts : provider.CreateOptsExt{
CreateOptsBuilder: networkCreateOpts,
Segments:          segments,
}
```
Thank you for your attention to this matter.

fix: Incorrect Documentation

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

This PR adds periodic jobs for the zed release that came out in oct 22. It also reduce the frequency of periodic jobs to run once every 3 days rather than every day.

Add periodic jobs for OpenStack zed release and reduce periodic jobs frequency

---

.github/workflows/functional-clustering.yaml
.github/workflows/functional-messaging.yaml

The zaqar devstack plugin has a workaround for the failing dependency
for ubuntu version 22.04. Let's use this as the runner in those jobs.

CI: workaround mongodb dependency for messaging and clustering master jobs

---

acceptance/openstack/identity/v3/limits_test.go
openstack/auth_env.go
openstack/identity/v3/limits/doc.go
openstack/identity/v3/limits/requests.go
openstack/identity/v3/limits/results.go
openstack/identity/v3/limits/testing/fixtures.go
openstack/identity/v3/limits/testing/requests_test.go
openstack/identity/v3/limits/urls.go

For #2289
[docs](https://docs.openstack.org/api-ref/identity/v3/#create-limits)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L103)

keystone: add v3 limits create operation

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

The Ubuntu 18.04 image for github action runner was deprecated [1]. Ubuntu is is unfortunately the only linux image available as a github action runner and using a more recent version of ubuntu to run the train and ussuri jobs proved to be impracticable [2]. We're forced to retire those jobs.
[1] https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
[2] https://github.com/gophercloud/gophercloud/pull/2585

Drop train and ussuri jobs

---

acceptance/openstack/identity/v3/limits_test.go
openstack/identity/v3/limits/doc.go
openstack/identity/v3/limits/requests.go
openstack/identity/v3/limits/results.go
openstack/identity/v3/limits/testing/fixtures.go
openstack/identity/v3/limits/testing/requests_test.go
openstack/identity/v3/limits/urls.go

For https://github.com/gophercloud/gophercloud/issues/2289
[docs](https://docs.openstack.org/api-ref/identity/v3/#show-limit-details)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L92)

keystone: add v3 limits get operation

---

acceptance/openstack/identity/v3/osinherit_test.go
openstack/identity/v3/osinherit/doc.go
openstack/identity/v3/osinherit/requests.go
openstack/identity/v3/osinherit/results.go
openstack/identity/v3/osinherit/testing/doc.go
openstack/identity/v3/osinherit/testing/fixtures.go
openstack/identity/v3/osinherit/testing/requests_test.go
openstack/identity/v3/osinherit/urls.go

Add PUT/HEAD/DELETE for indentity/v3/OS-INHERIT. Follow the same pattern as normal role assignments for consistency. 
This adds PUT/HEAD/DELETE for all combinations of domain/project and user/group.
[DOCS](https://docs.openstack.org/api-ref/identity/v3/index.html?&#os-inherit)
Fixes #2205 
Each commit adds one API call, thus it is a bit easier to review by reviewing one commit each time

Add PUT/HEAD/DELETE for indentity/v3/OS-INHERIT

---

acceptance/openstack/identity/v3/limits_test.go
openstack/identity/v3/limits/doc.go
openstack/identity/v3/limits/requests.go
openstack/identity/v3/limits/results.go
openstack/identity/v3/limits/testing/fixtures.go
openstack/identity/v3/limits/testing/requests_test.go

For #2289
[docs](https://docs.openstack.org/api-ref/identity/v3/#update-limit)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L115)
This is a base for detail and delete operations code I prepared.

keystone: add v3 limits update operation

---

.github/workflows/unit.yml

Fixes the unit tests when running with go 1.14.

Pin goimport dep to a version that works with go 1.14

---

.github/workflows/functional-basic.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml
acceptance/clients/conditions.go

Some acceptance tests rely on a version comparison to conditionally skip tests. It turns out we were not consistently setting the relevant `OS_BRANCH` environment variable in all the jobs, meaning the version comparison would fail and skip the test.
This PR does two things:
- consistently set the `OS_BRANCH` variable for all our acceptance jobs
- fail the test when the required `OS_BRANCH` variable is not set

Fix version comparison for acceptance tests

---

acceptance/openstack/identity/v3/limits_test.go
openstack/identity/v3/limits/doc.go
openstack/identity/v3/limits/requests.go
openstack/identity/v3/limits/results.go
openstack/identity/v3/limits/testing/fixtures.go
openstack/identity/v3/limits/testing/requests_test.go

For https://github.com/gophercloud/gophercloud/issues/2289
[docs](https://docs.openstack.org/api-ref/identity/v3/#delete-limit)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L124)

keystone: add v3 limits delete operation

---

acceptance/openstack/networking/v2/extensions/trunk_details/trunks_test.go
openstack/networking/v2/extensions/trunk_details/doc.go
openstack/networking/v2/extensions/trunk_details/results.go
openstack/networking/v2/extensions/trunk_details/testing/doc.go
openstack/networking/v2/extensions/trunk_details/testing/fixtures.go
openstack/networking/v2/extensions/trunk_details/testing/requests_test.go

Fixes https://github.com/gophercloud/gophercloud/issues/2624
https://github.com/openstack/neutron-lib/blob/c5ca1ddf420b827e4684dee6a6495475014a91e3/api-ref/source/v2/samples/trunks/trunk-details-show-response.json#L14-L30

neutron: Support trunk_details extension

---

acceptance/openstack/networking/v2/extensions/trunk_details/trunks_test.go

This simply adds a comment pointing to an upstream tracking bug for a workaround in https://github.com/gophercloud/gophercloud/pull/2625.
The bug is https://bugs.launchpad.net/neutron/+bug/2020552
The trunk_details acceptance test works around the bug. The tracking bug should allow somebody to confidently remove the workaround in the future.

Add upstream neutron bug for trunk_details

---

acceptance/clients/conditions.go
acceptance/openstack/sharedfilesystems/v2/replicas.go
acceptance/openstack/sharedfilesystems/v2/replicas_test.go
acceptance/openstack/sharedfilesystems/v2/schedulerstats_test.go
openstack/sharedfilesystems/v2/replicas/requests.go
openstack/sharedfilesystems/v2/replicas/results.go
openstack/sharedfilesystems/v2/replicas/testing/fixtures.go
openstack/sharedfilesystems/v2/replicas/testing/request_test.go
openstack/sharedfilesystems/v2/replicas/urls.go

Fixes #2633 
Looks like devstack doesn't support replicas. Here is the output of local tests:
```
$ go test -run TestReplica -v ./*.go
=== RUN   TestReplicaCreate
tools.go:80: {
"id": "125d64dd-aab9-4e24-8ccb-39dd455d1ba7",
"availability_zone": "zone-1b",
"cast_rules_to_readonly": false,
"host": "",
"share_id": "72a37fa6-20c9-43dc-a463-b802e96044d0",
"share_network_id": "ca0163c8-3941-4420-8b01-41517e19e366",
"share_server_id": "ed15ae66-af5d-4d72-8db2-a1f90a93a260",
"status": "available",
"replica_state": "out_of_sync"
}
replicas.go:54: Deleted replica: 125d64dd-aab9-4e24-8ccb-39dd455d1ba7
shares.go:103: Deleted share: 72a37fa6-20c9-43dc-a463-b802e96044d0
--- PASS: TestReplicaCreate (66.88s)
=== RUN   TestReplicaPromote
tools.go:80: {
"id": "6a39a458-b2ee-468f-b1d9-261db50eec8c", …
```

[manila]: Add Share Replicas support

---

.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-networking.yaml
acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/policy_test.go
acceptance/openstack/networking/v2/extensions/fwaas_v2/rule_test.go

Releases below Victoria are deprecated and not testing.
FWaaS_v2 is not compatible with releases below Zed.
FWaaS_v2 has no support for OVN currently and require openvswitch, Q_ML2_PLUGIN_MECHANISM_DRIVERS, Q_ML2_PLUGIN_TYPE_DRIVERS, Q_ML2_TENANT_NETWORK_TYPE and other custom variables.
Add only FWaaS_V2 workflow.
Skip tests for releases below Zed.
Small fix FWaaS_V2 test variable.
Exclude FWaaS_V2 tests from networking workflow acceptance tests filter.
Fixes #2636

[FWaaS_v2]: Add FWaaS_V2 workflow and enable tests

---

acceptance/openstack/blockstorage/v3/volumetypes_test.go
openstack/blockstorage/v3/volumetypes/doc.go
openstack/blockstorage/v3/volumetypes/requests.go
openstack/blockstorage/v3/volumetypes/results.go
openstack/blockstorage/v3/volumetypes/testing/fixtures.go
openstack/blockstorage/v3/volumetypes/testing/requests_test.go
openstack/blockstorage/v3/volumetypes/urls.go

Add Create/Delete/Update/Get support for encryption of volume types.
Fixes #2641
1.  Create an encryption for a volume type:
* [API Docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-private-volume-type-access-detail-detail#create-an-encryption-type)
* [Code](https://github.com/openstack/cinder/blob/facc1fc014a2f94a9e2767588da7e2f4ff73e3c5/cinder/api/contrib/volume_type_encryption.py#L68)
2.  Update an encryption for a volume type:
* [API Docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-private-volume-type-access-detail-detail#update-an-encryption-type)
* [Code](https://github.com/openstack/cinder/blob/facc1fc014a2f94a9e2767588da7e …

Add CRUD support for encryption in volume v3 types

---

.github/backport-labels.yaml
.github/workflows/backport_v1.yaml
.github/workflows/ensure-labels.yaml
README.md

The stable branch is now `v1`. Non-breaking changes will be backported by applying a `backport-v1` label.

Instrument backporting to v1

---

.github/labels.yaml
.github/semver-labels.yaml
.github/workflows/ensure-labels.yaml

The PR https://github.com/gophercloud/gophercloud/pull/2656 caused all labels to be removed, because each run of the action eliminates all labels that aren't listed.
This PR reintroduces our semver labels and the `good first issue` label in the repository.

chore: Fix labels

---

acceptance/openstack/blockstorage/v3/blockstorage.go
acceptance/openstack/blockstorage/v3/volumes_test.go

Starting from the Queens release, it is possible to attach a volume to
multiple hosts/servers, using a volume type with multiattach capability.
Cinder previously had a `multiattach` parameter that could be passed
during the volume creation. This parameter was recently removed [1], and
caused our jobs to fail.
This commit change the tests to no longer use the removed parameter.
Fixes https://github.com/gophercloud/gophercloud/issues/2657.
[1] https://github.com/openstack/cinder/commit/d4535c77493a7b362091b962f42f2613dea65dbe

tests: run MultiAttach with a capable Cinder Type

---

.github/workflows/codeql-analysis.yml
.github/workflows/ensure-labels.yaml

These jobs should run on all branches, so drop the branch filter that were in place.
For the CodeQL job, it seems like the github action syntax does not allow for a simplified `on` syntax, while at the same time using a `on.schedule`, so drop the periodic that we weren't paying attention to anyway. We have enough signal with just the PR jobs.

[CI] Drop branch filters for 'Ensure Labels' and 'CodeQL' jobs

---

.github/workflows/codeql-analysis.yml
.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Periodic jobs can't run against non-default branches with github action. Remove them from our stable branches to avoid confusion.
According to the github documentation [1]:
Scheduled workflows run on the latest commit on the default or base branch.
[1] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

[v1][CI] Drop periodic jobs from stable branch

---

.github/workflows/ensure-labels.yaml

This workflow should only run on the main branch. The labels are repo-wide and shouldn't be controlled by multiple branches, as there's a risk it removes non-listed labels if the label declaration files differ between branches.
Partially reverts https://github.com/gophercloud/gophercloud/pull/2674/.

Restore branch filter for ensure-labels workflow

---

README.md

We have a shiny new #gophercloud channel on kubernetes slack. Let's advertise it.

Advertise slack channel

---

.github/workflows/backport_v1.yaml

Using a fork is no longer necessary, as watermarks have been removed from the code.
This version bump brings merge commits.

Use git-backporting v4.1.0

---

openstack/blockstorage/v3/volumes/requests.go

The multiattach request parameter is no longer part of the API [1]. Starting with microversion 3.50 (Queens), you need to use a volume type with multiattach capability instead.
Depends on https://github.com/gophercloud/gophercloud/pull/2658.
[1] https://github.com/openstack/cinder/commit/d4535c77493a7b362091b962f42f2613dea65dbe

Cinder: Remove multiatttach request parameter

---

.github/workflows/backport_v1.yaml

We need to use a Personal Access Token (PAT) when creating the backport pull request
because we expect GitHub Actions workflows to be triggered when the pull request is opened.

backport-v1: use PAT token when creating the PR

---

acceptance/openstack/compute/v2/flavors_test.go
openstack/compute/v2/flavors/results.go
openstack/compute/v2/flavors/testing/requests_test.go

Fixes #2497 
Openstack API Ref:
[flavor get](https://docs.openstack.org/api-ref/compute/?expanded=resize-server-resize-action-detail,start-server-os-start-action-detail,create-server-back-up-createbackup-action-detail,show-details-of-specific-api-version-detail,show-flavor-details-detail#show-flavor-details)
nova code Ref:
https://github.com/openstack/nova/blob/5c32d5efe1e1aece48b680474617113c61a248d5/nova/objects/flavor.py#L220
As there is no extra_spec in flavor create's parameter,for acceptance test, I write a test which create extra_spec for a already existed flavor, then compare the get result's extra_spec.  [nova create flavor code](https://github.com/openstack/nova/blob/5c32d5efe1e1aece48b680474617113c61a248d5/nova/api/openstack/compute/flavor_manage.py#L55).

compute: add ext_specs to flavor

---

acceptance/openstack/loadbalancer/v2/loadbalancer.go
acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
openstack/loadbalancer/v2/l7policies/requests.go
openstack/loadbalancer/v2/l7policies/results.go

Tags are supported for octavia l7policy and l7rules since version 2.5. Add support for Create and Update.
[Docs](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-an-l7-policy-detail,update-a-l7-policy-detail,create-an-l7-rule-detail,update-a-l7-rule-detail#create-an-l7-policy)
partially implemets: #2381

Add tags for loadbalancer l7policy and l7rule

---

acceptance/openstack/loadbalancer/v2/loadbalancer.go
openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go
openstack/loadbalancer/v2/pools/requests.go

In order to support members without any subnet, the struct for the pool members need to be CreateMemberOpts.
Fixes #2559
API validation for UUID in octavia:
https://opendev.org/openstack/octavia/src/commit/c2c59f4c9eb9f9ef6081e386bf2bc1badc145241/octavia/api/v2/types/member.py#L127

loadbalancer: Use CreateMemberOpts instead of BatchUpdateMemberOpts in PoolCreateOpts

---

openstack/orchestration/v1/stacks/requests.go
openstack/orchestration/v1/stacks/testing/requests_test.go

Add verbosity to the error signaling a failure in the creation of the optionsmap.

orchestration: Explicit error in optionsmap creation

---

acceptance/openstack/baremetal/v1/conductors_test.go
openstack/baremetal/v1/conductors/doc.go
openstack/baremetal/v1/conductors/requests.go
openstack/baremetal/v1/conductors/results.go
openstack/baremetal/v1/conductors/testing/doc.go
openstack/baremetal/v1/conductors/testing/fixtures.go
openstack/baremetal/v1/conductors/testing/requests_test.go
openstack/baremetal/v1/conductors/urls.go

For #1429 
This commit adds support for the conductor API in Ironic.
- API Ref: https://docs.openstack.org/api-ref/baremetal/?expanded=list-conductors-detail,list-allocations-detail,show-conductor-details-detail#conductors-conductors
- List: https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/conductor.py#L108
- Get: https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/conductor.py#L143

Add conductor API to Baremetal V1

---

openstack/baremetal/inventory/testing/fixtures.go
openstack/baremetal/inventory/testing/types_test.go
openstack/baremetal/inventory/types.go
openstack/baremetalintrospection/v1/introspection/results.go
openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
openstack/baremetalintrospection/v1/introspection/testing/results_test.go

With the introduction of the Ironic inventory API, these types are now shared between Ironic and Inspector. No new functionality here yet, posting it to get the refactoring out of my way. Only the documented parts of the introspection data is migrated, not the Inspector-specific ones.
This change is technically breaking since the code is moved around and can no longer be imported at the old locations.
Part of #2612

Migrate baremetal inventory to a common location

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/nodes/urls.go

The plugin-specific part of the API gets a more sophisticated handling
than it was the case for Inspector: a new opaque type PluginData is used
for handling different formats.
The Ironic-native plugin data format will be introduced later after
some more preparation work is done.
Part of #2612

baremetal: introduce Node Inventory API

---

openstack/baremetal/inventory/plugindata.go
openstack/baremetal/inventory/testing/fixtures.go
openstack/baremetal/inventory/testing/plugindata_test.go
openstack/baremetal/inventory/testing/types_test.go
openstack/baremetal/inventory/types.go
openstack/baremetalintrospection/v1/introspection/results.go
openstack/baremetalintrospection/v1/introspection/testing/fixtures.go
openstack/baremetalintrospection/v1/introspection/testing/results_test.go

This change concerns plugin-specific structures that are shared between
ironic-inspector and the ironic's native inspection.
Names have been shortened for consistency and clarity.
Part of #2612

baremetal: finish moving common inventory bits

---

openstack/networking/v2/ports/requests.go

neutron v2 ports APIs allow to list ports by security group already:
https://docs.openstack.org/api-ref/network/v2/#show-port-details
This patch adds the `SecurityGroups` field to `ListOpts`.
One way to filter the ports by security group can be done with the
following code:
```
listOpts := ports.ListOpts{
SecurityGroups: []string{"2183457b-70cc-4fd0-a2dc-95323fa19e45"}
}
allPages, err := ports.List(networkClient, listOpts).AllPages()
if err != nil {
panic(err)
}
allPorts, err := ports.ExtractPorts(allPages)
if err != nil {
panic(err)
}
for _, port := range allPorts {
fmt.Printf("%+v\n", port)
}
```

networking/v2/ports: allow list filter by security group

---

.github/labels.yaml
.github/workflows/semver-auto.yaml

When testing if a PR is API backward compatible or not, we need to test
against the base branch, not the head against the PR branched is based
on.
Otherwise it can lead to the case where a breaking change was merged
after that a PR was proposed, go-apidiff will fail because it'll test
the repo against base_ref.
The PR needs to be rebased on base_ref so the actual compatibility can be
verified.
If the PR can't be rebase for any reason, we'll return a failure and add
the label `semver:unknown`.

workflow/semver-auto: rebase PR

---

.github/workflows/semver-auto.yaml

A caracter is missing for the rebase action in git ref.

CI: Fix a typo in semver-auto

---

.github/workflows/semver-auto.yaml

I haven't found an action that just runs a rebase without pushing it
into the repo.
Let's just run `git rebase -i` for now.

semver-auto: manual rebase instead of external action

---

.github/workflows/semver-auto.yaml

Change the tasks order, so we clean semver labels first.
This avoids the case when the rebase failed, and we still have the old
label, and also the `semver:unknown`, which is confusing.

semver-auto: remove labels first

---

.github/workflows/semver-auto.yaml

To avoid the `*** Please tell me who you are` error when a PR is locally
rebased to find out which semver label to apply, let's just set fake
user.email and user.name, which aren't used anyway since the PR isn't
actually rebased, but just for the workflow so we can run `go-apidiff`
which itself requires code to be committed.

semver-auto: tell who we are during rebase

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml
acceptance/openstack/blockstorage/v3/volumeattachments.go

- add `antelope` release in the matrix
- switch master jobs to run on ubuntu 22.04
- switch tests to use `lioadm` (supported and stable) and not `tgtd` (broken)
Fixes #2756

ci/functional: fix ubuntu version & add antelope

---

.github/workflows/backport_v1.yaml

If a backport is labeled as `semver-unknown` or `semver-major`, we
consider it unsafe to backport until someone has verified otherwise and
applied `semver-patch` or `semver-minor`.
We create a commit with an error to make it visible if that happens.
Fixes #2758

CI: automatically reject backward incompatible backports

---

.github/workflows/backport_v1.yaml

Extend the condition in case of a PR gets new labels after it has
merged, the steps will be executed and we'll check whether a backport is
accepted or not.

backport: include label name changes in events

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml
acceptance/openstack/blockstorage/v3/volumeattachments.go

- acceptance/volumeattachment: don't specify Connector
- ci/functional: switch LIO target instead of tgt
- ci/functional: add `antelope` release in the matrix
- ci/functional: reduce LOC
- ci/functional: switch master jobs to run on ubuntu 22.04

[v1] (clean manual backport) ci/functional: fix ubuntu version & add antelope

---

acceptance/openstack/compute/v2/bootfromvolume_test.go
acceptance/openstack/compute/v2/compute.go
openstack/compute/v2/extensions/bootfromvolume/requests.go
openstack/compute/v2/extensions/bootfromvolume/testing/fixtures.go
openstack/compute/v2/extensions/bootfromvolume/testing/requests_test.go

- Add tag field to compute block_device_v2
- Add requests test for new field
- acceptance/compute: remove flavor ID check
- Add acceptance tests for tag field to compute block_device_v2
This is a clean backport with no conflict.
I had to do it manually because the workflow has been fixed after these commits so it didn't run.

[v1] (manual clean backport) Add tag field to compute block_device_v2

---

acceptance/clients/conditions.go
acceptance/clients/testing/conditions_test.go
acceptance/openstack/loadbalancer/v2/loadbalancer.go
acceptance/openstack/loadbalancer/v2/quotas_test.go

There are two changes here:
- rename the `IsReleasesBelow()` and `IsReleasesAbove()` functions to `IsCurrentBelow()` and `IsCurrentAbove()` respectively.
- fix their behavior to account for numerical release names, after zed, and ensure that
comparing the same version always yields false. Also fixing bugs when comparing to master and add comprehensive tests.

Acceptance: Handle numerical version names in version comparison helpers

---

.github/workflows/semver-auto.yaml

- ci/semver-auto: return a failure only when needed
- Fix semver-auto

backport-v1: fixes to semver label

---

CHANGELOG.md
provider_client.go

Update CHANGELOG and update the user agent.

Prepare 1.7.0

---

openstack/baremetal/inventory/plugindata.go
openstack/baremetal/inventory/testing/fixtures.go
openstack/baremetal/inventory/testing/plugindata_test.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/results_test.go

Add logic to detect which PluginData is provided for the node.
Fixes #2612

baremetal: support ironic native PluginData

---

.github/workflows/unit.yml

Instead of using an old github action for coverall, switch to the
official one.

ci/unit: switch to coverallsapp/github-action

---

service_client.go

Request is a part of the public API, but it relies on being called by
Get/Post/etc to properly initialize its options. Namely:
1) it may crash on a nil map assignment if there are MoreHeaders,
2) it does not handle microversions.
This change moves the relevant code to Request.

Fix options initialization in ServiceClient.Request (fixes #2798)

---

.github/workflows/functional-baremetal.yaml

- Workaround to fix the grub-efi-amd64-signed happening in ubuntu 20.04

Fix baremetal jobs on Ubuntu 20.04

---

.github/workflows/functional-baremetal.yaml

This commit adds a workaround to baremetal jobs
running on ubuntu 20.04 since they are failling when installing grub-efi-amd64-signed

Add workaround for baremetal jobs on ubuntu 20.04

---

internal/acceptance/openstack/baremetal/httpbasic/nodes_test.go
internal/acceptance/openstack/baremetal/v1/nodes_test.go
openstack/baremetal/v1/drivers/results.go
openstack/baremetal/v1/drivers/testing/fixtures_test.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures_test.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/nodes/urls.go

* Driver updated to support
- default_firmware_interface and enabled_firmware_interfaces
* Node updated to support
- firmware_interface field can be specified
- List the Firmware Components requires API 1.86
Fixes #2794 
[https://review.opendev.org/c/openstack/ironic/+/885276]
[https://review.opendev.org/c/openstack/ironic/+/885425]
[https://docs.openstack.org/api-ref/baremetal/#node-firmware-nodes]

Support Firmware Interface

---

openstack/orchestration/v1/stacks/environment.go
openstack/orchestration/v1/stacks/environment_test.go
openstack/orchestration/v1/stacks/requests.go
openstack/orchestration/v1/stacks/template.go
openstack/orchestration/v1/stacks/template_test.go
openstack/orchestration/v1/stacks/utils.go
openstack/orchestration/v1/stacks/utils_test.go
testhelper/http_responses.go

This change fixes an issue in the handling of Heat templates that reference other files (child templates or files included by means of `get_file:`) and that also contain, in some other context, the same string as the relative path being referenced (that must indeed be substituted for the absolute local path).
The existing fixFileRefs() does a simple blind string replacement inside the referencing template, regardless of the context. This is not appropriate as the same string as the path being replaced could possibly appear outside of the valid template/file reference cases (`type: ...` and `get_file: ...`), as in the below example:
init-cmd:
type: OS::Heat::CloudConfig
properties:
cloud_config:
write_files:
- path: /etc/somefile
content: { get_file: somefile }
Here "somefile" in "{ …

Fix blind replacement of paths in Heat template referencing other files

---

internal/acceptance/openstack/networking/v2/ports_test.go
openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/testing/requests_test.go

Fixes #2807
Absolutely no idea! I can't even find the entry point for the ports api handler. This is reverse engineered from the behaviour from the cli client, which works.

Fix list ports with multiple fixedip parameters

---

openstack/compute/v2/extensions/bootfromvolume/requests.go

I recently found out that when not providing the GuestFormat to a block
device mapping, the device will be formated to `vfat` anyway.
https://opendev.org/openstack/nova/src/commit/d0b459423dd81644e8d9382b6c87fabaa4f03ad4/nova/privsep/fs.py#L257
I think it's valuable that we document that so the users know what to
expect.

Add more godoc to GuestFormat

---

internal/acceptance/openstack/objectstorage/v1/objects_test.go
openstack/objectstorage/v1/objects/requests.go

This PR backports a fix in CreateTempURL that was fixed in the main branch as a byproduct of https://github.com/gophercloud/gophercloud/pull/2821.
Before this patch, if an object's name or container name contained the string `/v1/`, it was not possible to create a TempURL for it. This was due to a bug in how the URL was split between the base part, and the object-path part.
With this patch, container names or object names containing `/v1/` can have a TempURL created successfully.
Fixes #2827

Allow objects.CreateTempURL with names containing /v1/

---

openstack/loadbalancer/v2/listeners/requests.go
openstack/loadbalancer/v2/monitors/requests.go
openstack/loadbalancer/v2/monitors/results.go
openstack/loadbalancer/v2/monitors/testing/fixtures_test.go
openstack/loadbalancer/v2/monitors/testing/requests_test.go
openstack/loadbalancer/v2/pools/requests.go

Seems like a bunch of resources are missing the tags fiels that Octavia API reference specified. This commit adds them.
Fixes #2829
https://docs.openstack.org/api-ref/load-balancer/v2/index.html

Octavia: Add tags to resources missing them

---

openstack/utils/choose_version.go
openstack/utils/testing/choose_version_test.go

This adds GetSupportedMicroversions and MicroversionSupported utility functions for working with microversions.
The doc string for ChooseVersion is also updated to clarify how it works.
Fixes #2791
TODO. I am not sure what is needed here

Add microversion utilities

---

openstack/blockstorage/apiversions/errors.go
openstack/compute/apiversions/errors.go
openstack/container/v1/capsules/errors.go
openstack/containerinfra/apiversions/errors.go
openstack/orchestration/v1/stacks/errors.go
openstack/sharedfilesystems/apiversions/errors.go
testhelper/convenience.go

Fixes #[PUT ISSUE NUMBER HERE]

chore: use String() instead of fmt.Sprintf

---

.github/workflows/unit.yml

Install Go tools with new newest Go version before switching to the target version of Go to run the unit tests.
This commit fixes an issue where the Go tools we use in unit tests can't be compiled with Go v1.14 any more.

unit tests: Fix the installation of tools

---

.github/workflows/functional-containerinfra.yaml

The stable victoria, wallaby, and xena branches are no longer available upstream for magnum. We need to use their respective `-eol` tag to keep using them in our CI jobs.

Fix devstack install on EOL magnum branches

---

internal/acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding_test.go

Since https://review.opendev.org/c/openstack/neutron/+/892815 it is no longer possible to update the vnic type of a bound port.
These doesn't seem to be an API to unbind the port other than deleting the port, so instead we're dropping the `VNICType` attribute from the update request in the `TestPortsbindingCRUD` test.

Fix networking acceptance tests

---

openstack/db/v1/instances/requests.go
openstack/db/v1/instances/testing/fixtures_test.go
openstack/db/v1/instances/testing/requests_test.go

For #2874
* code: added `AvailabilityZone` struct field
* code: add empty checking for that field
* tests: add `availability_zone` to `testing/fixtures_test.go`
* tests: add `AvailabilityZone` to `testing/requests_test.go`
* API Docs: https://docs.openstack.org/api-ref/database/#create-database-instance
* Model - Create: https://github.com/openstack/trove/blob/422507ca425f5a1be10cfc979165e7b8d58dfffa/trove/instance/models.py#L1186
* Service - Create: https://github.com/openstack/trove/blob/422507ca425f5a1be10cfc979165e7b8d58dfffa/trove/instance/service.py#L360
Related:
* https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1644
* https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1643

[db/v1/instance]: adding support for availability_zone for a db instance

---

internal/acceptance/openstack/loadbalancer/v2/loadbalancer.go
internal/acceptance/openstack/loadbalancer/v2/loadbalancers_test.go
internal/acceptance/openstack/networking/v2/networking.go
openstack/loadbalancer/v2/loadbalancers/requests.go
openstack/loadbalancer/v2/loadbalancers/results.go
openstack/loadbalancer/v2/loadbalancers/testing/fixtures_test.go
openstack/loadbalancer/v2/loadbalancers/testing/requests_test.go

Initially started with https://github.com/gophercloud/gophercloud/pull/2700 by @snigle - but we have tried to reach the author with no success, and some folks needs this PR.
To get it, we just need it rebased.
Fixes https://github.com/gophercloud/gophercloud/issues/2699
https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=show-load-balancer-details-detail#show-load-balancer-details

loadbalancer additional_vips by snigle

---

internal/acceptance/openstack/loadbalancer/v2/flavorprofiles_test.go
internal/acceptance/openstack/loadbalancer/v2/flavors_test.go
internal/acceptance/openstack/loadbalancer/v2/loadbalancer.go
openstack/loadbalancer/v2/flavorprofiles/doc.go
openstack/loadbalancer/v2/flavorprofiles/requests.go
openstack/loadbalancer/v2/flavorprofiles/results.go
openstack/loadbalancer/v2/flavorprofiles/testing/doc.go
openstack/loadbalancer/v2/flavorprofiles/testing/fixtures.go
openstack/loadbalancer/v2/flavorprofiles/testing/requests_test.go
openstack/loadbalancer/v2/flavorprofiles/urls.go
openstack/loadbalancer/v2/flavors/doc.go
openstack/loadbalancer/v2/flavors/requests.go
openstack/loadbalancer/v2/flavors/results.go
openstack/loadbalancer/v2/flavors/testing/doc.go
openstack/loadbalancer/v2/flavors/testing/fixtures.go
openstack/loadbalancer/v2/flavors/testing/fixutres.go
openstack/loadbalancer/v2/flavors/testing/requests_test.go
openstack/loadbalancer/v2/flavors/urls.go

Add support of Flavors and FlavorProfiles for Octavia
Fixes #2574 
https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/flavors.py
https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/flavor_profiles.py

Add support of Flavors and FlavorProfiles for Octavia

---

provider_client.go

Building from the development branch should not give a user agent that matches a release.
This PR must not be backported to a release branch.

Set the user agent to an unreleased version

---

.github/workflows/codeql-analysis.yml
.github/workflows/unit.yml
go.mod
go.sum
internal/ctxt/merge.go
internal/ctxt/merge_test.go
provider_client.go
service_client.go

Provide new methods to leverage per-call `context.Context`.
In the http.Request resulting from using these new context-aware calls, the per-call context values take precendence over the ProviderClient's.
Cancellation obeys both the per-call context and the ProviderClient's.

Context-aware methods to ProviderClient and ServiceClient

---

internal/ctxt/context.go
internal/ctxt/merge.go
internal/ctxt/merge_test.go
provider_client.go
service_client.go

Provide new methods to leverage per-call `context.Context`.
Backports https://github.com/gophercloud/gophercloud/pull/2883
This patch, suitable to be merged to `v1`, vendors the context package from the v1.21 standard library, to make `AfterFunc` available.

[v1] Context-aware methods to ProviderClient and ServiceClient

---

openstack/networking/v2/extensions/layer3/routers/results.go
openstack/networking/v2/extensions/layer3/routers/testing/requests_test.go

Fixes #2880
https://github.com/openstack/neutron/blob/master/neutron/objects/router.py#L376

Adding missing QoS field for router

---

openstack/client.go
openstack/identity/v2/tokens/requests.go
openstack/identity/v3/extensions/ec2tokens/requests.go
openstack/identity/v3/extensions/oauth1/requests.go
openstack/identity/v3/tokens/requests.go

Allow using a context to cancel and trace authentication calls.
In the process, add WithContext functions to token-requesting packages:
* openstack/identity/v2/tokens/requests.go
* openstack/identity/v3/extensions/ec2tokens/requests.go
* openstack/identity/v3/extensions/oauth1/requests.go
* openstack/identity/v3/tokens/requests.go

authentication: Add WithContext functions

---

openstack/networking/v2/ports/requests.go
openstack/networking/v2/ports/results.go
openstack/networking/v2/ports/testing/fixtures.go
openstack/networking/v2/ports/testing/requests_test.go

The current implementation does not do anything useful. The key-pairs must be extracted and added directly in the body instead of under "value_specs".
This commit fixes the implementation and also adds validation of the value_specs based on what is done in Heat. There are some banned keys that are not allowed in value_specs, and values are not allowed to overwrite existing fields either.
Fixes #2870

Fix value_specs implementation

---

openstack/config/clouds/clouds.go
openstack/config/clouds/clouds_test.go
openstack/config/clouds/options.go
openstack/config/clouds/tls.go
openstack/config/clouds/types.go
openstack/config/provider_client.go

This commit imports the clouds.yaml parsing code from the utils module, and exposes it in a way that fits the natural Gophercloud authentication flow.
Unlike the code from utils, this new `clouds.Parse` function keeps the separation between the ProviderClient (holding the cloud coordinates and a Keystone token) and the ServiceClient (holding specific endpoint configuration).
By default, `clouds.Parse` fetches its configuration from the environment, just like the openstack client would do.
Example use:
```Go
func main() {
ctx := context.Background()
ao, eo, tlsConfig, err := clouds.Parse()
if err != nil {
panic(err)
}
providerClient, err := config.NewProviderClient(ctx, ao, config.WithTLSConfig(tlsConfig))
if err != nil {
panic(err)
}
networkClient, err := …
```

Authenticate with a clouds.yaml

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-imageservice.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Also start using the commit hash of the release, rather than the tag.
Supersedes https://github.com/gophercloud/gophercloud/pull/2910

build(deps): bump EmilienM/devstack-action from 0.11 to 0.14

---

openstack/db/v1/instances/requests.go
openstack/db/v1/instances/testing/fixtures_test.go
openstack/db/v1/instances/testing/requests_test.go

Add configuration group id to createOpts and update unit tests accordingly.
Docs: https://docs.openstack.org/api-ref/database/#create-database-instance

db/v1/instance: Add configuration to createOpts

---

openstack/config/clouds/clouds.go
openstack/config/clouds/options.go

So that makes easier to have conditional With like that:
https://github.com/sardinasystems/fleeting-plugin-openstack/blob/90c744fc9ee23d8a18dad96f2a677a9d1a54222c/provider.go#L44-L52
Fixes #2913
In addition it fixes search for default `/etc/openstack/clouds.yaml` file.

v2: Add ParseOption type to made clouds.Parse() more usable for optional With* funcs

---

openstack/identity/v3/extensions/ec2tokens/requests.go

- replace math/rand -> crypto/rand
because this function has been deprecated since Go 1.20.
Fixes #[PUT ISSUE NUMBER HERE]

replace deprecated library

---

openstack/baremetal/v1/conductors/requests.go
openstack/baremetal/v1/nodes/requests.go
openstack/compute/v2/extensions/usage/requests.go

- opts.Detail, a bool type, itself represents a true or false value, so there is no need to compare it again with the comparison operator (==).
Fixes #[PUT ISSUE NUMBER HERE]

simplify conditional expressions

---

internal/acceptance/openstack/client_test.go
openstack/client.go
provider_client.go
testing/provider_client_test.go

Due to an error in implementing the addition of `context.Context`, the default reauth function caught the context passed when generating the ProviderClient, which could be long canceled when the reauthentication takes place.
This is a breaking change: this patch changes the signature of the reauthentication function in the ProviderClient to accept a context.
Fixes #2931

Fix AllowReauth reauthentication

---

provider_client.go

Change `(ProviderClient).Reauthenticate` to accept a `context.Context` as its first argument, and use it to perform the reauth call.

provider client: Reauthenticate with context

---

openstack/client.go

Due to an error in implementing the addition of context.Context, the default reauth function caught the context passed when generating the ProviderClient, which could be long canceled when the reauthentication takes place.
This is a modified backport of https://github.com/gophercloud/gophercloud/pull/2932.
Fixes #2931

[v1]  Fix AllowReauth reauthentication

---

openstack/compute/v2/extensions/volumeattach/doc.go
openstack/compute/v2/extensions/volumeattach/requests.go

The volume attachments API operates on volumes, not attachments. Correct the variable name.
Backports: #2939
Closes: #2861

[v1] compute: Use volumeID, not attachmentID for volume attachments

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-clustering.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Yoga has entered, and the rest will soon enter, the unmaintained [1]
phase. This means that the CI stability will be in the hands of a small
group of volunteers and will no longer be the responsibility of the
project teams. I don't believe the Gophercloud project can maintain CI
jobs on these branches in the long run, hence removing them.
[1] https://docs.openstack.org/project-team-guide/stable-branches.html#unmaintained

Drop CI coverage for Victoria-Yoga

---

.github/workflows/functional-baremetal.yaml
script/stackenv

Starting with 2024.1, some actions no longer work with a project scoped
token.

Use system scope when running baremetal tests

---

.github/workflows/backport_v1.yaml

This hopefully reduces the likelihood we're missing backports in stable branches.

Report on backporting errors

---

internal/acceptance/openstack/baremetal/v1/nodes_test.go
openstack/baremetal/v1/allocations/requests.go
openstack/baremetal/v1/conductors/requests.go
openstack/baremetal/v1/conductors/testing/requests_test.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/ports/requests.go
openstack/baremetal/v1/ports/testing/requests_test.go
params.go

Ironic expects a comma-separated string. Add a new feature to
BuildQueryString to choose the format of slices.
Closes: #2960

baremetal: fix handling of the "fields" query argument

---

.github/workflows/functional-fwaas_v2.yaml

Since https://review.opendev.org/c/openstack/neutron/+/909075, port-binding operation are restricted to the service role.
Update the policies so that we can continue exercising these tests in CI.
Fixes #2983

[CI] Fix portbiding tests

---

.github/workflows/functional-fwaas_v2.yaml

The path was missing the version which caused changes to FWaaS files to not trigger the FWaaS presubmit jobs. The periodics were unaffected.

[CI] Fix trigger for FWaaS v2 presubmit

---

internal/acceptance/openstack/baremetal/v1/nodes_test.go
openstack/baremetal/v1/allocations/requests.go
openstack/baremetal/v1/conductors/requests.go
openstack/baremetal/v1/conductors/testing/requests_test.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/ports/requests.go
openstack/baremetal/v1/ports/testing/requests_test.go
params.go

Backport: https://github.com/gophercloud/gophercloud/pull/2961
Supersedes https://github.com/gophercloud/gophercloud/pull/2980
Ironic expects a comma-separated string. Add a new feature to BuildQueryString to choose the format of slices.
Closes: #2960 
Manual backport since the original change had a different signature for the EachPage() function, where it expected a context.

[v1] baremetal: fix handling of the "fields" query argument

---

openstack/blockstorage/v3/volumes/requests.go

Fixes #2977
This PR adds the ability to filter volumes by the "bootable" flag, when using Cinder API V3.

Add bootable filter to v3 cinder list options

---

internal/acceptance/openstack/baremetal/v1/nodes_test.go
openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures_test.go
openstack/baremetal/v1/nodes/testing/requests_test.go
openstack/baremetal/v1/nodes/urls.go

Requires:
- https://github.com/gophercloud/gophercloud/pull/2961
Closes: #2958

baremetal: support for virtual media attach/detach

---

internal/acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go

A follow-up to https://github.com/gophercloud/gophercloud/pull/2936 that missed part of the
`internal/acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go` file.
Fixes #2981

[CI] Fix number of args passed to FWaaSv2 tests

---

.github/workflows/functional-baremetal.yaml

Zed now fails with a similar error. Let's make sure we start without
dnsmasq-base in all baremetal jobs.

functional-baremetal: remove dnsmasq-base on all versions

---

internal/acceptance/openstack/container/v1/capsules_test.go
internal/acceptance/openstack/db/v1/configurations_test.go
internal/acceptance/openstack/db/v1/flavors_test.go
internal/acceptance/openstack/db/v1/instances_test.go
internal/acceptance/openstack/dns/v2/recordsets_test.go
internal/acceptance/openstack/dns/v2/transfers_test.go
internal/acceptance/openstack/dns/v2/zones_test.go
internal/acceptance/openstack/networking/v2/extensions/fwaas/firewall_test.go

We have a number of tests that we do not appear to be running in CI. In addition, we are not running go vet with all suitable build tags resulting in some tests being skipped [[1][1]]. Combined, this has resulted in a number of tests that have not been fully updated to use context. While we will address the root cause elsewhere, we can fix the missed updates here.
You can validate this fix by overriding GOFLAGS, as outlined in [[1][1]]. For example, from the root directory:
```shell
GOFLAGS="-tags=acceptance" go vet ./...
```
[1]: https://github.com/golang/go/issues/29202
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>

tests: Fix lint issues

---

go.mod

Since golang 1.21, the patch version in go.mod is trickled to downstream consumers as minimum go version, and to their consumers etc. Remove the patch version, and use only minor version to allow consumers some flexibility.
Fixes: #3031

remove golang patch version from main go.mod

---

openstack/config/clouds/clouds.go
openstack/config/clouds/clouds_test.go

Before this patch, no `secure.yaml` could ever be found by the Parse function, because a programming error caused Gophercloud to always look at a path that doesn't exist.
Fixes #3039

clouds: Fix secure.yaml parsing

---

openstack/config/clouds/clouds.go
openstack/config/clouds/clouds_test.go

Before this patch, all default locations were scanned for a `clouds.yaml` even when a match was found. The last found `clouds.yaml` replaced any previous finding, effectively reversing the order of priority for the locations.
Fixes #3038

clouds: Fix the clouds.yaml locations

---

internal/acceptance/openstack/identity/v3/projects_test.go
openstack/identity/v3/projects/doc.go
openstack/identity/v3/projects/requests.go
openstack/identity/v3/projects/results.go
openstack/identity/v3/projects/testing/fixtures_test.go
openstack/identity/v3/projects/testing/requests_test.go
openstack/identity/v3/projects/urls.go

With this PR, we add API support for:
* Listing all  tags on a project.
* Modifying all tags of a project.
* Deleting all tags of a project.
Partially implements: https://github.com/gophercloud/gophercloud/issues/3015
List project  tags:
[API Docs](https://docs.openstack.org/api-ref/identity/v3/#list-tags-for-a-project)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/api/projects.py#L235)
Modify project tags:
[API Docs](https://docs.openstack.org/api-ref/identity/v3/#modify-tag-list-for-a-project)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/api/projects.py#L246)
Delete project tags:
[API Docs](https://docs.openstack.org/api-ref/identity/v3/#remove-all-tags-from-a-project)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/api/ …

Support list-modify-delete project tags api calls

---

internal/acceptance/openstack/identity/v3/roles_test.go
openstack/identity/v3/roles/doc.go
openstack/identity/v3/roles/requests.go
openstack/identity/v3/roles/results.go
openstack/identity/v3/roles/testing/fixtures_test.go
openstack/identity/v3/roles/testing/requests_test.go
openstack/identity/v3/roles/urls.go

With this PR, we add API support for:
* Create role inference rule.
* List all role inference rules.
* Delete role inference rule.
* Get a role inference rules.
Implements: #2225 
Create role inference rule:
[API Docs ](https://docs.openstack.org/api-ref/identity/v3/index.html#create-role-inference-rule)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/api/roles.py#L252)
Get role inference rule:
[API Docs ](https://docs.openstack.org/api-ref/identity/v3/index.html#get-role-inference-rule)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/api/roles.py#L227)
Delete a role inference rule:
[API Docs ](https://docs.openstack.org/api-ref/identity/v3/index.html#delete-role-inference-rule)
[Py code](https://github.com/openstack/keystone/blob/master/keystone/a …

Add support for implied roles

---

internal/acceptance/clients/clients.go
internal/acceptance/clients/conditions.go
internal/acceptance/openstack/baremetal/noauth/allocations_test.go
internal/acceptance/openstack/baremetal/noauth/nodes_test.go
internal/acceptance/openstack/baremetal/noauth/ports_test.go
internal/acceptance/openstack/blockstorage/noauth/snapshots_test.go
internal/acceptance/openstack/blockstorage/noauth/volumes_test.go
internal/acceptance/openstack/networking/v2/conditions.go
internal/acceptance/openstack/networking/v2/extensions/dns/dns_test.go
internal/acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go
internal/acceptance/openstack/networking/v2/extensions/fwaas_v2/policy_test.go
internal/acceptance/openstack/networking/v2/extensions/fwaas_v2/rule_test.go
internal/acceptance/openstack/networking/v2/extensions/layer3/l3_scheduling_test.go
internal/acceptance/openstack/networking/v2/extensions/mtu/mtu_test.go
internal/acceptance/openstack/networking/v2/extensions/qos/policies/policies_test.go
internal/acceptance/openstack/networking/v2/extensions/qos/rules/rules_test.go
internal/acceptance/openstack/networking/v2/extensions/qos/ruletypes/ruletypes_test.go
internal/acceptance/openstack/networking/v2/extensions/trunk_details/trunks_test.go
internal/acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
internal/acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent_test.go

Allow us to run all tests in a module and have those that require specific extensions or configuration be skipped.
This is broken out from #3001 to help minimize the diff from that (rather beefy) PR

tests: Add skips for feature- or configuration-dependent tests

---

internal/acceptance/openstack/blockstorage/noauth/blockstorage.go
internal/acceptance/openstack/blockstorage/v2/blockstorage.go
internal/acceptance/openstack/blockstorage/v2/schedulerhints_test.go
internal/acceptance/openstack/blockstorage/v2/volumes_test.go
internal/acceptance/openstack/blockstorage/v3/blockstorage.go
internal/acceptance/openstack/blockstorage/v3/schedulerhints_test.go
internal/acceptance/openstack/blockstorage/v3/volumes_test.go
internal/acceptance/openstack/compute/v2/compute.go
openstack/blockstorage/v2/volumes/doc.go
openstack/blockstorage/v2/volumes/requests.go
openstack/blockstorage/v2/volumes/testing/requests_test.go
openstack/blockstorage/v3/volumes/doc.go
openstack/blockstorage/v3/volumes/requests.go
openstack/blockstorage/v3/volumes/testing/requests_test.go
openstack/compute/v2/servers/doc.go
openstack/compute/v2/servers/requests.go
openstack/compute/v2/servers/testing/fixtures_test.go
openstack/compute/v2/servers/testing/requests_test.go

As noted in #2945 and #2938, scheduler hints in the Compute and Block Storage service are slightly weird in that they are passed as separate top-level keys in the request body, rather than nested in the `server` or `volume` bodies, respectively.
Reflect this API nuance in our own API by exposing these hints as a top-level argument to the `Create` functions for servers and volumes. This should ease the path to auto-generation down the line and keeps us a little "truer" to the APIs themselves.

compute, block storage: Rework scheduler hints

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

This has the ability to shave a few minutes off our deployment time for DevStack and is already being used [upstream in Nova](https://review.opendev.org/c/openstack/nova/+/919738). Use it here also.

Enable openstack-client-server service in functional jobs

---

.github/workflows/functional-baremetal.yaml

The RBAC changes were already there but the correct scope was not set
when adding the caracal branch.

CI: baremetal: also use system scope in 2024.1

---

script/collectlogs

We are seeing pretty consistent failures in some of our neutron jobs. Start storing logs so that we can debug this. While we're doing this, we also pass the `collectlogs` script through shellcheck and fix the issues we see.

CI: Capture service logs

---

openstack/client.go
openstack/client_test.go
openstack/identity/v2/tokens/requests.go

Rather than creating a tokens2.AuthOptions inside the authentication flow for identity v2, allow any structure that implements the tokens2.AuthBuilderOptions interface to be used. The interface is modified to add a CanReauth function like the v3 version has but provides a default implementation. The gophercloud.AuthOptions already implements this interface so there is no change to its API. Lastly add an AuthenticateV2Ext function which will allow an out of tree identity v2 auth mechanism to be implemented. fixes #2651. ref #1330.

identity: use AuthOptionsBuilder for v2 auth

---

docs/MIGRATING.md

Fixes #3062.
This is just the same instructions that I already provided in #2904, but which evidently were forgotten about.

add migration docs for error handling changes

---

internal/acceptance/openstack/networking/v2/extensions/agents/agents_test.go

An attempt to fix failing `TestBGPAgentRUD` tests

[tests]: increase timeout for the TestBGPAgentRUD test

---

internal/acceptance/openstack/networking/v2/extensions/layer3/layer3.go
internal/acceptance/openstack/networking/v2/extensions/layer3/portforwardings_test.go
openstack/networking/v2/extensions/layer3/portforwarding/requests.go
openstack/networking/v2/extensions/layer3/portforwarding/results.go

Fixes #3093 
https://github.com/openstack/neutron-lib/blob/47e1736c10ffd6f1850eba9970acdc00373f9de7/neutron_lib/api/definitions/fip_pf_description.py

[neutron]: introduce Description argument for the portforwarding

---

internal/acceptance/openstack/networking/v2/extensions/security_test.go
openstack/networking/v2/extensions/security/groups/requests.go
openstack/networking/v2/extensions/security/groups/results.go

Fixes #3091 
https://github.com/openstack/neutron-lib/blob/47e1736c10ffd6f1850eba9970acdc00373f9de7/neutron_lib/api/definitions/stateful_security_group.py#L36-L42

[neutron]: introduce Stateful argument for the security groups

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Since the go.mod and CHANGELOG.md already mentioned golang 1.22, we need to change the go version in tests as well.

[tests]: bump golang to 1.22

---

.github/workflows/backport.yaml

This should solve the cherry-pick order when backporting.

Bump git-backporting

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Otherwise you end up with lots of duplicate `functional-{service}-{branch}` tarballs when debugging.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>

CI: Append job ID to artifact name

---

.github/workflows/backport.yaml

With `v2` out, we are freezing `v1` to only receive bug fixes.
Backports to `v1` can be forced by manually creating a PR against `v1`.

Block `semver:minor` backports to v1

---

.github/workflows/check-pr-labels.yaml

Add a check that fails when the PR has the 'hold' label.

[v1] actions: Add a label to hold merging

---

.github/workflows/check-pr-labels.yaml

Before adding these trigger types, the `hold` job was often skipped, unnecessarily blocking the Pull request.

actions: Correctly refresh hold state

---

docs/MIGRATING.md

Some steps in the migration from Gophercloud v1 to v2 can be automated. Provide a script that can take out some of the pain.
After running the script, your code will likely not compile. The idea is that at this point, you're only left with a few changes that can't reasonably be automated.
* Add /v2 to all Gophercloud imports, except to the packages that have been removed without replacement
* Adjust the import path of moved packages
* Adjust the package identifier in the code where possible
* Add context.TODO() where required
* doesn't fix the use of removed extensions. For example, if you used `openstack/blockstorage/extensions/availabilityzones`, you will have to manually put that back into e.g. `servers.CreateOpts`
* it will only put `context.TODO()` where a context is required to …

MIGRATING.md: Provide a migration script

---

.github/labels.yaml
.github/workflows/semver-auto.yaml

Using `gh` lets us drop two external dependencies, and condensate the steps a bit.
After this change:
* new pushes in the PR won't trigger relabeling if the assessment is unchanged
* failures in the workflow will be notified as comments in the PR rather than via the `semver:unknown` label
The next natural step is to set this job as mandatory, to that a failure to assess semver will block merging.

actions: Refactor the semver assessment

---

.github/labels.yaml
.github/workflows/semver-auto.yaml

Manual backport of #3128 
Using `gh` lets us drop two external dependencies, and condensate the steps a bit.
After this change:
* new pushes in the PR won't trigger relabeling if the assessment is unchanged
* failures in the workflow will be notified as comments in the PR rather than via the `semver:unknown` label
The next natural step is to set this job as mandatory, to that a failure to assess semver will block merging.
---
This PR also creates `labels.yaml` (identical to master's) so that automatic backports can land without conflicts in the future.

[v1] actions: Refactor the semver assessment

---

internal/acceptance/openstack/networking/v2/extensions/security_test.go
openstack/networking/v2/extensions/security/groups/requests.go
openstack/networking/v2/extensions/security/groups/results.go

Fixes #3091
Backport of the #3092 without changing the List function signature

[v2] [neutron]: introduce Stateful argument for the security groups

---

.github/labels.yaml
.github/workflows/label-issue.yaml

Includes a Github action that automatically removes the `needinfo` label when the original author adds a comment.

Add needinfo label

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Use HTML comments to hide the suggestions from the final issue or Pull request text.

Github templates: Hide suggestions

---

openstack/baremetal/v1/nodes/requests.go

There is a mismatch between ServiceFail values used by Gophercloud and Ironic. Ironic uses "service failed" value [1], rather than "service fail". This commit addresses this discrepancy.
Fixes #3130 
[1] https://github.com/openstack/ironic/blob/stable/2024.1/ironic/common/states.py#L248

Align ServiceFail provisioning state value with Ironic

---

openstack/networking/v2/extensions/security/rules/requests.go

Backport of https://github.com/gophercloud/gophercloud/pull/3157
Before this patch, Gophercloud attempted to create a security group rule that would be applied regardless of the protocol by passing the literal `"any"` as the rule protocol.
Despite being correct according to [the documentation][1], Neutron rejects the value `"any"` with an HTTP status code of  `400 Bad Request`.
This change replaces the value of `ProtocolAny` to be the empty string `""`, which has the effect of creating a rule that applies to any protocol.
cf: [Neutron bug 2074056][2]
[1]: https://docs.openstack.org/api-ref/network/v2/#create-security-group-rule
[2]: https://bugs.launchpad.net/neutron/+bug/2074056
Fixes #2442

Fix security group rule "any protocol"

---

openstack/compute/v2/hypervisors/results.go
openstack/compute/v2/hypervisors/testing/fixtures_test.go
openstack/compute/v2/hypervisors/testing/requests_test.go

NOTE: this is based on and tested with v1.5.0 (I'm testing for https://github.com/openstack-exporter/openstack-exporter/issues/268 ).  Please let me know if this should be rebased, targeted to v1 branch, etc.?  Help appreciated for testing this. :)
Fixes #3026

Handle nova api version > 2.87 for hypervisor

---

docs/MIGRATING.md

These are a couple of small improvements to the automated v2 migration script:
- exclude vendor directory
- try converting all ErrDefaultXXX errors that existed in gophercloud v1 to their net/http equivalent

Small improvements to v2 migration script

---

.github/labels.yaml

Several pull requests in the backlog are code-complete according to their authors, but lack tests. This label will let us be more aware of the problem.

Add label: just-needs-tests

---

openstack/networking/v2/extensions/bgp/speakers/requests.go
openstack/networking/v2/extensions/bgp/speakers/testing/requests_test.go

Fixes https://github.com/gophercloud/utils/issues/198
Not sure whether we need to adjust the `utils` itself like https://github.com/gophercloud/utils/pull/230
I'm not sure whether we need to check for `err != io.EOF` in the `doRequest`'s `json.NewDecoder(resp.Body).Decode(options.JSONResponse)`. It's not clear whether API should return body or not, e.g.  `[]` or `{}` or an empty response.

[core]: handle empty response body

---

internal/acceptance/openstack/compute/v2/attachinterfaces_test.go
internal/acceptance/openstack/compute/v2/availabilityzones_test.go
internal/acceptance/openstack/compute/v2/bootfromvolume_test.go
internal/acceptance/openstack/compute/v2/compute.go
internal/acceptance/openstack/compute/v2/extension_test.go
internal/acceptance/openstack/compute/v2/flavors_test.go
internal/acceptance/openstack/compute/v2/instance_actions_test.go
internal/acceptance/openstack/compute/v2/keypairs_test.go
internal/acceptance/openstack/compute/v2/limits_test.go
internal/acceptance/openstack/compute/v2/quotaset_test.go
internal/acceptance/openstack/compute/v2/secgroup_test.go
internal/acceptance/openstack/compute/v2/servergroup_test.go
internal/acceptance/openstack/compute/v2/servers_test.go
internal/acceptance/openstack/compute/v2/services_test.go
internal/acceptance/openstack/compute/v2/volumeattach_test.go

Our test convenience function `AssertEquals` accept the expected value first, then the actual value. Many tests in Compute were using it the other way around, thus potentially returning confusing error messages.
https://github.com/gophercloud/gophercloud/blob/abca462164fb9fe6ab103b61fafb1399547f4438/testhelper/convenience.go#L218

compute: Fix expected and actual test results

---

.github/workflows/label-issue.yaml

The gh tool must be set to operate on an issue rather than on a PR.
cf https://docs.github.com/en/actions/use-cases-and-examples/project-management/adding-labels-to-issues
(thanks @stephenfin)

Fix clear-needinfo

---

openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures_test.go

Fixes https://github.com/gophercloud/gophercloud/issues/3172
I have 1-1 mapped with: https://docs.openstack.org/api-ref/baremetal/#list-nodes-detailed
=========================
Since all the fields I have added were already present in the test fixtures, this was an easy change!

Added required fields for Node API Parity

---

.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml

Antelope has entered the unmaintained [1] phase. We can no longer rely on this for testing.
[1] https://docs.openstack.org/project-team-guide/stable-branches.html#unmaintained

Drop CI coverage for Antelope

---

endpoint_search.go
openstack/blockstorage/noauth/requests.go
openstack/client.go
openstack/endpoint_location.go
service_client.go
testing/endpoint_search_test.go

Fixes #3207
This means we can identify a service by either its type or any of its official aliases, which is the expectation when it comes to navigating the service catalog.

Configure and respect service type aliases

---

.github/workflows/functional-workflow.yaml

Fixes #3234
Acceptance tests for Workflow/Mistral are missing on CI.
The goal of this PR is to add them to the Gophercloud CI so that they are executed regularly on the Workflow client code.

Adding CI job for testing workflow (Mistral)

---

openstack/baremetal/v1/nodes/requests.go
openstack/baremetal/v1/nodes/results.go
openstack/baremetal/v1/nodes/testing/fixtures_test.go

Added in baremetal api v1.95 disable_power_off expcicitly prevents a node from being powered off by ironic.
See https://specs.openstack.org/openstack/ironic-specs/specs/approved/nc-si.html
Fixes #3246
https://review.opendev.org/c/openstack/ironic/+/934740

Add support for disable_power_off

---

.github/labels.yaml

The `edit:testinfra` label was added to `labeler.yaml` for automatic
labeling based on path, but not to the list of managed labels.
With this change `edit:testinfra` is added to the list of managed
labels, so that automation doesn't fight to create and remove it.

labels: Add edit:testinfra

---

openstack/compute/v2/servers/results.go
openstack/compute/v2/servers/testing/fixtures_test.go
openstack/compute/v2/servers/testing/requests_test.go
openstack/objectstorage/v1/containers/results.go
openstack/objectstorage/v1/containers/testing/fixtures.go
openstack/objectstorage/v1/containers/testing/requests_test.go

Fixes https://github.com/gophercloud/gophercloud/issues/2386 and https://github.com/gophercloud/gophercloud/issues/1958
https://docs.openstack.org/api-ref/compute/?expanded=show-server-details-detail#:~:text=security%20group%20name.-,locked,-body
https://docs.openstack.org/api-ref/object-store/?expanded=create-container-detail#:~:text=X%2DContainer%2DSync%2DTo%20(Optional)

Add missing fields in Objectstorage and compute API

---

openstack/networking/v2/extensions/security/rules/requests.go
openstack/networking/v2/extensions/security/rules/testing/requests_test.go

Before this patch, security group rules could only be created in a batch when using slices of plain `rules.CreateOpts`. With this change, a slice of any type implementing `rules.CreateOptsBuilder` can be used to create security group rules in a batch.

bulk security group rule creation: Allow using CreateOptsBuilder

---

internal/acceptance/openstack/compute/v2/compute.go
openstack/compute/v2/keypairs/doc.go
openstack/compute/v2/keypairs/requests.go
openstack/compute/v2/servers/requests.go
openstack/loadbalancer/v2/flavors/testing/fixtures.go

This was missed in v2. Ensure we correct it in v3.

compute: Merge keypair CreateOptsExt

---

openstack/loadbalancer/v2/apiversions/results.go
openstack/networking/v2/apiversions/results.go

`son:"status"` is not a valid hint for JSON (de/en)coder.
There's no actual issue, everything works as expected - but only because no one ever needs to marshal those APIVersion structs back to JSON.

Fix JSON field name hints in APIVersion structs

---

internal/acceptance/openstack/blockstorage/v3/quotaset_test.go
openstack/blockstorage/v2/quotasets/results.go
openstack/blockstorage/v2/quotasets/testing/fixtures_test.go
openstack/blockstorage/v2/quotasets/testing/requests_test.go
openstack/blockstorage/v3/quotasets/results.go
openstack/blockstorage/v3/quotasets/testing/fixtures_test.go
openstack/blockstorage/v3/quotasets/testing/requests_test.go

The volume_type attributes are currently only set for QuotaSet objects.
Hence, implemented per `volume_type` QuotaUsage as a nested object 
of `QuotaUsageSet`for block storage. 
See API docs for refs.
block-storage v3
https://docs.openstack.org/api-ref/block-storage/v3/#show-quota-usage-for-a-project
block-storage v2
https://docs.openstack.org/api-ref/block-storage/v2/#show-quotas

block_storage: get quotausage for blockstorage volume_types

---

go.mod
go.sum

Backport of #3272 
Bumps [golang.org/x/crypto](https://github.com/golang/crypto) from 0.30.0 to 0.31.0.
- [Commits](https://github.com/golang/crypto/compare/v0.30.0...v0.31.0)
---
This manual backport is required because the development branch was moved to `main` after the original PR was merged, and tooling clearly is confused.

build(deps): bump golang.org/x/crypto from 0.30.0 to 0.31.0

---

openstack/compute/v2/servers/requests.go
openstack/compute/v2/servers/testing/requests_test.go

Fixes #2499
[openstack api ref](https://docs.openstack.org/api-ref/compute/?expanded=list-hypervisors-detail,create-server-detail#create-server)
[openstack python client](https://github.com/openstack/python-openstackclient/blob/f1cb66a476b948093986afd18a00941b7807a9c4/openstackclient/compute/v2/server.py#L1685-L1694)

Added support for `hypervisor_hostname`

---

openstack/compute/v2/servers/requests.go
openstack/compute/v2/servers/testing/requests_test.go

Backport: Added support for hypervisor_hostname to v2

---

internal/acceptance/openstack/baremetal/httpbasic/portgroups_test.go
internal/acceptance/openstack/baremetal/noauth/portgroups_test.go
internal/acceptance/openstack/baremetal/v1/baremetal.go
internal/acceptance/openstack/baremetal/v1/portgroups_test.go
openstack/baremetal/v1/portgroups/requests.go
openstack/baremetal/v1/portgroups/results.go
openstack/baremetal/v1/portgroups/testing/fixtures.go
openstack/baremetal/v1/portgroups/testing/requests_test.go
openstack/baremetal/v1/portgroups/urls.go

Fixes #3285 
Built from https://docs.openstack.org/api-ref/baremetal/#portgroups-portgroups (For Ironic this is considered reliable)

Added support for baremetal portgroups

---

internal/acceptance/openstack/networking/v2/extensions/layer3/floatingips_test.go
internal/acceptance/openstack/networking/v2/extensions/layer3/routers_test.go
internal/acceptance/openstack/networking/v2/extensions/qos/policies/policies_test.go
internal/acceptance/openstack/networking/v2/extensions/security_test.go
internal/acceptance/openstack/networking/v2/extensions/subnetpools/subnetpools_test.go
internal/acceptance/openstack/networking/v2/extensions/trunks/trunks_test.go
openstack/networking/v2/extensions/layer3/floatingips/requests.go
openstack/networking/v2/extensions/layer3/floatingips/results.go
openstack/networking/v2/extensions/layer3/routers/requests.go
openstack/networking/v2/extensions/layer3/routers/results.go
openstack/networking/v2/extensions/qos/policies/requests.go
openstack/networking/v2/extensions/qos/policies/results.go
openstack/networking/v2/extensions/security/groups/requests.go
openstack/networking/v2/extensions/security/groups/results.go
openstack/networking/v2/extensions/security/rules/requests.go
openstack/networking/v2/extensions/security/rules/results.go
openstack/networking/v2/extensions/subnetpools/requests.go
openstack/networking/v2/extensions/trunks/requests.go
openstack/networking/v2/extensions/trunks/results.go
openstack/networking/v2/networks/requests.go
openstack/networking/v2/ports/requests.go
openstack/networking/v2/subnets/requests.go
openstack/networking/v2/subnets/results.go

Consistently add support for the neutron `Resource revision numbers`
extension [1] for more resources that support it. It adds
a `RevisionNumber` field to all responses, and allows filtering via the
`RevisionNumber` list option. It was only partially implemented.
Support the `If-Match` constraints for these resources, and add test for it.
Add a few missing `CreatedAt` and `UpdatedAt` fields for networking
resources.
[1] https://docs.openstack.org/api-ref/network/v2/#revisions

Improve support for network `standard-attr-*` extensions

---

internal/acceptance/clients/conditions.go
internal/acceptance/openstack/networking/v2/extensions/layer3/routers_test.go

Due to https://bugs.launchpad.net/neutron/+bug/2101871, which causes neutron to return a 500 error.

CI: skip TestLayer3RouterRevision on bobcat

---

.github/workflows/unit.yaml

The original `gocovmerge` repository [1] has not seen a commit in 9 years and should be considered unmaintained.
Switch to fork has a go.mod pinned to go 1.22. Please review the diff [2] between the two repos to check if it's safe to use in gophercloud.
[1] https://github.com/wadey/gocovmerge
[2] https://github.com/wadey/gocovmerge/compare/master...alexfalkowski:gocovmerge:v1.4.0

[v2] Switch to a version of gocovmerge compatible with go 1.22

---

internal/acceptance/openstack/blockstorage/v3/snapshots_test.go
openstack/blockstorage/v3/snapshots/requests.go
openstack/blockstorage/v3/snapshots/results.go
openstack/blockstorage/v3/snapshots/testing/fixtures_test.go
openstack/blockstorage/v3/snapshots/testing/requests_test.go
openstack/blockstorage/v3/snapshots/urls.go

- Extended Snapshot struct to include additional fields: Progress, ProjectID, GroupSnapshotID, UserID, ConsumesQuota
- Implemented ListDetail function to retrieve detailed snapshot information from the snapshots/detail endpoint
- Added new test to validate the inclusion of additional fields and the functionality of  ListDetails
Fixes #2403
Documentation: https://docs.openstack.org/api-ref/block-storage/v3/#list-snapshots-and-details

Enhance Snapshot struct and add ListDetail function in V3 blockstorage

---

openstack/auth_env.go

If OS_PROJECT_NAME is set, it requires the domain to be set as well to get unique project entity on the identity service (keystone).

Update the doc of openstack.AuthOptionsFromEnv function

---

openstack/networking/v2/apiversions/constants.go
openstack/networking/v2/extensions/layer3/floatingips/constants.go
openstack/networking/v2/extensions/trunks/constants.go
openstack/networking/v2/extensions/vpnaas/services/constants.go
openstack/networking/v2/extensions/vpnaas/siteconnections/constants.go
openstack/networking/v2/networks/constants.go
openstack/networking/v2/ports/constants.go

This avoids the need to define these constants in consumer code.
Router also has a status field, but there's no documentation for it, so
let's not guess what the valid statuses are.

networking: add constants for statuses

---

internal/acceptance/openstack/dns/v2/dns.go
internal/acceptance/openstack/dns/v2/shares_test.go
openstack/dns/v2/zones/requests.go
openstack/dns/v2/zones/results.go
openstack/dns/v2/zones/testing/fixtures_test.go
openstack/dns/v2/zones/testing/requests_test.go
openstack/dns/v2/zones/urls.go

Fixes #3048
This PR adds zone share list and proper body read in the `Share` func. Previously this call leaked request bodies, because the response was not read.
https://docs.openstack.org/api-ref/dns/dns-api-v2-index.html#get-all-shared-zones

dns: implement shared zones list

---

.github/workflows/functional-networking.yaml
internal/acceptance/openstack/networking/v2/extensions/agents/agents_test.go

A manual backport of #3382 that drops the first commit, which is reverting a patch that never merged against the `v2` branch.

[v2] tests: Fix TestBGPAgentCRUD

---

internal/acceptance/openstack/networking/v2/extensions/extensions.go

Reduce the randomness of port creation.

acceptance: Prevent 409 when bulk-creating secgroup rules

---

internal/acceptance/openstack/blockstorage/v3/blockstorage.go
internal/acceptance/openstack/blockstorage/v3/manageablevolumes_test.go
openstack/blockstorage/v3/manageablevolumes/doc.go
openstack/blockstorage/v3/manageablevolumes/requests.go
openstack/blockstorage/v3/manageablevolumes/results.go
openstack/blockstorage/v3/manageablevolumes/testing/doc.go
openstack/blockstorage/v3/manageablevolumes/testing/fixtures_test.go
openstack/blockstorage/v3/manageablevolumes/testing/requests_test.go
openstack/blockstorage/v3/manageablevolumes/urls.go
openstack/blockstorage/v3/volumes/doc.go
openstack/blockstorage/v3/volumes/requests.go
openstack/blockstorage/v3/volumes/results.go
openstack/blockstorage/v3/volumes/testing/fixtures_test.go
openstack/blockstorage/v3/volumes/testing/requests_test.go

Nice to meet you. I always appreciate your developments.
I have this pull request ready to do, so could you please review it?
I implemented a missing blockstorage API call to manage an existing volume and unmanage a volume. 
API document for the endpoints are these: 
- https://docs.openstack.org/api-ref/block-storage/v3/#manage-an-existing-volume
- https://docs.openstack.org/api-ref/block-storage/v3/#unmanage-a-volume
I wrote the unit and acceptance tests and checked that they worked.
Therefore, I tested the new code with the environment and the script below.
- cinder-api/noble-updates,now 2:25.0.0-0ubuntu1~cloud0 all [installed]
- cinder-volume/noble-updates,now 2:25.0.0-0ubuntu1~cloud0 all [installed]
- using cinder lvm driver
```go
package main
import (
"context"
"fmt"
"log"
"os" …
```

blockstorage: add manage-existing and unmanage api call

---

.github/workflows/label-pr.yaml

It is currently too easy to forget to backport a PR to a release branch.
With this change, the label `backport-v2` is automatically added when the detected semver is patch or minor.

Automatically backport based on semver

---

openstack/objectstorage/v1/objects/testing/requests_test.go

Avoid conflicts when tests are run concurrently and randomly, as we now do in CI.

trivial: Avoid overlapping ports in live servers tests

---

Makefile

The latest version bump the minimum go version to 1.23 [[1][1]], which breaks jobs on the v2 branch.
This should be backported to v2.
[1]: https://github.com/gotestyourself/gotestsum/compare/v1.12.2...v1.12.3#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

make: Use fixed version of gotestsum

---

internal/acceptance/openstack/networking/v2/extensions/security_test.go
openstack/networking/v2/extensions/security/groups/requests.go
openstack/networking/v2/extensions/security/groups/testing/requests_test.go

It was not possible to update the security group name

neutron: support security group empty name update

---

internal/acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go
internal/acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go
internal/acceptance/openstack/networking/v2/extensions/bgp/speakers/speakers.go
openstack/networking/v2/extensions/bgp/peers/requests.go
openstack/networking/v2/extensions/bgp/peers/testing/requests_test.go
openstack/networking/v2/extensions/bgp/speakers/requests.go
openstack/networking/v2/extensions/bgp/speakers/testing/fixture.go
openstack/networking/v2/extensions/bgp/speakers/testing/requests_test.go

During the work on the the https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1892 PR I discovered that speakers create opts:
* don't support networks
* local AS must have an int type
* support tenant id
* AdvertiseFloatingIPHostRoutes and AdvertiseTenantNetworks must be a pointer to allow setting `false` values
peers create opts:
* support tenant id
Also update opts must contain pointers in order to allow updates to an empty string or false boolean value.

neutron: fix BGP peers and speakers struct member types

---

internal/acceptance/openstack/compute/v2/servers_test.go
openstack/compute/v2/servers/requests.go
openstack/compute/v2/servers/testing/fixtures_test.go
openstack/compute/v2/servers/testing/requests_test.go

Fixes #3444
* [hostname](https://github.com/openstack/nova/blob/0d586ccca88ae90b9634ee00b8f7f86a78b09cd0/nova/objects/instance.py#L131)
I've ran all compute acceptance tests against a 2025.1 DevStack environment and all passed.
Once this is accepted merged I'll also create a pull request to backport this into the v2 branch.

nova: add support for hostname updates

---

openstack/blockstorage/v3/volumetypes/requests.go
openstack/blockstorage/v3/volumetypes/testing/fixtures_test.go
openstack/blockstorage/v3/volumetypes/testing/requests_test.go

Fixes #3450
https://docs.openstack.org/api-ref/block-storage/v3/index.html#volume-types-types

blockstorage: add isPublic query option for volume types

---

openstack/networking/v2/extensions/layer3/routers/results.go
openstack/networking/v2/ports/results.go

I could not find any docs about `external_fixed_ip` struct to support omitted `subnet_id`, but I created test case in terraform provider and it works as expected, see https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1915
As for the port's `subnet_id`, the omission behavior is documented [here](https://docs.openstack.org/api-ref/network/v2/#create-port):
> The IP addresses for the port. If you would like to assign multiple IP addresses for the port, specify multiple entries in this field. Each entry consists of IP address (ip_address) and the subnet ID from which the IP address is assigned (subnet_id).
> If you specify both a subnet ID and an IP address, OpenStack Networking tries to allocate the IP address on that subnet to the port.
> If you specify only …

neutron: allow omission of subnet_id for IP address

---

internal/acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent.go
internal/acceptance/openstack/networking/v2/extensions/vlantransparent/vlantransparent_test.go

The 'vlan-transparent' extension is now enabled by default [1]. This is highlighting a bug in the aforementioned test: namely, that we are trying to update an attribute which is read-only [2]. Remove the update step of the job and fix the test.
[1] https://github.com/openstack/neutron/commit/11ff4f2f981969cf56ffcafa0a2f9a8fe11eabce
[2] https://github.com/openstack/neutron-lib/blob/fd011c955dfae1072555c69b6ba742b85f041736/neutron_lib/api/definitions/vlantransparent.py#L49

[v2] tests: Fix TestVLANTransparentCRUD test

---

.github/workflows/codeql-analysis.yaml
.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml
.github/workflows/functional-workflow.yaml
.github/workflows/lint.yaml
.github/workflows/unit.yaml

and use go-version-file: 'go.mod' for go version source
before:
after:

tests: shorten GH-A job names

---

.github/workflows/unit.yaml

The original `gocovmerge` repository [1] has not seen a commit in 9 years and should be considered unmaintained.
Switch to fork has a go.mod pinned to go 1.22. Please review the diff [2] between the two repos to check if it's safe to use in gophercloud.
[1] https://github.com/wadey/gocovmerge
[2] https://github.com/wadey/gocovmerge/compare/master...alexfalkowski:gocovmerge:v1.4.0
This is a cherry-pick of the #3325

Switch to a version of gocovmerge compatible with go 1.22

---

openstack/compute/v2/services/requests.go
openstack/compute/v2/services/testing/fixtures_test.go
openstack/compute/v2/services/testing/requests_test.go

This follows the same pattern as in the rest of the code and uses a pointer to fix #3471 and allow the caller to unset a prior ForceDown.
This unfortunately changes though the API in a breaking way.
Fixes  #3471 
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/services.py#L473-L479

Change compute services UpdateOpts fields ForceDown to pointer

---

script/getenvvar

Make this script a little more useful, based on my personal experiences using it.
* Handle multiple `clouds.yaml` files
* Use `OS_CLOUDS` if set
* Add uv dependencies metadata header

script: Improve getenvvar helper

---

openstack/compute/v2/hypervisors/requests.go
openstack/compute/v2/hypervisors/testing/fixtures_test.go
openstack/compute/v2/hypervisors/testing/requests_test.go

This introduces a new function GetExt in order to avoid breaking backwards compatibility.
Fixes #3479
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/hypervisors.py#L320-L334

Implement hypervisors.GetExt: Get with Query parameter

---

internal/acceptance/openstack/networking/v2/extensions/taas/taas.go
internal/acceptance/openstack/networking/v2/extensions/taas/tapmirrors_test.go
openstack/networking/v2/extensions/taas/tapmirrors/doc.go
openstack/networking/v2/extensions/taas/tapmirrors/requests.go
openstack/networking/v2/extensions/taas/tapmirrors/results.go
openstack/networking/v2/extensions/taas/tapmirrors/testing/requests_test.go
openstack/networking/v2/extensions/taas/tapmirrors/urls.go

Closes #3482
https://github.com/openstack/tap-as-a-service/blob/7984544610ed949414967cfe950f18336fa21880/neutron_taas/db/tap_mirror_db.py#L82
https://github.com/openstack/tap-as-a-service/blob/7acc6654ecdffafb22e6ef9ad64606e0c902a722/neutron_taas/services/taas/drivers/linux/ovs_taas.py#L584
I am not sure how to best deal with the Directions. According to [docs](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=create-tap-mirror-detail#create-tap-mirror) and [unit tests](https://github.com/openstack/tap-as-a-service/blob/master/neutron_taas/tests/unit/taas_client/osc/fakes.py#L97) the values of the Directions should be integers. However, using the [python taas …

Add networking taas tapmirror suite

---

openstack/networking/v2/extensions/security/rules/requests.go

This PR fixes a minor documentation issue in the PortRangeMax field of the security group rule. When the protocol is ICMP, this field actually represents the ICMP code, but the comment incorrectly stated it as the ICMP type. This change corrects that.

Fix incorrect ICMP field description in PortRangeMax comment

---

.github/actions/file-filter/Dockerfile
.github/actions/file-filter/action.yml
.github/actions/file-filter/file_filter_action.py
.github/workflows/functional-baremetal.yaml
.github/workflows/functional-basic.yaml
.github/workflows/functional-blockstorage.yaml
.github/workflows/functional-compute.yaml
.github/workflows/functional-containerinfra.yaml
.github/workflows/functional-dns.yaml
.github/workflows/functional-fwaas_v2.yaml
.github/workflows/functional-identity.yaml
.github/workflows/functional-image.yaml
.github/workflows/functional-keymanager.yaml
.github/workflows/functional-loadbalancer.yaml
.github/workflows/functional-messaging.yaml
.github/workflows/functional-networking.yaml
.github/workflows/functional-objectstorage.yaml
.github/workflows/functional-orchestration.yaml
.github/workflows/functional-placement.yaml
.github/workflows/functional-sharedfilesystems.yaml
.github/workflows/functional-workflow.yaml
.github/workflows/lint.yaml
.github/workflows/unit.yaml

We'd like to enable [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) so that we can ensure all jobs are run on a PR prior to merging that PR. To do this, we need to mark most of our jobs as *required*. However, we are currently only running those jobs on changes to specific files e.g.:
```yaml
name: functional-baremetal
on:
pull_request:
paths:
- 'openstack/auth_env.go'
- 'openstack/client.go'
- 'openstack/endpoint.go'
- 'openstack/endpoint_location.go'
- 'openstack/config/provider_client.go'
- 'openstack/utils/choose_version.go'
- 'openstack/utils/discovery.go'
- '**baremetal**'
- '.github/workflows/functional-baremetal.yaml'
jobs:
```
However, this causes jobs to never run …

Prepare for merge queues

---

pagination/testing/doc.go
provider_client.go
util.go

Address some gopls suggestions. The behaviour of the code is expected to remain unchanged.
* That `docs.go` file is a noop
* The use of `slices` in `provider_client.go` makes the code easier to read
* The `err` check I remove happened where `err` is untouched after the previous check.

refactor: Trivial fixes
